- .changeset/tender-geckos-agree.md
- documentation/docs/14-configuration.md
- packages/kit/src/core/preview/index.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/utils/url.js
- packages/kit/src/utils/url.spec.js
- packages/kit/test/apps/options/source/pages/endpoint.js
- packages/kit/test/apps/options/test/test.js
Fixes #2796. Right now, the `trailingSlash` option applies to all paths. Now that we've got rid of fallthrough routes, and can match pathnames to routes immediately, we have the option of only applying the `trailingSlash` option to pages. I think we should take it.
This is a breaking change. An alternative would be to add a new option, like
```js
trailingSlash: { pages: 'always', endpoints: 'never' }
```
or something, but I think that'd be a mistake. Right now, `always` _really_ means 'always unless the last segment of the path includes a `.` character' (i.e. `/foo.json` never redirects to `/foo.json/`), which is really just a proxy for 'always unless it's an endpoint', except that it has both false positives and negatives.
There's some redirect logic in `adapter-vercel` that I think we'd …
> ignore trailing slash on endpoints

- .prettierrc
- packages/adapter-cloudflare-workers/README.md
- packages/adapter-cloudflare/README.md
- packages/adapter-netlify/README.md
- packages/adapter-node/README.md
- packages/adapter-static/README.md
- packages/adapter-vercel/README.md
In general we use tabs everywhere, because we are sensible. GitHub's CSS, however, is _not_ sensible:
This PR adjusts the Prettier config so that we can link to individual package READMEs as documentation without feeling embarrassed. (I thought `.editorconfig` was supposed to fix this, which would be better since code copied from the READMEs would contain tabs, but clearly it doesn't.)
> use spaces in README.md files

- .changeset/hungry-coats-sort.md
- packages/kit/src/core/build/build_server.js
Fixes #1538, where I recommended that people do async setup work in `src/hooks.js` (or any other module, really) using top-level await. This works wonderfully in development, but it turns out `svelte-kit build` fails because Vite runs everything through `esbuild` (not sure why, if I'm perfectly honest, but that's a separate conversation) and we currently use `target: 'es2020'` which doesn't allow top-level await:
> chunks/hooks-4fb5bb73.js:206:0: ERROR: Top-level await is not available in the configured target environment ("es2020")
This changes it to `node16`. I tried `node14` at first, but that still didn't work even though top-level await definitely _is_ supported there. I think this is probably fine, and at any rate, you can override it in `config.kit.vite.build.target`.
> default to target: node14.8

- packages/adapter-cloudflare/README.md
similar to #4741 — this closes #2840 by documenting that the `functions` directory will be ignored, and functions should be implemented as SvelteKit endpoints
> add some docs about cloudflare functions

- .changeset/brave-rabbits-provide.md
- packages/adapter-cloudflare-workers/files/entry.js
- packages/adapter-cloudflare/src/worker.js
- packages/adapter-netlify/src/edge.js
It doesn't make sense to wrap `server.respond` in a try-catch — if an uncaught error happens during rendering (which should never happen) it should be handled by the platform (e.g. surfaced in error logs). It definitely shouldn't just cause a 500 to be returned silently. More discussion in https://github.com/sveltejs/kit/issues/4635#issuecomment-1108954358.
In any case, we weren't doing it consistently across adapters.
> remove try-catch around `server.respond`

- .changeset/large-geese-cheat.md
- packages/kit/src/core/sync/write_tsconfig.js
> only complain about missing lib alias if directory exists

- .eslintrc.json
- packages/kit/.eslintrc.json
- packages/kit/src/core/sync/create_manifest_data/index.spec.js
We can't (yet) tell uvu to disallow `test.only` tests (https://github.com/lukeed/uvu/issues/174), so I'd like to prevent this during linting instead.
The first commit of this PR purposefully does not fix the existing `test.only` so that we can make sure it's caught by CI. Once that happens, I'll push another commit to fix it.
> [chore] disallow test.only tests during linting

- packages/kit/src/core/sync/create_manifest_data/index.spec.js
Error message was updated before #4756 was merged, but not the messages in test assertions
> update error message in test assertion

- documentation/docs/80-migrating.md
> document how to get segment

- package.json
- pnpm-lock.yaml
Turbo has been failing locally with `ERROR  could not check if yarn is berry: could not detect yarn version: exit status 1`, something I've worked around by adding `"packageManager": "pnpm@6.32.11"` entry to `package.json`.
I decided to open an issue with turbo but it turns out this has already been fixed upstream, so this is just a `pnpm update turbo`.
> [chore] update turbo

- documentation/docs/02-routing.md
In line 111, the right example of getting json response should be `/items/[id]/__data.json`
> updated documentation: wrong way of getting raw response using `/__data.json`

- .changeset/hip-ears-reflect.md
- packages/kit/src/core/sync/write_tsconfig.js
It's probably best to discuss the side effects of this change, it fixes my issue of https://github.com/sveltejs/kit/issues/4460 and also https://github.com/sveltejs/kit/issues/4764 - However this was changed in https://github.com/sveltejs/kit/pull/4633 and maybe this change is what should stay and alternative solution to the issues can be done such as what I proposed here https://github.com/sveltejs/kit/issues/4460#issuecomment-1111603855
> update generated tsconfig

- .changeset/fast-crabs-applaud.md
- packages/create-svelte/shared/+eslint/package.json
When a user creates a SvelteKit app with `eslint` support using `create-svelte`, it ships the last `eslint` release under major version 7. With this pull request, `create-svelte` will now ship the latest `eslint` release (for now).
I'm worried that `eslint-plugin-svelte3` doesn't support `eslint@^8.0.0`, from [this discussion](https://github.com/sveltejs/eslint-plugin-svelte3/pull/155#issuecomment-1003056483).
`eslint-plugin-svelte3`'s peerDependencies [lists `eslint@>=6.0.0`](https://github.com/sveltejs/eslint-plugin-svelte3/blob/55fc0bdcb76748edec2b5613113574ba45b1a419/package.json#L28) since June 22, 2019, around when `eslint@6.0.1` was released.
Related: #3261
---
> [chore] bump `eslint` from version 7 to 8

- documentation/docs/15-types.md
Forgot to change this in #4791
> Update tsconfig docs

- sites/kit.svelte.dev/src/lib/search/SearchBox.svelte
Fixes issue where you lose the ability to scroll on a page if you close the search box if you use the `ctrl` (or `cmd`) + `k` shortcut.
Fixes https://github.com/sveltejs/kit/issues/4858
> fix: searchbox close shortcut

- packages/kit/types/ambient.d.ts
Update JSDocs for $app/paths.base to specify it can also be an empty string. This should clarify issue #4561.
> specify `base` in `$app/paths` can be the default empty string

- sites/kit.svelte.dev/src/routes/__error.svelte
The stacktrace makes it look like our 404 handling is broken and doesn't really add anything
> don't show stacktrace for 404 in dev mode

- packages/kit/test/apps/basics/src/routes/load/fetch-headers.svelte
- packages/kit/test/apps/basics/src/routes/store/stuff/foo.svelte
- packages/kit/test/apps/basics/test/test.js
While writing a test for a Safari only bug (PR #4846), the test suite exposed 13 false positives originating from browser specific behavior in the tests. This PR slightly tweaks the integration tests to be more browser agnostic and allows them to be run using WebKit. It doesn’t include changes to the Playwright config, so the WebKit tests would still be completely opt-in.
Test targeted headers that Safari doesn't support
"Press tab to highlight each item on a webpage" accessibility setting is turned off in Playwright. Need to use Alt+Tab for WebKit instead.
The test matched error.stack instead of error.message and WebKit doesn't show the message as the first line of the stack trace
Test checked for chrome specific error page.
The browsers block attempts to prevent navigation on a frame …
> WebKit tests

- .changeset/twenty-windows-build.md
- packages/kit/src/packaging/index.js
Currently sveltekit package does not update the generated tsconfig when packaging, this fixes that
> Generate tsconfig when running svelte-kit package

- .changeset/soft-ears-share.md
closes #4850 by bumping adapter-static. In future we should take care to add changesets to README changes
> bump adapter-static

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
Looks like we missed a place when upgrade to 4.6
> [chore] bump kit.svelte.dev to TypeScript 4.6

- .changeset/long-turkeys-boil.md
- packages/kit/src/core/config/index.spec.js
- packages/kit/types/index.d.ts
This PR adds stricter typings for `config.kit.prerender.entries`.
Before, editors won't flag the following as incorrect (but the compiler will):
```ts
/** @type {import('@sveltejs/kit').Config} */
const config = {
kit: {
prerender: {
entries: ['afdasd'],
},
},
};
```
With this PR, the type of `entries` is stricter, making it easier to debug before building.
> [feat] more specific types for `kit.prerender.entries` config

- .changeset/ninety-books-jam.md
- packages/adapter-netlify/index.js
Closes #4722 — fixes a bug introduced in #4657. If you have an existing `_redirects` file, it needs to be copied _before_ lambdas are generated, not after.
> append function redirects after copying existing redirects - fixes #4722

- .changeset/little-pots-rule.md
- packages/adapter-cloudflare-workers/README.md
- packages/adapter-cloudflare-workers/index.js
- packages/create-svelte/templates/default/wrangler.toml
closes #4885. I don't think there's much of a reason to continue supporting Wrangler 1, given Wrangler 2's overwhelming superiority.
> [breaking] drop Wrangler 1 support in favour of Wrangler 2

- .changeset/rude-masks-kneel.md
- packages/create-svelte/shared/+checkjs/jsconfig.json
- packages/create-svelte/shared/+typescript/tsconfig.json
The new SvelteKit project created by `npm init svelte` will by default overwrite the libs, modules, and targets added in #4791, so fix this.
> Fix tsconfig used in create-svelte

- sites/kit.svelte.dev/src/lib/docs/Contents.svelte
fixes #4620 with a belt-and-braces approach:
* factors `scroll-margin-top` into calculation of which section has been scrolled to
* forcibly highlights correct section when `hash` changes
* forcibly highlights correct section when a link is clicked
The latter two ensure that clicking on a link in the nav causes it to be highlighted even if the header in question is close enough to the bottom of the screen that the scroll-based logic would otherwise cause a different link to be highlighted, and even if the hash is current.
> ensure correct link is highlighted in docs nav

- .changeset/silver-elephants-attack.md
- packages/kit/src/runtime/client/client.js
fixes #3978. Even though the failure to load modules following a redeploy (which causes some filenames to be changed) was being dealt with (by causing the page to reload), rejections weren't being handled immediately before, when we preload modules to avoid waterfall.
This is a tricky thing to add a test for, but I verified that with this change the `unhandledrejection` event no longer happens, which should clean up Sentry logs etc.
> prevent unhandled rejections when loading page modules

- .changeset/olive-vans-talk.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/no-ssr/margin.svelte
- packages/kit/test/apps/basics/test/test.js
Fixes #4065. While resetting focus, Safari was scrolling over the top margin.
As it’s a Safari specific issue, the change in test from fail to pass is only visible when running Playwright with WebKit. 
This is my first PR, so let me know if I missed something in the workflow, thanks!
> prevent scroll when resetting page focus (#4065)

- .changeset/witty-chicken-teach.md
- packages/create-svelte/templates/default/CHANGELOG.md
Remove the project created by selecting `SvelteKit demo app` in `npm init svelte` as it contains unnecessary `CHANGELOG.md`
> remove unnecessary CHANGELOG.md

- packages/adapter-vercel/README.md
i think the link in adapter-vercel's README.md isn't correct, i replaced the `/svelte/` part with a `/[YOUR_USERNAME]/` placeholder.
> [docs] change `/svelte/` to username placeholder for the opt-in link

- packages/kit/src/packaging/index.js
- packages/kit/src/packaging/test/index.js
- packages/kit/src/packaging/test/watch/tsconfig.json
Packaging's "watches for changes" test hasn't worked on Windows. Upon investigation it was because of two reasons:
- We need to wait for `chokidar`'s `ready` event before writing the files;
- Typescript uses `crlf` on the generated `.d.ts` files by default, causing a mismatch with our expected output.
> [fix] get packaging test working on Windows

- .changeset/honest-rats-double.md
- packages/adapter-netlify/README.md
I tested running Node 16 on Netlify (see https://github.com/sveltejs/kit/issues/4916) and it works with the following caveat
> [docs] setting Node version in `adapter-netlify`

- .changeset/lemon-oranges-pump.md
- .github/workflows/ci.yml
- packages/adapter-vercel/index.js
- packages/kit/package.json
closes https://github.com/sveltejs/kit/issues/4916
> [breaking] drop Node 14 support

- .changeset/yellow-eagles-leave.md
- packages/kit/src/cli.js
- packages/kit/src/core/dev/index.js
Set default options for the `dev` command, similar to the `preview` command.
This shouldn't break anything, but could be helpful:
1. Ensure port is 3000, as Vite 3 changes to 5173. 
2. Set `--host` to `localhost` as Vite defaults to `127.0.0.1` in dev. 
Re no2, while Vite still forces `127.0.0.1` when `localhost` is specified (ref https://github.com/vitejs/vite/issues/7075), this will be changed in Vite 3 and the behaviour should be consistent with `preview` then.
Also ref: https://github.com/sveltejs/kit/pull/4729
> set default options for dev command

- .changeset/rich-singers-taste.md
- packages/adapter-vercel/index.js
The current implementation of Edge deployment on Vercel is piggybacking Middleware.
This PR uses the new general purpose Edge Function deployment mechanism to deploy them.
This enables Cache-Control support, for instance, and a more streamlined configuration (no `middlewarePath`, and using `dest` instead when rewriting).
I also fixed a bug for the root `/__data.json` file when running in `split: true` mode.
> Use general purpose edge functions for vercel-adapter

- .changeset/five-cows-happen.md
- packages/kit/test/typings/endpoint.test.ts
- packages/kit/types/private.d.ts
Taking the inverse of the current approach, rather than naively `extend`-ing `JSONValue`, we will explicitly recurse when hitting an object. Other than that, we'll check whether it's an invalid type that cannot be converted to JSON string rather than checking whether it's a valid JSON type, [that should be much simpler](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#exceptions).
Fixes #4926
> explicit recursive body validations

- .changeset/moody-roses-search.md
- packages/kit/src/cli.js
- packages/kit/src/core/dev/index.js
fix #4947
Turns out setting the default `host` value to `localhost`, makes plain `--host` option be `""` instead of `true`. 
Reverting #4932 as there isn't a nice way to handle this. Re Vite port being `5173` in the future, I've made `3000` as the default port in the base config.
> revert dev command default options

- .changeset/wise-houses-work.md
- packages/adapter-static/README.md
closes #3413. This makes it clearer that you're not supposed to bring your own fallback page or something
> clarify that the fallback page is created by SvelteKit

- .changeset/beige-mails-accept.md
- packages/create-svelte/README.md
> Add `create-svelte` README

- .changeset/swift-horses-march.md
- documentation/docs/07-service-workers.md
- packages/kit/src/runtime/server/page/render.js
closes #3342. This is a more sensible default, and since we can disable automatic service worker registration we don't need to provide any more granular control.
> delay automatic service worker registration until load event

- .changeset/yellow-apricots-stare.md
- packages/kit/src/core/dev/plugin.js
- packages/kit/test/apps/basics/src/routes/css/_base.css
- packages/kit/test/apps/basics/src/routes/css/_styles.css
- packages/kit/test/apps/basics/src/routes/css/index.svelte
- packages/kit/test/apps/basics/test/test.js
Fixes #3497
During dev, kit inlines css files in order to prevent FOUC. The current implementation injects all imported modules indiscriminately, but this conflicts with vite's own `@import` inlining.
Given a component:
```svelte
<script>
import '$lib/entry.css';
</script>
```
And the respective css files:
```css
/* entry.css */
@import './base.css';
html { color: green; }
/* entry.css eof */
/* base.css */
html { color: red; }
/* base.css eof */
```
By walking the `ModuleGraph` we end up inlining both `entry.css`'s and `base.css`'s _transformed_ content. Since vite inlines `base` into `entry`, we get the following injected css:
```css
/* entry.css */
/* base.css */
html { color: red; }
/* base.css eof */
html { color: green; }
/* entry.css eof */
/* base.css */
html { color: red; }
/* …
```
> [fix] deduplicate injected css during dev

- .changeset/real-buckets-smash.md
- packages/kit/types/ambient.d.ts
- turbo.json
Adds a note about how you can't use `import` statements in the app declaration file, closes #3853
> Add note about ambient dts files to App types

- .changeset/odd-pumas-grow.md
- packages/kit/src/core/dev/index.js
it's `server.port`, not `server.fs.port`. This sets us up for Vite 3 (which changes the default port to 5173)
> fix port override

- .changeset/eight-rivers-battle.md
- packages/kit/src/runtime/server/page/render.js
- packages/kit/test/prerendering/basics/test/test.js
supersedes #4698, closes #4685. This is a compromise measure — it keeps the existing behaviour, but adds a test to make sure we don't accidentally change the hydration mechanism in a way that breaks apps manipulating the markup in certain ways.
> add test to prevent accidental breakage of data-hydrate mechanism

- .changeset/rude-geese-roll.md
- packages/kit/types/index.d.ts
- packages/kit/types/internal.d.ts
- packages/kit/types/private.d.ts
#4805 only explicitly requested moving `RequestEvent` to `index.d.ts`, but `ResolveOptions` is also part of `Handle`'s input API, so I moved it too. If, for some reason, we don't want that to be a publicly-accessible type, I'll move it back.
Fixes #4805.
> move `RequestEvent` and `ResolveOptions` as public types

- documentation/docs/04-loading.md
See #1575. We might want to add some warnings when these properties are encountered when rendering error pages, but the first step is to document the expected behaviour
> document that status, error, redirect, cache are ignored when rendering error pages

- .changeset/moody-moose-jump.md
- packages/kit/src/core/dev/plugin.js
Fixes #4987.
Turns out you were right, @Rich-Harris: not all pushes were happening synchronously. 😬 
`add` was supposed to `return find_deps` but I missed it at some point. Rewrote `add_by_url` so both branches work similarly and it's readily apparent they're both promises now.
> [fix] fouc regression in dev mode

- packages/adapter-cloudflare-workers/package.json
- packages/adapter-cloudflare/package.json
- packages/adapter-netlify/package.json
- packages/adapter-vercel/package.json
- pnpm-lock.yaml
Vite was using 0.14.29. This makes us use the same version so that we only have one version
I didn't add a changeset as this shouldn't have user-visible changes, but of course nothing ever works as it should in software, so maybe a changeset would be valuable?
> [chore] standardize esbuild version

- .changeset/eight-tomatoes-yawn.md
- packages/kit/src/core/dev/index.js
> [fix] don't watch `outDir` except `generated`

- .changeset/empty-fishes-design.md
- packages/create-svelte/shared/+eslint+prettier/package.json
- packages/create-svelte/shared/+eslint-prettier/package.json
- packages/create-svelte/shared/+eslint/.eslintignore
- packages/create-svelte/shared/+prettier/.prettierignore
- packages/create-svelte/shared/-eslint+prettier/package.json
Use separate ignore files for prettier and eslint.
Fixes #4937
> use separate ignore files for prettier and eslint

- .changeset/few-scissors-agree.md
- packages/adapter-vercel/index.js
fixes #4933. I don't truly understand why this was failing, but reverting to `cjs` rather than `esm` seems to fix it. If it turns out that other apps _need_ `esm` then we can expose it as a config option
> revert to using cjs for lambda

- .changeset/curly-doors-type.md
- packages/create-svelte/index.js
- packages/create-svelte/shared/+eslint/.eslintignore
- packages/create-svelte/shared/+prettier/.prettierignore
`package.json` wasn't formatted correctly by default according to `.prettierrc`
> correct default package.json format

- turbo.json
i think the absence of this might be causing deploys to fail on e.g. https://github.com/sveltejs/kit/pull/5016 because it's incorrectly replaying cache hits
> tweak turbo config

- .changeset/forty-lions-give.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/load/fetch-relative.json.js
- packages/kit/test/apps/basics/src/routes/load/fetch-relative.svelte
- packages/kit/test/apps/basics/src/routes/load/index.svelte
- packages/kit/test/apps/basics/test/test.js
When using `load`'s `fetch`, it's natural to assume URLs will be resolved relatively to the navigation's target page. Instead, they take the current page into account. This means that, in practice, we must always use absolute or root-relative URLs.
This PR resolves URLs relatively to the target page before issuing the native `fetch`. It's a simple fix, with just a couple of wrinkles we must pay attention to:
- The `Request` object is mostly read-only, so we need to consume its body and manually copy properties into the new request;
- Our ssr-included payloads wouldn't match the full URLs, so we skip normalization during hydration.
> [fix] resolve fetch requests from the target page

- .changeset/olive-lies-train.md
- documentation/docs/80-migrating.md
- packages/adapter-static/test/apps/prerendered/src/app.html
- packages/adapter-static/test/apps/spa/src/app.html
- packages/create-svelte/templates/default/src/app.html
- packages/create-svelte/templates/skeleton/src/app.html
- packages/kit/src/core/build/build_server.js
- packages/kit/src/core/config/index.js
- packages/kit/src/core/dev/plugin.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/test/apps/amp/src/app.html
- packages/kit/test/apps/basics/src/app.html
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/apps/options-2/src/app.html
- packages/kit/test/apps/options/source/template.html
- packages/kit/test/prerendering/basics/src/app.html
- packages/kit/test/prerendering/disabled/src/app.html
- packages/kit/test/prerendering/options/src/app.html
- packages/kit/test/prerendering/paths-base/src/app.html
- packages/kit/test/prerendering/trailing-slash/src/app.html
- sites/kit.svelte.dev/src/app.html
Never got round to creating an issue for this, but I think it's a no-brainer — we should have been more explicit from the start that `%namespace.body%` is a SvelteKit thing, not a Svelte thing
> replace `%svelte.body%` etc with `%sveltekit.body%`

- .changeset/nine-kangaroos-laugh.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/page/load_node.js
- packages/kit/types/index.d.ts
> rename `LoadInput` to `LoadEvent`

- documentation/docs/01-web-standards.md
- documentation/docs/04-loading.md
Closes #3380. Rather than introducing a new version of `fetch`, I think it makes sense to just document the fact that the way to make credentialled fetches in server-side code is to pass cookie/auth headers.
> explain how to make credentialled fetches in server-side code

- packages/kit/src/cli.js
- packages/kit/src/core/dev/index.js
- packages/kit/src/core/dev/plugin.js
I don't think this needs to be passed around. Removing it simplifies things and results in less code. And if we want to use the `vite` CLI then we won't be able to pass it in the way we can from the `svelte-kit` CLI
> [chore] remove `cwd` as a method parameter

- .changeset/fast-islands-lick.md
- packages/create-svelte/templates/default/package.template.json
- packages/create-svelte/templates/default/src/hooks.ts
Now that we only support Node 16 and above, we can drop the dependency on `@lukeed/uuid` in favour of Using The Platform.
Closes #4929
> use `crypto.randomUUID()`

- .changeset/lovely-flies-care.md
- packages/adapter-netlify/src/serverless.js
- packages/kit/src/runtime/server/endpoint.js
closes #4174 (I think — it's awkward to test these changes without actually releasing the adapter, since everything gets installed from npm inside Netlify)
no, this isn't DRY. i don't think it's worth creating a new export just for this. we can do that if it turns out other adapters need to copy the same logic
> base64-encode binary responses

- .changeset/pretty-actors-chew.md
- packages/kit/src/core/dev/plugin.js
- packages/kit/test/apps/basics/test/test.js
> ensure correct case is used for static assets

- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/fetcher.js
i have ABSOLUTELY NO IDEA how this passed CI in the first place, but apparently #5041 broke a bunch of stuff somehow? my browser suddenly started complaining that you can't call `fetch` if it's a property of something that isn't `window`. seems like a weird constraint but who am i to judge.
no changeset because #5041 wasn't released yet, so no need
> use free variable for native fetch

- .changeset/fresh-sheep-help.md
- packages/kit/src/cli.js
- packages/kit/src/core/dev/index.js
- packages/kit/src/core/preview/index.js
We shouldn't read the Kit config in the CLI, but rather in the Vite plugin so that it will work with the `vite` CLI as well. This doesn't move the config reading all the way to the plugin yet, but does remove it from the CLI which is a step in that direction
> [chore] return config from server start methods

- .changeset/stupid-maps-hide.md
- packages/adapter-auto/package.json
- packages/adapter-cloudflare-workers/package.json
- packages/adapter-cloudflare/package.json
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-static/package.json
- packages/adapter-vercel/package.json
- packages/amp/package.json
fixes #5028 (I think?). No types for `@sveltejs/kit/*` but I don't think we need them because of `types/ambient.d.ts`
> add types to pkg.exports

- .changeset/tricky-beers-unite.md
- packages/kit/package.json
Necessary for https://nodejs.org/api/webcrypto.html
> Update `engines` to specify that Node 16.7 is required

- .changeset/lemon-planets-sit.md
- packages/kit/src/core/sync/utils.js
- packages/kit/src/core/sync/write_types.js
Fixes #5059.
`svelte-kit sync` always completely deletes the `types` directory when it writes types. Then, it re-writes types by looking for changed files. If no files have been changed, the `types` directory is gone for good (or at least until a file is changed). See the repro in the linked issue.
This fixes the issue by always rewriting all of the types (since we're deleting everything, we need to rewrite everything). I'm not really sure how to test this change, though this does fix the repro.
If there's some larger issue here that needs a bigger fix, feel free to just close this and move on!
> fix: Generated types no longer permanently delete themselves

- .changeset/odd-bottles-drop.md
- packages/kit/src/core/dev/index.js
- packages/kit/src/core/dev/plugin.js
we'll need to move everything to occur inside the plugin if we want to be able to use it from Vite
> [chore] trigger sync and other setup from plugin

- .changeset/thirty-bees-lay.md
- packages/kit/src/core/dev/plugin.js
this fixes some local test failures that started following #5063 (that PR wasn't to blame, it just exposed the underlying issue)
> only recreate manifest when necessary

- .changeset/empty-numbers-wink.md
- packages/kit/src/core/build/build_client.js
- packages/kit/src/core/build/build_server.js
- packages/kit/src/core/build/build_service_worker.js
- packages/kit/src/core/build/index.js
- packages/kit/src/core/build/utils.js
Share the same base config between Vite client and server builds. This removes 30 lines of code and will make it easier to make build happen within a plugin
> [chore] shared Vite build config

- .changeset/lemon-timers-deliver.md
- packages/adapter-auto/index.d.ts
- packages/adapter-auto/index.js
- packages/adapter-cloudflare-workers/index.d.ts
- packages/adapter-cloudflare-workers/index.js
- packages/adapter-cloudflare/index.d.ts
- packages/adapter-cloudflare/index.js
- packages/adapter-netlify/index.d.ts
- packages/adapter-netlify/index.js
- packages/adapter-node/index.d.ts
- packages/adapter-node/index.js
- packages/adapter-static/index.d.ts
- packages/adapter-static/index.js
- packages/adapter-vercel/index.d.ts
- packages/adapter-vercel/index.js
As discussed in #5110, the entry `index.d.ts` files of the adapters all use a node-resolution-compatible export syntax like this:
```ts
declare function plugin(): Adapter; 
export = plugin; 
```
However, all of these packages use ESM (instead of CommonJS) so they can instead use:
```ts
export default function plugin(): Adapter;
```
Making this change resolves a Typescript 4.7+ error where `import adapter from '@sveltejs/adapter-auto';` throws a compiler error when the `tsconfig.json` is configured with `moduleResolution` set to `NodeNext` or `ESNext`.
To make this change, all of the `index.js` files that import these types have to have their JSDoc import statements changed to explicitly grab the `default` export. E.g. `/** @type {import('.')} **/` ➡️ `/** @type {import('.').default} **/`. …
> Update adapter entrypoint typings to be NodeNext/ESNext-compatible.

- .changeset/dry-cars-dance.md
- packages/kit/package.json
- packages/kit/src/core/dev/plugin.js
- packages/kit/src/runtime/client/client.js
- pnpm-lock.yaml
- turbo.json
Currently, if you introduce an error into a component that causes rendering to fail...
```svelte
<p>{this_variable_does_not_exist}</p>
```
...fixing the component won't cause the page to recover, because Svelte itself is now in a broken state. (We plan to make Svelte more resilient to this sort of thing, but it's a ways off.) Adding `hot.optimistic: false` to the `vite-plugin-svelte` options causes the page to reload on HMR updates after a rendering error is encountered.
That solves half the problem. If the page reloads and it's _still_ broken, the server will render an error page. Since the error page generally won't use the component where the error was, subsequent HMR updates will be ignored, so fixing the component won't cause the error page to go away.
I think a reasonable way to fix …
> robustify error handling

- .changeset/nine-rats-bake.md
- packages/kit/test/typings/endpoint.test.ts
- packages/kit/types/private.d.ts
We shouldn't be spreading the values but instead pass in the whole object or information would be lost when recursing. This was my mistake.
> recurse whole object

- CONTRIBUTING.md
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/build/utils.js
- packages/kit/src/core/config/index.js
- packages/kit/src/core/generate_manifest/index.js
- packages/kit/src/core/sync/write_manifest.js
- packages/kit/src/core/sync/write_tsconfig.js
- packages/kit/src/runtime/server/page/load_node.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/page/respond.js
Adds code comments to help new devs around the codebase. I didn't add comments for methods where I felt the name would be self-explanatory, but tried to comment a lot of the more important methods whose functioning might be more complicated.
CC @gtm-nayan - feel free to let me know if there are others you'd like me to add here
> [docs] improve documentation for new developers

- .changeset/clean-spiders-sin.md
- packages/create-svelte/templates/default/src/routes/index.svelte
Just created my first project with svelte kit and came across this minor issue. div is not allowed as a child for heading, changed it to span.
> fix: use inline element in heading

- sites/kit.svelte.dev/src/lib/search/SearchResultList.svelte
we're leaving performance on the table here
> add sveltekit:prefetch to search results

- .changeset/cold-sheep-yawn.md
- documentation/docs/11-page-options.md
- documentation/docs/14-configuration.md
- documentation/docs/16-seo.md
- packages/kit/src/core/build/build_server.js
- packages/kit/src/core/build/utils.js
- packages/kit/src/core/config/index.spec.js
- packages/kit/src/core/config/options.js
- packages/kit/src/core/dev/plugin.js
- packages/kit/test/apps/amp/svelte.config.js
This is a duplicate option. Having two ways of setting it makes it really difficult to create the svelte plugin without loading the config first which ends up making plugin creation `async`. This would remove the need for `async` in https://github.com/sveltejs/kit/pull/5094
> [breaking] remove `kit.browser.hydrate` config in favor of `compilerOptions.hydratable`

- sites/kit.svelte.dev/src/lib/search/Search.svelte
we get dinged on lighthouse for not using a passive event listener. we _can't_ make the `touchstart` passive because we need to prevent the event default (otherwise the input gets focused, which we don't want); this seems like the best alternative
> use touchend instead of touchstart

- documentation/docs/02-routing.md
> [docs] be more specific about the definition of page endpoints

- .changeset/hip-kangaroos-check.md
- packages/adapter-cloudflare-workers/README.md
- packages/adapter-cloudflare-workers/index.js
Updates the example provided for `wrangler.toml` file for
the `adapter-cloudflare-workers` documentation, to follow
the specs on wrangler@2.
Changes from Cloudflare include:
- The `type` key is no longer needed.
- The `zone_id` is unnecessary since they can deduce this from routes directly.
- The `compatibility_date` is required when publishing.
- The `main` key belongs to the global scope, instead of the `build.upload` section
- The `format` key  is inferred automatically from the code.
> [docs] update wrangler.toml example to wrangler@2

- .changeset/popular-pets-obey.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/page/load_node.js
- packages/kit/src/utils/url.js
- packages/kit/test/apps/basics/src/routes/load/url-to-string.svelte
- packages/kit/test/apps/basics/test/test.js
Fixes #5083.
This is the "surgical approach" -- just replace the `hash` property with a custom getter. The other option is (if we're really committed to using a Proxy):
```typescript
new Proxy(url, {
get: (target, property, receiver) => {
if (property === 'hash') {
throw new Error(
'url.hash is inaccessible from load. Consider accessing hash from the page store within the script tag of your component.'
);
}
if (!(property in target)) {
return undefined;
}
const value = target[property];
return typeof value === "function"
? (...args) => value.apply(target, args)
: value;
}
});
```
This scares me a little bit, because it's a lot harder to anticipate what other side effects it might exhibit.
> fix: URL instance methods work in `load`

- .changeset/thick-swans-join.md
- packages/create-svelte/bin.js
- packages/create-svelte/templates/default/.meta.json
- packages/create-svelte/templates/skeleton/.meta.json
closes #5217
Here's how the descriptions look
> create-svelte: Add descriptions to select options

- .changeset/young-pens-exist.md
- packages/kit/src/core/dev/plugin.js
- packages/kit/test/apps/basics/test/test.js
~Just checking CI for now, hopefully won't break #4997 (merci Windows gods 🙏)~ Yayy
Fixes #5142
> fix manifest not updating on route creation

- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/utils.js
The test suite recently started failing for me locally — turns out the Control Center app on Monterey likes to occupy port 5000. Not sure why this only started happening recently. Anyway, this seems to get things running again
> fix some tests that fail locally

- .changeset/great-bags-worry.md
- packages/kit/src/runtime/app/env.js
- packages/kit/types/ambient.d.ts
It feels incomplete having "browser" and "dev" env variables without their counterparts, "server" and "prod". One could argue that they're redundant because you can write `!browser` and `!dev`, but i personally like `if(server) {}` instead of `if(!browser) {}`
> added server and prod env variables

- packages/kit/test/utils.d.ts
- packages/kit/test/utils.js
It needs to return a `Promise` since it's `async` or else you get warnings about unnecessary `await` calls
> [chore] fix start_server type

- .changeset/short-lamps-sing.md
- packages/kit/src/runtime/client/client.js
- packages/kit/types/ambient.d.ts
follow-up to #5282 — if `goto` accepts a `URL` object, it probably makes sense for the argument to be called `url` and not `href` (which implies a string, unlike `url` which is pleasingly ambiguous). we can also skip the resolution against the base URI in the case where a `URL` is supplied
> rename goto(href) to goto(url)

- .changeset/lovely-foxes-visit.md
- packages/create-svelte/shared/+eslint+prettier+typescript/.eslintrc.js
- packages/create-svelte/shared/+eslint+prettier-typescript/.eslintrc.js
- packages/create-svelte/shared/+eslint+typescript/.eslintrc.js
- packages/create-svelte/shared/+eslint-typescript/.eslintrc.js
I'm not sure why this uses `.cjs` files. Maybe a holdover from an old version of eslint
> Use ESM eslint config files

- documentation/docs/00-introduction.md
- sites/kit.svelte.dev/src/routes/index.svelte
Suggested in https://github.com/sveltejs/sites/pull/352, which would also need to be merged if we want to do this
I think this is a good change somce it uses a command that will also work with pnpm whereas init does not
> [docs] suggest npm create rather than npm init

- .changeset/four-glasses-explain.md
- packages/kit/src/vite/index.js
Closes https://github.com/sveltejs/kit/issues/5296
Array options will be merged. We only need to ensure we're not overriding the remaining primitives which are not in `enforced_config`
`spa` option does not exist and can be removed
`root` already defaults to `cwd` and can be removed
> [fix] allow user to set dev port

- .changeset/slimy-carpets-smash.md
- packages/adapter-cloudflare-workers/index.js
- packages/adapter-cloudflare/index.js
- packages/adapter-netlify/index.js
Vercel was done here: https://github.com/sveltejs/kit/pull/5197
We should do the others as well
> Generate sourcemaps

- sites/kit.svelte.dev/src/lib/docs/server/index.js
`<data-lsp lsp=''>foo</data-lsp>` can simply be replaced with `foo`. Closes #5238
> remove <data-lsp> altogether if no content - fixes #5238

- .changeset/spotty-ladybugs-teach.md
- packages/kit/src/runtime/server/index.js
- packages/kit/test/apps/basics/test/test.js
> fix server crash when accessing a malformed URI

- .changeset/quick-chicken-hide.md
- packages/kit/src/vite/index.js
`root` is no longer set since https://github.com/sveltejs/kit/pull/5303. This logs an unnecessary warning when using Storybook
> [fix] don't log warning if root is configured

- .github/workflows/release.yml
No release PR was generated after merging #5332, because the release workflow failed. I think this would have fixed it
> only build public packages when releasing

- .changeset/healthy-wasps-poke.md
- packages/kit/types/index.d.ts
- packages/kit/types/internal.d.ts
Discovered through comment in #2040
This is necessary so people can use this new resolution mode and still get proper typings for things like $app/stores
This isn't all that's needed though:
- Vite 3 is needed so we get their exports map which makes vite/client resolve correctly
- Svelte bump needed to properly expose CompileOptions. It's imported from a path which isn't accessible when adhering to export maps
> [fix] Adjust type imports to satisfy TS NodeNext moduleResolution

- documentation/docs/14-configuration.md
> [docs] remove kit.vite config from docs

- packages/adapter-static/package.json
- pnpm-lock.yaml
found via `node scripts/check-dependencies.js`
> synchronise port-authority versions

- .changeset/tiny-flies-know.md
- packages/kit/src/vite/index.js
Followup to https://github.com/sveltejs/kit/pull/5356. Looks like `closeBundle` is called in dev by Vite. So when updating `svelte.config.js` or `vite.config.js` which restarts the server, the process immediately exits, instead of restarting.
Closes https://github.com/sveltejs/kit/issues/5294
> fix: skip process.exit in dev

- .changeset/sixty-bees-explain.md
- packages/adapter-cloudflare/README.md
- packages/adapter-cloudflare/src/worker.js
This PR exposes [Cloudflare's Worker Cache API](https://developers.cloudflare.com/workers/runtime-apis/cache/) as `caches` in the `platform` object. This allows hooks to do elaborate caching, for example, [I use the Cache API](https://github.com/modrinth/knossos/blob/1b34ce1fb906f400fac72e753244890aba87009e/src/adapter/files/worker.js#L63-L85) to cache certain pages based on request cookies.
> Expose `caches` to Cloudflare adapter through Platform

- package.json
Running `pnpm build` at the top of the repo was giving the same types of errors as were fixed in #5362 for the release job.
This adds a `--filter` so that `pnpm build` only tries to build packages and not individual tests. (It also doesn't try to build kit.svelte.dev, which makes the build much faster.)
> filter top-level 'pnpm build' to just packages

- .changeset/smart-peas-compare.md
- packages/kit/src/runtime/server/page/load_node.js
- packages/kit/test/apps/basics/test/test.js
This should resolve at least part of #5380. It might be that this ends up being the only thing we want to do as part of that issue. This PR is similar to #3690 which omitted the `Host` header.
> [fix] omit Connection header from requests made by load fetch

- .changeset/angry-crabs-walk.md
- packages/kit/package.json
closes https://github.com/sveltejs/kit/issues/5370
not exactly sure why Node 16.9 is now required, but it fixes it, so :shrug:
> [breaking] require Node 16.9

- .changeset/wet-hairs-wink.md
- packages/kit/src/runtime/server/endpoint.js
- packages/kit/test/apps/basics/src/routes/endpoint-output/stream.js
- packages/kit/test/apps/basics/test/test.js
> allow body to be a binary `ReadableStream`

- .changeset/swift-dots-cry.md
https://github.com/sveltejs/kit/pull/5394 looks screwed up. we probably need to do this before cutting a release
> don't create changelog for test-basics

- .changeset/ninety-dodos-exercise.md
- packages/kit/src/runtime/server/page/render.js
Replaced arrow function with anonymous function in the init_service_worker script for support old browsers
This is necessary for the application to work in WebView on Android >= 5.1 (Chromium >= 39).
Arrow functions are only supported in Android WebView >= 45, [see MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
> small fix in init_service_worker

- .github/workflows/ci.yml
Can't remember what glitch this was masking, but `--force` defeats the object of using turbo
> remove --force

- .changeset/yellow-years-remember.md
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/vite/build/build_server.js
- packages/kit/src/vite/build/build_service_worker.js
- packages/kit/src/vite/build/utils.js
- packages/kit/src/vite/index.js
@userquin is trying to get `vite-plugin-pwa` working with SvelteKit. That plugin adds a mutable manifest to the bundle. Since the bundle is written to the `outDir` we need the `outDir` to be set to `client` instead of `client/immutable`
> [fix] allow Vite plugins to output mutable assets

- .changeset/lemon-elephants-chew.md
- packages/create-svelte/shared/+playwright+typescript/playwright.config.ts
- packages/create-svelte/shared/+playwright-typescript/playwright.config.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/utils.js
Closes #5429 which was introduced with #5392.
I have changed the web server port from 3000 to 4173 in the `playwright.config.js` templates to be in line with the preview server ports from `vite`.
I am not totally sure if the changes to the tests are good enough. But if the `vite` ports will change in the future the tests should be failing.
I am also not quite sure if my selections for the changeset are correct.
> [fix] Use vite preview port in templates for playwright config

- .changeset/cool-drinks-press.md
- packages/kit/src/vite/index.js
@userquin is trying to write files in `vite-plugin-pwa` in `writeBundle`, but it's not working because the adapter isn't copying them to the output folder. Moving `adapt` to occur later should fix this
> [fix] `adapt` in `closeBundle`

- .changeset/smooth-hornets-think.md
- packages/kit/src/core/sync/create_manifest_data/index.js
- packages/kit/src/core/sync/create_manifest_data/index.spec.js
- packages/kit/src/utils/routing.js
- packages/kit/src/utils/routing.spec.js
closes #5261
There was a discrepancy between the allowed names for matcher files and matchers in route names, took the opportunity to remove that as well. Was it there for a special reason?
> unify matcher name restrictions and clearer error on bad param/matcher names

- .changeset/new-geckos-vanish.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/routing/prefetching/hash-route.svelte
- packages/kit/test/apps/basics/src/routes/routing/prefetching/prefetched.json.js
- packages/kit/test/apps/basics/src/routes/routing/prefetching/prefetched.svelte
- packages/kit/test/apps/options/source/pages/__layout.svelte
- packages/kit/test/apps/options/source/pages/prefetching/index.svelte
- packages/kit/test/apps/options/source/pages/prefetching/prefetched.js
- packages/kit/test/apps/options/source/pages/prefetching/prefetched.svelte
- packages/kit/test/apps/options/test/test.js
> fix(5457): normalize path on prefetch

- .changeset/green-masks-confess.md
- packages/kit/src/node/index.js
Closes #5412.
I'm not 100% sure this is correct — in particular, I'm not sure what's supposed to happen if someone tries to upload a huge file and you early-exit with a 413; the response doesn't seem to get acknowledged while the request is still pending (which never stops being true, if you don't buffer it or create a reader).
But it does fix the vulnerability — data is only buffered if you ask for it to be buffered.
No test because I'm not really sure how you'd go about testing such a thing.
> use pull method

- packages/adapter-static/package.json
- packages/adapter-static/test/utils.js
- packages/kit/package.json
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/utils.js
- pnpm-lock.yaml
I was worried there was a race condition in `start_server`. If two workers find an open port, pick the same port, then try to start the server on it then there will be a failure. Using the built-in port finding mechanism would hopefully avoid this. Plus, one less dependency is always nice
> Remove need for port-authority

- documentation/docs/03-routing.md
__Docs change__
This change adds to the [advanced routing docs](https://kit.svelte.dev/docs/routing#advanced-routing-sorting) to include a note about predefined/static routes taking precedence over dynamic ones.
I think the existing docs attempted to do this by saying "More specific routes are higher priority" but it wasn't clear that a dynamic route would be less specific than a predefined route.
> [docs] clarify static route priority

- CONTRIBUTING.md
- packages/kit/test/apps/amp/test/test.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/apps/options-2/test/test.js
- packages/kit/test/apps/options/test/test.js
The tests have stopped hanging for me since https://github.com/sveltejs/kit/pull/5482. There is still flakiness. I'd like to debug that, but running the tests takes too long right now, so I'm hoping to re-parallelize them. Has https://github.com/sveltejs/kit/pull/5482 fixed the increased flakiness with parallelization that others were seeing? If not, perhaps we could find a compromise option like parallelize unless on the CI?
> [chore] speed up tests

- packages/kit/test/apps/basics/test/test.js
I noticed that one test had `close` in a `finally` and the others did not. It seems like a good idea, so I added it to the others
> [chore] ensure secondary test server is closed

- packages/kit/test/utils.js
When creating test traces, Playwright converts all spaces to `-`. I want to be sure it doesn't also convert `+` to `-` as that would make the names of the tests with and without javascript equivalent. This should make it clearer which trace I'm receiving
> [chore] clarify test names

- .changeset/hot-planes-shout.md
- packages/kit/src/utils/http.js
- packages/kit/src/utils/http.spec.js
- closes #4962  
- User encountered clients sending invalid accept header values in the wild, resulting in 500 error codes in logs.
- minor change, so I don't think this needs a changelog
> ignore invalid accept header values instead of throwing an error

- documentation/docs/12-page-options.md
prerendering happens in the Vite plugin - not the adapter
> [docs] clarify that prerendering isn't handled by adapters

- packages/kit/test/apps/basics/src/routes/accessibility/__layout.svelte
- packages/kit/test/apps/basics/test/test.js
This test fails in Firefox locally if you're OS settings prevent the browser from cycling through `<a>` elements (which is a completely mad, totally inaccessible default. Chrome gets this right).
This PR fixes it by using a `<button>` instead
> fix firefox test

- .github/workflows/ci.yml
@dominikg reported that this repo doesn't build on WIndows 10. The `windows-latest` tag will use Windows Server 2022 instead of Windows Server 2019, so I was curious if that would pick up the build failure. It doesn't but maybe is still worth using `windows-latest` to align with the fact that we use `ubuntu-latest`. Or should we pin it to 2022 so that if things break when they update the latest we won't be surprised?
> [chore] test using windows-latest

- .changeset/warm-knives-swim.md
- packages/adapter-static/platforms.js
- packages/adapter-vercel/README.md
- packages/adapter-vercel/index.js
As of today, all apps deployed to Vercel can use the [Build Output API v3](https://vercel.com/docs/build-output-api/v3). It's no longer necessary to set the `ENABLE_VC_BUILD` environment variable, and instead of only opting into v3 behaviour when that environment flag is set, we can always use the v3 behaviour. This means we can delete all the v1 code.
> remove ENABLE_VC_BUILD checks, use v3 build output API for all vercel apps

- .changeset/slimy-ways-applaud.md
- packages/adapter-node/package.json
- packages/adapter-node/src/index.js
- pnpm-lock.yaml
This is an alternative to #5491. Adding a new option that adds or disables the middleware feels like a bad precedent, and we've often wondered if it really belongs here (rather than at the load balancer level, for example).
Since we clearly document how to use the exported handler with a custom server, I think it's safe to err on the side of simplicity and just get rid of it
> remove `compression` middleware from adapter-node output server

- documentation/faq/80-integrations.md
- sites/kit.svelte.dev/src/lib/docs/server/index.js
- sites/kit.svelte.dev/vite.config.js
Since merging #5530, the site is failing to deploy because the FAQ isn't typechecking (this is a good thing — the system is working)
> fix faq, and make it easier to find the source of doc typechecking errors

- .changeset/large-seahorses-check.md
- packages/kit/src/vite/index.js
see https://github.com/sveltejs/kit/pull/5520#issuecomment-1184909493
> Alternative to #5520

- packages/kit/test/apps/amp/vite.config.js
- packages/kit/test/apps/options-2/vite.config.js
We're using these options in two of the test projects, but not in the other two. It probably makes sense to use them in all
> [chore] use consistent Vite options in test projects

- packages/kit/test/apps/amp/vite.config.js
- packages/kit/test/apps/basics/vite.config.js
- packages/kit/test/apps/options-2/vite.config.js
- packages/kit/test/apps/options/vite.config.js
I had some consistent flakes locally that I tracked down to being an issue with the Vite client reloading the page. I discovered it by seeing a cancelled request using Playwright Trace that seemed to be caused by a new requesting being issued. I tracked down the request initiator with the following code inserted at the beginning of the flaky test (must be before the first page visit with JavaScript enabled):
```
if (javaScriptEnabled) {
// ChromeDevTools/devtools-protocol#56
// increase CallStackDepth to fix initiator stack issue in chrome
const client = await page.context().newCDPSession(page);
await client.send('Debugger.enable');
await client.send('Debugger.setAsyncCallStackDepth', { maxDepth: 32 });
// #1395
// puppeteer request events don't propagate initiator currently
// so …
```
> [fix] disable HMR in tests

- .changeset/early-eagles-boil.md
- packages/adapter-vercel/index.js
> make resolution failures more appealing

- documentation/docs/15-configuration.md
There's basically nothing we can do to allow Svelte-controlled CSS transitions on a page with a `style-src` CSP directive that doesn't include `unsafe-inline`. Best we can do is document it.
Closes #5215
> document transition CSP caveat

- .changeset/twenty-vans-divide.md
- packages/adapter-vercel/index.js
> dont remove `.vercel/output` directory

- packages/adapter-cloudflare/README.md
This PR fixes 2 things in the `adapter-cloudflare` README.md
**Number One:**
- Per https://github.com/sveltejs/kit/issues/4916, SvelteKit has dropped Node 14 support.
- This PR updates the `adapter-cloudflare` docs to remove mentions about SvelteKit supporting Node 14.
**Number Two:**
- `_headers` and `_redirects` config files that Cloudflare Pages uses only apply to static assets, not server-side rendered pages.
- Info about these files was added to the README.md, this PR modifies this to add that important detail.
- Closes https://github.com/sveltejs/kit/issues/5575, reverts https://github.com/sveltejs/kit/pull/5453
> Updated adapter-cloudflare README

- packages/kit/scripts/extract-types.js
Makes it just a tad bit nicer to read, some examples (making it in one column so that the images are still visible)
|Before/After|
|---|
|1. `Load`|
|![image](https://user-images.githubusercontent.com/8156777/179534903-77ec932a-240e-4ed3-af3c-61b2e59bd41f.png)|
|![image](https://user-images.githubusercontent.com/8156777/179534972-ae93b6e0-2876-407f-9c9f-71e38c924010.png)|
|2. `RequestHandler` & `RequestHandlerOutput`|
|![image](https://user-images.githubusercontent.com/8156777/179535743-5f7faeae-712a-450d-b766-61aa4334f28b.png)|
|![image](https://user-images.githubusercontent.com/8156777/179535848-5480c86f-6fb6-462e-b445-ba6e02f06261.png)|
|3. etc.|
> bump prettier format print width

- .changeset/quick-boxes-reflect.md
- packages/kit/src/vite/index.js
to allow custom resolutions, local links etc
the previous implementation did a read of local devDependencies. That does not work when pnpm overrides are used, or the local devDependency is set to a link of a local version etc.
Vite exports it's version so just use that instead.
> fix: use actual vite version in version check 

- packages/create-svelte/test/check.js
enable prettier and eslint in create-svelte test projects and test most run scripts instead of just  `pnpm run check`
> test: extend create-svelte tests to cover most package.json scripts

- documentation/docs/00-introduction.md
As of Vite 3.0 the default dev server port is now 5173 and the preview server listening at 4173.
https://vitejs.dev/blog/announcing-vite3.html#vite-cli
> The default dev server port is now 5173

- .changeset/tough-dolls-relate.md
- packages/kit/src/runtime/client/client.js
Fixes #5415
The alternative fix would have been to do this in beforeunload, but this might result in more possibilities of flickering than the other way around.
I didn't know how to possibly write a test for this since this requires cross site navigation _and_ a bfcache hit.
> [fix] Reset navigating store upon return to site with a bfcache hit

- .changeset/smooth-cars-reflect.md
- packages/adapter-cloudflare-workers/index.js
- packages/adapter-cloudflare/index.js
- packages/adapter-netlify/index.js
- packages/adapter-node/index.js
- packages/adapter-static/index.js
- packages/adapter-vercel/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/adapt/builder.spec.js
- packages/kit/types/index.d.ts
Have `writeClient` write both the client and static files and remove `writeStatic`. This is a breaking change for adapter authors.
If we were using Vite's `publicDir` and `base` options it would put the static files into the client directory. This change will free us up to be able to utilize those options in the future. This change was prototyped in https://github.com/sveltejs/kit/pull/5601, but it's getting too large and complicated, so I'm breaking it up.
> [breaking] remove `writeStatic` to align with Vite

- .changeset/eleven-crews-knock.md
- packages/kit/src/vite/build/utils.js
- packages/kit/test/apps/basics/src/routes/cyclical-dynamic-import/_is_even.js
- packages/kit/test/apps/basics/src/routes/cyclical-dynamic-import/_is_odd.js
- packages/kit/test/apps/basics/src/routes/cyclical-dynamic-import/index.svelte
> handle circular dependencies in dynamic imports

- .changeset/lucky-plums-listen.md
- packages/kit/src/node/index.js
- packages/kit/test/apps/basics/src/routes/endpoint-output/stream-throw-error.js
- packages/kit/test/apps/basics/test/server.test.js
The reader can throw an exception if there is no interception, then the application will crashing.
> Handle the reader error

- .changeset/strong-cats-wonder.md
- packages/kit/src/core/generate_manifest/index.js
- packages/kit/src/vite/build/build_server.js
- packages/kit/src/vite/build/build_service_worker.js
- packages/kit/src/vite/build/utils.js
- packages/kit/src/vite/index.js
This fixes an issue that @userquin ran into trying to make `vite-plugin-pwa` work with SvelteKit. He was using Vite/Rollup's `emit` to output a service worker manifest and expecting it to be served from the root directory, but it was ending up under `_app`. `_app` is arguable only for stuff generated by SvelteKit though. I could imagine lots of other things like a `robots.txt` or something you might want to generate with a Vite plugin that need to go in a certain location and are impossible to put there today.
I also think the code ends up being a little nicer this was as we don't end up having to specify the app dir in quite as many places
I'm splitting this out from https://github.com/sveltejs/kit/pull/5601 as that PR was becoming too unwieldy
> [fix] change Vite's output directory from _app to client

- .changeset/tricky-maps-know.md
- packages/kit/src/node/index.js
- packages/kit/src/node/polyfills.js
> add formData method in superclass rather than monkey-patch

- README.md
grygrflzr's example isn't maintained and still on Vite 2, so remove it. Update the `vite-plugin-svelte` example to the ESM version
> [docs] update example Vite projects

- documentation/faq/50-aliases.md
The current FAQ for adding path aliases in the FAQ say to use `npm run sync` which no longer exists. From my understanding, it was replaced with `npm run prepare`, so I have updated the script name in the docs to prevent confusion.
- [] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0
> [docs] Change from "sync" to "prepare" script in alias FAQ

- .changeset/modern-jars-return.md
- packages/adapter-node/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/adapt/builder.spec.js
- packages/kit/src/vite/build/utils.js
- packages/kit/src/vite/dev/index.js
- packages/kit/src/vite/index.js
- packages/kit/src/vite/preview/index.js
Trying https://github.com/sveltejs/kit/commit/14c18e3cdf023b587e1946e1b012f33cadb8d82a again, but in a way that will pass the CI this time
This sets the `publicDir` option, but still uses our own `sirv` middleware to serve static assets. Having `publicDir` set though means that assets end up where expected for Vite plugins like `vite-plugin-pwa` and that they can find where we keep our assets
> set Vite's `publicDir` option

- .changeset/plenty-radios-turn.md
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/vite/dev/index.js
- packages/kit/test/apps/basics/src/routes/errors/stack-trace/_bad.js
- packages/kit/test/apps/basics/src/routes/errors/stack-trace/index.svelte
- packages/kit/test/apps/basics/test/server.test.js
please god let this be the last one of these. closes #3371
> prevent double stack trace 'fixes'

- .changeset/witty-carrots-notice.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/routing/slashes/index.svelte
- packages/kit/test/apps/basics/test/client.test.js
fixes #5087, by only normalising URLs we're navigating to once we've established that it's a page within the app
> only normalise internal URLs

- .changeset/soft-humans-cheer.md
- packages/kit/src/core/prerender/prerender.js
- packages/kit/src/vite/index.js
Remove `entries` and `files` from `prerender` function since they're difficult to construct entities. This will make https://github.com/sveltejs/kit/issues/5306 much easier to implement
> [chore] simplify internal prerender API

- .changeset/nasty-seahorses-know.md
- documentation/docs/06-hooks.md
- documentation/docs/17-seo.md
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/test/apps/amp/src/hooks.js
- packages/kit/test/apps/basics/src/hooks.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/prerendering/basics/src/hooks.js
- packages/kit/types/index.d.ts
Closes #4910.
This replaces the `transformPage` API with `transformPageChunk`, so that we can respond in a streaming fashion in future. We're not yet taking advantage of that ability, but updating the API is the first step.
Previously, `transformPage` took the entire HTML document:
```js
export function handle({ event, resolve }) {
return resolve(event, {
transformPage: ({ html }) => html.replace('old', 'new')
});
}
```
Now, it takes a _chunk_ of HTML plus a `done` boolean. Chunks are not guaranteed to be well-formed HTML (they might include the opening tag of an element but not its closing tag, for example) but nor are they arbitrary — they will always be split at sensible boundaries (like `%sveltekit.[property]%` or before the contents of a layout or page component). Because of that, …
> replace transformPage with transformPageChunk

- .changeset/modern-jars-return.md
- packages/adapter-node/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/adapt/builder.spec.js
- packages/kit/src/core/prerender/prerender.js
- packages/kit/src/vite/build/utils.js
- packages/kit/src/vite/dev/index.js
- packages/kit/src/vite/index.js
- packages/kit/src/vite/preview/index.js
Reverts sveltejs/kit#5648.
I don't know this for certain (the stack trace is truncated, and I don't have time to investigate more deeply), but it's pretty clear that Vite is trying to process requests that originate from `<script>` and `<link>` elements, whereas previously we were bypassing its static file handling.
I'm just going to revert this now because it's bad breaking change that seems to have affected a lot of people — we can take another run at it later, when we can figure out how to make those requests bypass Vite.
> Revert "set Vite's `publicDir` option"

- packages/kit/CHANGELOG.md
Automated tooling got the PR number wrong, so let's fix it. Specifically, #5683 is the PR that actually contains the code changes and justification for the changes. #5684 contains just the changeset that was forgotten in #5683. So the automated tooling picked up #5684 as the PR to put in the changelog, but #5683 is the one that anyone reading the changelog will actually care about. By switching the changelog contents to point to #5683 for this release, we let everyone avoid having to make an additional click to find the actually useful information.
I'm not including a changeset in *this* PR since it makes no code changes. Likewise, no issue link and no tests.
> Update PR number in CHANGELOG.md

- .changeset/nasty-falcons-ring.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/load/layout-props/__layout.svelte
- packages/kit/test/apps/basics/src/routes/load/layout-props/a.svelte
- packages/kit/test/apps/basics/src/routes/load/layout-props/b.svelte
- packages/kit/test/apps/basics/test/client.test.js
Fixes #5247 by not adding unchanged layout or page props to the root props
> [fix] Prevent needless prop updates causing rerenders

- .changeset/red-rivers-approve.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/load/change-detection/session/unused.svelte
- packages/kit/test/apps/basics/src/routes/load/change-detection/session/used.svelte
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/basics/test/test.js
Fixes #3732 (and maybe some other issue? Could have sworn I saw something similar about props running in another issue)
No test yet, want to confirm first that this is the right fix
> [fix] Prevent rerender when route state did not change

- .changeset/light-vans-suffer.md
- packages/adapter-node/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/adapt/builder.spec.js
- packages/kit/src/core/prerender/prerender.js
- packages/kit/src/vite/build/utils.js
- packages/kit/src/vite/dev/index.js
- packages/kit/src/vite/index.js
- packages/kit/src/vite/preview/index.js
- packages/kit/test/apps/basics/src/app.html
This is a second stab at https://github.com/sveltejs/kit/pull/5648 which was reverted for causing https://github.com/sveltejs/kit/issues/5672
The issue was that we were serving static files from within the Kit middleware, so the transform middleware was being executed on them. This moves static serving into its own middleware so that they're served without the transform middleware being called on them
> Set Vite's publicDir and correctly serve public assets earlier in pipeline

- packages/adapter-static/test/apps/prerendered/src/app.html
- packages/adapter-static/test/apps/spa/src/app.html
- packages/create-svelte/templates/default/src/app.html
- packages/create-svelte/templates/skeleton/src/app.html
- packages/kit/test/apps/amp/src/app.html
- packages/kit/test/apps/basics/src/app.html
- packages/kit/test/apps/options-2/src/app.html
- packages/kit/test/apps/options/source/template.html
- packages/kit/test/apps/writes/src/app.html
- packages/kit/test/prerendering/basics/src/app.html
- packages/kit/test/prerendering/fallback/src/app.html
- packages/kit/test/prerendering/options/src/app.html
- packages/kit/test/prerendering/paths-base/src/app.html
- packages/kit/test/prerendering/trailing-slash/src/app.html
- sites/kit.svelte.dev/src/app.html
This saves some bytes and avoids propagating an obsolete workaround. The initial scale _already_ defaults to 1. `initial-scale=1` in `viewport` was propagated widely by https://css-tricks.com/probably-use-initial-scale1/ (though css-tricks itself doesn't use it). It was necessary to work around [the orientation change bug](https://webdesignerwall.com/tutorials/iphone-safari-viewport-scaling-bug) in Safari for iOS < 9. iOS 9 was released in 2015 and iOS < 9 usage is extremely low in 2022.
https://webhint.io/docs/user-guide/hints/hint-meta-viewport/ seems authoritative about it no longer being necessary.
> Remove initial-scale=1 from <meta name="viewport">

- README.md
Recommend a simpler version of Vite SSR template for checking if it's a Vite bug.
Uses https://github.com/bluwy/create-vite-extra
> [docs] update vite ssr repro template

- .changeset/tiny-eels-hear.md
- packages/kit/scripts/special-types/$env+static+private.md
- packages/kit/src/core/sync/write_env.js
- packages/kit/types/ambient.d.ts
Generated JSDoc comments were malformed, and the current documentation didn't specify which variables are loaded to private modules (which, given the link to Vite, made it look like they were controlled by Vite's prefixing).
> hotfix: Small issues with recent environment variables PR

- .changeset/breezy-cooks-pump.md
- packages/kit/src/vite/dev/index.js
During dev the environment was loaded after the user hooks. When accessing variables from `$env/dynamic/private` in code that is executed while importing the hooks (or any dependent modules) the environment was empty.
> fix: load env before importing hooks during dev

- documentation/docs/18-assets.md
`svimg` is better maintained than `svelte-image`
> [docs] update example image preprocessor

- .changeset/tricky-moose-sip.md
- packages/create-svelte/templates/default/src/app.d.ts
- packages/create-svelte/templates/skeleton/src/app.d.ts
- packages/kit/src/core/sync/sync.js
- packages/kit/src/core/sync/write_ambient.js
- packages/kit/src/core/sync/write_env.js
Closes #5677. Includes reference to `@sveltejs/kit` types in ambient file, and removes reference from `app.d.ts`.
> feat: reference kit types in ambient file

- .changeset/gold-spies-fail.md
- packages/kit/src/vite/dev/index.js
- packages/kit/src/vite/index.js
- packages/kit/src/vite/utils.js
- packages/kit/src/vite/utils.spec.js
Closes #5723 and closes #5747. 
The paths for both Vite and Rollup's module graphs needed to be normalized, along with the illegal import paths.
Because Tailwind needs to analyze basically every file in your project, Vite thinks it imports all of them, meaning it'll almost always import `$env/*/private`, causing our helpful module analysis to be, well, unhelpful. In dev, we now ignore non-`js|ts|svelte` files. Rollup doesn't have this problem (because it doesn't have to worry about HMR), so we can be stricter and just analyze all imports. I think this strikes a happy medium. "Provide armor against footguns in dev, and provide even better armor when we try to go to prod."
> fix: `$env/*/private` throws for client-side imports on Windows and Tailwind doesn't freak out

- .changeset/big-coins-suffer.md
- packages/kit/src/runtime/client/client.js
Fix #5725
Because `url.origin` is not `"null"` in all browsers, it would be better to check `protocol` instead.
> fix: check url protocol instead of origin

- packages/kit/test/apps/amp/package.json
- packages/kit/test/apps/basics/package.json
- packages/kit/test/apps/options-2/package.json
- packages/kit/test/apps/options/package.json
- packages/kit/test/apps/writes/package.json
- packages/kit/test/prerendering/basics/package.json
- packages/kit/test/prerendering/fallback/package.json
- packages/kit/test/prerendering/options/package.json
- packages/kit/test/prerendering/paths-base/package.json
- packages/kit/test/prerendering/trailing-slash/package.json
In eef885be16b06852c481c5eac333f48941045961 (#5760) I broke the `"check"` scripts — this fixes them
> fix sync scripts

- .changeset/nine-bees-agree.md
- packages/kit/src/cli.js
Fixes #5769, hopefully. It's really hard to know this sort of thing for sure until we merge and publish.
> [fix] update CWD before running postinstall sync

- .changeset/hot-beds-tickle.md
- packages/kit/src/vite/utils.js
We're about to embark on a [significant redesign](https://github.com/sveltejs/kit/discussions/5748) that will touch many parts of the codebase. Until that work is finished, PRs are very likely to result in merge conflicts, and will likely be ignored until the redesign work is complete (by which time they will likely be stale). Please consider delaying your PR until then.
Thank you for understanding!
---
This fixes #5786 and #5784. I'd like a review from someone whose brain isn't fried. The problem is that the recursive import analysis was removing modules from `seen` when all of their children did not contain an illegal module. Somehow, this removal allowed cyclical imports to infinitely get stuck in a loop, but I just can't visualize how. It _seems_ like there should be some point at …
> fix: Prevent import cycles from crashing build

- .changeset/violet-jars-visit.md
- packages/kit/package.json
- packages/kit/test/apps/basics/src/routes/load/large-response/text.txt.js
- pnpm-lock.yaml
Had to update a test because Undici got a bit stricter about the spec in https://github.com/nodejs/undici/pull/1550
This test file will be moved in https://github.com/sveltejs/kit/pull/5778, but other than that should not cause any merge conflicts
> [chore] upgrade to Undici 5.8.1

- .changeset/famous-birds-boil.md
- packages/migrate/migrations/routes/utils.js
`test/prerendering/basics` failed to migrate because one of the files has spaces, which meant it was being interpreted as multiple arguments
> handle spaces in filenames when migrating

- .changeset/cuddly-ads-kick.md
- packages/migrate/migrations/routes/index.js
- packages/migrate/migrations/routes/migrate_scripts/index.js
- packages/migrate/migrations/routes/migrate_scripts/samples.md
- packages/migrate/migrations/routes/utils.js
harden declared logic around imports:
- remove type only load imports
- handle imports with same name as load exports
- bail on `export * from ..`
- handle undefined declared map.
> [fix] harden migration around imports

- .changeset/wise-hotels-matter.md
- packages/migrate/migrations/routes/migrate_page_js/index.js
- packages/migrate/migrations/routes/migrate_page_js/samples.md
- packages/migrate/migrations/routes/utils.js
.. and migrate props to data: props automatically
> [fix] check load function input

- .changeset/dull-pants-return.md
- packages/kit/src/vite/build/build_server.js
- packages/kit/src/vite/build/build_service_worker.js
- packages/kit/src/vite/build/utils.js
- packages/kit/src/vite/index.js
I've seen removing the plugin cause confusion for multiple people. I think a better way to do it is to leave it in place, but make it mostly a no-op in SSR mode. Plus it's less code, so that's nice
> [chore] get rid of remove_svelte_kit

- .changeset/cyan-radios-attend.md
- packages/adapter-node/index.js
- packages/adapter-node/package.json
- packages/adapter-static/index.js
- packages/adapter-static/package.json
- packages/kit/package.json
- packages/kit/src/core/adapt/builder.js
- packages/kit/types/index.d.ts
- pnpm-lock.yaml
Closes #3796
This PR move `compress` inside `builder` to avoid having it duplicate inside `adapter-node` and `adapter-static`.
We're about to embark on a [significant redesign](https://github.com/sveltejs/kit/discussions/5748) that will touch many parts of the codebase. Until that work is finished, PRs are very likely to result in merge conflicts, and will likely be ignored until the redesign work is complete (by which time they will likely be stale). Please consider delaying your PR until then.
Thank you for understanding!
---
> Move compress inside kit

- .changeset/red-masks-confess.md
- packages/migrate/migrations/routes/migrate_page_js/samples.md
- packages/migrate/migrations/routes/utils.js
Oversight from the previous PR
> [fix] Fix error placement on (arrow) function when checking load input

- documentation/docs/02-web-standards.md
- documentation/docs/03-routing.md
- documentation/docs/04-layouts.md
- documentation/docs/05-loading.md
- documentation/docs/09-a-options.md
- documentation/docs/15-configuration.md
- documentation/docs/16-types.md
- documentation/docs/17-seo.md
- documentation/docs/80-migrating.md
> Docs for the new API

- .changeset/rare-deers-hunt.md
- packages/kit/src/vite/build/build_server.js
- packages/kit/src/vite/build/utils.js
- packages/kit/src/vite/index.js
Workaround for https://github.com/vitejs/vite/issues/9636
Closes https://github.com/sveltejs/kit/issues/5803
> [fix] avoid manifest collisions

- .changeset/odd-trees-visit.md
- packages/kit/src/index/private.js
- packages/kit/src/runtime/server/page/index.js
- packages/kit/test/apps/basics/src/routes/shadowed/simple/post/+page.server.js
- packages/kit/test/apps/basics/test/server.test.js
- packages/migrate/migrations/routes/migrate_page_js/index.spec.js
- packages/migrate/migrations/routes/utils.js
Actions were broken in #5778, this fixes them
> fix actions

- .changeset/itchy-donuts-unite.md
- packages/kit/src/core/sync/create_manifest_data/index.js
Fixes #5893. No test because this depends on vagaries of where SvelteKit is running
> Only search for layout name in basename, rather than fully resolved pathname

- packages/migrate/migrations/routes/migrate_page_server/index.spec.js
lint is failing on https://github.com/sveltejs/kit/pull/5861. this should fix it
> [chore] fix migration test linting

- .changeset/swift-seahorses-argue.md
- packages/migrate/migrations/routes/index.js
- packages/migrate/migrations/routes/migrate_scripts/index.js
`npx svelte-migrate routes` creates a `+page.js` file if you have a `<script context="module" lang="ts">`, when it should instead create a `.ts` file. This fixes it
> create .ts files from `<script context="module" lang="ts">`

- .changeset/twelve-stingrays-cry.md
- packages/kit/src/core/sync/write_types.js
Fixes #5899 
Is there any other possible extensions? Should we have a utility function to extract and replace the extension of a filename?
> make generated type import path ends in `.js` 

- .changeset/good-mails-crash.md
- packages/kit/src/core/sync/write_types.js
Fixes #5899 
Applies the `.ts` to `.js` logic from #5907 (which only changed `AwaitedErrors`) to `AwaitedProperties`
> Fix generated path extension for AwaitedProperties types

- .changeset/slow-spiders-agree.md
- documentation/docs/04-advanced-routing.md
- packages/kit/src/core/sync/create_manifest_data/index.js
- packages/kit/src/core/sync/create_manifest_data/index.spec.js
> [feat] better clarify invalid named layout references

- .changeset/lazy-owls-run.md
- packages/kit/src/runtime/server/page/fetch.js
Fixes #5870.
If your app is, say, sitting behind some sort of API gateway that injects `Content-Length` into its incoming requests, and then you try to use `fetch` in `load` during SSR, Undici is going to have a bad time with that header.
This PR adds this header to the blacklist. This seemed like a pain to test because ordinarily this header isn't present, so I did not add a test.
> [fix] omit Content-Length header from requests made by load fetch

- .changeset/angry-peaches-warn.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/test/apps/basics/src/routes/actions/form-errors/+page.server.js
- packages/kit/test/apps/basics/src/routes/actions/form-errors/+page.svelte
- packages/kit/test/apps/basics/test/test.js
- packages/kit/types/internal.d.ts
> [fix] hydrate validation errors

- .changeset/brave-apricots-approve.md
- packages/kit/src/core/sync/write_types.js
- packages/kit/src/core/sync/write_types.spec.js
> [fix] Handle function without params when writing TS proxy

- .changeset/smooth-bags-sell.md
- packages/adapter-cloudflare-workers/files/entry.js
https://github.com/sveltejs/kit/pull/5081 already did it for adapter-cloudflare and both the docs and types for adapter-cloudflare-workers mention it, alas it wasn't returned.
---
> fix: actually expose platform.caches in adapter-cloudflare-workers

- documentation/docs/19-accessibility.md
Add docs around SvelteKit's accessibility features and what developers need to do to play nicely with them.
I focused these docs on SvelteKit-specific concerns (route announcements, focus management) instead of general a11y practices (e.g. skip link, button vs link, etc). In the future, a "Guides" section on learn.svelte.dev may be a good place to go deeper into general a11y best practices, or integrated into the official SvelteKit tutorial.
I'm looking for feedback on prose, accuracy of information, and thoughts on anything else we want to include (or exclude).
Leaving in draft for now until the dust settles on the big routing changes.
Prior art:
- [Next.js](https://nextjs.org/docs/accessibility)
- [Remix](https://remix.run/docs/en/v1/guides/accessibility)
- …
> Add accessibility documentation

- .changeset/tender-bottles-cheer.md
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/vite/build/build_server.js
- packages/kit/src/vite/dev/index.js
- packages/kit/test/apps/basics/src/routes/no-ssr/browser-only-global/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/types/internal.d.ts
> [fix] Lazy load Svelte components to reenable no-ssr use cases

- documentation/docs/01-project-structure.md
Fix param matchers reference on docs/01-project-structure.md
> Fix param matchers reference on docs

- .changeset/happy-peaches-visit.md
- packages/kit/src/core/config/index.spec.js
- packages/kit/src/core/sync/create_manifest_data/index.js
- packages/kit/src/core/sync/create_manifest_data/index.spec.js
Render pages without a .svelte file in their proper layout/error files
Fixes #5910
> [fix] manifest generation

- .changeset/chilled-years-smash.md
- packages/create-svelte/templates/default/src/lib/form.ts
This update does not quite change or add any functionality, but aims at improving the readability of the `form.ts` file from the default create-svelte app. I noticed `e` was used as the event argument, and then later in the same handler as an error variable. To me this was a bit confusing to read and it does not appear to hold significant value with a shorter variable name. For newcomers this can be off-putting or confusing reading multiple variables with the same name in the same function (despite block scoping)
> chore: give verbose names to form args "e"

- .changeset/sour-cherries-play.md
- packages/kit/src/core/sync/write_types.js
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/types.d.ts
- packages/kit/src/runtime/server/endpoint.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/index.js
- packages/kit/src/runtime/server/page/load_data.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/page/types.d.ts
- packages/kit/src/utils/escape.js
- packages/kit/types/index.d.ts
- packages/kit/types/private.d.ts
Fixes #5963, closes #5940 (by introducing the event types, which make proxy generation unnecessary if you use them)
- Tightens up the `Params` type in most places: It's `Partial<Record<string, any>>` for the generic type because if you don't type it, you don't know which values are on there. It's also needed in case of layouts where params could be present or not present dependening on the child route. This may be a breaking change for people using strict mode, not having explicitly typed the params generic, and accessing it without checking if it's defined.
- Adds event types for the load functions and the `RequestHandler`. Example: `export function load(params: PageLoadEvent) {..}` - this makes the generation of proxy JS files unnecessary (proxy files only update on file save and when …
> [fix] Fix params and parent data types

- .changeset/nasty-shoes-mate.md
- packages/kit/src/vite/dev/index.js
Attempt to fix #5941. No test because the bug doesn't happen inside the workspace
> avoid double import of `$env/dynamic/[mode]` modules

- packages/kit/types/index.d.ts
these types arguably don't belong in `@sveltejs/kit` but for now it's where they live, and it probably makes sense to provide them. more importantly, it gets the site building again
> add types for config.package so the docs build

- .changeset/gentle-news-shout.md
- packages/kit/src/runtime/server/page/index.js
- packages/kit/test/apps/basics/src/routes/shadowed/post-success-redirect/+page.server.js
- packages/kit/test/apps/basics/src/routes/shadowed/post-success-redirect/+page.svelte
- packages/kit/test/apps/basics/src/routes/shadowed/post-success-redirect/redirected/+page.svelte
- packages/kit/test/apps/basics/test/test.js
Closes #5976
Sets status to 303 when a POST handler returns a location.
> [fix] set `status` to 303 when POST provides a `location`

- .changeset/twenty-numbers-breathe.md
- packages/kit/package.json
- pnpm-lock.yaml
Now that `svelte-kit package` is no longer a part of core SvelteKit, it no longer needs `chokidar` as a dependency.
> [chore] remove chokidar as dependency of kit

- .changeset/gorgeous-snakes-pretend.md
- packages/kit/src/runtime/server/page/index.js
- packages/kit/test/prerendering/basics/src/routes/redirect-server/+page.server.js
- packages/kit/test/prerendering/basics/test/test.js
Fixes the docs (currently if you client-side-nav to `/docs`, it hangs)
> Prerendered server redirects

- .changeset/gold-rocks-hang.md
- documentation/docs/15-configuration.md
- packages/create-svelte/templates/libskeleton/src/app.d.ts
- packages/kit/types/index.d.ts
- packages/package/src/types.d.ts
- packages/package/types/index.d.ts
Some missed updates from #5730
> packaging migration cleanup

- .changeset/fresh-pigs-tease.md
- packages/kit/src/runtime/server/page/index.js
- packages/kit/test/apps/basics/test/server.test.js
Closes #5936. This behaviour is nothing more than a historical accident. It's buggy, and there's no reason to keep it.
If we want routes to serve both HTML and non-HTML, #5896 is a more promising approach.
> remove ability for +page.server.js to respond to GET requests with JSON

- .changeset/selfish-tips-divide.md
- packages/create-svelte/shared/+typescript/package.json
Helps with #5779
I argue this is a good addition because you could be making changes to the code base while not running `vite dev`, so changes are not reflected, and then when you the command it would have out-of-date `$types`.
> [fix] Run svelte-kit sync before svelte-check in check scripts

- .changeset/mighty-students-develop.md
- packages/kit/src/vite/utils.js
- packages/kit/src/vite/utils.spec.js
> [fix] Handle windows paths and regexp chars in kit.alias

- .changeset/honest-parrots-compare.md
- packages/kit/src/runtime/server/endpoint.js
- packages/kit/test/apps/basics/src/routes/errors/endpoint-throw-error/+server.js
- packages/kit/test/apps/basics/src/routes/errors/endpoint-throw-redirect/+server.js
- packages/kit/test/apps/basics/test/server.test.js
Fixes #5993
This results in a (in my opinion correct) change in behavior: If you `throw` an `error`, you will no longer have the message rendered in the nearest `+error.svelte`, instead it's just blank text, which is what I'd expect from querying a regular endpoint.
> [fix] Handle `throw error/redirect` in `+server.js`

- .changeset/ninety-fans-cover.md
- packages/kit/types/index.d.ts
> [fix] make errors in Action less restrictive

- .changeset/wise-berries-pay.md
- packages/kit/src/core/sync/write_types.js
- packages/kit/src/core/sync/write_types.spec.js
Was wrong if a layout referenced a named layout in the same folder
Fixes #6013
> [fix] correct parent data type for layouts

- .changeset/tiny-pears-check.md
- packages/kit/src/runtime/client/client.js
This is a hack, but it's a working quick solution. Fixes #5980
> [fix] Silence unknown prop warnings coming from SvelteKit

- .changeset/ninety-snakes-melt.md
- packages/migrate/migrations/routes/index.js
- packages/migrate/migrations/routes/migrate_scripts/index.js
- packages/migrate/migrations/routes/migrate_scripts/index.spec.js
- packages/migrate/migrations/routes/migrate_scripts/samples.md
Should make migration easier in most cases. I've seen enough people do exactly this by hand (or suggest doing this), so I think it's worth suggesting automatically.
> [feat] Suggest props destructuring if possible

- .changeset/ninety-vans-talk.md
- packages/kit/src/core/sync/write_types.js
Fixes #6044
Also fixes layout params. They wrongfully contained the slugs above them, too.
> [fix] Generate types when Svelte file missing

- .changeset/famous-boxes-tap.md
- packages/kit/src/vite/build/utils.js
- packages/kit/src/vite/index.js
part of solution for https://github.com/sveltejs/kit/issues/5952
see https://github.com/sveltejs/kit/issues/5952#issuecomment-1218844057, where some of the ids mentioned are in `.vite` and the `?v=hash` query is also a sign
> fix: prevent optimizeDeps for @sveltejs/kit

- .changeset/lazy-ants-watch.md
- packages/kit/src/runtime/client/client.js
Fixes #6080. Not sure if we need a more comprehensive approach to preventing these sorts of things from slipping in, but for now I think the easiest thing is just to remove it.
> Remove use of `[].at(-1)` in client code

- packages/create-svelte/test/check.js
the `create-svelte` tests are absurdly verbose, and it makes it very hard to find actual problems when reviewing CI failures
> make create-svelte tests a bit less look-at-me

- .changeset/ten-gorillas-itch.md
- packages/kit/src/core/config/index.spec.js
- packages/kit/src/core/config/options.js
Throw error if browser.hydrate is false and brower.router is true. The router needs at least the router component to be hydrated, and we currently can't dynamically compile Svelte components as hydratable or not on case-by-case basis
Closes #4382
> [fix] Throw on invalid browser options

- .changeset/rich-walls-doubt.md
- packages/kit/src/utils/routing.js
- packages/kit/src/utils/routing.spec.js
Prior to this PR, if you had a route that started with an encoded `@` symbol, it would not recognize the route because it split it based on the decoded `@` symbol which is used for named layouts. This PR moves the decoding until after the split.
In the following setup, `/@foo` would not be accessible.
```
routes/
%40foo/
+page.svelte
+page.svelte
```
> Fix pattern matching for `@` encoded routes

- .changeset/tidy-mice-kick.md
- packages/kit/src/core/sync/write_types.js
When you create only two files:
```
+layout-root.server.js
+layout-root.svelte
```
`import("./$types").LayoutServerLoad.root` is undefined. I guess it is due to a copy-paste typo.
> Fix wrong LayoutServerLoad.name type

- .changeset/wet-crews-smoke.md
- packages/adapter-vercel/index.js
This should use the same esbuild platform setting as the Cloudflare adapter, as Vercel Edge Functions are based on Cloudflare Workers. I discovered this issue while using the Supabase JS client.
> [FIX] Use the 'browser' platform setting for esbuild for Vercel Edge Functions

- .changeset/tricky-cheetahs-warn.md
- packages/kit/src/core/sync/create_manifest_data/index.js
Prior to this PR, the following setup results in the encoded route being sorted before the `+error.svelte` component. This results in a build failure as the encoded route references the default error component.
```
routes/
%40foobar/
+page.svelte
+error.svelte
```
> Prioritize sorting of +error files

- documentation/docs/15-configuration.md
- documentation/faq/50-aliases.md
this FAQ was originally about Vite stuff, but now that it's about SvelteKit it should probably just live in the main docs
> [docs] fold alias FAQ into alias docs

- .changeset/ninety-walls-heal.md
- packages/kit/src/runtime/app/stores.js
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/page/load_data.js
There are a few objects in the codebase with getters that give more helpful errors messages that describe what features have replaced these removed/renamed features. However, these getters are also triggered when doing an object `{ ...spread }`, which isn't very helpful. This updates these to use `Object.definedProperties` so that we may specify `enumerable: false` on these getters.
> use enumerable: false for temporary no-longer-exists getters

- .changeset/olive-ducks-talk.md
- packages/migrate/migrations/routes/migrate_page_js/index.js
- packages/migrate/migrations/routes/migrate_page_js/samples.md
- packages/migrate/migrations/routes/migrate_page_server/index.js
- packages/migrate/migrations/routes/migrate_page_server/samples.md
- handle error without message, fixes #6088
- automigrate status 200 in load
- handle GET without body (which is wrong, but people could have that)
> [fix] Migration fixes

- .changeset/hot-lions-cough.md
- .changeset/warm-pots-melt.md
- packages/create-svelte/shared/+checkjs/jsconfig.json
- packages/create-svelte/shared/+typescript/tsconfig.json
- packages/kit/src/core/sync/write_tsconfig.js
Also add some notes to tsconfig/jsonfig
Fixes #5833
I briefly thought about making this configurable through `kit.files`, but didn't do so because only the tsconfig includes generation would benefit from it - you'd still need to update the package.json scripts yourself.
> [fix] add test folder to includes

- documentation/docs/05-load.md
Make clear that a load rerun does not remount the page
From https://github.com/sveltejs/kit/discussions/5883#discussioncomment-3437736
> [docs] clarify load rerun behavior

- packages/kit/types/index.d.ts
I was reading the docs and saw a missing code wrap on `+server.js`.
| Before Change | After Change |
| - | - |
| ![image](https://user-images.githubusercontent.com/20136585/185929893-ac60639b-51f6-4e64-933c-fa29ea5a92fd.png) | ![image](https://user-images.githubusercontent.com/20136585/185929915-bd23a3b4-676d-4977-8a29-dfaa24ce3e2b.png) |
> added inline code wrapper

- .changeset/quiet-comics-crash.md
- packages/kit/src/core/sync/write_tsconfig.js
When using a vite.config.ts (instead of a vite.config.js) TypeScript generates an error:
```
error TS2307: Cannot find module '@sveltejs/kit/vite' or its corresponding type declarations.
1 import { sveltekit } from "@sveltejs/kit/vite";
~~~~~~~~~~~~~~~~~~~~
Found 1 error in vite.config.ts:1
```
Adding the **vite.config.ts** to the includes fixes this issue.
Also closes #5443
> fix: Add support for vite.config.ts

- packages/kit/types/index.d.ts
A follow-up to #6175
I believe this should be marked as optional, as well as to make it consistent with the other properties
> make env properties optional

- packages/kit/scripts/special-types/$env+static+private.md
> clarify empty env vars

- documentation/docs/05-load.md
Clarifies both where the dependency exists and that `depends` has a var args param. The example was initially unclear to me as it looked to be showing one URL depending on another.
> [docs] clarify depends docs

- .changeset/small-apples-visit.md
- packages/kit/src/core/sync/write_types.js
Introduced a bug in #6174 — a route without a `+page|layout[.server].js` or `+server.js` wouldn't have `$types.d.ts` created for it, even though that file would be referenced by a child route that inherited from it. This is the correct check.
No test added because it was already causing failures (at a loss as to how it snuck through CI previously, but 🤷)
> always create $types.d.ts for a route with layout, leaf or endpoint

- documentation/docs/18-assets.md
I previously removed a reference to `matyunya/svelte-image`, but missed one as well it appears. That library is unmaintained, so probably better not to mention it. Also, after digging in more to it and `xiphux/svimg` I think neither are ideal because they are preprocessors and so don't integrate well with the Vite processing pipeline.
> [docs] update asset docs

- .changeset/strong-cooks-run.md
- packages/kit/src/runtime/server/page/index.js
fixes #6243.
Explanation:
1. Unless `config.kit.prerender.enabled` is set to `false`, SvelteKit will always try to prerender pages
2. It begins with all known static paths (e.g. `/`) and crawls from there
3. If it finds that a page is not prerenderable (i.e. `config.kit.prerender.default = false` or `prerender = false`) it will bail out
4. Otherwise it will continue, and generate the `.html` file — and, if appropriate, the `__data.json` file that powers it
5. When `ssr` is `false`, it returns the response before checking to see if the page is prerenderable
6. As such, SvelteKit believes that routes were prerendered when they in fact weren't
7. Routes that we know were prerendered are removed from the generated manifest, so that servers and serverless functions don't bundle code for stuff …
> only generate non-SSR pages when prerendering

- packages/kit/test/apps/amp/playwright.config.js
seeing a lot of timeouts on the safari tests for some reason, possibly a combination of the machine being underpowered and the AMP validator being a steaming turd
> increase timeout to a silly number

- .changeset/moody-plums-mate.md
- packages/create-svelte/templates/default/src/lib/form.ts
- packages/kit/types/ambient.d.ts
After #5778 you have to `invalidate()`, not `invalidate(location.href)`, as there's no longer just a single endpoint that corresponds to the page itself.
Fixes #6240
> invalidate data after form submit

- .changeset/khaki-foxes-applaud.md
- .changeset/loud-lions-walk.md
- .changeset/shiny-gifts-drive.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/index.js
- packages/kit/src/runtime/server/page/load_data.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/page/respond_with_error.js
- packages/kit/src/utils/url.js
- packages/kit/src/utils/url.spec.js
- packages/kit/test/apps/basics/src/routes/load/invalidation/url/+page.server.js
- packages/kit/test/apps/basics/src/routes/load/invalidation/url/+page.svelte
- packages/kit/test/apps/basics/src/routes/routing/hashes/pagestore/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/types/index.d.ts
Closes #6199
Closes #6126
Something we noticed recently is that our use of accessors on `RequestEvent` and `LoadEvent` made it difficult to do this sort of thing:
```js
const augmented_event = { ...event, extra_stuff };
```
On `RequestEvent`, we had `get clientAddress` — this PR changes that to `getClientAddress`, which is a breaking change.
On `LoadEvent`, we previously had `get url`. But we don't actually need to track whether `url` was accessed, just whether its _properties_ were accessed (and only the properties that could change during a session — not `url.origin` etc), allowing `load` functions to be more conservative about when they re-run.
I also noticed we weren't previously tracking `url` access when loading server data, which is now fixed.
> remove getters

- .changeset/friendly-dodos-exercise.md
- packages/kit/src/core/sync/write_types/index.js
- packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/(main)/$types.d.ts
- packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/(main)/sub/$types.d.ts
- packages/kit/src/core/sync/write_types/test/layout/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/simple-page-server-and-shared/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/simple-page-server-only/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/simple-page-shared-only/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/nested/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/nested/[...rest]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/nested/[slug]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/[...rest]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/[slug]/$types.d.ts
- packages/kit/types/index.d.ts
- T extends Record<string, any>  allows T to be an array, Record<string, known> doesn't, closes #6261
- RequestHandler generic is partial now to align with the other types and prevent type conflicts
- generate definite set of route params, this is more correct and makes hover info better
> [fix] type tweaks

- documentation/docs/05-load.md
> clarify when load runs

- .changeset/two-pianos-stare.md
- packages/create-svelte/templates/default/src/lib/form.ts
error:
```
/home/dominikg/develop/sveltejs/kit/.test-tmp/create-svelte/default-checkjs/src/lib/form.js:31:31
Error: A binding pattern parameter cannot be optional in an implementation signature. 
*/
export function enhance(form, { pending, error, result } = {}) {
let current_token;
```        
see https://github.com/microsoft/TypeScript/issues/49869
first caught by vite-ecosystem-ci but also fails kit's own ci.
> [fix] type definition update for typescript 4.8

- .changeset/neat-cameras-swim.md
- packages/kit/src/core/sync/write_types/index.js
- packages/kit/src/core/sync/write_types/index.spec.js
> [fix] prevent unused types warning

- .changeset/rotten-mice-compete.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/load/server-data-reuse/no-load/+page.svelte
- packages/kit/test/apps/basics/src/routes/load/server-data-reuse/with-server-load/+page.server.js
- packages/kit/test/apps/basics/src/routes/load/server-data-reuse/with-server-load/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/types/internal.d.ts
Don't reuse server load data from previous page if current doesn't have a load function
Fixes #6300
> [fix] wrong reuse of server load data

- CONTRIBUTING.md
> [docs] update path to vite plugin in contributing guide

- .changeset/funny-keys-appear.md
- packages/kit/src/core/sync/write_root.js
my page utilizing server actions was not receiving errors in `export let errors`... until now!
sorry about the half hearted PR, pretty sure this API is going to change dramatically soon anyway.
thank you for building this project
> set errors on root component - relates to #6279

- sites/kit.svelte.dev/src/lib/docs/server/index.js
This does not expose any user-visible changes, but makes it easier to enable TypeScript support to the docs backend. allowing me to write code blocks in TypeScript
Using this throughout the docs would require a larger overhaul to render both JS and TS and add a toggle between them, so I'm not sure that's something I'll do in the short-term. However, this is helpful in allowing me to experiment with stuff like adding a TypeScript example to our homepage to demonstrate that we provide TypeScript type declarations.
> [docs] don't hardcode file extension in docs server

- .changeset/shiny-sloths-juggle.md
- packages/adapter-netlify/src/edge.js
- packages/adapter-vercel/files/edge.js
This fixes a regression created in #6327, due to the usage of top level await, which isn't supported in Vercel Edge Functions right now.
Using a deferred promise and awaiting within the response it practically the same thing, but works.
> [adapter-vercel] don't use top level await in Vercel Edge Functions

- .changeset/short-comics-unite.md
- packages/kit/src/core/sync/write_client_manifest.js
- packages/kit/src/runtime/client/ambient.d.ts
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/parse.js
Fixes #6349
Fixes #6336
While fixing it I thought of ways to make the manifest shorter. I did that in a second commit so it can be reverted if not appropriate.
No test, I can't think of a way to test this without creating another test app, which I wanted to avoid - but can do so if we feel it's necessary.
> [fix] encode if root layout has server load

- packages/kit/package.json
We need to place `"types"` as the first one according to https://nodejs.org/api/packages.html#community-conditions-definitions, though I don't think there's any problem so far, so we probably don't need a changeset for this.
> move types export to the top

- packages/kit/package.json
> [chore] tiny-glob doesn't need to be dependency and devDependency

- CONTRIBUTING.md
> update contributing entry points

- .changeset/hip-trains-vanish.md
- packages/kit/package.json
Removed some obsolete packaging references, and updated the glob pattern as we're still publishing [`sync/write_types` test suites](https://github.com/sveltejs/kit/tree/master/packages/kit/src/core/sync/write_types/test)
> prevent test suites getting published

- .changeset/quiet-poems-tease.md
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/utils/escape.spec.js
- packages/kit/types/internal.d.ts
When we started serializing server data with devalue, the old JSON serialization of it was left in. This removes it.
This also updates the types so that `server_data` is no longer a valid `type` to pass to `render_json_payload_script`. This required a slight adjustment to the unit tests.
> [fix] remove vestigial JSON server_data

- .changeset/weak-hotels-hang.md
- packages/package/src/config.js
- packages/package/src/utils.js
- packages/package/test/fixtures/resolve-alias/expected/Test.svelte
- packages/package/test/fixtures/resolve-alias/expected/package.json
- packages/package/test/fixtures/resolve-alias/expected/utils/index.d.ts
- packages/package/test/fixtures/resolve-alias/expected/utils/index.js
- packages/package/test/fixtures/resolve-alias/src/lib/Test.svelte
- packages/package/test/fixtures/resolve-alias/src/lib/utils/index.ts
- packages/package/test/fixtures/resolve-alias/svelte.config.js
- packages/package/test/fixtures/resolve-alias/tsconfig.json
Related to https://github.com/sveltejs/kit/issues/1950
This PR includes support for other aliases besides `$lib` for the package command. It reads the alias information from `kit` object in `svelte.config.js`.
I'm not sure this is the correct approach, open to suggestions and improvements.
> [feat] support for other aliases in package command

- .changeset/big-trainers-love.md
- packages/adapter-node/README.md
- packages/adapter-node/ambient.d.ts
- packages/adapter-node/index.js
- packages/adapter-node/package.json
- packages/adapter-node/rollup.config.js
- packages/adapter-node/src/handler.js
- packages/adapter-node/src/index.js
- packages/kit/types/index.d.ts
- pnpm-lock.yaml
This closes #3176, by always bundling dev dependencies using `esbuild`. Supersedes #6301.
> Bundle non-prod dependencies with esbuild

- .changeset/dull-cheetahs-clean.md
- .changeset/lovely-otters-lie.md
- packages/create-svelte/templates/default/src/app.d.ts
- packages/create-svelte/templates/libskeleton/src/app.d.ts
- packages/create-svelte/templates/skeleton/src/app.d.ts
- packages/kit/scripts/special-types/$env+dynamic+private.md
- packages/kit/scripts/special-types/$env+dynamic+public.md
- packages/kit/src/core/env.js
- packages/kit/src/core/sync/write_ambient.js
- packages/kit/src/runtime/env-private.js
- packages/kit/src/runtime/env-public.js
- packages/kit/test/build-errors/apps/private-dynamic-env-dynamic-import/src/app.d.ts
- packages/kit/test/build-errors/apps/private-dynamic-env/src/app.d.ts
- packages/kit/test/build-errors/apps/private-static-env-dynamic-import/src/app.d.ts
- packages/kit/test/build-errors/apps/private-static-env/src/app.d.ts
- packages/kit/types/ambient.d.ts
> Generate dynamic env types

- .changeset/unlucky-elephants-appear.md
- packages/kit/package.json
#6413 broke everything — `svelte-kit sync` no longer works in `postinstall` (or indeed anywhere else) because the files `write_ambient` depends on aren't included in the package.
Gonna expedite a release for this one as it's... quite a bad bug
> include type descriptions in package

- documentation/docs/02-web-standards.md
- documentation/docs/11-adapters.md
- documentation/docs/80-migrating.md
- documentation/faq/80-integrations.md
closes https://github.com/sveltejs/kit/issues/6414
> [docs] fix broken links to endpoint docs

- .changeset/red-rice-bathe.md
- packages/kit/src/exports/hooks/sequence.js
- packages/kit/src/exports/hooks/sequence.spec.js
- packages/kit/types/ambient.d.ts
Closes #4051.
After this change, a `transformPageChunk` option passed to the first `handle` in a sequence will be respected by later calls to `resolve`
> merge `resolve` options when using `sequence`

- .changeset/calm-steaks-yell.md
- packages/kit/package.json
- pnpm-lock.yaml
see https://github.com/sveltejs/vite-plugin-svelte/issues/422
> fix: bump vite-plugin-svelte to 1.0.3 to fix  svelte-inspector in vite 3.1

- packages/kit/src/exports/hooks/sequence.js
- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
I got some improvements and bug fixes into `vite-imagetools` which makes it easier to use. The other half of our `vite-imagetools` usage is in `site-kit` and that half is simplified a fair amount in https://github.com/sveltejs/sites/pull/371/commits/96b71053efc3736c91c25bbb86597b9a380fd5df.
`lint` is failing, but it must be unrelated to this PR
> [chore] upgrade vite-imagetools

- .changeset/odd-sloths-sit.md
- packages/kit/src/runtime/server/index.js
this was causing confusion — see #6473
> print error message if `resolveOpts.ssr` is set

- sites/kit.svelte.dev/src/routes/+page.svelte
- sites/kit.svelte.dev/src/routes/Hero.svelte
Missed a few things last time around:
- passing an unused `width` property
- ended up with `undefined` width due to using `width` vs `w`
- also added `sizes` and generated smaller images for mobile
This should be the last of the image cleanup in this repo for awhile
> [site] hero fixes

- .changeset/cold-penguins-share.md
- packages/adapter-netlify/index.js
Closes #6490
With this PR `tiny-glob` only grab files and skip over directories. Currently it's possible to trip netlify-adapter if a route name ends in .js
> Fix netlify-adapter to only glob files

- .changeset/odd-months-grow.md
- packages/kit/src/runtime/server/utils.js
- packages/kit/test/apps/basics/test/server.test.js
closes #1931.
Today, if you have a route like this...
```js
// src/routes/error/+server.js
export function GET() {
throw new Error('yikes');
}
```
...then visiting `/error` will show you the fallback error page:
If you `fetch` the page with an `application/json` header, you'll get a JSON representation of the error...
...but by default `fetch` will get HTML. In most cases that's probably not that helpful.
This PR reverses the precedence during content negotiation, so that if a request has an `accept: */*` header (which `fetch` requests do, by default) it will prefer JSON to HTML.
> prefer JSON error responses over HTML in fetch case

- .changeset/ninety-tables-switch.md
- .changeset/rude-nails-work.md
- .changeset/shiny-vans-jam.md
- documentation/docs/05-load.md
- packages/create-svelte/templates/default/src/lib/form.ts
- packages/kit/src/runtime/app/navigation.js
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/types.d.ts
- packages/kit/test/apps/basics/src/routes/load/change-detection/one/[x]/+page.svelte
- packages/kit/test/apps/basics/src/routes/load/invalidation/forced/+page.svelte
- packages/kit/types/ambient.d.ts
Closes #6354.
Related to #6489, #6274 and #5305 (we can remove the `breaking change` label from the latter two once this is merged).
It's very possible that we'd need to add an `options` object to `invalidate(...)` in future. Since overloaded functions are a terrible idea, that'd mean that to accommodate the no-argument case where you want to invalidate everything, we'd have to do this...
```js
invalidate(undefined, {...});
```
...which is sinful. A better approach, which happens to be clearer and easier to document, is to create a new `invalidateAll` function:
```diff
<script>
-  import { invalidate } from '$app/navigation';
+  import { invalidateAll } from '$app/navigation';
</script>
-<button on:click={() => invalidate()}>reload</button>
+<button on:click={() => …
```
> future-proof `invalidate()`

- packages/create-svelte/templates/default/vercel.json
- sites/kit.svelte.dev/vercel.json
Not sure what changed, but these started resulting in deployment errors:
They don't seem to be doing anything anyway, so I'll just delete them
> remove incorrect vercel.json files

- .changeset/selfish-ads-kick.md
- packages/kit/package.json
- pnpm-lock.yaml
to avoid vite 3.1.0-beta peerDependency warning
> fix: update vite-plugin-svelte dependency 

- packages/create-svelte/templates/default/vercel.json
- sites/kit.svelte.dev/vercel.json
Reverts sveltejs/kit#6513. Turns out this was a temporary glitch. The bot is super noisy so having this config is nice
> Revert "remove incorrect vercel.json files"

- .changeset/nice-poets-taste.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/test/client.test.js
Fix https://github.com/sveltejs/kit/issues/6463 by automatically skipping prefetching of external URLs instead of warning app developers. This aligns with how Next.js solves the same problem.
> fix: Silently skip prefetching external URLs instead of warning

- .changeset/fresh-brooms-relate.md
- packages/kit/src/core/generate_manifest/index.js
- packages/kit/src/runtime/client/parse.js
I was seeing this in the CI logs:
It's happening because `JSON.stringify` turns `undefined` to `null` inside an array, unhelpfully. Bit weird that it isn't actually causing anything to fail, but I figured it was worth fixing anyway
> fix server manifest generation

- .changeset/breezy-ladybugs-dance.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/types.d.ts
- packages/kit/test/apps/basics/src/routes/after-navigate/a/+page.svelte
- packages/kit/test/apps/basics/src/routes/after-navigate/b/+page.svelte
- packages/kit/test/apps/basics/src/routes/store/navigating/+layout.svelte
- packages/kit/types/index.d.ts
closes #6551 — gives `beforeNavigate` and `afterNavigate` more information about which route they are navigating from and to
> augment `Navigation` type

- .changeset/spicy-games-trade.md
- documentation/docs/09-link-options.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/utils.js
#6532. This updates the docs to clarify that `data-sveltekit-prefetch` and `data-sveltekit-prefetch=""` are equivalent, and also adds console errors at dev time if you pass an incorrect value.
> Warn about incorrect `data-sveltekit-x` values

- .changeset/red-tomatoes-leave.md
- packages/kit/src/runtime/server/page/fetch.js
- packages/kit/test/apps/basics/src/routes/load/cors/+page.js
- packages/kit/test/apps/basics/src/routes/load/cors/+page.svelte
- packages/kit/test/apps/basics/src/routes/load/cors/no-cors/+page.js
- packages/kit/test/apps/basics/src/routes/load/cors/no-cors/+page.svelte
- packages/kit/test/apps/basics/test/test.js
closes #5074, by increasing the fidelity of the server-side `fetch` implementation passed to `load`. If a request is made for an external resource, and it doesn't respond with an appropriate `access-control-allow-origin` header, it will fail the same way that the browser's `fetch` fails (albeit with a different error message, since there's no standardisation here). 
If the request was made with `no-cors`, we return a response with an empty body.
> simulate CORS errors in server-side fetch

- .changeset/hot-mayflies-visit.md
- packages/kit/src/exports/vite/build/utils.js
Fix #4644
This disables a [Rollup optimization](https://rollupjs.org/guide/en/#why-do-additional-imports-turn-up-in-my-entry-chunks-when-code-splitting) which shouldn't affect us as we use esbuild to-rebundle for most adapters.
> disable hoistTransitiveImports by default

- packages/kit/src/core/sync/create_manifest_data/index.js
- packages/kit/src/utils/routing.js
very minor fix — this stuff doesn't need to be in `parse_route_id`, where it gets included in the client runtime. We only need to do these checks at manifest generation time
> move some stuff out of client-facing code

- .changeset/blue-wombats-shake.md
- documentation/docs/11-page-options.md
- documentation/docs/14-configuration.md
- packages/adapter-static/index.js
- add the file ending, which should make it more clear where to put things (even if some use .ts, they'll get the idea)
- remove obsolete config
Closes #6538
> [docs] prerendering adjustments

- .changeset/modern-apricots-develop.md
- packages/create-svelte/templates/default/package.template.json
- packages/create-svelte/templates/default/src/hooks.ts
demo app is due for a more comprehensive overhaul, but we can at least simplify stuff using the new `cookies` API in the meantime
> remove cookie from demo app

- .changeset/tall-plums-join.md
- documentation/docs/06-form-actions.md
- packages/kit/src/runtime/server/page/actions.js
We can't have default actions next to named actions, because if you POST to a named action without a redirect, the query parameter is persisted in the URL, which means the next default POST would go through the named action from before.
> [breaking] disallow default and named actions next to each other

- .changeset/cyan-elephants-accept.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/cookie.spec.js
Fixes #6609. 
After a cookie is deleted with `cookies.delete('foo')`, subsequent calls in the same request to `cookies.get('foo')` will return `undefined`.
> [fix] cookies.delete  

- .changeset/five-seas-end.md
- packages/kit/src/exports/vite/build/utils.js
Fixes https://github.com/sveltejs/kit/issues/6563
SvelteKit expects paths don't end with `/` and Vite expects that they do
> [fix] address Vite warning when using base or asset path

- packages/kit/scripts/special-types/$env+dynamic+private.md
It wasn't immediately clear to me, https://github.com/sveltejs/kit/issues/6204, that `$env/dynamic` might be loaded differently depending on `dev`/`prod`. Because `$env/dynamic` included `.env` during `dev`, I erroneously assumed it would do the same during `prod` (a la dotenv) when using `adapter-node`.
The second sentence could be clearer but I don't know enough about the topic to make it so.
> [docs] Highlight different `$env/dynamic` behavior between `dev` and `prod`

- .changeset/strange-adults-rest.md
- packages/create-svelte/templates/default/src/routes/todos/+page.svelte
- packages/kit/src/runtime/app/forms.js
- packages/kit/types/ambient.d.ts
closes #6630. This makes two breaking changes to the `enhance` action:
1. the input `form` is now `element`, and refers to the element the action was added to. To type that, the function and the SubmissionFunction interface now both take three generic params instead of two.
2. The returned callback is a `({ element, form, data, result }) => {...}` function instead of just `(result) => {...}`. This makes it easier to do things like `use:enhance={() => whatever}`, where `whatever` is a function that (for example) calls `form.reset()`.
> change use:enhance signature to support `<button formaction>`

- documentation/docs/06-form-actions.md
Docs show it as `(result)` which is not correct, instead it is a property of the argument object.
> Result is a property of the use:enhance callback

- .changeset/forty-news-kiss.md
- documentation/docs/01-project-structure.md
- packages/kit/src/core/config/default-error.html
- packages/kit/src/exports/vite/build/build_server.js
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/test/apps/basics/src/error.html
If you use `error.html` and customized it, replace `%sveltekit.message%` inside it with `%sveltekit.error.message%`
Closes #6645
> [breaking] change sveltekit.message to sveltekit.error.message

- .changeset/violet-wolves-reflect.md
- packages/kit/src/runtime/app/forms.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte
- packages/kit/test/apps/basics/test/test.js
- packages/kit/types/ambient.d.ts
This is a breaking change because the `element` property was removed from `enhance` and the action only is possible to apply to forms again; also the interface generic has been removed accordingly.
Fixes #6660
Superseedes/closes #6658 
Reverts #6633, because we can achieve the same with `event.submitter`
> [breaking] only allow enhance on form; pass abort controller

- .changeset/long-icons-hope.md
- documentation/docs/07-hooks.md
- packages/kit/src/runtime/client/client.js
See here if you want to know how to migrate: #6586
- add missing changeset, closes #6664
- enhance docs, closes #6669
- fix fallback message in client
> [fix] error rework cleanup

- .changeset/red-cherries-fly.md
- packages/adapter-node/src/handler.js
- packages/adapter-vercel/files/serverless.js
- packages/kit/src/exports/node/index.js
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/src/exports/vite/preview/index.js
- packages/kit/types/ambient.d.ts
A few things changed here:
- allow HTTP/2 streaming. i.e. undefined `content-length` when using HTTP/2
- I have no idea wtf `err.reason` was. Changed it to `err.message`
- made `getRequest` take a single arg so that we can easily add a new option to it like `bodySizeLimit` (https://github.com/sveltejs/kit/issues/6542) if we want the adapter to handle that option
> [breaking] request creation cleanup

- .changeset/tricky-ducks-kneel.md
- packages/adapter-node/README.md
- packages/adapter-node/src/handler.js
- packages/kit/src/exports/node/index.js
- packages/kit/types/ambient.d.ts
closes https://github.com/sveltejs/kit/issues/6542
> [breaking] limit adapter-node request size

- documentation/docs/19-accessibility.md
Accessibility docs updated to match changes of #6586. `hooks.js` should be `hooks.server.js`
> Updated accessibility doc to match hooks.server.js

- .changeset/tiny-houses-matter.md
- packages/kit/src/runtime/app/forms.js
- packages/kit/types/ambient.d.ts
Already had a use for the new `action` property passed to `enhance`, though I immediately wanted it to be a `URL` instead of a `string`, since the most likely thing you'll want to do with it is check `action.searchParams.has('/foo')` etc
> make action passed to enhance callback a URL

- .changeset/modern-falcons-tan.md
- .changeset/twelve-points-knock.md
Fixes #6690. This changed in #6586 but that didn't include changesets.
> add create-svelte changeset for hooks and use:enhance changes

- documentation/docs/01-project-structure.md
In the [project structure](https://kit.svelte.dev/docs/project-structure) docs there is a `tests` subheading listed within `Project files` and a `test` subheading listed within `Other files`. Feels like a duplication. This change will remove the `test` subheading.
> docs: remove `test` subheading in the project-structure

- documentation/docs/00-introduction.md
- documentation/docs/80-migrating.md
While working on another PR, I noticed that a couple links were full absolutely links with a host, which is unnecessary, and might be confusing to someone running the site locally.
This does _not_ update any of the absolute links to kit.svelte.dev in any readmes or in any published types, because we do need those to continue to be fully absolute.
> [docs] remove absolute host from some internal docs links

- packages/adapter-static/README.md
An often recurring question using the static adapter in SPA mode is why it keeps seeing "file not found" after being deployed.  This confusion stems from the idea that SvelteKit can somehow handle the redirects necessary.  This change adds a small explainer text to remind developers that this is something they have to configure themselves as it fully depends on what kind of server they use.
> Add explainer on configuring hosts with SPA mode.

- .changeset/friendly-starfishes-yell.md
- packages/adapter-cloudflare-workers/package.json
- packages/adapter-cloudflare/package.json
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-vercel/package.json
- packages/create-svelte/templates/default/package.json
- packages/kit/test/build-errors/apps/server-only-folder-dynamic-import/package.json
- packages/kit/test/build-errors/apps/server-only-folder/package.json
- packages/kit/test/build-errors/apps/server-only-module-dynamic-import/package.json
- packages/kit/test/build-errors/apps/server-only-module/package.json
- pnpm-lock.yaml
I was wondering why my project's lockfile had gotten so much longer after a recent upgrade, and at least part of the reason is that Vite 3.1.0 is bringing in esbuild 0.15 and the adapters are bringing in 0.14. This updates all of the adapters to ^0.15.6, the same range as Vite currently uses.
While I was at it, I also updated some dev deps on Vite throughout this repo from the 3.1.0 beta to ^3.1.0, so we don't have two versions of Vite getting installed.
> [chore] update adapters to esbuild 0.15

- documentation/docs/07-hooks.md
#6565 replaced the `externalFetch` hook with a more generic `handleFetch` which isn't specific to requests with external URLs. I think this part of the documentation wasn't updated to reflect that, it should no longer say "...for an external resource..." in the definition of the `handleFetch` hook.
> Remove "for an external resource" from the definition of `handleFetch`

- .changeset/twenty-apricots-grin.md
- packages/adapter-node/index.js
- packages/adapter-static/index.js
Improving the performance by running the independent async functions in parallel ✈️.
_Sorry if I made any mistakes :(_
> Improve performance by compressing in parallel

- .changeset/blue-glasses-compete.md
- packages/kit/types/index.d.ts
> [fix] ActionData type

- documentation/docs/12-page-options.md
I was searching for the word initialize and found that the wording in the documentation is somewhat inconsistent. I choose the predominant wording which is the American one. I'm open to changing it the other way around.
> Language consistency: initialise -> initialize

- .changeset/eight-vans-exercise.md
- packages/adapter-auto/README.md
- packages/adapter-auto/adapters.js
This PR adds a check for [Azure Static Web Apps](https://docs.microsoft.com/en-us/azure/static-web-apps/overview) to adapter-auto. If it succeeds, it uses [svelte-adapter-azure-swa](https://github.com/geoffrich/svelte-adapter-azure-swa), which I maintain. This package is not automatically added as a dependency of adapter-auto, users need to install it first.
The check uses the `GITHUB_ACTION_REPOSITORY` [environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) to check if we are building using the [Azure SWA action](https://github.com/Azure/static-web-apps-deploy). Azure SWA builds on GitHub actions by default.
I tested this using patch-package on one of my SWA projects and it seemed to work.
> [feat] support Azure Static Web Apps in adapter-auto

- .changeset/funny-cycles-travel.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/routing/hashes/pagestore/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
> [fix] update current.url on hashchange

- .changeset/immaculate-error-handler.md
- packages/adapter-vercel/index.js
> fix traced warnings from unexpected token

- .changeset/gorgeous-flowers-doubt.md
- packages/kit/src/runtime/client/client.js
Fixes #5980
This could result in false negatives but the probability for that is minimal and not seing the warning sometimes is better than seing the warning without being able to do anything about it
> [fix] silence prop warnings

- documentation/docs/05-load.md
No longer true with new handleError
> [docs] remove obsolete note

- .changeset/five-jobs-drum.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/load/url-query-param/+page.js
- packages/kit/test/apps/basics/src/routes/load/url-query-param/+page.server.js
- packages/kit/test/apps/basics/src/routes/load/url-query-param/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/basics/test/test.js
> [fix] reuse server data while not reusing client load

- .changeset/six-pants-melt.md
- packages/kit/src/core/sync/write_types/index.js
Fixes #6842 - Types are not properly updated for routes under group layouts
Routes were not found by id under group layouts. replacing '\' with '/' fixes this for route id's.
> Fixes #6842: Routes were not found by id under group layouts

- documentation/docs/06-form-actions.md
The https://kit.svelte.dev/docs/form-actions promote a security vulnerability:
> ## Authentication Responses
> Using any of the authentication mechanisms (login, password reset or password recovery), an application must respond with a generic error message **regardless** of whether:
>
> - The user ID or password was incorrect.
> - The account does not exist.
> - The account is locked or disabled.
>
> The objective is to prevent the creation of a [discrepancy factor](https://cwe.mitre.org/data/definitions/204.html), allowing an attacker to mount a user enumeration action against the application.
Source: https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#authentication-responses
> doc: Improved security in code example

- .changeset/chatty-moose-love.md
- packages/kit/types/index.d.ts
Fixes #6865. The return type of `cookies.get` is `string|undefined`, not `string|void`.
> change return type of cookies.get back to string|undefined

- .changeset/light-eagles-call.md
- packages/create-svelte/shared/+eslint+prettier/package.json
- packages/create-svelte/shared/+prettier/.prettierrc
- packages/create-svelte/shared/-eslint+prettier/package.json
- packages/create-svelte/test/check.js
fixes #6804 
i'm not sure why this is needed again, it was previously removed in favor of the `pluginSearchDirs` setting in prettierrc. 
Now we use both.
Note: the tests for create-svelte received 2 updates
1) pin them to the same vite version kit uses to avoid type incompatibility errors with `pnpm check` during tests
2) updated list of tested commands to include `format`, remove `prepare` and sort them differently
> fix: prettier not working for svelte files in create-svelte projects

- packages/kit/src/core/sync/write_types/index.js
- packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/(main)/$types.d.ts
- packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/(main)/sub/$types.d.ts
- packages/kit/src/core/sync/write_types/test/layout/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/simple-page-server-and-shared/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/simple-page-server-only/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/simple-page-shared-only/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/nested/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/nested/[...rest]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/nested/[slug]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/[...rest]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/[slug]/$types.d.ts
- packages/kit/types/index.d.ts
Implementing the stuff discussed in #6869
Return type of load functions are correctly merged if not returned directly ([example](https://github.com/sveltejs/kit/pull/6869#issuecomment-1250377159))
All generated `*Data` type exports are more readable.
> improve readability of generated types

- .changeset/cyan-pianos-bake.md
- packages/package/src/utils.js
- packages/package/test/fixtures/typescript/expected/Plain.svelte
- packages/package/test/fixtures/typescript/src/lib/Plain.svelte
- packages/package/test/fixtures/typescript/svelte.config.js
> [fix] don't strip type="application/.." tags

- .changeset/cool-beans-only.md
- packages/kit/src/core/sync/write_types/index.js
fix write_types on windows. paths still had `'\'` which causes lookup on routes by id to fail.
the `posixify(path:string)->string` function should have been used rather than `path.posix` to align with how paths are handled elsewhere in the same file.
> [fix] #6842 - write_types does not work on windows

- .changeset/young-students-relate.md
- packages/kit/src/runtime/client/client.js
#6770. Small QOL improvement — if you log the navigation object, it shouldn't invoke the getters that throw an error telling you not to use `from` and `to` as URLs
> make URL property getters non-enumerable

- .changeset/odd-beds-smile.md
- packages/adapter-node/index.js
- packages/adapter-node/package.json
- pnpm-lock.yaml
Alternative to #6855, which is itself an alternative to #6797.
With this PR, we bundle `adapter-node` apps with Rollup instead of esbuild. It's slower, but avoids https://github.com/evanw/esbuild/issues/1921 which doesn't look like it'll be fixed any time soon (even though there's a PR — https://github.com/evanw/esbuild/pull/2067), and means that we can deal with both ESM and CJS dependencies without adding more configuration.
> bundle with rollup instead of esbuild

- .changeset/smart-forks-double.md
- packages/package/src/utils.js
As commented on #6887 the stripping fails for our project https://github.com/Brain-Bones/skeleton. We are not doing anything with application/ that that ticket is trying to remedy, but I can't see a way to figure out which file is making this fail.  This is a simple fix that makes packaging work for us again.
> Quick check for undefined s4

- .changeset/flat-owls-care.md
- .changeset/short-spies-relax.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/index.js
- packages/kit/test/apps/basics/src/hooks.server.js
- packages/kit/test/apps/basics/src/routes/cookies/serialize/+server.js
- packages/kit/test/apps/basics/src/routes/routing/symlink-from
- packages/kit/test/apps/basics/test/server.test.js
- packages/kit/types/index.d.ts
Successor to https://github.com/sveltejs/kit/pull/6888
Closes https://github.com/sveltejs/kit/issues/6735
- fixes a bug where cookies and headers were only set when the request matched a route
- implements `cookies.serialize`
> add cookies.serialize function and always set headers/cookies

- .changeset/five-tools-arrive.md
- .changeset/strong-baboons-travel.md
- packages/adapter-node/src/handler.js
- packages/adapter-vercel/files/serverless.js
- packages/kit/src/exports/node/index.js
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/src/exports/vite/preview/index.js
> Respond with status code 413 if request body is too large

- .changeset/dirty-candles-peel.md
- packages/kit/src/core/sync/create_manifest_data/index.js
- packages/kit/src/core/sync/create_manifest_data/index.spec.js
> [fix] allow missing routes folder

- .changeset/orange-rocks-return.md
- packages/adapter-cloudflare/index.js
Looks like #6530 broke Cloudflare Pages deployments. I think this should fix it, if I understand correctly. cc @jrf0110 and @jahands for visibility
```
18:01:33.742 | Found _routes.json in output directory. Uploading.
18:01:33.761 | Validating asset output directory
18:01:34.611 | Deploying your site to Cloudflare's global network...
18:01:39.781 | Parsed 1 valid header rule.
18:01:44.711 | Success: Assets published!
18:01:45.627 | Error: Failed to publish your Function. Got error: Error 8000057: Rules must start with '/' in _routes.json
```
> Ensure all excluded files in `_routes.json` start with /

- .changeset/mean-chefs-swim.md
- packages/kit/src/runtime/server/page/csp.js
- packages/kit/types/private.d.ts
Add `wasm-unsafe-eval` keyword to `BaseSource` to conform to CSP directive [source list](https://www.w3.org/TR/CSP/#framework-directive-source-list)
> CSP add wasm-unsafe-eval

- .changeset/hot-steaks-hang.md
- packages/kit/src/runtime/server/page/fetch.js
- packages/kit/test/apps/basics/src/routes/load/fetch-origin-external/+page.js
- packages/kit/test/apps/basics/src/routes/load/fetch-origin-external/+page.svelte
- packages/kit/test/apps/basics/src/routes/load/fetch-origin-internal/+page.js
- packages/kit/test/apps/basics/src/routes/load/fetch-origin-internal/+page.svelte
- packages/kit/test/apps/basics/src/routes/load/fetch-origin-internal/resource/+server.js
- packages/kit/test/apps/basics/test/server.test.js
Add the `Origin` header to server-side fetch. 
The problem has been introduced with #6550, where browser CORS behaviour was simulated for the server-side requests. For CORS requests to work properly, the `Origin` header is mandatory.
Fixes: #6608
> fix: (issue-6608) Add origin header to server-side fetch

- .changeset/kind-adults-drum.md
- documentation/docs/07-hooks.md
- packages/create-svelte/templates/default/src/app.d.ts
- packages/create-svelte/templates/skeleton/src/app.d.ts
- packages/create-svelte/templates/skeletonlib/src/app.d.ts
- packages/kit/src/core/sync/sync.js
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/types.d.ts
- packages/kit/src/runtime/control.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/utils.js
- packages/kit/types/ambient.d.ts
- packages/kit/types/index.d.ts
- packages/kit/types/internal.d.ts
closes #6905. This is a breaking change, but I expect it to be very limited in impact.
> rename `App.PageError` to `App.Error`

- .changeset/flat-dancers-sell.md
- packages/kit/src/runtime/server/endpoint.js
- packages/kit/test/prerendering/options/src/routes/+layout.svelte
- packages/kit/test/prerendering/options/src/routes/rss.xml/+server.js
- packages/kit/test/prerendering/options/test/test.js
Fixes #5079. Most of the pieces were in place, but currently SvelteKit errors if you have a `<link>` in a prerendered page that points to a non-prerenderable `+server.js` file. 
With this PR, if the crawler hits those routes, it won't error but nor will it prerender the route.
> allow prerendered pages to link to non-prerenderable endpoints

- packages/kit/test/apps/basics/test/client.test.js
It looks like the test is still flaking out. I think it's because you could get the response, check the value, and then the value is updated. Writing it this way avoids that possibility
> [chore] fix flaky test

- .changeset/cold-wasps-flow.md
- packages/kit/src/core/sync/write_types/index.js
- packages/kit/src/core/sync/write_types/test/simple-page-server-only/_expected/$types.d.ts
In a case like this...
```svelte
<script>
/** @type {import('./$types').ActionData} */
export let form;
</script>
```
...`form` is `undefined` until a form is submitted, but that isn't reflected in the types.
> allow `ActionData` to be undefined

- .changeset/hungry-flowers-hope.md
- packages/kit/postinstall.js
> only run postinstall if package.json exists

- .changeset/blue-lizards-type.md
- packages/kit/src/core/sync/write_types/index.js
- packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/(main)/$types.d.ts
- packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/(main)/sub/$types.d.ts
- packages/kit/src/core/sync/write_types/test/layout/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/simple-page-server-and-shared/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/simple-page-server-only/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/simple-page-shared-only/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/nested/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/nested/[...rest]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs-layout-not-all-pages-have-load/_expected/nested/[slug]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/[...rest]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/[slug]/$types.d.ts
> [fix] prevent never for data types, notice moved/deleted files

- .changeset/sharp-beers-learn.md
- packages/kit/src/runtime/app/forms.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte
- packages/kit/test/apps/basics/test/test.js
> Add the submitter value with name to formData for use:enhance

- .changeset/seven-roses-float.md
- packages/migrate/migrations/routes/migrate_page_server/samples.md
- packages/migrate/migrations/routes/utils.js
Previously, any other top level statement such as an import wrongfully failed the uppercase migration
> [fix] more robust uppercase migration

- .changeset/proud-dingos-sing.md
- packages/adapter-netlify/rollup.config.js
- packages/adapter-node/index.js
- packages/adapter-node/rollup.config.js
Fix #6931
Set `prefersBuiltin: true` explicitly for `@rollup/plugin-node-resolve` to suppress warning (it's true by default).
I also set it for the `rollup.config.js` used to build `adapter-node` and `adapter-netlify` itself for consistency.
> [fix] remove builtin modules warning for adapter-node

- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/basics/test/test.js
Dedup `Promise.all([page.waitForNavigation(), ...` by using `clicknav` test utility
> use `clicknav` utility in test suites

- .changeset/tame-horses-design.md
- packages/create-svelte/templates/default/src/routes/sverdle/+page.server.ts
- packages/create-svelte/templates/default/src/routes/sverdle/words.server.ts
There's a bug in Vite's SSR module transformation — this code...
https://github.com/sveltejs/kit/blob/99929adca2834b09af37d8259d3f0280e8a7c1df/packages/create-svelte/templates/default/src/routes/sverdle/%2Bpage.server.ts#L83-L97
...breaks because the `const [index, guesses, answers]` line causes it to mistakenly think that the `answers` import is shadowed, when it's actually in a different scope. I don't have time to create a repro/issue on Vite right now, but fixing the demo app is a high priority.
> Work around vite bug

- .changeset/honest-tips-wonder.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/cookie.spec.js
- packages/kit/types/index.d.ts
Alternative to #7039. Prevents cookies from being discarded on Safari, which doesn't respect `secure` cookies when on insecure `localhost`.
> default to insecure cookies on http://localhost

- documentation/docs/12-adapters.md
The link was broken, but the type definition exists in `index.d.ts` in the same directory, so I updated the link to that file.
> Fixed link to Adapter type definition

- .changeset/pretty-pigs-give.md
- packages/kit/src/core/prerender/prerender.js
- packages/kit/src/runtime/server/index.js
- packages/kit/test/prerendering/basics/src/routes/初めまして/+page.svelte
Fixes #7074
From what I can see the proposed changes in the issue are correct, there's nothing encoding the routeId prior to the code where it is then encoded for the header
> [fix] decode routeIds in headers for prerendering

- .changeset/metal-adults-pay.md
- documentation/docs/16-configuration.md
- packages/kit/src/core/prerender/prerender.js
- packages/kit/types/ambient.d.ts
Closes #4528
On thing I'm wondering is if we should auto-prepend the base path when using `goto`. This is an API under our control, so we could safe people from prepending it there all the time. It would probably be a breaking change though for everyone who already does this. And it would also probably need an option to turn it off if you actually want to redirect relative to the domain root. So maybe ... don't do this after all?
> [docs] explain ramifications of base path

- .changeset/many-planes-taste.md
- packages/create-svelte/index.js
- packages/create-svelte/package.json
- packages/create-svelte/types/index.d.ts
Export types from `create-svelte` package.
Closes #7053.
> [feat] extract and export types from `create-svelte`

- .changeset/eleven-seahorses-report.md
- packages/adapter-cloudflare-workers/README.md
- packages/adapter-cloudflare-workers/index.d.ts
- packages/adapter-cloudflare-workers/index.js
Fixes: #7103 
Adds the ability to use a config file other than `wrangler.toml`, like:
```js
import adapter from '@sveltejs/adapter-cloudflare-workers';
export default {
kit: {
adapter: adapter({ config: '<your-wrangler-name>.toml' })
}
};
```
> adapter-cloudflare-workers: Configure custom wrangler.toml file name

- documentation/docs/03-routing.md
- packages/kit/src/core/sync/write_types/index.spec.js
- packages/kit/src/core/sync/write_types/test/layout-advanced/(main)/+page.js
- packages/kit/test/apps/basics/test/client.test.js
There are mentiones of `page.js` and `layout.js` where instead `+page.js` and `+layout.js` should be mentioned.
> make comment, tests & docs match the new route naming

- .changeset/funny-elephants-brake.md
- packages/adapter-node/package.json
- packages/kit/package.json
- packages/kit/src/exports/node/polyfills.js
- pnpm-lock.yaml
This upgrades the version of `undici` used by Kit to one that support multipart form data, removes `node-fetch` as a dependency, and removes the hack in polyfills.js.
It also removes `node-fetch` as a (dev) dependency to `adapter-node`, because it was only being used in tests, which are currently not being run. We'll have to revisit this later anyway if we want to run those tests in CI, at which point we can hopefully rewrite them to use something other than `node-fetch`.
There is still `node-fetch@2.6.7` in our tree via some other dependencies that we can't do much about, but this PR is able to remove the `node-fetch@3` dependency.
> [chore] bump undici for multipart form data support

- .github/workflows/ci.yml
- .github/workflows/release.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- .changeset/early-kiwis-raise.md
- packages/kit/src/exports/node/index.js
In #3572 to fix #3566 we started stripping HTTP/2 pseudo-headers from the incoming requests because `node-fetch`'s `Request` implementation couldn't handle them. This may or may not have been possible to revert when we switched to `undici` and were only using `node-fetch` for its multipart formdata handle - but it should certainly be possible now that we're not using `node-fetch` at all.
My understanding is that there's currently something else amiss with Vite's `--https` mode, so I tested this with the Node adapter and a custom entrypoint defining an HTTP/2 server, as described in #3566, and things seemed to work fine.
This change _does_ mean that `event.request.headers` will start having these HTTP/2 pseudo-headers present when an HTTP/2 server is being used, but this is probably safe - …
> [chore] remove unnecessary Request pseudo-header removal

- .changeset/chilled-suns-travel.md
- documentation/docs/10-service-workers.md
- packages/kit/src/exports/vite/build/build_service_worker.js
- packages/kit/test/prerendering/basics/src/service-worker.js
- packages/kit/test/prerendering/basics/test/test.js
- packages/kit/test/prerendering/basics/vite.config.js
Closes https://github.com/sveltejs/kit/issues/6329 and https://github.com/sveltejs/kit/issues/5682.
Implements Option 1 proposed by @Rich-Harris in https://github.com/sveltejs/kit/issues/6329#issuecomment-1229207997
Vite constant replacement using define only applies to service-worker builder.
> [fix] service-worker builder constant replacement

- .changeset/curvy-suits-sleep.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/cookie.spec.js
- packages/kit/src/runtime/server/fetch.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/index.js
- packages/kit/src/runtime/server/page/load_data.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/page/respond_with_error.js
- packages/kit/src/runtime/server/page/types.d.ts
- packages/kit/src/runtime/server/utils.js
- packages/kit/test/apps/basics/src/routes/load/serialization/+page.js
- packages/kit/test/apps/basics/src/routes/load/serialization/+page.server.js
- packages/kit/test/apps/basics/src/routes/load/serialization/+page.svelte
- packages/kit/test/apps/basics/src/routes/load/serialization/fetched-from-server.json/+server.js
- packages/kit/test/apps/basics/src/routes/load/serialization/fetched-from-shared.json/+server.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/types/index.d.ts
Closes #6320. This moves SvelteKit's `fetch` wrapper to `RequestEvent` so that it can be used by server-only `load` functions and `+server.js` handlers as well as shared `load` functions. (It can even be used in `handle`, or — somewhat pointlessly — inside `handleFetch`, as a consequence of where it now lives.)
Marking as draft because we're no longer using (or able to use) `GENERIC_ERROR`, and I'm not quite sure what the consequences of that are just yet.
> Add `fetch` to `RequestEvent`

- .changeset/four-crabs-beg.md
- packages/kit/src/runtime/server/page/render.js
I noticed the `link`s on my site are actually quite far down. This puts them first
> [perf] render head links before other content

- documentation/docs/02-web-standards.md
The phrase:
> for e.g. getting data that
Doesn't make sense. English is hard, and choosing the "correction" here is a matter of opinion, but I think dropping the "e.g." makes the intent clear and gets rid of an abbreviation that serves no purpose. 
Thanks for considering!
Ref: https://www.merriam-webster.com/words-at-play/ie-vs-eg-abbreviation-meaning-usage-difference
> [docs] remove extra e.g.

- packages/kit/src/core/sync/write_types/index.js
Fixes: #7201
Updating the syntax of sveltekit postinstall script so that in a library handling node 14 nothing is complaining.
This PR is not meant to support node 14 in SvelteKit, it's just to pass postinstall script for libs supporting node 14 is other environements.
> [fix] postinstall working on node 14

- .changeset/sharp-lies-grin.md
- packages/adapter-netlify/index.js
We used to do this and somehow lost it, which has been causing me frustration. I'm pretty sure we do it in the other adapters though I didn't confirm that
> [fix] clear out build directory when running `adapter-netlify`

- sites/kit.svelte.dev/src/lib/search/SearchResultList.svelte
> prevent overflowing headers in search results

- sites/kit.svelte.dev/src/lib/search/search.js
According to https://github.com/nextapps-de/flexsearch/blob/9abb781357f04e7db8529654c6941009771f4bf1/src/index.js#L106, `Index` is now the default export.
> fix flexsearch usage

- .changeset/pretty-scissors-march.md
- packages/kit/src/runtime/server/page/actions.js
fixes #7224 
Throws an error that suggests a fix instead of displaying `[object Object]`.
The new error message:
`Cannot "throw invalid()". Use "return invalid()"`
> add custom error message for `throw invalid()` in actions

- .changeset/yellow-kids-marry.md
- packages/create-svelte/templates/default/src/routes/sverdle/+page.svelte
fixes #7238
provides a custom form `enhance` callback for the demo app `/sverdle` to prevent `form.reset()` being called by the default callback.
> Fix sverdle form reset

- .changeset/smooth-waves-accept.md
- packages/adapter-cloudflare-workers/files/entry.js
- packages/adapter-cloudflare-workers/index.js
- packages/adapter-cloudflare/index.js
- packages/adapter-cloudflare/src/worker.js
- packages/adapter-netlify/index.js
- packages/adapter-netlify/src/edge.js
- packages/adapter-node/index.js
- packages/adapter-node/src/handler.js
- packages/adapter-vercel/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/generate_manifest/index.js
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/src/exports/vite/index.js
- packages/kit/types/index.d.ts
- packages/kit/types/internal.d.ts
Prefixes appDir with config.kit.paths.base for adapter-(cloudflare, cloudflare-workers, netlify). Didn't touch node, as there's some discussion around how that should be handled differently in #3726. Would be great if @asendia and @tv42 could test the adapters for their respective issues, since I've never used those platforms with sveltekit.
I'm aware it would be better if the base path was handled outside of SvelteKit instead of creating nested folders like this, but (at least for workers sites), I can't think of a better alternative.
fixes #4442, fixes #2843, fixes #3726
- add manifest.prefix and builder.getAppPrefixDirectory()
- adapter-cloudflare*: use manifest.prefix instead of manifest.appDir
- adapter-netlify: use prefixed appDir for cache headers
- adapter-vercel: use prefixed …
> feat: use config.kit.paths.base for static assets

- .changeset/ten-pets-tease.md
- packages/kit/src/exports/vite/build/build_server.js
fixes: #7166
Continuation, because I've noticed that it does not correctly resolve absolute paths to relative - if routes are relative paths outside of `cmd`  Also I think it's more robust  way to get relative path rather than using splice.
> fix: properly convert absolute paths to relative

- .changeset/dull-wombats-train.md
- packages/kit/src/runtime/client/client.js
Fixes #6496
Takes the approach mentioned here: https://github.com/sveltejs/kit/issues/6496#issuecomment-1233650328
Maybe @Rich-Harris can shed some light on what he ment with the two follow-up comments: Why checking the origin would be better, or why it isn't that easy after all (if you use the protocol check, it is easy, unless I missed something)
Edit: I'm answering this myself - when the protocol is different, we don't know if this will result in "nothing" (like `mailto:`) or an external navigation - which is why the logic isn't that easy (I guess that's what Rich meant). I think we should finalize and merge 
#6813 first and then come back to this to figure out the best way to handle this. My idea is to "take note" of the navigation if the protocol is different, and then in …
> [fix] better navigation protocol check

- .changeset/wild-bags-cheat.md
- packages/create-svelte/templates/skeletonlib/package.template.json
After running `svelte-package` (via `create-svelte`), the user is supposed to
run: `npm publish package/`. However, it is easy to accidentally run 
`npm publish` on the wrong directory out of habit. With this change, 
when the user accidentally tries to publish the `./` directory, they will be 
directed to publish the `./package/` directory instead.
In case it is useful, thanks.
> Direct user to publish `./package/` directory instead of `./`

- .changeset/spotty-kangaroos-peel.md
- packages/kit/src/core/sync/write_tsconfig.js
$types.d.ts files not referenced in user code were not loaded on startup in the IDE, because the includes list did not contain references to them. This resulted in suboptimal DX because they're not part of autocompletion suggestions or even unrecognized then.
> [fix] add $types to includes for better DX

- .changeset/serious-llamas-smoke.md
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/page/actions.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/utils.js
- packages/kit/test/apps/basics/test/test.js
> [fix] more informative serialization error messages

- .changeset/tame-bats-tell.md
- documentation/docs/13-page-options.md
- documentation/docs/16-configuration.md
- packages/adapter-static/README.md
- packages/adapter-static/index.d.ts
- packages/adapter-static/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/prerender/prerender.js
- packages/kit/src/utils/filesystem.js
- packages/kit/test/build-errors/prerender.spec.js
> [feat] more info about prerendering errors and new strict option

- .changeset/real-taxis-march.md
- packages/kit/src/exports/vite/build/utils.js
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/src/exports/vite/index.js
- packages/kit/src/utils/url.js
- packages/kit/src/utils/url.spec.js
- packages/kit/types/internal.d.ts
This is a small thing but I noticed we're including this code in production client builds, quite unnecessarily. There might be other cases, and after this PR we can just wrap them in a `if (!__SVELTEKIT_BROWSER__)` block to remove them from client builds.
> remove non-browser code from browser builds

- .changeset/twenty-monkeys-glow.md
- packages/kit/src/runtime/client/client.js
Happened to come across `Uncaught (in promise) Error: Attempted to prefetch a URL that does not belong to this app ` in an app today and didn't immediately find the cause.
The url in the message can help finding where in the application it happened, also added some guidance and docs link for good measure.
In my case it was a link to a page that hadn't been created yet. If thats the only way to reach this error, maybe the url is enough to not confuse users into disabling prefetching too eagerly?
> chore: improve error message for prefetching invalid url

- .changeset/nervous-students-march.md
- documentation/docs/06-form-actions.md
- packages/create-svelte/templates/default/src/routes/sverdle/+page.svelte
- packages/kit/src/runtime/app/forms.js
- packages/kit/types/ambient.d.ts
It's not uncommon to want the form values be preserved, so it makes sense to have this configurable
> [feat] add reset option to update method of enhance

- .changeset/chilled-students-unite.md
- packages/adapter-static/index.js
Fixes #7340.
We missed a bug in https://github.com/sveltejs/kit/pull/7264 — `strict` should be assumed to be `true`, and the `options` object should be optional
> make options object optional

- .changeset/strange-crabs-shop.md
- packages/kit/src/core/prerender/prerender.js
- packages/kit/src/core/sync/create_manifest_data/index.js
- packages/kit/src/core/sync/create_manifest_data/index.spec.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/utils.js
- packages/kit/src/utils/routing.js
- packages/kit/src/utils/routing.spec.js
- packages/kit/test/apps/basics/test/server.test.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/build-errors/prerender.spec.js
> prefix all route IDs with `/`

- packages/kit/scripts/extract-types.js
Fixes #7330
Fixes whitespace for Modules and Types code snippets.
> Whitespace in docs code snippets

- .changeset/polite-trainers-share.md
- packages/create-svelte/templates/default/src/routes/sverdle/+page.svelte
- packages/create-svelte/templates/default/src/routes/sverdle/how-to-play/+page.svelte
> Add missing titles and descriptions to the Sverdle pages

- .changeset/sixty-rats-divide.md
- packages/create-svelte/templates/default/src/routes/sverdle/+page.svelte
- packages/create-svelte/templates/default/src/routes/sverdle/how-to-play/+page.svelte
This also eliminates the Vite warnings:
[vite:css] start value has mixed support, consider using flex-start instead
Using `justify-content: flex-start;` has here the same result as `justify-content: start;` (they are different only if the flex direction is opposite to the natural), and it has a wider compatibility (see [caniuseit](https://caniuse.com/mdn-css_properties_justify-content_flex_context_start_end)).
> Use `justify-content: flex-start;` on Sverdle CSS to avoid compatibility issues

- .changeset/three-meals-vanish.md
- packages/kit/src/runtime/client/parse.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/utils/routing.js
- packages/kit/src/utils/routing.spec.js
> [fix] don't run matchers for empty optional params

- .changeset/smart-dolphins-mix.md
- packages/kit/src/runtime/app/forms.js
Due to the return of regular JSON requests of #7177, issue #6357 is relevant back again. Although now I couldn't reproduce the behavior, it stills problematic and needed to be fixed.
Clearly, when you simulate regular form submission, you should check that the browser never used a cached result of previous POST request.
It is unclear how browsers choose to handle this situation, see [this stackoverflow question](https://webmasters.stackexchange.com/questions/111298/what-happens-if-you-dont-set-cache-control-header).
Since browsers seems to be more careful on programically `fetch` POST requests, I couldn't catch a browser really use caching for this "no cache-control header" responses.
Currently on form submission from enhanced forms, there is no cache control header from the server, no …
> Always avoid caching form submission on enhanced forms

- .changeset/shiny-eels-brush.md
- packages/kit/src/runtime/server/page/render.js
Closes #7262
- Tested it out with return `json`
- with `new Error`
> [fix] show more descriptive error if data returned from `load` is a non-POJO

- .changeset/itchy-ants-explode.md
- packages/kit/package.json
- packages/kit/src/exports/vite/index.js
- pnpm-lock.yaml
We'll turn `prebundleSvelteLibraries` on by default in `vite-plugin-svelte` 2.0 when Vite 4 comes out. For now we turn it on here. The feedback thus far has been good
Ref https://github.com/sveltejs/kit/issues/2612
> [chore] upgrade to `vite-plugin-svelte` 1.1.0 and enable `prebundleSvelteLibraries`

- .changeset/fair-seas-clean.md
- packages/kit/src/core/generate_manifest/index.js
- packages/kit/src/core/sync/create_manifest_data/index.js
- packages/kit/src/core/sync/write_types/index.js
- packages/kit/src/core/sync/write_types/index.spec.js
- packages/kit/src/core/sync/write_types/test/slugs/_expected/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/_expected/x/[[optional]]/$types.d.ts
- packages/kit/src/core/sync/write_types/test/slugs/x/[[optional]]/+page.js
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/src/runtime/client/parse.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/utils/routing.js
- packages/kit/src/utils/routing.spec.js
- packages/kit/types/internal.d.ts
Follow-up to #7346 — if `/x/[[y]]` matches `/x`, then `params.y` should be undefined.
I haven't updated the generated types yet, I just added a failing test
> Undefined optional params

- .changeset/gold-moons-poke.md
- packages/kit/package.json
- packages/kit/src/exports/node/index.js
- pnpm-lock.yaml
> [fix] support and pin undici 5.12.0

- .changeset/eighty-turkeys-exercise.md
- documentation/docs/20-core-concepts/20-load.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/cookie.spec.js
- packages/kit/src/runtime/server/index.js
- packages/kit/types/index.d.ts
- Warnings will be logged to the console if it's detected that there's likely misusage of the path parameter.
- More documentation
- Fix mismatch of cookie path between /foo and /foo/__data.json server-load calls by emulating browser behavior of the default path
Fixes #6609
> [fix] harmonize cookie path and add dev time warnings

- .changeset/lucky-moles-count.md
- packages/kit/src/exports/node/index.js
- packages/kit/src/exports/vite/dev/index.js
This gets us pretty darn close to being able to set the `base` option in Vite correctly. Right now we hardcode it to `./`, which isn't correct and I suspect is one of the reasons the highly upvoted https://github.com/sveltejs/kit/issues/2958 doesn't work. There's one more thing we'll need to fix it which is https://github.com/vitejs/vite/issues/9236 and I'm working on getting that in as part of Vite 4
The reason we need this is that Vite rewrites the `url` to strip out the base path, which makes the `url` not what we might expect. I looked into changing that in Vite and discussed with the Vite team. While there's the possibility we might be able to do it, it's not easy and would affect the entire Vite ecosystem, so we'd need to get buy in from all the other frameworks. And actually, what …
> Use `req.originalUrl` for better Vite compatibility

- packages/kit/src/constants.js
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/index.js
- packages/kit/src/runtime/server/utils.js
- packages/kit/src/utils/url.js
A thought I had while reviewing #7416 — our data suffix handling is a bit raggedy, and would maybe be nicer if we encapsulated the repetitious logic into helper functions.
No changeset or tests needed for this change
> DRY out data suffix handling

- documentation/docs/30-advanced/70-packaging.md
I'm seeing lots of people tying their packages unnecessarily to SvelteKit, which is probably not what we intend by making svelte-kit package the default way to build Svelte packages
> [docs] mention how to make packages more widely usable

- .changeset/tender-kiwis-happen.md
- packages/kit/src/runtime/server/index.js
Fixes #7434
Was accidentally introduced through #7419
> [fix] correctly strip data suffix at root page

- .changeset/great-geese-sort.md
- packages/create-svelte/scripts/update-template-repo-contents.js
> [fix] remove Sverdle from Stackblitz template

- .github/workflows/release.yml
- CONTRIBUTING.md
- package.json
We're building 0 packages now
```sh
> pnpm turbo run build --filter="./packages/*"
• Packages in scope: 
• Running build in 0 packages
Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
Time:    183ms
```
> remove root build script

- .changeset/long-ghosts-act.md
- packages/kit/package.json
- packages/kit/src/core/prerender/prerender.js
- pnpm-lock.yaml
The newest version of `devalue` only de-duplicates non-primitives. That means that a value like `[null, null]` is serialized sensibly:
```diff
<script type="module" data-sveltekit-hydrate="1vcz4c4">
import { start } from "./_app/immutable/start-050325ff.js";
start({
env: {},
hydrate: {
status: 200,
error: null,
node_ids: [0, 3],
params: {},
routeId: "/",
-      data: (function(a){return [a,a]}(null)),
+      data: [null,null],
form: null
},
paths: {"base":"","assets":""},
target: document.querySelector('[data-sveltekit-hydrate="1vcz4c4"]').parentNode,
trailing_slash: "never"
});
</script>
```
It also makes it _much_ less likely that you'd end up with an IIFE with too many arguments. Between that and the fact that we now use `devalue.stringify` rather than `devalue.uneval`, we can close …
> bump devalue version

- packages/kit/src/core/sync/create_manifest_data/index.js
It looks like we now have three things call manifest :laughing: Adding this doc to help me keep them straight
> [docs] add a JSDoc for create_manifest_data

- .changeset/little-seahorses-argue.md
- packages/adapter-static/README.md
> update README to avoid process.env.NODE_ENV

- .changeset/empty-dryers-applaud.md
- packages/kit/src/exports/vite/dev/index.js
Fixes https://github.com/sveltejs/kit/pull/7288
Don't put the module into the graph with `ssrLoadModule` which will add the server-side code, but instead use `ensureEntryFromUrl` leaving the `ssr` parameter `undefined`
> [fix] check for private var usage in client code instead of server code

- .changeset/empty-dryers-applaud.md
- packages/kit/src/exports/vite/dev/index.js
Reverts sveltejs/kit#7487, which did not fix the issue — it only skips the check the _first_ time the module is imported, but still runs it ever time after that
> Revert "[fix] check for private var usage in client code instead of server code"

- packages/kit/src/core/config/options.js
some `undefined` input conditions could be removed because `validate` handles it
https://github.com/sveltejs/kit/blob/79030401ecad1f4daaff8e6d3e7ff6022d5c5c78/packages/kit/src/core/config/options.js#L406-L410
> [chore] kit core/config/options.js cleanup

- .changeset/wild-lions-care.md
- packages/adapter-netlify/README.md
Added some more context around edge functions and examples to the readme for `adapter-netlify`.
- [x ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x ] This message body should clearly illustrate what problems it solves.
> Small tweaks to readme

- documentation/docs/30-advanced/20-hooks.md
Relates to changes of #7450
It was decided that `route` itself should not be `null` to reduce potential for `null` reference errors.
Docs still claimed otherwise.
> [docs] `event.route` is never `null`.

- .changeset/ten-hairs-drum.md
- packages/kit/src/exports/vite/build/build_service_worker.js
- packages/kit/src/exports/vite/build/utils.js
- packages/kit/src/exports/vite/index.js
- packages/kit/src/exports/vite/utils.js
- packages/kit/src/exports/vite/utils.spec.js
This PR splits the `get_aliases` function into two. One that returns aliases that are consumer-configurable, another that returns the 'stock' aliases (`__GENERATED__` and `$app`).
With this refactor, this PR also involves the config aliases in service worker builds, meaning service workers can import modules using custom aliases defined in `svelte.config.js`.
> Service worker config aliases (#7496)

- .changeset/clean-sheep-run.md
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/load_data.js
- packages/kit/test/apps/basics/src/routes/caching/server-data/+page.server.js
- packages/kit/test/apps/basics/src/routes/caching/server-data/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
...using the Vary header, which allows one cached response for each variation of the x-sveltekit-invalidated header, ensuring we cache matching responses for all invalidation scenarios
Closes #6477
> [feat] enable caching for __data.json requests

- .changeset/young-geckos-sit.md
- packages/kit/src/utils/routing.js
- packages/kit/src/utils/routing.spec.js
Segment is already decoded here, so another decoding is not needed
https://github.com/sveltejs/kit/blob/eab9680966812f8755b6d1fe37a310610ec43777/packages/kit/src/utils/routing.js#L24
> [fix] prevent double decoding of path segment

- .changeset/funny-planes-judge.md
- packages/kit/src/exports/node/index.js
We can't recover from it, but we shouldn't crash
Fixes #7560
> [fix] handle locked readable stream when reading body

- .changeset/cold-monkeys-relate.md
- packages/kit/src/exports/vite/preview/index.js
Noticed that https://kit.svelte.dev/content.json isn't being served when running `preview` locally due to some faulty logic
> serve prerendered non-page files when running preview

- .changeset/large-starfishes-relate.md
- packages/kit/src/exports/vite/index.js
When watching, static directory is missing on outDir because the vite svelte-kit plugin clean them
How to reproduce:
Create a clean svelte-kit project (choose skeleton and no to all questions)
- npm create svelte@latest watch_bug
- cd watch_bug
- npm install
- touch static/file.txt
- npx vite build -w
- Check files on .svelte-kit/output/client/, is missing file.txt and favicon.png
Couldn't devote too much time to do a better solution, so my PR only avoid cleaning directories when using --watch
> [fix] don't clean build and output directories when using `--watch`

- .changeset/rotten-files-work.md
- documentation/docs/20-core-concepts/10-routing.md
- documentation/docs/30-advanced/20-hooks.md
- documentation/docs/30-advanced/25-errors.md
- packages/kit/src/runtime/server/endpoint.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/utils.js
- packages/kit/test/apps/basics/src/hooks.server.js
- packages/kit/test/apps/basics/test/server.test.js
- handle expected errors thrown in handle hook correctly
- remove wrong catch of thrown invalid class (only viable inside actions; and it should be returned)
- document behavior around errors thrown in handle/load/endpoint
Closes #7272
> [fix] error docs + handle expected error

- sites/kit.svelte.dev/.gitignore
- sites/kit.svelte.dev/src/lib/docs/server/index.js
When developing the site locally, it takes forever to load a page that includes a lot of code snippets, because they have to be processed by shiki-twoslash which is quite expensive. It's very annoying.
This adds a simple cache that makes it essentially instant to see changes. It also speeds up builds by a massive amount, if the cache is already populated. In future we could conceivably wire this up to Turborepo's remote cache to speed up deploys across the board, though I'm not doing that here because there's probably lots of gotchas around type changes in SvelteKit being respected, or version changes invalidating caches.
> cache code snippets

- package.json
I know we've run into sticky caches before, but at the moment we're not using Turborepo at all. For things like docs changes we're causing CI to take waaaay longer than it needs to. I think we should remove `--force` and deal with caching bugs as they arise
> remove --force from test script

- .changeset/empty-vans-draw.md
- packages/kit/src/core/prerender/crawl.js
Fixes the following error:
```
The following pages contain links to /#hash, but no element with id="hash" exists on /
```
when using `<a name="hash">` anchors.
> fix: Add support linking to for <a name="hash"> tags.

- .changeset/cyan-beds-smoke.md
- packages/kit/src/runtime/server/index.js
closes #7458. the bug and the fix are both trivial enough that I didn't bother adding a test for this
> don't print search params error when prerendering fallback page

- .changeset/purple-parrots-tell.md
- packages/kit/src/core/sync/create_manifest_data/index.js
- packages/kit/src/core/sync/create_manifest_data/index.spec.js
Closes #5967
This was surprisingly easy
> [feat] add fallback component for layouts without one

- .changeset/curly-suits-lay.md
- packages/kit/src/core/generate_manifest/index.js
- packages/kit/src/exports/vite/preview/index.js
Fixes #7618 - root layout/error should always be included
Fixes #7633 - windows path conversion
> [fix] prerendering path and layout fixes

- .changeset/purple-apes-whisper.md
- .changeset/slimy-laws-argue.md
- documentation/docs/10-getting-started/30-project-structure.md
- packages/create-svelte/templates/default/src/app.html
- packages/create-svelte/templates/skeleton/src/app.html
- packages/kit/src/runtime/client/start.js
#7585. In addition to the warning, it adds `display: contents` to the wrapper elements in the template apps
> Warn if `%sveltekit.body%` is a direct child of `<body>`

- pnpm-lock.yaml
This just refreshes the lockfile. It's necessary in order to be compatible with TypeScript 4.9 (https://github.com/sveltejs/kit/issues/7654) as some of the older packages use an outdated type which causes issues with a difference in types for `AbortController` between TypeScript and Definitely Typed
> [chore] upgrade minor package versions

- documentation/docs/50-api-reference/10-configuration.md
<hr>
Might solve #4440
Adds placeholder for nonce in the CSP section of the configuration part of the API reference docs
> Add nonce placeholder to CSP docs

- packages/kit/package.json
- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
https://github.com/sveltejs/kit/pull/7657 updated `pnpm-lock.yaml` without touching any `package.json` files. Maybe that's giving the cache difficulty? Upgrade `marked` to touch the `package.json` files and see if it fixes the Vercel deployment issues
> [chore] upgrade marked

- documentation/docs/30-advanced/10-advanced-routing.md
> document [x+2e]well-known pattern

- .changeset/gentle-rocks-run.md
- packages/package/src/index.js
This allows `vite-plugin-svelte` to detect which libraries are Svelte libraries
> [feat] warn if svelte not found in dependencies or peerDependencies

- .changeset/clever-students-report.md
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/test/apps/basics/test/server.test.js
closes #7664. we might just want to wait for #7543 instead depending on ETA (@benmccann?)
> add ACAO: * to static assets in dev

- .changeset/fair-dolls-press.md
- packages/kit/src/core/sync/create_manifest_data/index.js
> allow .d.ts files to have + prefix

- .changeset/calm-ways-jump.md
- packages/kit/src/exports/vite/build/utils.js
- packages/kit/src/runtime/client/utils.js
fixes #7144. #7689 makes this nice and easy
> don't hardcode `version` in client bundle

- .changeset/lucky-gifts-jump.md
- packages/kit/types/index.d.ts
Fixes #7319
Also overall a more sensible approach; the function is public, so is their return type
> [fix] export HttpError/Redirect interface

- .changeset/clean-grapes-think.md
- packages/create-svelte/templates/default/.gitignore
- packages/create-svelte/templates/skeleton/.gitignore
- packages/create-svelte/templates/skeletonlib/.gitignore
Because why new SvelteKit users need to figure this out by themselves?
> Ignore Vite timestamp files by default in `create-svelte` templates (added to `.gitignore`)

- .changeset/new-kangaroos-double.md
- packages/kit/src/core/prerender/fixtures/ids/input.html
- packages/kit/src/core/prerender/fixtures/ids/output.json
- packages/kit/src/core/prerender/prerender.js
- packages/kit/test/prerendering/basics/src/routes/encöded-hash-link/+page.svelte
> Handle hash links with non-ASCII characters when prerendering

- documentation/docs/20-core-concepts/30-form-actions.md
* Show `$page` store and `form` variable in invalid form example. 
I was a bit stumped by how to to display the status code passed into `return invalid()`, so I hyper-focused on the "Validation errors" section on this page and couldn't find information despite it being mentioned:
> The invalid function lets you return an <ins>HTTP status code</ins> (typically 400 or 422, in the case of validation errors) along with the data
`$page` and `$page.status` are mentioned several times on that document already, so hopefully this small change to the example will help others.
> docs: add relevant variables to form example

- .changeset/twenty-forks-beg.md
- packages/adapter-auto/index.js
> adapter-auto: defer adapter installation until required

- .changeset/serious-bottles-wave.md
- packages/adapter-vercel/index.js
> [fix] handle root route for split config

- .changeset/fresh-geese-flow.md
- packages/adapter-node/README.md
Supersedes #7693, closes #7042. We'll have to see if this is enough
> Clarify requirement to specify `ORIGIN` in `adapter-node`

- .changeset/quick-weeks-explode.md
- packages/adapter-vercel/index.js
fixes #7725. The prerendered page wasn't being served because the `overrides` config in `.vercel/output/config.json` can't have a `path` value with a trailing slash. To get the correct behaviour we have to remove the trailing slash, and also add two entries to the `routes` config for each prerendered page:
```json
{ "src": "/the-path/", "dest": "/the-path" },
{ "src": "/the-path", "status": 308, "headers": { "Location": "/the-path/" } }
```
> write redirects for prerendered pages with trailing slashes

- .changeset/empty-fireants-fetch.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/cookie.spec.js
before: external fetch cookie was sent plain
```
browser
|
(request with url-encoded cookie) (cookie=foo%2Bbar)
|
v
sveltekit node app
|
(external fetch request made with url-DEcoded cookie) (cookie=foo+bar)
|
v
backend service
```
after: external fetch cookie is url-encoded
```
browser
|
(request with url-encoded cookie) (cookie=foo%2Bbar)
|
v
sveltekit node app
|
(external fetch request made with url-ENcoded cookie) (cookie=foo%2Bbar)
|
v
backend service
```
My kit app was making external `fetch` requests with cookies that were different from the the cookies that were part of the original request to the app.
My request coming from the browser had a session cookie that was url-encoded. My sveltekit server code would then use the kit-`fetch` to make a request to a backend api server that …
> external fetch calls: ensure serialized cookie values are url-encoded

- .changeset/calm-peaches-enjoy.md
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/index.js
- packages/kit/test/apps/basics/src/hooks.server.js
- packages/kit/test/apps/basics/src/routes/redirect/+page.svelte
- packages/kit/test/apps/basics/src/routes/redirect/in-handle/+page.server.js
- packages/kit/test/apps/basics/src/routes/redirect/in-handle/+page.svelte
- packages/kit/test/apps/basics/test/test.js
Fixes #7787
During fixing this, I wondered why the tests also pass without the fix, and discovered that this specific behavior will only occur if there's no root `+layout.server.js` (because then it wouldn't try to rerequest the data, failing again, resulting in a fallback to the server where the redirect would be handled correctly), which we have in the tests. I'm not sure if it's worth creating another test suite for this, so I left it like this.
> [fix] handle redirects in handle hook while processing data request

- .changeset/grumpy-maps-complain.md
- packages/kit/src/core/adapt/builder.js
- packages/kit/types/index.d.ts
Removes getStaticDirectory() because of no more usage, as stated in #7800.
> Removed getStaticDirectory() 

- packages/kit/test/apps/basics/test/client.test.js
just a minor cleanup I noticed while looking at the test that's failing the latest Playwright version
> [chore] don't hardcode port in test

- .changeset/itchy-beers-suffer.md
- packages/kit/src/runtime/client/client.js
We have some code that relies on introspecting the `name` of `console.warn`— some metaprogramming to provide dev-only logs. This update to make `console.warn` an anonymous function means it no longer has a name, which breaks that assumption.
Normally:
```js
console.warn.name
> 'warn'
```
In SvelteKit dev:
```js
console.warn.name
> ''
```
> Make console.warn named function

- .changeset/shy-queens-wash.md
- packages/kit/src/core/generate_manifest/index.js
- packages/kit/types/index.d.ts
- packages/kit/types/private.d.ts
closes #7798. I haven't yet checked community adapters to make sure no-one is using this
> remove `format` option from `generateManifest(...)`

- .changeset/honest-peas-cry.md
- packages/create-svelte/shared/+playwright+typescript/playwright.config.ts
- packages/create-svelte/shared/+playwright-typescript/playwright.config.js
closes #7825 
The globs weren't matching, playwright has a [default testMatch](https://playwright.dev/docs/test-configuration#testing-options) that works pretty well as long as we contain it with testDir and it's nice to have fewer moving parts so did away with globs altogether
> [create-svelte] Fix playwright filter

- .changeset/rude-actors-serve.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/load/mutated-url/+page.js
- packages/kit/test/apps/basics/src/routes/load/mutated-url/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
Turns out if you mutate `$page.url`, e.g. to update a search param, SvelteKit mistakenly thinks no navigation is necessary
> make `$page.url` resilient against mutations

- packages/adapter-netlify/index.js
This was removed in https://github.com/sveltejs/kit/pull/7820 and is causing lint to fail. It didn't fail on that PR because Turbo is a giant steaming pile of shit. Here is the Turbo output from that PR:
>@sveltejs/adapter-netlify:check: cache hit, suppressing output 98cf59e7443a315b
@sveltejs/adapter-netlify:lint: cache hit, suppressing output e148ef9617701497
No changeset necessary since it's only a lint fix and won't impact users
> [fix] don't pass second arg to `generateManifest`

- documentation/docs/30-advanced/25-errors.md
The generated template has a `declare` as does `20-hooks.md`
> [docs] add missing declare

- .changeset/lazy-islands-deny.md
- packages/create-svelte/shared/+checkjs/package.json
- packages/create-svelte/shared/+eslint+prettier/package.json
- packages/create-svelte/shared/+eslint+typescript/package.json
- packages/create-svelte/shared/+eslint/package.json
- packages/create-svelte/shared/+playwright/package.json
- packages/create-svelte/shared/+prettier/package.json
- packages/create-svelte/shared/+typescript/package.json
- packages/create-svelte/shared/+vitest/package.json
I overlooked these files when upgrading dependencies earlier. It's important to bump these as Playwright is currently pinned and this will unpin it. It will also bump the versions of dependencies to a minimum version which supports TypeScript's `satisfies` operator
> Upgrade dependencies in templates

- sites/kit.svelte.dev/src/lib/docs/server/render.js
> [docs] fix link

- .changeset/few-bugs-retire.md
- packages/adapter-node/README.md
The adapter-node README file mentions `RequestEvent.clientAddress`, but that's now a function: `RequestEvent.getClientAddress()`.
> [docs] update reference to `getClientAddress()`

- .changeset/thin-pillows-work.md
- packages/kit/src/exports/vite/build/build_server.js
- packages/kit/src/exports/vite/utils.js
- packages/kit/src/exports/vite/utils.spec.js
two suggestions from @dominikg:
- code was broken when `force` was used as we'd drop the other `optimizeDeps` options
- we don't need our own config merge function as Vite has one that's exported
> [fix] correct Vite config merging with force option

- .changeset/wet-trainers-perform.md
- packages/kit/src/core/sync/write_types/index.js
- packages/kit/src/exports/vite/dev/index.js
In contrast to server hooks, client hooks are written to the client manifest and therefore need rebuilding when they are added/removed.
I noticed this while working on the tutorial
> [fix] rebuild manifest when client hooks or param matcher file is added/removed

- .changeset/heavy-forks-search.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/index.js
- packages/kit/test/apps/basics/test/client.test.js
..instead of Vary, because that header is not supported on all CDNs/platforms, leading to wrong cache behavior
> [fix] use searchParams for x-sveltekit-invalidated

- sites/kit.svelte.dev/src/lib/docs/Contents.svelte
- sites/kit.svelte.dev/src/lib/docs/TSToggle.svelte
- sites/kit.svelte.dev/src/lib/docs/ToggleButton.svelte
- sites/kit.svelte.dev/src/lib/search/SearchBox.svelte
- sites/kit.svelte.dev/src/routes/search/+page.svelte
- sites/site-kit/src/lib/components/Nav.svelte
Some minor a11y improvements to the docs. 
The largest change was fixing the accessibility of the JS/TS toggle. Instead of a checkbox, I refactored it to use `<button aria-pressed>` instead. Using a checkbox isn't inaccessible, but a [button is a better fit for this usecase](https://adrianroselli.com/2019/08/under-engineered-toggles-too.html#Button):
>  If flipping the toggle immediately performs an action on the page (such as updating a setting), then a `<button>` is a better fit. Unlike a checkbox, which only changes its state, a `<button>` conveys to a user that something will happen. 
The label on the control also wasn't clear (it was "JavaScript TypeScript"), so I instead gave it the label "TypeScript code examples" (visually hidden). Combined with the state of `aria-pressed`, it …
> a11y improvements to kit.svelte.dev

- .changeset/hot-news-bake.md
- packages/kit/src/exports/vite/dev/index.js
fixes #7942 
the vite client assumes that changes to html files should only trigger a full reload if they are named index.html and the path to the file matches the browser path. kit uses `src/app.html` by default which fails that check.
so we send another full-reload event to the client without a path - this forces it's hand.
> [fix] ensure that editing app.html reloads open dev page

- .changeset/wild-mangos-develop.md
- sites/kit.svelte.dev/src/routes/+layout.svelte
fixes #7954 
Changes the `<main>` element `overflow-y` from `auto` to `hidden`.
> [docs] fix double scrolling on mobile site

- .changeset/beige-kangaroos-appear.md
- packages/kit/src/core/sync/write_types/index.js
- packages/kit/src/runtime/client/client.js
Closes #7961. Prior art: #6994.
> fix: ActionData type - disallow `undefined`, allow `null`

- .changeset/witty-spies-occur.md
- packages/kit/src/runtime/app/forms.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/actions.js
- packages/kit/src/runtime/server/page/index.js
fixes #7965 
fixes #7957 
* Returns a `405` response for an action request when no server file exists for a page.
* Adds a JSON body for the "cross-origin POST" and "no actions exist" error responses.
> [fix] handle missing server file for an action request

- package.json
ecosystem-ci run of kit is one of the slowest. the tests for create-svelte and svelte-package are less relevant, and esp. create-svelte takes a while.  
after this pr we can update vite-ecosystem-ci to call that script and it will be faster.
intentionally doesn't use turbo to not mess with it or its caching
> [chore] add test script for vite-ecosystem-ci that runs just the kit tests

- .changeset/seven-bikes-give.md
- packages/kit/src/exports/vite/index.js
The Storybook folks are currently working on Storybook 7 which has two nice improvements: you can use a Vite builder without installing Webpack at all and it has first-class support for SvelteKit! A wrinkle in the SvelteKit support is that SvelteKit runs in the same Vite instance and installs a middleware that ends up serving all the requests breaking the Storybook server. This splits the SvelteKit Vite plugin into two so that they can remove the middleware plugin - that way they still get the aliases and other things our plugin provides without taking over the whole server and breaking everything else.
This is arguably a breaking change if anyone is looking for `vite-plugin-svelte-kit`, but hopefully no one is doing that. It's a bit of an implementation detail that we've never publicly …
> [feat] split Vite plugin in two

- .changeset/stupid-panthers-learn.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/utils.js
- packages/kit/test/apps/basics/src/hooks.server.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/types/index.d.ts
This is breaking change for people who relied on the `__data.json` suffix being present on `event.url` which is now no longer the case. Use the new `isDataRequest` boolean instead.
```diff
export function handle({ event, resolve }) {
-  if (event.url.pathname.endsWith('__data.json') {
+  if (event.isDataRequest) {
// ..
}
return resolve(event);
}
```
closes #7926
Open question: Should we also remove those things from the original `request` object? I vote for "no".
> [breaking] strip __data.json from url

- .changeset/dirty-rockets-fry.md
- packages/kit/src/runtime/app/forms.js
> [fix] throw error when using enhance on GET forms

- sites/kit.svelte.dev/src/routes/+page.svelte
lord knows why it's okay with some svelte-orange-on-white links but not others. it's almost as if it's just making things up as it goes along. anyway, i am at peace with this change because it's tucked away at the bottom, and gets us a 💯 a11y score on lighthouse
> increase link contrast

- .changeset/popular-crabs-shop.md
- packages/kit/src/core/config/index.spec.js
- packages/kit/src/core/config/options.js
- packages/kit/src/exports/vite/build/build_server.js
- packages/kit/src/exports/vite/build/utils.js
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/src/exports/vite/index.js
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/options/source/pages/routing/link-outside-app-target/source/+page.svelte
- packages/kit/test/apps/options/source/pages/routing/link-outside-app-target/state.js
- packages/kit/test/apps/options/source/pages/routing/link-outside-app-target/target/+page.svelte
- packages/kit/test/apps/options/source/template.html
- packages/kit/test/apps/options/svelte.config.js
- packages/kit/test/apps/options/test/test.js
- packages/kit/types/index.d.ts
- packages/kit/types/internal.d.ts
If you relied on the new behavior introduced in #7766, you can get that back by adding `embedded: true` to your `svelte.config.js`:
```diff
export default {
kit: {
+    embedded: true
}
}
```
Closes #7940
Closes #4935
Adds a new option which defaults to false. If true, events related to navigation etc are listened to on the target element rather the html root
~Open questions~ solved: 
- ~approach sensible? I figured using the `define` feature for this is the most straightforward and treeshakes nicely~ it is
- ~using `data-sveltekit-root` instead (as discussed in the issue)? Advantage: no config option, more control ("I use popper.js with embedded Kit, and it adds itself to some tag higher than the target). Disadvantage: feels clunky, a little more startup code that might not be as …
> [breaking] add embedded option, turned off by default

- .changeset/modern-radios-develop.md
- sites/kit.svelte.dev/src/routes/+layout.svelte
fixes #7947 
Moves the `<SearchBox>` component out of the `<main>` element because iOS has an issue with `z-index`.
The `<nav>` had a higher z-index than the container of the SearchBox so the search box gets hidden. It ignores the z-index of the search box.
> [docs] fix iOS search box hidden by nav

- documentation/docs/20-core-concepts/30-form-actions.md
The type of the function passed to the `use:enhance` action should be specified in the docs. This makes it easier for developers working in TS to get type checking and intellisense within custom `enhance` functions.
As far as I can tell a manual link isn't needed for the type, but if it is the correct page appears to be [here](https://kit.svelte.dev/docs/types#public-types-submitfunction). Credit to [ShadowMobX on discord](https://discord.com/channels/457912077277855764/1050623304312045618/1050625506594271274) for the insight.
As this is a simple doc update, I don't see a reason to open an issue/discussion or implement tests for it.
n/a, simple doc change
> Added `SubmitFunction` type to use:enhance docs

- .changeset/gold-phones-clap.md
- packages/adapter-node/README.md
> document how to manually load .env files in adapter-node

- .changeset/shaggy-bikes-wink.md
- packages/adapter-static/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/prerender/fallback.js
- packages/kit/src/core/prerender/prerender.js
- packages/kit/types/index.d.ts
closes #7899. This changes the behaviour around fallback `200.html`/`404.html` pages so that they are only generated when needed (which, in practice, means only in `adapter-static`). 
As a result, no rendering takes place during the build unless `prerender.entries` is populated.
> [breaking] add `builder.generateFallback(fallback)` API

- documentation/docs/20-core-concepts/20-load.md
- documentation/docs/30-advanced/20-hooks.md
- documentation/docs/30-advanced/25-errors.md
- documentation/docs/50-reference/40-types.md
- sites/kit.svelte.dev/src/lib/docs/server/index.js
- sites/kit.svelte.dev/src/lib/docs/server/index.spec.js
would be nice to get this change in as it reduces the need for proxy types. the site won't build though, because (I think) shiki-twoslash is using an older TypeScript and doesn't know how to deal with the newfangled syntax. A cursory glance didn't show me how to fix it so I'm just going to leave this here for a moment
> generate TS with `satisfies`

- .changeset/cool-seahorses-cross.md
- documentation/docs/20-core-concepts/20-load.md
- documentation/docs/30-advanced/20-hooks.md
- documentation/docs/30-advanced/25-errors.md
- documentation/docs/50-reference/40-types.md
- packages/create-svelte/templates/default/src/routes/sverdle/+page.server.ts
- packages/kit/src/core/sync/write_types/index.spec.js
- sites/kit.svelte.dev/src/lib/docs/server/index.js
- sites/kit.svelte.dev/src/lib/docs/server/index.spec.js
sucrase, prettier, and eslint all support TypeScript 4.9 now. However, it looks like VS Code is still on 4.8.4
> Use `satifies` operator

- .changeset/loud-phones-chew.md
- documentation/docs/20-core-concepts/30-form-actions.md
- packages/create-svelte/templates/default/src/routes/sverdle/+page.server.ts
- packages/kit/src/exports/index.js
- packages/kit/src/runtime/app/forms.js
- packages/kit/src/runtime/control.js
- packages/kit/src/runtime/server/page/actions.js
- packages/kit/src/runtime/server/page/index.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/test/apps/basics/src/routes/actions/form-errors-persist-fields/+page.server.js
- packages/kit/test/apps/basics/src/routes/actions/form-errors/+page.server.js
- packages/kit/test/apps/basics/src/routes/actions/update-form/+page.svelte
- packages/kit/test/apps/basics/src/routes/shadowed/error-post/+page.server.js
- packages/kit/test/types/actions.test.ts
- packages/kit/types/index.d.ts
> [breaking] rename `invalid(...)` and `ValidationError`

- sites/site-kit/src/lib/icons/link-white.svg
- sites/site-kit/src/lib/styles/text.css
The permalink in the kit website doesn't have a good contrast while in dark mode. This changes that by adding a light coloured version of the `link.svg` graphic.
Before:
After:
> [docs] improve visibility of permalink in dark mode

- sites/kit.svelte.dev/src/app.html
Fixes https://github.com/sveltejs/kit/issues/7901
Specifying `color-scheme` will theme the browser native elements that would otherwise not be automatically themed, such as scrollbars. `"dark light"` is a special value that respects the operating system preferences.
Here's what it looks like on Windows 11 with system theme set to dark:
| Before | After |
| --- | --- |
| ![](https://user-images.githubusercontent.com/9084735/206809436-e4ca9979-37b9-4ece-88c1-6ced6e707c35.png) | ![](https://user-images.githubusercontent.com/9084735/206809371-f8d4a436-3bdc-4d24-8994-1fa14cb41c0d.png) |
Note that if in the future a manual theme switcher is added to the site, then this will need to be overridden in CSS using the `color-scheme` property.
```css
html[data-theme="light"] { color-scheme: light; } …
```
> [docs site] Add color-scheme meta tag

- .changeset/violet-donuts-share.md
- packages/kit/types/ambient.d.ts
aside: Using 'declare module' for these exports kind of feels like a hack to me, unless it's needed for the docs we should maybe be using "exports.types" alongside the js files listed in package.json but out of scope for this PR.
> add type declaration for vitePreprocess reexport

- sites/site-kit/src/lib/styles/text.css
This is a continuation of #8034
Basically I found another thing that did not sidescroll, here:
https://kit.svelte.dev/docs/advanced-routing
Can be seen on both mobile and desktop:
Instead of doing an issue like before (#8032) I thought I would give it a go to fix it myself this time.
note:
The inline-flex and padding is to give the scrollable element the same appearance as before. I have tested my change on desktop chrome (osx) and on mobile safari (iphone ios) to great success.
> [fix] make `<p> <code>` elements in docs scrollable

- .changeset/clever-ducks-wave.md
- packages/kit/src/exports/vite/index.js
- packages/kit/src/exports/vite/utils.js
- packages/kit/test/apps/options/source/template.html
- packages/kit/test/apps/options/test/test.js
Setting Vite's base URL makes the 404 message a bit different in dev vs prod, but that seems like a very minor issue. Setting it will make a number of things easier like probably allowing us to fix https://github.com/sveltejs/kit/issues/2958, fix Vite PWA trying to read the base path from Vite, etc.
There were a few places I added trailing slashes. This avoids unnecessary redirects and makes the tests run faster and be less flaky. That probably could have been a separate PR, but I found it while working on this, so just crammed them in here
> [fix] set Vite base URL

- .changeset/dry-snails-own.md
- packages/kit/src/runtime/app/forms.js
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte
- packages/kit/test/apps/basics/test/test.js
- packages/kit/types/index.d.ts
Fixes #8072 
I wanted to create a `+error.svelte` in `test/apps/basic/src/routes/actions/enhance` for this test, but somehow it is not mounted in the "js"-test. I also tried to put it in `test/apps/basic/src/routes/actions`, that also didn't work.
Furthermore, I've tried to debug with playwright debug, but couldn't find any reason why it does not work.
> Set correct `$page.status` when using `enhance` and result is of type `'error'`

- .changeset/brave-numbers-destroy.md
- packages/kit/src/exports/vite/dev/index.js
recently sveltekit changed to passing the svelte config inline to vite-plugin-svelte. With this way, vite-plugin-svelte does not watch svelte.config.js for changes to restart the vite devserver, as configFile: false indicates it should not use it.
this PR sets up a watcher in kits dev plugin that does the same. Restarting the server is absolutely required in this case.
> [fix] restart on config change

- .changeset/lucky-apples-breathe.md
- packages/kit/src/exports/vite/build/utils.js
Fixes #8082
More robust/conservative alternative to #8083, although it's worth looking into whether we should change esbuild's `platfrom` option to `neutral` either way.
> [fix] ensure export conditions are resolve through Vite

- sites/kit.svelte.dev/src/lib/search/Search.svelte
- sites/kit.svelte.dev/src/routes/Banner.svelte
- sites/kit.svelte.dev/src/routes/home/Deployment.svelte
- sites/kit.svelte.dev/src/routes/home/Showcase.svelte
- sites/site-kit/src/lib/components/SkipLink.svelte
Keeping this separate from #8069 since these are smaller fixes instead of a larger design change.
- remove duplicate text in showcase/deploy links by setting `alt=""` on the images - e.g. the link was read out as "Vercel logo Vercel" or "Screenshot of pudding.cool pudding.cool", now it's simply "Vercel" and "pudding.cool"
- make banner a <header> (resolves "all page content must be contained by landmarks warnings")
- move skip link in front of banner - it was almost entirely obscured
- treat focusing deployment links the same as hovering them (i.e. color in logo and change text color)
- label search input
- make CTRL+K a div instead of a label - it doesn't really work as a label to the search input. I considered linking it to the input with `aria-describedby` but that didn't feel correct.
> [docs] fix small a11y issues

- .changeset/four-ligers-help.md
- packages/kit/src/core/config/index.js
The alternative would be to move the "set a fallback error.html path if not set" logic into load_error_page, which @Rich-Harris added [here](https://github.com/sveltejs/kit/pull/6367/commits/d5c986bf28e889dddbcef4ab3af8ca5a8083f508)
> [fix] load errorTemplate from correct location

- .changeset/chilly-pumas-look.md
- .changeset/fifty-yaks-cheer.md
- packages/adapter-cloudflare-workers/index.js
- packages/adapter-cloudflare/index.js
- packages/adapter-netlify/index.js
- packages/adapter-vercel/index.js
closes https://github.com/sveltejs/kit/issues/8082
> [fix] set platform to neutral for cloudflare build

- .changeset/shy-toys-confess.md
- packages/kit/src/exports/vite/dev/index.js
follow-up to #8093:
* clears the error overlay once the error is fixed (by doing a full page reload — not sure if there's a better way?)
* removes the 'failed to update manifest' message — that's internal jargon we don't really use in a public-facing way
* removes the stack trace — it's all internal stuff that's no help to the user
* responds with an error page if the page is reloaded, instead of a) stumbling along with a stale manifest or b) in the case that the manifest was invalid from the start, failing with a cryptic internal error
> more robust recovery from manifest errors

- .changeset/chilly-pumas-look.md
- .changeset/smooth-pianos-kiss.md
- packages/adapter-cloudflare-workers/index.js
- packages/adapter-cloudflare/index.js
- packages/adapter-netlify/index.js
- packages/adapter-vercel/index.js
Reverts sveltejs/kit#8083. Turns out this was a mistake, since it breaks packages like `cross-fetch` which assume that if you're not resolving `browser` modules, you want the Node version instead.
Since we bundle `esm-env`, the original reason for #8083 no longer applies.
> Revert "[fix] set platform to neutral when calling esbuild"

- .changeset/proud-cats-smash.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/cookie.spec.js
> [fix] don't de/encode initial and explicit string headers

- sites/kit.svelte.dev/src/routes/home/Deployment.svelte
this link is arguably more useful for Vercel users
> point to the template instead of the adapter

- .changeset/config.json
We want bumpVersionsWithWorkspaceProtocolOnly, not updateInternalDependencies, in order to control non-"workspace:*" versions for packages in this repo ourselves. If we don't change this, any change in Kit would result in a major release for adapter because changesets would bump the peerDependencies
> [chore] Changeset config fix

- sites/kit.svelte.dev/src/routes/search/+page.server.js
closes #8165 
A better solution might be something like a custom vite plugin for the docs, so that all the files are resolved by the bundler instead of a prerender call.
> use prerendered endpoint to get content for search

- .changeset/nervous-lamps-pay.md
- packages/kit/package.json
- packages/package/package.json
Closes #8173. The `>=16.14` range also includes Node 17, which (apparently at least in some versions) doesn't support the three-argument version of `util.inspect.custom`. People shouldn't be using Node 17 anyway. I think we can make this change as a fix rather than as a breaking change.
> exclude Node 17.x as supported version

- .changeset/config.json
uses a negated micromatch pattern to only include @sveltejs packages and published non-org packages.
This skips over the plethora of test apps and other non-published things like the templates.
Con: adding new non-org packages does require extending the negated pattern
Pro: adding new test apps or other non-published packages does not require changes
As the second case is arguably happening more often and first publish of a new package is something we have to plan for either way, i prefer this approach over a positive pattern
> chore: add ignore list to changesets config

- sites/kit.svelte.dev/src/routes/home/Svelte.svelte
The emphasised text "It's a love letter to web development" in the video section of the kit site home page has a poor contrast in dark mode. This removes the inline style `color: --sk-theme-2;` from that text to make it more visible.
Before:
After:
> [site] fix homepage dark mode strong text colour

- documentation/docs/20-core-concepts/20-load.md
Returning a promise (`c.value`) is not possible in `+*.server.js` files.
> [docs] Fixed filename in promise unwrapping section

- .changeset/rare-frogs-crash.md
- packages/create-svelte/shared/+playwright+default/tests/test.ts
Congrats to the version release! Before no web-first assertion was used for the assertion, which means that it did not retry and just failed when the text was not matching. Now its using [toHaveText](https://playwright.dev/docs/test-assertions#locator-assertions-to-have-text) which is recommended and not flaky.
There were more such places inside the sveltekit codebase, seems not related, since its not customer facing, but might still be worth updating.
> chore(create-svelte): address flakiness in playwright test

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
I don't see anywhere in the code where this is referenced
I don't notice any issues on the homepage from this being removed: https://kit-svelte-7ioul50vz-svelte.vercel.app/
> [chore] remove unused dependency

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
- sites/kit.svelte.dev/src/lib/Image.svelte
- sites/kit.svelte.dev/vite.config.js
Upgrade to 4.0.13 which exports the `Picture` type so that we can properly type our `Image` component
Also, remove leading `.` in the config
> [chore] vite-imagetools improvements

- packages/adapter-static/package.json
- packages/adapter-static/test/apps/prerendered/package.json
- packages/adapter-static/test/apps/spa/package.json
- packages/kit/package.json
- packages/kit/test/apps/amp/package.json
- packages/kit/test/apps/basics/package.json
- packages/kit/test/apps/dev-only/package.json
- packages/kit/test/apps/options-2/package.json
- packages/kit/test/apps/options/package.json
- packages/kit/test/apps/writes/package.json
- packages/kit/test/build-errors/apps/prerenderable-incorrect-fragment/package.json
- packages/kit/test/build-errors/apps/prerenderable-not-prerendered/package.json
- packages/kit/test/build-errors/apps/private-dynamic-env-dynamic-import/package.json
- packages/kit/test/build-errors/apps/private-dynamic-env/package.json
- packages/kit/test/build-errors/apps/private-static-env-dynamic-import/package.json
- packages/kit/test/build-errors/apps/private-static-env/package.json
- packages/kit/test/build-errors/apps/server-only-folder-dynamic-import/package.json
- packages/kit/test/build-errors/apps/server-only-folder/package.json
- packages/kit/test/build-errors/apps/server-only-module-dynamic-import/package.json
- packages/kit/test/build-errors/apps/server-only-module/package.json
- packages/kit/test/prerendering/basics/package.json
- packages/kit/test/prerendering/options/package.json
- packages/kit/test/prerendering/paths-base/package.json
- packages/kit/test/prerendering/ssr-false/package.json
- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
Run our tests against Vite 4.0.4. This includes a mitigation (though not fix) for a race condition in Vite, so may make our Windows CI more stable
> [chore] upgrade to Vite 4.0.4

- documentation/docs/30-advanced/25-errors.md
From time to time people do not read the entire docs and just jump in, here they see that they can add extra properties besides `message` in the error object, but doing that will give TypeScript warnings.  This change just gives a heads-up to those needing this, that later will be explained how to define this new type.
> Add extra clarification for custom error message

- documentation/docs/30-advanced/20-hooks.md
I'm not an expert at promises, but I believe this `async` is unnecessary since we don't do any `await` inside the function
> [docs] remove unused async

- packages/kit/src/runtime/server/page/load_data.js
This patch uses the route id in the error message rather than the route object `... (at [object Object])`
> Fix route formatting in error message

- documentation/docs/30-advanced/10-advanced-routing.md
`src/routes/[[a]]/foo/+page.svelte` doesn't match the route `/foo-abc` , and there aren't any cases with parameter matcher, so I propose using `src/routes/[[a=string]]/+page.svelte` instead.
> [docs] fix route example in 10-advanced-routing.md

- documentation/docs/20-core-concepts/20-load.md
Reverts sveltejs/kit#8194. I disagree with that change — in SvelteKit layouts, slots are 'void' in that they can't have fallback content. This change makes it look like you _can_ put stuff inside slots, and almost looks like you're _expected_ to put something there.
> Revert "Improved example code"

- .changeset/tricky-foxes-buy.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/routing/form-get/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
fixes #8253
* Checks if a submit value is present then appends the name and value to the form data.
* Updates the enhanced GET test with an expected submit name and value pair.
> include submitter value in enhanced GET forms

- .changeset/wise-adults-pull.md
- packages/kit/src/core/prerender/prerender.js
- packages/kit/src/exports/node/polyfills.js
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/src/exports/vite/preview/index.js
- packages/kit/src/utils/platform.js
- packages/kit/types/internal.d.ts
Fixes https://github.com/sveltejs/kit/issues/8324
> [fix] don't polyfill undici if using Deno or Bun

- .changeset/shy-monkeys-raise.md
- packages/kit/src/runtime/server/index.js
- packages/kit/types/index.d.ts
This PR is to resolve issue https://github.com/sveltejs/kit/issues/8230 in which the platform object does not match it's types.
`event.platform` is typed as an empty object by default so I am changing the server response to fallback to this rather than allowing it to be undefined.
An alternative could be to update the types to make platform optional within event.
> Update request type definitions to make platform possibly undefined

- .changeset/healthy-singers-stare.md
- .changeset/old-chicken-cough.md
- packages/adapter-static/index.js
- packages/adapter-static/platforms.js
- packages/adapter-vercel/index.js
Hello! 
Solves https://github.com/sveltejs/kit/issues/8331
Before prerendered data.json or other non-html pages weren't included in Vercel config. It correctly adds them to it.
I monkey patched the change to my private project and it correctly worked. While fixing I found that it's also applicable to adapter Vercel. However, I'm not familiar with the codebase and the adapters system, so I'm not sure about the correctness of my approach. I'm also not sure about the test for the change but can provide one if given some advice and it's needed 😀
> [Fix] Add prerendered assets to Vercel config

- .changeset/quiet-feet-compare.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/types.d.ts
fixes #8351. This bug was made possible by lazy typing, so rather than add a new test (since we really need to figure out a way to reduce our reliance on e2e tests) I made the types stricter instead.
> guarantee that $page.route has the correct shape

- .changeset/healthy-lizards-drum.md
- documentation/docs/30-advanced/10-advanced-routing.md
- packages/kit/src/core/sync/create_manifest_data/index.js
This allows for param matcher tests to be collocated with their matchers
fixes #7583
Collocation of tests is a common practice, and the current param matcher scanning will throw an error if there are `.{test,spec}.{js,ts}` files in the `src/params` directory, as it sees them as malformed param names.
This is a simple change that just skips over those files instead of throwing an exception.
> Ignore param matchers that match .{spec,test}.{js,ts}

- documentation/docs/20-core-concepts/20-load.md
`invalidateAll` is imported, but `invalidate` is not.
> [docs] add missing import

- .changeset/dry-poets-crash.md
- packages/kit/src/runtime/client/utils.js
- packages/kit/types/ambient.d.ts
The current type for `updated.check()` is `boolean` which allows for subtle errors like the below. This will always be true since the runtime type for `check()` is a promise.
```ts
if (updated.check()) { // always true
// do something
}
```
And the code should be:
```ts
if (await updated.check()) {
// do something
}
```
Updating the types means that TS catches my mistake.
> [fix] `updated.check()` type changed to Promise<boolean>

- documentation/docs/60-appendix/10-migrating.md
> [docs] note prod dependency requirement of html-minifier

- packages/kit/test/apps/basics/test/client.test.js
This test was flaking (https://github.com/sveltejs/kit/actions/runs/3877364096/jobs/6612302810) and I can't tell why. It hit the tests's timeout limit of 45s, but as far as I can tell there wasn't anything that went wrong. Possibly this code simplification will fix it, but even if not it seemed like a good thing to do regardless
> [chore] simplify test for external link

- packages/kit/types/internal.d.ts
these are no longer used anywhere
> remove unused flags

- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/basics/test/server.test.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/apps/options/test/test.js
It seems the server may not be closing. The docs for `server.close` say "the server is finally closed when all connections are ended". Try doing `context.close()` first to see if it kills any dangling connections.
> [chore] close page before closing server

- .changeset/polite-stingrays-smell.md
- packages/adapter-cloudflare-workers/README.md
- packages/adapter-cloudflare/README.md
- packages/adapter-netlify/README.md
- packages/adapter-vercel/README.md
Closes #8039
I'm not sure what else besides documentation we can do here - the runtime error is outside of our control, and simulating this during dev sounds super hard (there's also an open issue about that somewhere I think).
> [docs] add note about inability to access file system at runtime

- packages/kit/test/apps/amp/src/app.html
- packages/kit/test/apps/options-2/src/app.html
- packages/kit/test/apps/writes/src/app.html
It's printing a warning that `%sveltekit.body%` needs to be contained within another element, which is cluttering up the console
> [chore] fix console warnings in tests

- .changeset/shy-readers-help.md
- packages/kit/src/runtime/client/fetcher.js
fixes #7992
Pretty impressive how Firefox traces things across listeners/async. This is the stack trace for a `<button on:click={() => fetch('/')}>fetch</button>`:
```
window.fetch@http://127.0.0.1:5173/@fs/REDACTED/svelte-kit/packages/kit/src/runtime/client/fetcher.js?t=1673437793682:31:46
click_handler@http://127.0.0.1:5173/src/routes/+page.svelte:303:35
EventListener.handleEvent*listen@http://127.0.0.1:5173/node_modules/.vite/deps/chunk-P54SLY7E.js?v=e5cdb4e8:360:8
listen_dev@http://127.0.0.1:5173/node_modules/.vite/deps/chunk-P54SLY7E.js?v=e5cdb4e8:1891:25
mount@http://127.0.0.1:5173/src/routes/+page.svelte:239:15
createProxiedComponent/instrument/targetCmp.$$.fragment.m@http://127.0.0.1:5173/@fs/REDACTED/svelte-kit/node_modules/.pnpm/svelte-hmr@0.15.1_svelte@3.55.0/node_modules/svelte …
```
> [fix] no false positive warnings for fetch uses in firefox

- .changeset/wise-otters-swim.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/types.d.ts
- packages/kit/src/runtime/server/page/render.js
Clicking a page link and staying on the same page with nothing changing still changed the $page.store, because
- form was always !== undefined (it's null)
- $page.error was set to undefined after hydration, but it should be null
No test because it's super silly to e2e test this - we really need `client.js` to be unit-testable.
Discovered while investigating another issue which is no longer reproducible.
> [fix] avoid unnecessary $page store updates

- .changeset/angry-ways-divide.md
- packages/kit/src/runtime/server/data/index.js
- packages/kit/test/apps/basics/src/routes/prerendering/prerendered-endpoint/api/+server.js
- packages/kit/test/apps/basics/src/routes/prerendering/prerendered-endpoint/page/+page.server.js
- packages/kit/test/apps/basics/src/routes/prerendering/prerendered-endpoint/page/+page.svelte
- packages/kit/test/apps/basics/test/test.js
> [fix] prerendered endpoint callable from non-prerendered server load

- documentation/docs/20-core-concepts/10-routing.md
- documentation/docs/30-advanced/25-errors.md
> docs: clarify some +error.svelte behavior

- .changeset/mean-pants-destroy.md
- packages/kit/types/index.d.ts
> docs: links to http status codes

- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/basics/test/server.test.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/apps/options/test/test.js
- packages/kit/test/utils.d.ts
- packages/kit/test/utils.js
so we don't have to try/finally inside the tests and leave playwright created contexrt alone
> chore: move `start_server` util in tests into a fixture

- .changeset/eleven-rules-sleep.md
- packages/adapter-cloudflare-workers/ambient.d.ts
- packages/adapter-cloudflare/ambient.d.ts
fixes #8268
Theoretically someone could have relied on us auto-loading the ambient types previously, but I doubt it because it means that `adapter-cloudflare` would have been imported somewhere where our `tsconfig.json`'s `include` includes it (the `svelte.config.js` isn't), _and_ you'd need to access cloudflare-specific things outside of `platform`. Getting the behavior back as a user is as easy as slapping `/// <reference types="@cloudflare/workers-types" />` at the top of `src/app.d.ts`.
> fix: don't load ambient worker types

- .changeset/tidy-tools-suffer.md
- documentation/docs/30-advanced/40-service-workers.md
- packages/kit/src/core/sync/write_tsconfig.js
This is necessary so the recommended way to get sw types doesn't remove the globals from other files in the project.
Also document how to get types working inside the file closes #8127
> fix: exclude service worker from tsconfig

- .changeset/selfish-tools-prove.md
- packages/create-svelte/templates/default/src/app.d.ts
- packages/create-svelte/templates/skeleton/src/app.d.ts
- packages/create-svelte/templates/skeletonlib/src/app.d.ts
- packages/kit/types/ambient.d.ts
> fix: adjust `app.d.ts` to diminish confusion about imports

- .changeset/nine-pets-join.md
- packages/kit/src/exports/vite/index.js
Uses a preprocessor to check the script contents of Svelte files for "export const prerender/csr/ssr/trailingsSlash =" or a missing `<slot />` in case of a layout file
closes #7411
closes #7773
> feat: add preprocessor warning about common mistakes

- .changeset/tiny-badgers-swim.md
- packages/kit/src/runtime/server/page/render.js
> fix: provide better error message in case of missing `+page.svelte`

- .changeset/breezy-vans-prove.md
- packages/adapter-auto/package.json
- packages/adapter-cloudflare-workers/package.json
- packages/adapter-cloudflare/package.json
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-static/package.json
- packages/adapter-vercel/package.json
- packages/amp/package.json
These are already in `exports` and are causing publint warnings for me
> chore: remove superfluous fields from package.json

- .changeset/purple-poets-approve.md
- packages/adapter-cloudflare-workers/package.json
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-static/package.json
- packages/adapter-vercel/package.json
- packages/amp/package.json
Fix https://github.com/sveltejs/kit/issues/8530
npm and pnpm includes the file in `pkg.main` to publish by default. Since https://github.com/sveltejs/kit/pull/8519 removed the `pkg.main` field, we forgot to add the `index.js` file to the `pkg.files` field, causing it to be missing after publish.
This PR updates the `pkg.files` field
> fix: publish missing files

- .changeset/olive-cars-wonder.md
- packages/migrate/migrations/routes/migrate_scripts/index.js
fixes #8518
Adds a more extensive regex that checks for `export let` when a load function is present.
> fix: add more extensive migration export regex

- packages/kit/test/apps/basics/test/test.js
Another attempt of https://github.com/sveltejs/kit/pull/8440
A few of the flaky tests use [`type`](https://playwright.dev/docs/api/class-page#page-type) to input text. This PR updates them to use [`fill`](https://playwright.dev/docs/api/class-locator#locator-fill) instead, which is more reliable.
There is a slight difference in behavior between `type` and `fill`. Fill seems more robust because it carries out a [few](https://playwright.dev/docs/actionability) more extra checks before interacting with the element.
> Try inputting text using `fill` to reduce test flakiness

- .changeset/clean-onions-doubt.md
- packages/kit/types/index.d.ts
Someone in the Discord reported that there's a direct link to the vercel sveltekit docs instead of kit.svelte.dev for the typing for Action. This PR changes it to kit.svelte.dev.
> fix: correct link in types documentation

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
this will hopefully prevent changesets PRs like https://github.com/sveltejs/kit/pull/8588 from failing
> change dependency workspace:^

- documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
- documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
- documentation/docs/30-advanced/20-hooks.md
- documentation/docs/30-advanced/25-errors.md
- packages/adapter-static/test/apps/spa/src/app.d.ts
- packages/kit/test/apps/basics/src/app.d.ts
- packages/kit/test/apps/options-2/src/app.d.ts
- packages/kit/test/apps/options/source/app.d.ts
- packages/kit/test/apps/writes/src/app.d.ts
- packages/kit/test/build-errors/apps/private-dynamic-env-dynamic-import/src/app.d.ts
- packages/kit/test/build-errors/apps/private-dynamic-env/src/app.d.ts
- packages/kit/test/build-errors/apps/private-static-env-dynamic-import/src/app.d.ts
- packages/kit/test/build-errors/apps/private-static-env/src/app.d.ts
- packages/kit/test/build-errors/apps/server-only-folder-dynamic-import/src/app.d.ts
- packages/kit/test/build-errors/apps/server-only-folder/src/app.d.ts
- packages/kit/test/build-errors/apps/server-only-module-dynamic-import/src/app.d.ts
- packages/kit/test/build-errors/apps/server-only-module/src/app.d.ts
updates docs to use the preferred form of `App` declaration. closes #8587
> chore: use `declare global` instead of ambient declarations

- .changeset/forty-berries-march.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/cookie.spec.js
closes #8584. ~~Though a large part of me thinks this should be an error rather than a warning. Thoughts?~~ it is now an error
> feat: throw error if cookie size exceeds 4,129 bytes

- documentation/docs/20-core-concepts/30-form-actions.md
- sites/kit.svelte.dev/src/lib/docs/server/index.js
Changes the Form actions documentation section TS examples to use `satisfies`.
They are currently using the old `export const actions: Actions = {`
https://kit.svelte.dev/docs/form-actions
> docs: add satisfies for actions

- .changeset/cold-students-repair.md
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/test/apps/options/source/pages/test.txt
- packages/kit/test/apps/options/test/test.js
[Importing an asset](https://kit.svelte.dev/docs/assets) would not work if you'd set `paths.base` because we were not stripping off the base path before checking for the asset on the file system
> fix: allow importing assets while using base path

- .changeset/gorgeous-bulldogs-talk.md
- packages/kit/src/runtime/server/respond.js
- packages/kit/test/apps/basics/src/hooks.server.js
- packages/kit/test/apps/basics/test/cross-platform/test.js
fixes #8643
Adds headers and cookies to the response when using `throw redirect` in `handle` so that it behaves similarly to returning a new redirect `Response` in `handle`.
I'm sure there's a more elegant approach to this fix and the test, but I can't quite figure it out (this is my first time writing a test). Would appreciate any suggested changes.
> fix: set headers when throwing redirect in handle

- .changeset/fast-boxes-perform.md
- packages/kit/src/runtime/server/page/render.js
- turbo.json
fixes https://github.com/sveltejs/kit/issues/2958
> fix: include base path in path to start script

- .changeset/early-rockets-impress.md
- packages/create-svelte/scripts/build-templates.js
This PR solves a minor formatting issue present in TypeScript demo app. The issue is that for `packages/create-svelte/templates/default/src/routes/sverdle/+page.server.ts` [line 59](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/src/routes/sverdle/%2Bpage.server.ts#L59) and `packages/create-svelte/templates/default/src/routes/sverdle/game.ts` [line 23](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/src/routes/sverdle/game.ts#L23) produced corresponding TypeScript files have double space where closing `/***/` JSDoc comment from original templates was located. I believe the only outcome caused by this PR is that TypeScript demo app in two linked locations has single space instead of a double space.
> fix: remove duplicate space in create-svelte templates for TS demo app

- .changeset/new-insects-raise.md
- packages/kit/src/runtime/server/page/actions.js
- packages/kit/src/runtime/server/page/index.js
- packages/kit/test/apps/basics/test/server.test.js
> fix: provide proper error when POSTing to a missing page endpoint

- documentation/docs/60-appendix/10-migrating.md
This PR simply enhances the docs by fixing a bad url. Originally, the info about custom servers was on the readme for the adapter-node, but then, it was moved into the adapter-node page on the svelte kit docs themselves.
---
> docs: url was wrong for custom node server

- .changeset/nervous-bags-jog.md
- packages/kit/src/core/sync/ts.js
- packages/kit/src/core/sync/write_tsconfig.js
- packages/kit/src/core/sync/write_types/index.js
> fix: add `ignoreDeprecations` flag for TS 5.x

- packages/kit/src/utils/fork.js
another possible solution to the timeouts in #8636
> delay until ready

- documentation/docs/25-build-and-deploy/50-adapter-static.md
In this PR, `config.kit.prerender.enabled` was removed: https://github.com/sveltejs/kit/pull/7762
The `adapter-static` docs still referenced it, which sent me down a little rabbit hole where I had to find that out the hard way.
> docs: `config.kit.prerender.enabled` does no longer exist

- documentation/docs/20-core-concepts/20-load.md
Newcomers may benefit from this one added line. Especially since if a user accidentally writes something like this client-side:
```js
throw redirect(302, '/somePage');
```
There isn't an any indication of why it fails. So if they head over to the docs, this will point them in the right direction. (It would be great if SvelteKit also had a good error message for throwing a redirect client side, too.)
Forgive me ignoring the checklist, this is merely a proposed doc change.
> Mention client-side navigation alongside server-side redirect

- .changeset/purple-starfishes-sip.md
- packages/adapter-vercel/index.js
fixes #8755
Adds a redirect for prerendered non-trailing slash routes to `adapter-vercel`.
Previously, only prerendered trailing slash routes would be added to the redirects list in the vercel config file.
> fix: add prerendered redirect for non-trailing slash routes with the Vercel adapter

- .changeset/silent-planes-smell.md
- packages/kit/src/runtime/client/fetcher.js
- packages/kit/src/runtime/hash.js
- packages/kit/src/runtime/server/page/load_data.js
- packages/kit/src/runtime/server/page/serialize_data.js
- packages/kit/src/runtime/server/page/types.d.ts
- packages/kit/test/apps/basics/src/routes/load/fetch-cache-control/+page.svelte
- packages/kit/test/apps/basics/src/routes/load/fetch-cache-control/headers-diff/+page.js
- packages/kit/test/apps/basics/src/routes/load/fetch-cache-control/headers-diff/+page.svelte
- packages/kit/test/apps/basics/src/routes/load/fetch-cache-control/headers-diff/+server.js
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/basics/test/test.js
> fix: cache mechanism for request with different headers

- .changeset/chatty-forks-press.md
- .changeset/fast-jokes-sing.md
- packages/kit/src/utils/routing.js
- packages/kit/src/utils/routing.spec.js
Fixes https://github.com/sveltejs/kit/issues/8601
Actually, managed to clean up the whole thing and make it work with every valid test case I could think of.
~~It's not pretty (it's not *that* bad either), but it works.~~
~~There's still a case it doesn't solve though, but I'm fairly confident we got time before someone actually goes for such thing.~~
> fix: allow rest parameters to follow multiple optional - or not - parameters

- documentation/docs/25-build-and-deploy/90-adapter-vercel.md
In a Vercel deployment, you can create API routes like so:
```js
// project/api/hello.js
export default function handler(request, response) {
response.status(200).json({
body: 'hello'
});
}
```
If you have an `api` directory, Vercel will inject a route into your configuration that matches all `/api/*` requests. This means that any `project/src/routes/api/*` routes will never be invoked.
Currently, the documentation says Vercel `api` functions are ignored, which is incorrect. This PR fixes it.
> docs: clarify Vercel `api` functions

- .changeset/honest-geckos-jog.md
- packages/kit/src/exports/vite/index.js
regression reported in https://github.com/vite-pwa/sveltekit/issues/21
I don't think the reset would do anything. `buildStart` will be run for both the server and client builds before `closeBundle` is run for either
> fix: await finalise hook and run it only once

- .github/workflows/ci.yml
- package.json
- packages/kit/package.json
- packages/kit/test/apps/basics/package.json
- packages/kit/test/build-errors/package.json
Firefox takes twice as long to run as Chrome. By splitting dev and build into two jobs we can run them in parallel and finish twice as fast soling our timeout issues
I also moved the Firefox tests to Ubuntu. Eventhough this means we test an additional variant it reduces our billing because Windows is billed at a higher rate
> chore: split dev and build cross-browser tests

- sites/kit.svelte.dev/src/lib/docs/server/index.js
Closes #7854. Extracts generics along with the name to establish extra information when converting to typescript.
I would absolutely love a suggestion on this, as the current trick to un-indent the closing brace in generics is a bit hacky and may not work in different use cases.
> docs: apply generics to typescript example

- .changeset/warm-bananas-sneeze.md
- packages/adapter-node/ambient.d.ts
- packages/adapter-node/index.js
- packages/adapter-node/src/handler.js
fixes #8755
Adds prerendered pages to the manifest so that a middleware can check if a counterpart route exists, and redirect to it.
I'm not too experienced with Express / Polka and writing middleware for them, so I'm sure this can be fixed up a bit.
Specifically, I'm sure there's a way to skip the middleware for serving prerendered routes and go straight to ssr.
We should do this since we already check if it's prerendered or not.
Also, I'm not sure if there are any penalties for including the prerendered routes list in the manifest.
> add trailing slash redirect middleware to adapter-node

- documentation/docs/20-core-concepts/40-page-options.md
- packages/adapter-static/index.js
- packages/adapter-vercel/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/adapt/builder.spec.js
- packages/kit/src/core/adapt/index.js
- packages/kit/types/index.d.ts
- packages/kit/types/private.d.ts
Follow-up to https://github.com/sveltejs/kit/pull/8740#issuecomment-1414088396. It's increasingly apparent that `builder.createEntries` is the wrong API — it tries to make it simple to merge routes into a single function, but the result is anything but.
The approach here is much simpler — just expose the `RouteDefinition` objects to the builder directly, and let it do whatever it wants.
WIP — need to kick the tyres a bit more before committing
> Route level config alt

- .changeset/loud-pans-fly.md
- packages/kit/types/ambient.d.ts
#8775. I don't think we can/should change the behaviour until 2.0, but in the meantime we can discourage people from using `goto` with external URLs
> tell people to avoid `goto(external)`

- .changeset/slimy-donkeys-itch.md
- packages/kit/src/runtime/server/endpoint.js
- packages/kit/src/runtime/server/respond.js
- packages/kit/test/apps/basics/src/routes/prerendering/prerendered-endpoint/proxy/+server.js
- packages/kit/test/apps/basics/test/server.test.js
fixes #8851
adds `state.initiator` in `endpoint.js#render_endpoint` similar to https://github.com/sveltejs/kit/pull/8453 as suggested by Simon (dummdidumm)
> fix: prerendered endpoint callable from non-prerendered endpoint

- .changeset/fuzzy-kangaroos-relate.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/utils.js
Closes #7966
Closes https://github.com/sveltejs/kit/pull/8142
Reading [this comment](https://github.com/sveltejs/kit/pull/8142#issuecomment-1351327046), there's a chance I may have completely misunderstood what the PR was trying to do, but at least this is what I got from the repro and the list of steps on #7966.
> fix: correctly handle HttpError on the client

- .changeset/silent-icons-guess.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/load/serialization/+page.js
- packages/kit/test/apps/basics/test/test.js
fixes https://github.com/sveltejs/kit/issues/8852
Slices the origin from any client fetch request URLs so that they're always similar in format to fetches done on the server.
Also adjusts one of the tests to account for absolute URL fetches in shared load functions.
> fix: correctly serialize request url when using load `fetch`

- .changeset/breezy-cycles-thank.md
- packages/kit/test/types/actions.test.ts
- packages/kit/types/index.d.ts
> fix: ensure types of all form actions are accessible

- renovate.json
Renovate is calling upgrades of devDeps chore and deps fix. If we're upgrading because of renovate then it's usually not because there's some specific issue we're trying to address, so I think chore is more appropriate
> chore: mark all renovate changes as chore

- .changeset/lucky-tables-jam.md
- packages/kit/src/core/postbuild/crawl.js
- packages/kit/src/core/postbuild/fixtures/basic-src/input.html
The empty src was crawled as a relative url.
On `/page/about` this would route to `/page/` which could 404
Demo: https://stackblitz.com/edit/sveltejs-kit-template-default-ccvbsj?file=src/routes/page/about/+page.svelte
> fix: Prevent crawling empty urls from <img src="">

- .changeset/cyan-ladybugs-divide.md
- packages/adapter-auto/adapters.js
- packages/adapter-auto/index.js
MUST be released before #8740 is merged
`version` is used to pin the installed adapter version and should point to the latest version of the adapter that is compatible with adapter-auto's current peerDependency version of SvelteKit. Will prevent adapter-auto from accidentally installing adapter versions that are possibly incompatible with the user's SvelteKit version.
> fix: pin adapter versions in adapter-auto

- .changeset/late-dancers-vanish.md
- packages/adapter-node/package.json
- packages/adapter-node/rollup.config.js
- packages/adapter-node/src/handler.js
- pnpm-lock.yaml
fixes #8888 
Tests have been disabled for adapter-node since #2931, so didn't add any in this one. Will look into re-enabling.
> fix: serve_prerendered breaks on node http server

- .changeset/large-tables-breathe.md
- packages/adapter-netlify/index.js
- packages/adapter-vercel/index.js
For the Vercel and Netlify adapters. adapter-auto on earlier versions could install them when it shouldn't
Related to #8911
> chore: throw helpful migration error

- .changeset/large-toes-fetch.md
- packages/kit/src/runtime/app/stores.js
- packages/kit/types/ambient.d.ts
this separates out the error message part of #8547 from the docs, since it's a no-brainer
> print useful errors when subscribing to stores during SSR

- .changeset/six-poems-exist.md
- packages/kit/src/runtime/client/client.js
https://github.com/sveltejs/kit/issues/8301#issuecomment-1397139603 — aside from the question around what should happen when preloading data results in an error response, we should only be printing 'Attempted to preload...' errors to the console when preloading was done explicitly. No test for this, it felt like overkill
> ignore external links when automatically preloading

- .changeset/famous-hornets-invite.md
- packages/kit/src/exports/node/polyfills.js
Currently there is no global `File` object available. Usually this is fine, as any "file" returned by `FormData` still has the normal properties and methods available.
The problem became apparent when using `zod-form-data`, a library that relies on the global `File` object.
```javascript
import { zfd } from "zod-form-data";
const schema = zfd.formData({
pdf: zfd.file(),
});
```
Discussion [here](https://discord.com/channels/457912077277855764/1072401358419935262).
This is a simple fix, just adds another import from `undici` to include `File`.
> Update polyfills.js to include File

- .changeset/rich-chefs-refuse.md
- packages/adapter-netlify/index.js
no issue, i saw this while looking at something else
> fix: correctly compare routes when splitting functions

- .changeset/dirty-days-fix.md
- packages/kit/src/runtime/server/utils.js
- packages/kit/test/apps/basics/test/server.test.js
fixes https://github.com/sveltejs/kit/issues/8967
changes the list iteration keyword from `in` to `of` so comparisons are correctly made with the values in the list of allowed http methods.
> fix: correctly check allowed endpoint methods

- documentation/docs/30-advanced/40-service-workers.md
The additional reference is needed for $service-worker to be properly typed
Came out of https://github.com/sveltejs/kit/commit/6c7f9b201e5b70f456e5f34d43b9380ffa907db6#commitcomment-99882092 (cc @bart)
> docs: service worker types

- .changeset/rich-llamas-knock.md
- .changeset/thirty-ways-dress.md
- packages/adapter-static/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/postbuild/fallback.js
fixes #8971 — we were missing an `await`. Also takes advantage of the new `forked` utility to make the code a bit nicer
> fix: generate fallback page before compressing

- .changeset/loud-comics-stare.md
- packages/kit/src/runtime/client/client.js
> fix: warn when preload fails

- documentation/docs/20-core-concepts/20-load.md
- packages/kit/types/index.d.ts
The language "which results in a noop" is unnecessarily technical and doesn't clearly explain why that is bad.
This changes it to "which would prevent SvelteKit from handling it".
---
> docs: use less technical language to describe why catching redirects and errors is fraught

- .changeset/eleven-buckets-hammer.md
- packages/kit/src/exports/vite/index.js
This fixes a regression from #8977 where vite_config is the resolved config so build.minify is defaulted to `false` for ssr builds if the user doesn't specify an option manually.
I *think* `minify` is the only relevant inline option that's [overriden](https://github.com/vitejs/vite/blob/5364c901dca31d4a16dac288bcb55305949d10ae/packages/vite/src/node/build.ts#L324), so this should be the only one that needs special handling.
> fix: client build minification

- .changeset/strange-sheep-grab.md
- documentation/docs/25-build-and-deploy/40-adapter-node.md
- packages/adapter-node/index.d.ts
- packages/adapter-node/index.js
- packages/adapter-node/rollup.config.js
- packages/adapter-node/src/handler.js
This would close #7374 - I wasn't sure the best way to go about this but settled on this solution. Instead of building the polyfills into the `handle.js` before publishing `adapter-node` it will build a `shims.js` file which `handle.js` imports. If the `polyfill` option is `false` when the adapter code runs then it will empty the local copy of `shims.js` so it won't end up loading any polyfills
> Add polyfill option to adapter-node

- sites/kit.svelte.dev/src/lib/search/content.server.js
closes #8992
This hook or renderer or whatever marked calls it is only invoked for raw HTML in the markdown files which I doubt there's any we would want to index, and example html inside eg. codeblocks works as intended.
> docs: Strip decorative HTML from search results

- .changeset/long-paws-judge.md
- packages/kit/package.json
- packages/kit/src/exports/vite/index.js
- packages/kit/src/internal.d.ts
- packages/kit/src/runtime/app/paths.js
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/utils.js
- packages/kit/src/runtime/server/fetch.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/respond.js
- packages/kit/src/runtime/shared.js
- packages/kit/types/ambient.d.ts
- sites/kit.svelte.dev/src/lib/docs/server/render.js
closes https://github.com/sveltejs/kit/issues/9009
> fix: use internal alias that won't collide with user aliases

- .changeset/clever-books-study.md
- packages/adapter-cloudflare/index.js
closes https://github.com/sveltejs/kit/issues/9041
Checks for the `_headers` and `_redirects` filenames when filtering assets to add to the `exclude` list in the `_routes.json` file.
> fix: prevent `_headers` and `_redirects` files from being included in Cloudflare `_routes.json`

- .changeset/selfish-doors-watch.md
- packages/kit/src/exports/vite/index.js
- packages/kit/src/internal.d.ts
- packages/kit/src/runtime/app/paths.js
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/utils.js
- packages/kit/src/runtime/server/fetch.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/respond.js
- packages/kit/src/runtime/shared.js
closes https://github.com/sveltejs/kit/issues/9047
closes #9049 
We mess around with `@sveltejs/kit` in `optimizeDeps` and `ssr.external`/`ssr.noExternal`. Use a different package name to avoid that. That's probably also related to why the tests didn't catch this - Vite automatically handles pnpm linked packages differently
> fix: use non-existent package name for virtual module

- packages/create-svelte/test/check.js
see #9047  which was not caught even though  create-svelte tests do run `build` in a project created with local `create-svelte`.
for some reason absolute path overrides without `file:` protocol are treated differently, adding it made the test fail with when using `@sveltejs/kit/paths` instead of `__sveltekit_paths` as internal virtual module.
> fix(test): use file: protocol for overrides in create-svelte tests for stricter resolve

- .changeset/bright-lizards-deny.md
- packages/kit/src/core/postbuild/analyse.js
- packages/kit/src/exports/vite/build/build_server.js
- packages/kit/src/utils/exports.js
- packages/kit/src/utils/exports.spec.js
- packages/kit/types/internal.d.ts
- closes #9034 
This adds a more helpful error message around "Invalid export" (module export validation) to help steer users who are using a named export in the wrong file that is supported elsewhere.
I used a relatively simple approach with hard coded file names because I didn't want to overengineer it too much. If we want a more flexible solution I'm open to suggestions.
I'm not sure if this is a "change that should be noted in one or more packages' changelogs", so please tell me if you want a changeset for this. If yes, would it be a feature?
> Error hint for invalid exports

- .changeset/fast-mugs-cover.md
- packages/migrate/package.json
- packages/migrate/utils.js
fixes #9084
Published files with the change:
```
npm notice 470B   README.md                                     
npm notice 594B   bin.js                                        
npm notice 2.1kB  migrations/package/index.js                   
npm notice 2.2kB  migrations/package/migrate_config.js          
npm notice 4.6kB  migrations/package/migrate_pkg.js             
npm notice 6.7kB  migrations/routes/index.js                    
npm notice 5.3kB  migrations/routes/migrate_page_js/index.js    
npm notice 3.6kB  migrations/routes/migrate_page_server/index.js
npm notice 4.4kB  migrations/routes/migrate_scripts/index.js    
npm notice 5.5kB  migrations/routes/migrate_server/index.js     
npm notice 205B   migrations/routes/tasks.js                    
npm notice 10.2kB …
```
> fix: published files for svelte-migrate

- .changeset/pretty-kids-camp.md
- documentation/docs/25-build-and-deploy/90-adapter-vercel.md
- packages/adapter-vercel/files/serverless.js
- packages/adapter-vercel/index.d.ts
- packages/adapter-vercel/index.js
We shipped incremental static regeneration on Vercel last week, but it was broken. Turns out there were a few extra hoops to jump through.
Brief explanation of the changes:
* every route needs a `group`, so that if you invalidate `/foo` you simultaneously invalidate `/foo/__data.json` — this is assigned automatically
* the pathname is passed to the prerender function as the `__pathname` query parameter. `req.url` is reconstructed by `adapter-vercel` before the request is handed off to SvelteKit
* so that we can know if `/foo` or `/foo/__data.json` is being requested, while still allowing `/foo` and `/foo/__data.json` to be invalidate simultaneously, we need to create two Vercel routes for each SvelteKit route with `isr`. To save space, these are symlinks rather than duplicates
> fix: ISR support for `adapter-vercel`

- .changeset/quick-cats-jam.md
- packages/create-svelte/templates/skeletonlib/package.template.json
publint is called by the package script above. This doesn't really "fix" anything so labelled it as a chore but still needs a changeset.
> chore: run publint only once in prepublish script

- packages/create-svelte/test/check.js
Ever since #9052, `create-svelte` tests fail for me locally. I haven't been able to figure out why, so I figured I'd just do this for now
>  omit file protocol for create-svelte tests outside CI

- .changeset/friendly-pandas-sort.md
- packages/package/src/validate.js
- packages/package/test/fixtures/assets/package.json
- packages/package/test/fixtures/emitTypes-false/package.json
- packages/package/test/fixtures/javascript/package.json
- packages/package/test/fixtures/resolve-alias/package.json
- packages/package/test/fixtures/svelte-kit/package.json
- packages/package/test/fixtures/typescript/package.json
- packages/package/test/index.js
- packages/package/test/watch/package.json
> fix: dont emit false positive export condition warning

- .changeset/chilly-rats-glow.md
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/page/render.js
It turns out that if `response.body` is a `ReadableStream`, it must be a `ReadableStream<Uint8Array>`. This escaped notice before, because Node does its own thing, quelle surprise
> encode streamed chunks

- .changeset/smart-fishes-boil.md
- packages/kit/src/runtime/server/page/render.js
The newline needs to come _after_ the `<script>`, not before, so that it evaluates immediately
> append newline to trigger script evaluation

- .changeset/plenty-pugs-hunt.md
- packages/kit/src/runtime/server/data/index.js
It turns out that `text/plain` is buffered in some cases. I don't really understand how or why, but using a proprietary content type for streamed `__data.json` files seems to do the trick
> use a proprietary content-type

- .changeset/thirty-dodos-play.md
- documentation/docs/30-advanced/70-packaging.md
- packages/migrate/migrations/package/migrate_pkg.js
- packages/migrate/migrations/package/migrate_pkg.spec.js
> fix: include index in typesVersions because it's always matched

- .changeset/nice-pugs-occur.md
- packages/adapter-vercel/index.js
This enables streaming from serverless functions on Vercel (edge functions already support streaming)
> enable experimental response streaming

- .changeset/good-bikes-cross.md
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/endpoint.js
- packages/kit/src/runtime/server/fetch.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/index.js
- packages/kit/src/runtime/server/page/load_data.spec.js
- packages/kit/src/runtime/server/page/respond_with_error.js
- packages/kit/src/runtime/server/respond.js
- packages/kit/src/runtime/server/utils.js
- packages/kit/test/apps/basics/src/hooks.server.js
- packages/kit/test/apps/basics/src/routes/prerendering/prerendered-endpoint/+page.svelte
- packages/kit/test/apps/basics/test/test.js
- packages/kit/types/internal.d.ts
fixes #9183
also consolidates usage of state.initiator across the server, only setting it in one place now where it's correct, prior to calling the internal fetch function. this means it now compares by url string, not matched route
> fix: allow relative fetch to endpoint outside app from within handle

- packages/kit/src/exports/vite/index.js
Simplifies `noExternal`, and reinstates the `external` config that #9172 incorrectly removes
> fix: always bundle SvelteKit, always externalize CommonJS dependencies during development

- .changeset/mighty-cars-wave.md
- packages/create-svelte/bin.js
- packages/create-svelte/package.json
- pnpm-lock.yaml
Thought I'd have a go at using [`@clack/prompts`](https://twitter.com/n_moore/status/1624951793829519362) to make the `create-svelte` experience slightly more polished.
Before:
After:
> feat: use @clack/prompts

- .changeset/lazy-olives-mix.md
- packages/kit/src/exports/vite/index.js
We had added SvelteKit to `external` in https://github.com/sveltejs/kit/pull/5861 to make the tests pass as it was needed for Vite 3. It appears to no longer be necessary with Vite 4
This partially addresses https://github.com/sveltejs/kit/issues/9162. There's still another issue I'll need to fix
> fix: bundle SvelteKit when using Vitest

- .changeset/tiny-deers-complain.md
- packages/adapter-vercel/index.js
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/postbuild/analyse.js
- packages/kit/types/index.d.ts
- packages/kit/types/internal.d.ts
Vercel Cron Jobs are launching. Thanks to their API, we don't actually have to make any changes to support them.  However, as a courtesy to our users, we _can_ make sure that a SvelteKit app exports a `GET` API handler that matches the path for each cron job. We can't do more than warn here, as users could handle these requests in `handle`, but I think the normal usecase would be to define a `+server.ts` endpoint.
> feat: Validate Vercel cron paths

- .changeset/gold-fireants-talk.md
- packages/kit/src/exports/vite/index.js
fixes #9234
FYI @benmccann @Rich-Harris we _always_ need `@sveltejs/kit` to be part of `noExternal`. Else the build output contains something like 
```js
import { redirect } from '@sveltejs/kit';
// some compiled code..
redirect(307, '..');
```
while the output code _also_ contains the SvelteKit server runtime, including their own definitions for `Redirect` etc classes, which means all instanceof checks fail.
> fix: always add `@sveltejs/kit` to `noExternal` for ssr build

- documentation/docs/20-core-concepts/50-state-management.md
- packages/kit/src/runtime/app/stores.js
builds on #8547:
* focuses on how to prevent shared state on the server rather than saying 'you don't need to worry about this if you build an SPA', because that will unduly encourage people to build SPAs
* separate section for stores+context
* explanation of component state preservation
* mention snapshots
* remove form stuff
> docs: state management part 2

- .changeset/chilled-rivers-learn.md
- packages/kit/src/exports/vite/index.js
Closes https://github.com/sveltejs/kit/issues/9162
We should really add tests for this...
> fix: correct undefined reference to global var with Vitest

- .changeset/witty-drinks-burn.md
- packages/adapter-vercel/index.js
* closes #8287
Ensures that you never see this:
> add catch-all route for framework 404s rather than platform 404s

- .changeset/nasty-guests-sing.md
- packages/kit/src/utils/routing.js
- packages/kit/src/utils/routing.spec.js
Closes https://github.com/sveltejs/kit/issues/9261
In the scenario outlined in the linked issue, with 2 chained optional parameters, skipping the first optional parameter would result in a 404.
When the first optional parameter was detected as being missing, a buffer variable was incremented to allow the 2nd parameter to be correctly assigned. However this buffer was never reset (except in the case of a [...rest] parameter being present). This was triggering the `if(buffered) return;`  check, resulting in a 404.
This change resets the buffer back to 0 in the appropriate circumstance.
The check verifies that the next parameter is not a [...rest] parameter. If it is, we don't reset the buffer in order to trigger the coalescing of remaining values into [...rest].
If it's _not_ a rest …
> fix: successive optional route parameters can now be empty

- .changeset/tough-seals-attend.md
- packages/adapter-node/index.js
closes #9264. The issue was that the dependency in question, `vidstack`, has a bunch of different exports for different conditions; the `node` condition points at a module that is capable of running on the server.
When running in `dev` and `preview`, the module was loaded through Node, and so naturally the `node` condition was used. But `adapter-node` bundles the dependency using the `default` condition, which points at a production browser build.
This PR fixes it by using the `node` export condition for resolution when bundling dependencies.
> use `node` export condition when bundling

- .changeset/thin-readers-speak.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte
- packages/kit/test/apps/basics/test/test.js
> set `form` to `null` before updating it with real values

- .changeset/nervous-beans-roll.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/src/runtime/server/cookie.spec.js
- packages/kit/types/index.d.ts
> feat: add `cookies.getAll`

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
This is basically the only place `ssr-svelte` is documented and bugs won't reproduce if you use the standard template, which means even for advanced users there's no way to understand how to report a bug other than this documentation.
it was accidentally removed in https://github.com/sveltejs/kit/pull/8109
reverts https://github.com/sveltejs/kit/pull/9094
> chore: restore bug reporting section of readme

- .changeset/popular-jeans-wait.md
- packages/adapter-cloudflare-workers/index.js
- packages/adapter-cloudflare/index.js
> use es2022 instead of es2020

- .changeset/heavy-spiders-invite.md
- packages/create-svelte/bin.js
Relates to #9317 
A number of folks on Discord have been asking how to toggle options in the new 'Select additional options' step when running `npm create svelte@latest`. This change aims to provide a hint for this lesser-known prompt experience.
> fix(create-svelte): add hint when scaffolding

- .changeset/silver-teachers-lick.md
- packages/kit/src/runtime/client/client.js
closes #9189. This fix is pleasingly simple. No tests because I don't think it would be possible to write one for this
> reset scroll before resetting focus
