sveltejs/kit

packages/kit/src/core/build/index.js

Remove unused variable

---

.changeset/wild-cooks-drive.md
packages/kit/src/core/build/index.js

Do not build endpoint code for client

---

documentation/migrating/01-migrating.md

Closes https://github.com/sveltejs/kit/issues/34
This should be a pretty good start though is admittedly thin in a few places. We can add to it over time as people surface items, etc.

Start on a migration guide

---

README.md

since the repo is open and people are already finding it (👋 everyone), I figured it couldn't hurt to manage expectations a bit

add a banner to the README

---

examples/realworld.svelte.dev/src/setup/index.js
examples/sandbox/src/setup/index.js

Update for https://github.com/sveltejs/kit/pull/524#issuecomment-798975284

Fix getSession examples

---

packages/kit/src/runtime/server/page.js
packages/kit/src/types.d.ts

Closes https://github.com/sveltejs/kit/issues/232 and also fixes one of the remaining type errors

Fix error handling when thrown type is not Error

---

packages/kit/src/runtime/client/renderer.js
packages/kit/src/runtime/server/page.js

Oops. I lied when I said the last commit fixed one of the `pnpm check` errors. Now it actually does

Fix two more type errors

---

.changeset/small-pigs-doubt.md
packages/create-svelte/package.json

create-svelte: include missing ts-template

---

examples/svelte-kit-demo/src/routes/about/index.svelte
examples/svelte-kit-demo/src/routes/blog/[slug].svelte
examples/svelte-kit-demo/src/routes/blog/index.svelte
examples/svelte-kit-demo/src/routes/index.svelte

Show the title instead of localhost:3000

Add page titles to demo site

---

examples/svelte-kit-demo/src/routes/index.svelte

Or should we just delete this example project?

Remove outdated reference to Snowpack

---

packages/kit/src/runtime/server/page.js

I had gotten a bit lost and Rich was nice enough to set me straight. Adding the explanation in here for others and so I don't forget :smile:

Add a couple code comments

---

packages/kit/src/core/build/index.js
packages/kit/src/core/create_app/index.js
packages/kit/src/core/dev/index.js
packages/kit/src/runtime/server/endpoint.js
packages/kit/test/apps/basics/src/routes/routing/[...rest]/deep.json.js
packages/kit/test/apps/basics/src/routes/routing/[...rest]/deep.svelte
packages/kit/test/apps/basics/src/routes/routing/[...rest]/index.svelte
packages/kit/test/apps/basics/src/routes/routing/__tests__.js
packages/kit/types.d.ts
packages/kit/types.internal.d.ts

expose more types, tidy up others

---

documentation/migrating/01-migrating.md

This is one of the hardest things to figure out about migrating, so hopefully this will give people a pointer on where to start

Add some information about how to migrate integrations

---

packages/kit/src/runtime/client/renderer.js

Just the header type issues left now...

Fix TODO for setting load error status

---

.changeset/gorgeous-planes-rhyme.md
examples/hn.svelte.dev/src/routes/$layout.svelte
packages/kit/src/core/adapt/prerender.js
packages/kit/src/core/build/index.js
packages/kit/src/core/dev/index.js
packages/kit/src/runtime/server/page.js
packages/kit/types.internal.d.ts

only require prerender export on pages, not layouts

---

.changeset/moody-queens-sell.md
packages/kit/src/runtime/client/router.js
packages/kit/test/apps/basics/src/routes/routing/__tests__.js

create history entry for initial route

---

.changeset/brown-days-agree.md
packages/kit/package.json
packages/kit/src/core/build/index.js
packages/kit/src/core/dev/index.js
pnpm-lock.yaml

switch to @sveltejs/vite-plugin-svelte

---

.changeset/stale-mirrors-attend.md
packages/kit/src/core/create_app/index.js
packages/kit/src/runtime/app/navigation.js
packages/kit/src/runtime/client/renderer.js
packages/kit/src/runtime/client/router.js
packages/kit/types.internal.d.ts

Shrink client manifest

---

packages/kit/types.d.ts

Also create a separate interface for the response

request handler response can return a promise

---

README.md

Update README to reflect public beta

---

.changeset/poor-snakes-explode.md
packages/kit/src/runtime/server/index.js
packages/kit/src/runtime/server/page.js
packages/kit/test/apps/basics/src/routes/__tests__.js
packages/kit/test/apps/basics/src/routes/answer.json.js
packages/kit/test/apps/basics/src/routes/index.svelte

check options.initiator in correct place

---

.changeset/brave-turkeys-bathe.md
packages/kit/src/runtime/client/renderer.js
packages/kit/src/runtime/server/page.js
packages/kit/test/apps/basics/src/routes/load/__tests__.js
packages/kit/test/apps/basics/src/routes/load/fetch-request.json.js
packages/kit/test/apps/basics/src/routes/load/fetch-request.svelte
packages/kit/test/apps/basics/src/routes/load/index.svelte

allow first argument to fetch in load to be a Request

---

documentation/docs/01-routing.md
documentation/docs/03-loading.md

These forgot to be updated alongside the types.

Docs: update function signatures

---

packages/adapter-begin/README.md
packages/adapter-vercel/README.md

With the latest PRs in adapter-vercel + this config file, I was able to successfully deploy to Vercel. Thanks, all 😄

Update adapter-vercel README.

---

.changeset/proud-sloths-exercise.md
packages/kit/src/runtime/client/renderer.js
packages/kit/src/runtime/client/router.js
packages/kit/src/runtime/client/types.d.ts
packages/kit/test/apps/basics/src/routes/routing/__tests__.js
packages/kit/test/apps/basics/src/routes/routing/prefetched/index.json.js
packages/kit/test/apps/basics/src/routes/routing/prefetched/index.svelte

make prefetching work

---

.changeset/sharp-days-exercise.md
packages/kit/src/core/build/index.js

Update $service-worker module to reflect docs

---

examples/svelte-kit-demo/README.md

#639. Lots more to do here...
...but this gives us a template I think we can use.
Demo app deployed to Vercel: https://kit-zeta.vercel.app/

README for vercel deployment of demo app

---

documentation/docs/03-loading.md

Update 03-loading.md - Fix missing quote in doctype

---

packages/kit/src/runtime/client/router.js

Initialize router with current history state

---

examples/realworld.svelte.dev/src/routes/articles.json.js

Fixes a tiny omission from this commit:
https://github.com/sveltejs/kit/commit/d881b7ea260121bddb8eebdb41b47271aebda45a#diff-4faadfdd2ffd5e4a681f7849e5b875ca96b3e11c9a31565c59f4d5899edef377R4-R7
Both `pnpm test` and `pnpm lint` passed.

Fix: request.query -> query in realworld example

---

.changeset/smooth-items-exercise.md
packages/kit/src/runtime/server/page.js
packages/kit/test/apps/basics/src/routes/load/__tests__.js
packages/kit/test/apps/basics/src/routes/xss/__tests__.js
packages/kit/test/apps/basics/src/routes/xss/index.json.js
packages/kit/test/apps/basics/src/routes/xss/index.svelte

prevent XSS when serializing fetch results

---

.github/workflows/ci.yml

shrink test matrix

---

.changeset/funny-needles-talk.md
packages/kit/src/runtime/server/page.js
packages/kit/test/apps/basics/src/routes/ssr/__tests__.js
packages/kit/test/apps/basics/src/routes/ssr/index.svelte

omit CSS if `ssr = false`

---

packages/create-svelte/template/src/routes/index.svelte

I [created an issue](https://github.com/sveltejs/kit/issues/952) where I explain the problem.
In summary: The included template index file (with "Hello World!" and the counter example) does not have a page <title>. This causes the page to be inaccessible.
As for creating a changelog, I could not find documentation that defined "changes that should be noted in one or more packages changelogs" so I'm not sure if this meets that criteria.

Add page <title> to template index file

---

.changeset/tricky-bats-smoke.md

changelog for 952

---

documentation/docs/01-routing.md

I see a lot of new users who aren't that familiar with SSR vs CSR, etc. really get tripped up on page vs endpoints and what to put where. Hopefully a bit of introductory text would help ease the path for them

Add some upfront documentation about pages vs endpoints

---

documentation/faq/50-aliases.md

[docs] Fix broken markdown

---

documentation/faq/50-aliases.md

This will make sure when the FAQ section is done (other PR) these blocks will be highlighted appropriately.

Syntax highlight FAQ content

---

documentation/faq/70-packages.md

I finally understand a bit what's going on. Hoping to impart some of that understanding to the reader :smile:

Improve Vite bundling FAQ

---

packages/kit/test/apps/basics/src/routes/routing/__tests__.js
packages/kit/test/test.js
packages/kit/test/types.d.ts

add back helper, reduce test flakiness hopefully

---

documentation/docs/00-introduction.md
packages/kit/README.md

I never knew you could do it until Rich just pointed it out https://github.com/sveltejs/kit/pull/1014#issuecomment-819453251. This seems slightly simpler and also demonstrates something users might not find by themselves otherwise

Simplify project creation instructions

---

examples/hn.svelte.dev/src/routes/$error.svelte
examples/realworld.svelte.dev/src/routes/$error.svelte

This PR: https://github.com/sveltejs/kit/pull/1021 but applied to the examples, to make them functional again.

Fix $error in examples

---

packages/kit/test/apps/basics/src/routes/imports/__tests__.js
packages/kit/test/apps/basics/src/routes/imports/index.svelte
packages/kit/test/apps/basics/src/routes/imports/markdown.svelte
packages/kit/test/apps/basics/svelte.config.cjs

test for #737

---

.changeset/orange-boats-love.md
packages/kit/src/runtime/client/router.js

make sveltekit:prefetch a noop if no href

---

.changeset/nine-starfishes-destroy.md
packages/adapter-node/package.json

`adapter-node`: include missing entry point

---

.changeset/poor-goats-cheer.md
packages/create-svelte/scripts/build-templates.js

include dotfiles when creating new project

---

packages/create-svelte/templates/default/package.json
packages/create-svelte/templates/default/package.template.json
pnpm-lock.yaml

With this change, the demo app works on Vercel: https://kit-demo-rfak6s1bc-sveltejs1.vercel.app/todos

move cookie and uuid to dependencies from devDependencies

---

.githooks/pre-push

i keep needing to do this and it's super annoying

always regenerate lockfile on push

---

.changeset/poor-terms-explain.md
packages/adapter-netlify/index.js

write serverless function to correct place

---

.changeset/brown-bugs-arrive.md
packages/adapter-cloudflare-workers/index.js
packages/create-svelte/templates/default/package.json
packages/create-svelte/templates/default/wrangler.toml
pnpm-lock.yaml

Cloudflare adapter now generates the required package.json.
Also, fixed some wrangler.toml stuff in the demo app so that we can get it deployed. It isn't 100% working yet, but we're getting there

Cloudflare stuff

---

packages/create-svelte/bin.js

Closes: #1087 
```diff
Next steps:
1: cd foo
-  2: npm install (or pnpm install, or yarn)
-  3: npm run dev -- --open
+  2: git init && git add -A && git commit -m 'Initial commit'
+  3: npm install (or pnpm install, or yarn)
+  4: npm run dev -- --open
To close the dev server, hit Ctrl-C
Stuck? Visit us at https://svelte.dev/chat
```

create-svelte: print about `git init` before `npm install` in "Next steps"

---

.changeset/ninety-singers-invite.md
packages/create-svelte/templates/default/src/hooks.ts

just a hunch, but it looks like this matters to cloudflare workers

uppercase method in template

---

.changeset/fluffy-dryers-jump.md
packages/kit/src/core/build/index.js
packages/kit/src/core/create_app/index.js
packages/kit/src/core/create_manifest_data/index.js
packages/kit/src/core/dev/index.js
packages/kit/test/apps/basics/src/routes/routing/rest/non-greedy/$layout.svelte
packages/kit/test/apps/basics/src/routes/routing/rest/non-greedy/[dynamic]-bar/[...rest].svelte
packages/kit/test/apps/basics/src/routes/routing/rest/non-greedy/__tests__.js
packages/kit/test/apps/basics/src/routes/routing/rest/non-greedy/foo/[...rest].svelte

prevent `...rest` params from swallowing characters 

---

packages/kit/types/endpoint.d.ts

Fixes sveltejs/kit#1018
Very simple change, not sure how to write a test for a typescript type change only...
Feel free to delete this if more involved then it looks.

Allow RequestHandler type to return undefined

---

.prettierrc

Silences this wall of warnings

chore: silence prettier unknown option warning

---

.changeset/config.json
.changeset/lazy-carpets-join.md
.github/workflows/ci.yml
packages/create-svelte/.gitignore
packages/kit/src/core/dev/index.js

Fixes #1170. Had to fix some unrelated stuff before I could push these changes, excuse the poor git hygiene

Don't swallow errors in hooks.js

---

.changeset/itchy-lobsters-tie.md
packages/kit/src/core/adapt/prerender.js

update prerender error message as per #1176

---

packages/create-svelte/templates/default/package.json
packages/kit/package.json
pnpm-lock.yaml

~~Make sure our tests succeed on Vite 2.2.3~~
They don't, so make sure our tests succeed on Vite 2.2.2.

Update Vite to 2.2.2

---

documentation/docs/03-loading.md

Explain layout can also export the load function

---

packages/adapter-netlify/README.md

hi! i used to work at netlify.
i figured i would better document the netlify adapter install instructions because it tripped me up as well as Rich Harris at Svelte Summit so it definitely needs some documenting

add install instructions and warning for netlify adapter

---

.changeset/quiet-years-own.md
packages/create-svelte/templates/default/package.json
packages/create-svelte/templates/skeleton/package.template.json
packages/kit/package.json
packages/kit/src/core/dev/index.js
pnpm-lock.yaml

fix: remove ?import from svelte component id and update to vite 2.2.3 (fixes #1227)

---

packages/kit/package.json
pnpm-lock.yaml

Update the vite plugin which has useful bug fixes

Update Vite Plugin

---

documentation/docs/12-cli.md

Closes https://github.com/sveltejs/kit/issues/1242

Link to Vite issue in docs for more details

---

packages/create-svelte/templates/skeleton/svelte.config.cjs

fix(template): typehint default config file

---

packages/adapter-static/README.md

There is some missing information on how to implement the static adapter in the README file.
https://github.com/sveltejs/kit/issues/1325

Adding additional instructions to this adapter

---

.changeset/polite-apes-relax.md
packages/create-svelte/shared/+prettier/.prettierignore

Forgotten in 0befffbe1fdebd78ccd66a9261bd6dec9d5f5b6b

Leftover .svelte -> .svelte-kit

---

.changeset/khaki-ears-repeat.md
.changeset/poor-bears-report.md
packages/adapter-static/test/apps/prerendered/package.json
packages/adapter-static/test/apps/spa/package.json
packages/create-svelte/templates/default/package.template.json
packages/create-svelte/templates/skeleton/package.template.json
packages/kit/package.json
packages/kit/test/apps/basics/package.json
pnpm-lock.yaml

make Vite a prod dep of SvelteKit

---

.changeset/curly-ravens-do.md
.changeset/rare-mice-mate.md
packages/create-svelte/templates/default/package.json
packages/kit/package.json
pnpm-lock.yaml

vite 2.3.1 disables the problematic fs check by default

unpin vite and use ^2.3.1 to skip 2.3.0

---

examples/hn.svelte.dev/package.json
packages/adapter-begin/package.json
packages/adapter-cloudflare-workers/package.json
packages/adapter-netlify/package.json
packages/adapter-node/package.json
packages/adapter-static/package.json
packages/adapter-vercel/package.json
packages/create-svelte/package.json
packages/create-svelte/scripts/build-templates.js
packages/create-svelte/templates/default/package.template.json
packages/create-svelte/templates/skeleton/package.template.json
packages/kit/package.json
packages/kit/test/apps/basics/package.json
pnpm-lock.yaml

This hopefully fixes the release step once and for all by reverting #1434

fix: change workspace deps to carat

---

.changeset/chilled-zebras-check.md
packages/kit/package.json

As suggested in https://github.com/sveltejs/kit/pull/1469

Update compatible Node versions

---

.changeset/twelve-onions-burn.md
packages/adapter-begin/package.json
packages/adapter-cloudflare-workers/package.json
packages/adapter-netlify/package.json
packages/adapter-node/package.json
packages/adapter-static/package.json
packages/adapter-vercel/package.json
pnpm-lock.yaml

Fixes https://github.com/sveltejs/kit/issues/1422

Make kit a peerDependency of the adapters

---

.github/ISSUE_TEMPLATE/questions-and-help.md
documentation/docs/99-troubleshooting.md

We should probably have a separate tag for SvelteKit vs Svelte

Use sveltekit tag on StackOverflow

---

.changeset/slow-buses-beam.md
packages/create-svelte/templates/default/package.json
packages/kit/package.json
pnpm-lock.yaml

Only upgrading to 2.3.3 instead of the latest 2.3.4 because the tests fail otherwise

Upgrade to Vite 2.3.3

---

.changeset/funny-terms-repair.md
packages/adapter-begin/package.json
packages/adapter-cloudflare-workers/package.json
packages/adapter-netlify/package.json
packages/adapter-node/package.json
packages/adapter-static/package.json
packages/adapter-vercel/package.json

Fixes https://github.com/sveltejs/kit/issues/1618

Remove peerDependencies due to pnpm bug

---

.changeset/soft-students-cover.md
packages/kit/package.json
pnpm-lock.yaml

clean update to 2.3.6, superseeds https://github.com/sveltejs/kit/pull/1622

update vite to 2.3.6

---

.changeset/shy-jeans-fly.md
packages/kit/package.json
packages/kit/src/core/build/index.js
packages/kit/src/core/dev/index.js
pnpm-lock.yaml

Fix: update vite-plugin-svelte and vite

---

.changeset/seven-planes-fly.md
packages/kit/src/core/adapt/prerender.js

Fixes https://github.com/sveltejs/kit/issues/1697

Stricter regex for getting element attributes during prerendering

---

packages/adapter-node/README.md

Add missing comma

---

packages/adapter-node/README.md

Other PRs are failing their checks due to this unrelated error in `master`

fix failing lint from #1719

---

README.md

Add note to install test dependencies

---

documentation/docs/11-ssr-and-javascript.md

clarify prerendering

---

documentation/docs/05-modules.md

[docs] clarify `$app/stores` imports differences

---

.changeset/few-suits-flash.md
documentation/docs/05-modules.md
packages/adapter-node/index.js

Check if '${out}/prerendered' exists, before precompressing

---

.changeset/mighty-cherries-float.md
packages/kit/package.json
pnpm-lock.yaml

chore: Update Vite to ^2.4.1

---

packages/adapter-begin/README.md
packages/adapter-cloudflare-workers/README.md
packages/adapter-netlify/README.md
packages/adapter-node/README.md
packages/adapter-static/README.md
packages/adapter-vercel/README.md
packages/kit/README.md

Make the changelogs more discoverable

Link to Changelogs from Readmes

---

.changeset/proud-sloths-talk.md
packages/adapter-node/src/index.js

Log both host and port

---

.changeset/short-buttons-mix.md
.changeset/spicy-jeans-rest.md
packages/kit/src/runtime/server/index.js
packages/kit/types/helper.d.ts
packages/kit/types/hooks.d.ts
packages/kit/types/index.d.ts
packages/kit/types/internal.d.ts

[fix] correct types mismatch

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Using non-existant labels resulted in no labelling at all :/

fix: update issue labels in forms config to use existing labels

---

.changeset/silly-phones-worry.md
packages/kit/src/core/make_package/index.js

[fix] better error message when loading svelte2tsx

---

documentation/docs/03-loading.md

Clarify reactive in load function
See discussion: https://github.com/sveltejs/kit/issues/1930

Document load reactivity

---

packages/adapter-netlify/README.md

this is just a tweak to readme, to address confusion from users https://twitter.com/BrittneyPostma/status/1416101106648813572

[netlify adapter] add note on Netlify node version

---

.changeset/thick-peas-shop.md
packages/kit/src/runtime/server/page/load_node.js

Fixes https://github.com/sveltejs/kit/issues/1963
Thanks to @babeard for suggesting the fix

[fix] correctly detect external fetches

---

.changeset/modern-news-rhyme.md
packages/kit/src/runtime/server/index.js
packages/kit/src/runtime/server/page/render.js
packages/kit/src/runtime/server/page/respond.js
packages/kit/src/runtime/server/page/respond_with_error.js
packages/kit/src/runtime/server/utils.js

Closes https://github.com/sveltejs/kit/issues/1982

Handle errors with incorrect type

---

documentation/docs/80-adapter-api.md

[docs] fix typo

---

documentation/migrating/01-migrating.md

[docs] minor wording improvement in migration guide

---

.changeset/wet-lemons-cheat.md
packages/kit/src/core/adapt/prerender.js
packages/kit/src/runtime/server/page/load_node.js

Fixes https://github.com/sveltejs/kit/issues/1527

[fix] consider protocol-relative URLs as external

---

packages/kit/src/runtime/hash.js

Related to https://github.com/sveltejs/kit/issues/1582
Not quite sure that one needed to be re-opened. Should this PR close it?

[docs] document what hash function is being used

---

.changeset/smooth-icons-yell.md
packages/kit/src/runtime/server/endpoint.js
packages/kit/test/apps/basics/src/routes/routing/fallthrough-simple/[page].svelte

This was also mentioned in https://github.com/sveltejs/kit/issues/2041. Gets more of the tests passing

[fix] allow endpoint shadowing to work

---

.changeset/angry-maps-divide.md
packages/kit/src/runtime/server/page/respond.js
packages/kit/types/internal.d.ts

Fixes https://github.com/sveltejs/kit/issues/1393. Gets some more tests passing

[fix] successfully load nested error pages

---

.changeset/smart-papayas-look.md
packages/kit/src/core/adapt/prerender.js
packages/kit/src/core/dev/index.js

Fixes https://github.com/sveltejs/kit/issues/2000

[fix] solve regression parsing unicode URLs

---

examples/hn.svelte.dev/netlify.toml

Missed updating this in https://github.com/sveltejs/kit/pull/2058

Fix Netlify config

---

.gitignore
examples/hn.svelte.dev/.netlify/netlify-plugin-pnpm/index.js
examples/hn.svelte.dev/.netlify/netlify-plugin-pnpm/manifest.yml
examples/hn.svelte.dev/netlify.toml

Netlify deploys are broken. Hoping this fixes them

[chore] use pnpm to build Netlify example

---

documentation/docs/03-loading.md

Closes https://github.com/sveltejs/kit/issues/1833

[docs] add documentation for fetch

---

.changeset/nervous-laws-rule.md
packages/kit/src/runtime/client/router.js
packages/kit/src/runtime/client/start.js

Fixes https://github.com/sveltejs/kit/issues/1764

[fix] fully initialize router before rendering

---

packages/kit/types/endpoint.d.ts

@NoelAbrahams, FYI your example on https://github.com/microsoft/TypeScript/issues/1897#issue-56296923 seems incorrect to me

[fix] JSONValue can't be a Date

---

documentation/docs/01-routing.md

Closes https://github.com/sveltejs/kit/issues/735

[docs] document body parsing

---

README.md

Addresses comment from #2116 
NA
NA

[docs] list packages, link repos & changelogs

---

documentation/docs/02-layouts.md

No issue was present for this pr. This pr makes a small change to the layout documentation. The nav in the example had incorrect routes using a `.` period and no `/` slashes. I updated the nav to what would be the correct routes.
- [x ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x ] This message body should clearly illustrate what problems it solves.
- [ x] Ideally, include a test that fails without this PR but passes with it.
- [ x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`
- [ x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a …

Update Layout Documentation Incorrect routes

---

.changeset/smart-humans-eat.md
packages/kit/package.json
pnpm-lock.yaml

next.16 includes improvements for svelte deduplication, bump version in kit so users get updated

[fix] update vite-plugin-svelte

---

documentation/docs/04-hooks.md

Closes https://github.com/sveltejs/kit/issues/1862

[docs] update `handle` docs to clarify when it runs

---

packages/kit/src/core/create_app/index.js

this has caused some confusion. the hope is that this will save people from spending time on PRs like #2160, which change behaviour from that which is (currently — not set in stone, though I'd be surprised if we decided to change it) intended.
No changeset required

add note to fallback code

---

README.md
package.json
pnpm-lock.yaml

This PR will build the local docs and serve them on port `3456` of localhost. This will allow us to validate changes when working on the docs locally.
There will be a partner PR in the sites repo shortly.

Docs preview

---

packages/kit/src/runtime/client/types.d.ts
packages/kit/src/runtime/server/page/types.d.ts
packages/kit/tsconfig.json

[chore] use absolute import paths for types

---

documentation/docs/00-introduction.md

Inspired by @vkwd's PR https://github.com/sveltejs/kit/pull/2176
Closes #2176
Adds some more information about what SvelteKit provides, how to setup your editor and tooling, etc.

[docs] update introduction

---

.changeset/beige-beers-explain.md
packages/adapter-node/index.js

fixes https://github.com/sveltejs/kit/issues/2238

[fix] provide default port only if path not provided

---

.changeset/large-horses-flash.md
packages/adapter-static/index.js

[fix] clear adapter-static output

---

.changeset/thin-bats-protect.md
packages/kit/src/core/dev/index.js

Fixes https://github.com/sveltejs/kit/issues/871
Incredibly grateful to @jasonlyu123 for coming up with the fix!

[fix] HMR on Windows

---

examples/hn.svelte.dev/package.json
packages/adapter-static/package.json
packages/create-svelte/package.json
packages/create-svelte/templates/default/package.json
packages/kit/package.json
pnpm-lock.yaml

Update svelte to 3.42.2 so that tests run with the latest version

chore: update svelte to 3.42.2

---

packages/kit/test/apps/basics/src/routes/redirect/_tests.js
packages/kit/test/apps/basics/src/routes/routing/_tests.js

minor cleanup. no changeset since it's only changing the tests

[chore] remove unnecessary awaits on page url

---

.changeset/breezy-students-refuse.md
packages/kit/package.json
pnpm-lock.yaml

Update to apply fix for this issue https://github.com/sveltejs/vite-plugin-svelte/issues/162

[chore] update vite-plugin-svelte

---

packages/kit/src/core/config/index.js
packages/kit/src/core/config/index.spec.js
packages/kit/src/core/config/options.js
packages/kit/src/core/config/test/index.js
packages/kit/src/core/config/types.d.ts

Simplifies the config validation without introducing new dependencies (follow-up to https://github.com/sveltejs/kit/pull/2366#issuecomment-913187660)

Dry out config

---

packages/create-svelte/templates/default/src/hooks.ts

Since the cookie library it's already installed, lets use it to create the cookie too!

[chore] template: use installed cookie package to serialize cookie

---

.github/workflows/release.yml
package.json

chore: bump lockfile after versioning

---

packages/create-svelte/shared/+eslint+prettier/package.json

Thank you for such a nice framework :tada:
I just removed one extra whitespace.

chore: remove extra whitespace

---

README.md

Added 'git clone' to README

---

documentation/docs/05-modules.md

The PR doesnt really change anything substantially, so I haven't done these

Fixed a very minor grammatical error

---

.changeset/late-monkeys-call.md
packages/kit/src/core/dev/index.js

fixes https://github.com/sveltejs/kit/issues/2510

[fix] allow passing in https certs again

---

packages/adapter-cloudflare-workers/README.md

Improved documentation for `cloudflare-workers` with the help of [This](https://www.scien.cx/2021/06/21/deploying-sveltekit-using-cloudflare-workers/) post.

Improved documentation for cloudflare-workers

---

.changeset/smart-planets-beam.md
packages/adapter-node/src/kit-middleware.js

Fix #2532
A single malicious request can bring down the entire web server in adapter-node

Fix denial of service vulnerability in adapter-node

---

.changeset/silver-rice-flash.md
package.json
packages/kit/rollup.config.js
pnpm-lock.yaml

I'll send a PR to bump it in Vite as well

[chore] upgrade commonjs plugin for better ignoreTryCatch default

---

.changeset/pretty-melons-jog.md
packages/adapter-node/tests/smoke.js

Update adapter-node test. Add a test for malformed url

[chore] add test for malformed urls

---

.changeset/gold-carrots-sniff.md
packages/kit/src/core/adapt/prerender.js
packages/kit/types/app.d.ts
packages/kit/types/internal.d.ts

Further work on https://github.com/sveltejs/kit/issues/2249. I had some more improvements I wanted to work on, but wanted to break this off as a separate PR to make it more reviewable
CC @jthegedus

[fix] don't expose prerender options

---

examples/hn.svelte.dev/src/routes/[list]/rss.js

no changeset since this is just an example

[fix] make HN example RSS feed work

---

packages/create-svelte/templates/default/src/app.html
packages/create-svelte/templates/skeleton/src/app.html

Close https://github.com/sveltejs/kit/issues/2790

[chore] add meta description for demo app and skeleton

---

documentation/faq/60-env-vars.md
documentation/faq/80-integrations.md

We can tweak it when Vite 2.7 is released, but thought I'd at least get some newer info out there in the meantime

[docs] update FAQ with newer info about Firebase and Vite

---

packages/adapter-node/README.md

remove excess "." in middleware example code

[docs] remove excess dot

---

README.md

Link the latest adapter in packages list

add adapter-cloudflare to packages section

---

documentation/docs/10-adapters.md

Link adapter-cloudflare for pages in docs

add adapter-cloudflare to adapters docs

---

documentation/docs/00-introduction.md

this is really just to trigger the docs workflow, so that https://github.com/sveltejs/action-deploy-docs/pull/5 takes effect

tweak some docs

---

README.md

- add `bash` language hint to code fence
- reword phrases to use active voice
- correct `e.g.,` punctuation 
- correct typos
1. `and` -> `an`
2. `eventhough` -> `even though`
- add `,` where appropriate
- remove verbiage
Signed-off-by: Vladislav Doster <Vladislav.doster@Mastercard.com>

docs: grammar, punctuation, and code fence fixes

---

packages/adapter-node/README.md

clarify env stuff

---

.changeset/cool-swans-sleep.md
.changeset/young-students-chew.md
packages/adapter-auto/CHANGELOG.md
packages/create-svelte/.gitignore
packages/create-svelte/shared/+typescript/svelte.config.js
packages/create-svelte/shared/-typescript/svelte.config.js
packages/create-svelte/templates/default/package.json
packages/create-svelte/templates/default/package.template.json
packages/create-svelte/templates/skeleton/package.template.json
pnpm-lock.yaml

add adapter-auto to template configs

---

.changeset/kind-wolves-yawn.md
packages/adapter-auto/package.json

Add missing files to adapter-auto package

---

packages/create-svelte/templates/default/.gitignore
packages/create-svelte/templates/default/.ignore
packages/create-svelte/templates/default/vercel.json

we don't need the PR comments, if necessary we can click the link in the 'checks' box

tell the vercel git integration not to comment on PRs

---

documentation/docs/03-loading.md

---- 
Not sure if you want full tests for a two letter spelling fix in the docs, but happy to provide them if asked for.

fix(docs): Minor spelling fix in loading docs

---

.changeset/perfect-experts-hammer.md
packages/create-svelte/templates/default/.gitignore
packages/create-svelte/templates/skeleton/.gitignore

Fixes #2925, reason behind the proposed change stated there.

create-svelte: Do not gitignore .env.example (fix #2925)

---

.github/workflows/release.yml

see annotation on last release action run https://github.com/sveltejs/kit/actions/runs/1567442400

[chore] use changesets/action@v1 instead of deprecated @master

---

CONTRIBUTING.md
README.md

suggested by @bluwy in https://github.com/sveltejs/kit/pull/3029. I think it's a good idea
Rendered: https://github.com/sveltejs/kit/tree/separate-contrib

[docs] separate out contributing guide

---

documentation/faq/60-env-vars.md
documentation/faq/80-integrations.md

Remove some FAQ notes that reference Vite 2.7 as we are now already using it.

docs: remove vite 2.7 notes

---

.changeset/red-papayas-prove.md
packages/create-svelte/templates/default/src/hooks.ts
packages/create-svelte/templates/default/src/lib/form.ts

[fix] comply demo app to TypeScript strict mode

---

packages/adapter-cloudflare-workers/README.md

Small change to remove contradiction in the documentation between adapter-cloudflare-workers, and adapter-cloudflare.

Fixing typo in readme

---

packages/adapter-cloudflare/README.md

docs(adapter-cloudflare): Clarify workers integration

---

.changeset/little-tables-decide.md
packages/adapter-node/src/handler.js

fixes https://github.com/sveltejs/kit/issues/3141

fix: only add handlers for directories that exist

---

packages/kit/src/core/build/build_server.js
packages/kit/src/core/build/index.js

The files being written are part of the server, so it'd make sense for that to happen in `build_server`

[chore] do all server building in one file

---

packages/kit/src/core/dev/index.js

[chore] fix VS Code syntax highlighting

---

.github/workflows/ci.yml

Adjust test timeout to be 10 minutes

---

documentation/docs/12-packaging.md

[docs] info on (dev)dependencies when packaging

---

.changeset/many-papayas-invite.md
packages/adapter-cloudflare-workers/index.js

Fixes https://github.com/sveltejs/kit/issues/3211

fix: use path/posix to resolve relative paths

---

.changeset/early-news-taste.md
packages/adapter-cloudflare/index.js

Last adapter with `relative` that needs converting
Related #3163, #3200, #3211, #3212

[fix] use posix to resolve relative path

---

packages/adapter-netlify/package.json
packages/adapter-netlify/src/handler.js
pnpm-lock.yaml

This just gets rid of some of the red squigglies in adapter-netlify/src/handler.js. No changeset/test/etc necessary

type adapter-netlify

---

.changeset/rich-ligers-smash.md
packages/kit/src/core/adapt/prerender.js

fixes https://github.com/sveltejs/kit/issues/3228

[fix] strip hash fragments during prerendering

---

packages/kit/src/runtime/server/parse_body/read_only_form_data.js

remove accidental export

---

documentation/faq/80-integrations.md

the issue being referenced has been closed and is no longer a problem

[docs] remove outdated line from faq

---

packages/adapter-static/README.md

Whoops https://github.com/sveltejs/kit/commit/e881c7c57a3b136f92eba3aaef8952b11591a8e1#r63790728, thanks @Valexr!

add missing hash in permalinks

---

documentation/docs/04-hooks.md

Updating the docs to cover the updated use of request.url.pathname vs request.path
- [ X] This message body should clearly illustrate what problems it solves.

Docs - updating hooks doc use of request.url.pathname vs request.path

---

documentation/docs/90-additional-resources.md

svelte.dev is also inside sites repo now.

---

documentation/docs/90-additional-resources.md

just a minor addition to docs to show people how to find examples of sveltekit stuff, and prompt them to add theirs!

[docs] add links to sveltekit examples for people to find

---

.changeset/many-hairs-push.md

Add changesets for adapter auto, cloudflare, vercel, netlify, so the changes in #3357 gets included in these adapter's builds

chore: re-release adapters for fetch polyfill change

---

.changeset/healthy-pandas-pull.md
packages/adapter-static/CHANGELOG.md

cleanup changelog slip up

---

packages/create-svelte/templates/default/src/lib/Counter.svelte

This is just cosmetic fix to clearly work with text selection on the counter demo page

Fix hidden-text user-selection for Counter.svelte in default template

---

.gitattributes

Fingers crossed this updates the languages detected by linguist, I've made sure to refresh the page multiple times and HTML is not appearing anymore, [see fork languages section](https://github.com/ignatiusmb/kit). Don't know why or how GitHub fooled me in #3378, clearly I wouldn't be able to screenshot it if it wasn't working.

exclude fixtures from linguist

---

.changeset/real-icons-study.md

[chore] add changeset for create-svelte

---

.changeset/khaki-bears-film.md
packages/kit/src/runtime/server/page/render.js

[fix] register service worker regardless of hydrate/router option

---

documentation/docs/11-page-options.md
documentation/docs/14-configuration.md

- Link to paragraph "script context module" in Svelte docs has changed

[docs] update links to svelte.dev docs

---

.github/workflows/update_template.yml

fix repository name for update template

---

.github/workflows/update_template.yml

setup node, install pnpm, and build cli

---

.github/workflows/update_template.yml

install and build pnpm

---

.github/workflows/update_template.yml

Reorder pnpm install

---

.github/workflows/update_template.yml

Explicit dirnames

---

.github/workflows/update_template.yml

set pnpm cache dir explicitly

---

.github/workflows/release.yml
.github/workflows/update_template.yml

upgrade node from 12 to 16

---

.github/workflows/update_template.yml

set git username

---

.github/workflows/update_template.yml

fix git syntax

---

documentation/docs/10-adapters.md

Broken link `install a custom adapter`

---

documentation/migrating/01-migrating.md

update examples link in migrating

---

.changeset/funny-ads-move.md
packages/create-svelte/shared/+eslint+prettier+typescript/.eslintrc.cjs
packages/create-svelte/shared/+eslint+typescript/.eslintrc.cjs
packages/create-svelte/shared/+eslint+typescript/package.json

Addressing concerns from discord, we want to minimize the stuff in config files as much as possible, one of which would be to upgrade TS eslint plugins.

bump eslint plugin and parser

---

package.json

remove --tag param from changeets

---

documentation/faq/70-packages.md

I've spent a lot of time fixing various packages that people have run into. At first I was doing this because most of the time it was a Vite issue. However, now it's usually a packaging issue. I'd love to have some docs to point people at because bad packaging is a commonly-made mistake

[docs] add packaging guidelines

---

packages/create-svelte/templates/default/package.json

make default template private

---

.changeset/thin-swans-cheat.md
packages/create-svelte/shared/README.md

another small tweak to bump create-svelte version

tweak readme

---

.github/workflows/update_template.yml

fix tag trigger

---

.changeset/shaggy-donkeys-run.md
packages/create-svelte/templates/default/package.template.json

another meaningless change

---

.changeset/dry-baboons-turn.md

kjngkdjfngfdg

---

.changeset/twenty-papayas-compare.md
packages/create-svelte/package.json

for petes sake

---

.changeset/ninety-dolls-sniff.md

this is just to check that `changeset publish` will run `postpublish` scripts. if it does, we're all set

bump create-svelte

---

documentation/docs/11-page-options.md
documentation/docs/14-configuration.md

follow up docs for #3578

---

.changeset/light-pumas-heal.md
packages/kit/src/runtime/server/endpoint.js

#3505 - json response condition update

---

packages/adapter-cloudflare/README.md
packages/adapter-netlify/README.md
packages/adapter-vercel/README.md

Supersedes #3637 — we need to be able to document the Vercel-specific options, for people who outgrow adapter-auto.

recommend using adapter-auto instead of cloudflare/netlify/vercel

---

documentation/docs/04-hooks.md

fix handleError docs

---

.changeset/witty-news-dress.md
packages/kit/src/core/build/index.js

i'm 90% sure this will fix #3652. No test for same reason as #3570

fix service_worker typo

---

packages/kit/src/runtime/server/page/index.js
packages/kit/src/runtime/server/page/load_node.js
packages/kit/src/runtime/server/page/render.js
packages/kit/src/runtime/server/page/respond.js
packages/kit/src/runtime/server/page/respond_with_error.js
packages/kit/types/internal.d.ts

Server-Side Render Render Options is up there with Automated Teller Machine Machine and Cascading Style Sheet StyleSheet

rename SSRRenderOptions/State to SSROptions/State

---

.changeset/chilled-rivers-talk.md
documentation/docs/01-routing.md
packages/kit/types/endpoint.d.ts
packages/kit/types/helper.d.ts

It's very weird that we call it `JSONString` when it's usually not a string

rename JSONString to JSONValue

---

sites/kit.svelte.dev/src/app.html

small change to check a) if preview deploys work and b) to verify that kit.svelte.dev is being deployed from this repo

remove id="svelte"

---

documentation/faq/00-other-resources.md
documentation/faq/10-version-numbers.md
documentation/faq/20-hmr.md
documentation/faq/30-fallthrough.md
documentation/faq/40-adapters.md
documentation/faq/45-assets.md
documentation/faq/50-aliases.md
documentation/faq/60-env-vars.md
documentation/faq/65-read-package-json.md
documentation/faq/70-packages.md
documentation/faq/80-integrations.md
pnpm-lock.yaml
sites/kit.svelte.dev/package.json
sites/kit.svelte.dev/src/_env.ts
sites/kit.svelte.dev/src/lib/docs/index.js
sites/kit.svelte.dev/src/routes/docs/index.js
sites/kit.svelte.dev/src/routes/docs/index.svelte
sites/kit.svelte.dev/src/routes/faq/index.js
sites/kit.svelte.dev/src/routes/faq/index.svelte
sites/kit.svelte.dev/src/routes/migrating/index.js
sites/kit.svelte.dev/src/routes/migrating/index.svelte
sites/kit.svelte.dev/svelte.config.js

Step 4 of the [checklist](https://github.com/sveltejs/kit/issues/3696)

Local docs

---

documentation/docs/01-routing.md
documentation/docs/03-loading.md
documentation/faq/30-fallthrough.md
documentation/migrating/04-pages.md

sync advanced routing links

---

documentation/docs/04-hooks.md

closes https://github.com/sveltejs/kit/issues/3750

[docs] clarify that default value of ssr is true

---

.changeset/chatty-ducks-shop.md
packages/kit/src/runtime/client/router.js

Just a addition to #3757 for #3746

Fix client side router issue with handling hash

---

.changeset/shy-bats-move.md
packages/kit/src/runtime/server/page/load_node.js
packages/kit/src/utils/escape.js

Cleaned up version of https://github.com/sveltejs/kit/pull/3797

[fix] replace broken escaping with a working version

---

documentation/docs/01-routing.md

add some explanatory text

---

.changeset/seven-cows-design.md

Follow-up changeset to #3790 which only includes changeset for adapter-static

bump adapter-node for wasm compression

---

packages/adapter-cloudflare-workers/files/entry.d.ts
packages/adapter-cloudflare-workers/index.js
packages/adapter-cloudflare-workers/package.json
packages/adapter-cloudflare-workers/tsconfig.json
packages/adapter-cloudflare/files/worker.js
packages/adapter-cloudflare/index.js
packages/adapter-vercel/index.js
packages/kit/src/core/adapt/builder.js
packages/kit/src/core/adapt/prerender/prerender.js
packages/kit/src/runtime/client/router.js
packages/kit/src/runtime/server/index.js
packages/kit/src/runtime/server/page/load_node.js
packages/kit/src/utils/url.js
packages/kit/src/utils/url.spec.js
packages/kit/test/prerendering/basics/src/routes/encoding/[path].json.js
packages/kit/test/prerendering/basics/src/routes/encoding/[path].svelte
packages/kit/test/prerendering/basics/src/routes/encoding/path with spaces.svelte
packages/kit/test/prerendering/basics/src/routes/encoding/redirect.svelte
packages/kit/test/prerendering/basics/test/test.js
packages/kit/types/config.d.ts
packages/kit/types/index.d.ts
pnpm-lock.yaml

This began as a fix for #3848 but has turned into something more comprehensive, as I ran into some encoding bugs while working on it

prerendering overhaul

---

sites/kit.svelte.dev/src/lib/search/Search.svelte
sites/kit.svelte.dev/src/lib/search/SearchBox.svelte

IOS is over-emphasizing the magnifying glass

IOS magnifying glass

---

.github/workflows/ci.yml
packages/kit/test/apps/basics/test/test.js

Currently they fail to upload, this might fix it with a stricter path 🤔

ci: fix test results upload

---

.changeset/gentle-apes-tease.md
packages/kit/src/runtime/client/router.js
packages/kit/test/apps/basics/test/test.js

Stripped-down version of #3873

prevent duplicated history

---

.github/workflows/ci.yml

ci: tar test results before upload, filter retries, limit retention 

---

packages/kit/src/runtime/client/router.js

https://github.com/sveltejs/kit/pull/3873#issuecomment-1040804783

explain hash_navigating flag

---

CONTRIBUTING.md

GitHub makes it hard to reach the artifacs, feel free to edit if it's not clear

docs(contributing): add steps to find ci screenshots

---

documentation/docs/01-routing.md

explain how to access parameters

---

packages/kit/src/core/build/build_client.js
packages/kit/src/core/dev/index.js
packages/kit/src/core/dev/plugin.js
packages/kit/src/core/generate_manifest/index.js
packages/kit/src/runtime/server/page/render.js

changes that will help me navigate this code the next time I come back to it
Companion PR: https://github.com/sveltejs/svelte/pull/7271

[docs] code clarifications around CSS rendering

---

packages/kit/src/runtime/client/renderer.js
packages/kit/src/runtime/client/router.js
packages/kit/src/runtime/client/types.d.ts

via https://github.com/sveltejs/kit/pull/3969#issuecomment-1042491525

fix initial spa render of 404 errors

---

CONTRIBUTING.md

Some minor link and formatting updates. Also updates info about developing the sveltekit website.

update contributing docs

---

documentation/docs/01-routing.md

[docs] fix typo in fallthrough routes

---

documentation/docs/16-assets.md

I think we should mention CSS somewhere. Also, there was a missing word or something around "in you may"

[docs] add a bit more context about `url()`

---

documentation/docs/01-routing.md
sites/kit.svelte.dev/src/lib/docs/client/docs.css
sites/kit.svelte.dev/src/routes/content.json.js

Update Endpoints documentation with helpful details:
- Describe how simple endpoints can be accessed directly via `/__data.json`.
- Describe how standalone endpoints can be given file extensions (`.json`).

Update Endpoints documentation with helpful details.

---

sites/kit.svelte.dev/src/lib/docs/client/docs.css

fix: user-select: none; for permalink in titles

---

packages/kit/src/utils/url.js
packages/kit/types/ambient.d.ts
packages/kit/types/index.d.ts

Some minor housekeeping. We should turn on linting for `.d.ts` files some time later

chore: organize and deduplicate types

---

packages/kit/test/apps/basics/src/routes/anchor-with-manual-scroll/anchor.svelte
packages/kit/test/apps/basics/src/routes/anchor/anchor.svelte
packages/kit/test/apps/basics/src/routes/use-action/focus-and-scroll.svelte
packages/kit/test/apps/basics/test/test.js

I observed the results of a recent CI run on the master branch.
Then I noticed that mostly `url-supplied anchor is ignored with onMount() scrolling on navigation to page` is failed.
So I focused on how to fix this test.
Then, I also fixed the related tests.
And finally, I changed 3 things.
The test `url-supplied anchor is ignored with onMount() scrolling on navigation to page` is using `#onMount`, but if JavaScript is disabled, it doesn't run. So scroll event is not happen.
So the expected result should be `#go-to-element` but it was `#abcde`.
So I changed it.
Because this test depends on CSS file but I think sometimes assertion is run before loading the CSS file.
So in the second commit, I put style in HTML directly. Then I think the test will be stable.
Just I added the missing `await`. …

[chore] FIx test flakiness

---

packages/create-svelte/templates/skeleton/src/app.d.ts

I was monitoring the CI and it was failing on Lint.
---

[Chore] Fix lint

---

.changeset/hip-windows-sit.md

once more with feeling

---

packages/kit/types/ambient.d.ts

---
Presumably, this means `load` **function**?
If not, and this means a general term `preload`, please close this PR.

[docs] fix typo 

---

documentation/docs/13-configuration.md

Fixed typo

---

sites/kit.svelte.dev/src/routes/__layout.svelte

Copying over https://github.com/sveltejs/sites/commit/3b7f537f1d73c9ef52d60d2aebce682050758d11

[site] remove unnecessary scrollbar

---

packages/kit/src/core/build/utils.js
packages/kit/types/index.d.ts
packages/kit/types/internal.d.ts
packages/kit/types/private.d.ts

More cleanup, see individual commits for intent
Also fixes empty documentation in additional types

types cleanup

---

documentation/docs/03-loading.md

mention 'query string' so it shows up in search

---

sites/kit.svelte.dev/src/hooks.js

Docs redirects

---

packages/kit/src/core/preview/index.js

fix svelte-kit preview

---

packages/kit/types/index.d.ts

Update for docs types

---

sites/kit.svelte.dev/src/lib/search/SearchBox.svelte

fixes #4169, supersedes #4246 and #4230

minimise height of unpopulated search box - 

---

packages/adapter-netlify/index.js

It just took me at least half an hour to find these docs again because I didn't know the terminology Netlify used, so I thought I'd add a link for reference

[docs] add code comment to Netlify adapter

---

packages/kit/src/core/build/build_server.js
packages/kit/src/core/build/utils.js
packages/kit/src/core/sync/create_manifest_data/index.spec.js
packages/kit/src/runtime/server/utils.js

tidy up JSDoc blocks

---

.changeset/slimy-pigs-trade.md
packages/kit/src/cli.js

skip svelte-kit sync if no config file exists yet

---

documentation/docs/10-page-options.md

Fix typo confit -> config

---

.changeset/violet-mayflies-arrive.md
documentation/docs/13-configuration.md
packages/kit/src/core/sync/create_manifest_data/index.js
packages/kit/src/core/sync/sync.js
packages/kit/src/core/sync/write_matchers.js
packages/kit/src/runtime/client/client.js

complete validators renaming

---

packages/kit/types/internal.d.ts
packages/kit/types/private.d.ts

Removes unused types and imports

cleanup and lint types

---

sites/kit.svelte.dev/src/lib/search/SearchBox.svelte

Currently if you use the search feature, you can't scroll - [reported here](https://discord.com/channels/457912077277855764/750401468569354431/958427659233288192)

[site] Remove pointer events none on search

---

packages/kit/types/index.d.ts

clarify load type

---

.changeset/breezy-olives-battle.md
packages/kit/src/core/sync/create_manifest_data/index.js
packages/kit/src/core/sync/create_manifest_data/index.spec.js
packages/kit/src/utils/routing.js

allow index files to use named layouts

---

.changeset/hungry-falcons-raise.md
packages/kit/src/runtime/server/page/respond_with_error.js
packages/kit/test/apps/basics/src/routes/__error.svelte
packages/kit/test/apps/basics/test/test.js

respect ssr: false when rendering 404 page

---

.github/ISSUE_TEMPLATE/bug_report.yml

People keep trying to get away with shit repros. If we update the text to explain what constitutes a good repro, that will probably still happen, but we can at least point to this as we close the issue

Demand better repros

---

documentation/docs/04-hooks.md

clarify that handle is only called when the server receives a request

---

.github/workflows/release.yml

and remove echo from dist-tag call

ci: release action - add NPM_TOKEN to npmrc 

---

.changeset/popular-kids-run.md
package.json
packages/adapter-static/package.json
packages/create-svelte/package.json
packages/create-svelte/shared/+playwright+typescript/package.json
packages/create-svelte/shared/+playwright/package.json
packages/kit/package.json
pnpm-lock.yaml

Closes https://github.com/sveltejs/kit/issues/4488

[chore] upgrade to Playwright 1.21.0

---

.changeset/loud-shrimps-drive.md
packages/create-svelte/templates/default/package.json
packages/kit/package.json
pnpm-lock.yaml

closes https://github.com/sveltejs/kit/pull/4591

[chore] upgrade cookie library

---

package.json
pnpm-lock.yaml

remove action-deploy-docs

---

documentation/docs/01-web-standards.md

[docs] remove absolute URLs to localhost in Web Standards

---

.changeset/afraid-oranges-doubt.md
packages/create-svelte/templates/default/.ignore
packages/create-svelte/templates/skeleton/.ignore

`.turbo` was showing up in new projects, oops

ignore .turbo directory when building templates

---

documentation/docs/03-layouts.md

ErrorLoad merged into Load.
#4515
#4461

[docs] Error pages - Load JSDoc type fix

---

.changeset/silly-boxes-beam.md
packages/adapter-vercel/index.js

fix adapter-vercel

---

.changeset/brown-nails-wait.md
packages/adapter-vercel/index.js

remove unused target option

---

sites/kit.svelte.dev/src/routes/index.svelte

unclear how #4690 got through CI without this

fix kit.svelte.dev

---

sites/kit.svelte.dev/src/routes/docs/[slug].svelte
sites/kit.svelte.dev/src/routes/docs/index.svelte
sites/kit.svelte.dev/src/routes/faq/index.svelte
sites/kit.svelte.dev/svelte.config.js

prerender all of kit.svelte.dev

---

documentation/docs/80-migrating.md

clarify relative vs root-relative URLs

---

.changeset/ten-apricots-admire.md
packages/kit/src/core/sync/create_manifest_data/index.js
packages/kit/src/core/sync/create_manifest_data/index.spec.js

Throw error when named layouts recursively inherits back to itself, right now it will hang in an infinite loop

throw error for recursive layout

---

packages/adapter-vercel/README.md

clarify vercel functions

---

.changeset/small-crabs-sparkle.md
packages/kit/src/core/sync/create_manifest_data/index.js
packages/kit/src/core/sync/create_manifest_data/index.spec.js

Fixes https://github.com/sveltejs/kit/issues/4717

throw error is named layouts in directory

---

.changeset/lemon-emus-relax.md
packages/kit/src/cli.js

fix #4777
node18 has a breaking change at https://github.com/nodejs/node/pull/41431

fix: display network logs in node 18

---

documentation/docs/80-migrating.md

Documentation for issue #2060 which can be closed afterwards.
Feel free to improve the wording if needed.

add hint for adapter-node custom server to migration guide

---

package.json
pnpm-lock.yaml

for reasons i don't pretend to understand, #4836 fails `pnpm check` but this doesn't. just gonna leave this here and see if CI passes

bump eslint-plugin-svelte3

---

.changeset/cuddly-knives-learn.md
packages/kit/src/core/dev/plugin.js

fixes https://github.com/sveltejs/kit/issues/915
I wrote the PR description in British for Rich's benefit :laughing:

[fix] stop flash of unstyled content when using CSS flavours

---

documentation/docs/02-routing.md

document how to link between pages

---

.changeset/wise-wombats-speak.md
packages/kit/src/core/build/prerender/prerender.js
packages/kit/test/prerendering/paths-base/package.json
packages/kit/test/prerendering/paths-base/src/app.html
packages/kit/test/prerendering/paths-base/src/routes/dynamic/[slug].svelte
packages/kit/test/prerendering/paths-base/src/routes/index.svelte
packages/kit/test/prerendering/paths-base/src/routes/nested/index.svelte
packages/kit/test/prerendering/paths-base/svelte.config.js
packages/kit/test/prerendering/paths-base/test/test.js
packages/kit/test/prerendering/paths-base/tsconfig.json
pnpm-lock.yaml

only skip files that were already written when prerendering

---

documentation/docs/02-routing.md

The docs on multiple parameters in routing mix up the names of parameters, which can cause confusion.

Typo in documentation regarding routes with multiple parameters

---

documentation/docs/02-routing.md

document that matchers run in the browser

---

documentation/docs/02-routing.md
documentation/docs/03-layouts.md
documentation/docs/04-loading.md

Some of the docs weren't referencing the new __types directory for generated types. Confused me for a minute so I updated it.

[docs] update docs to use new `__types` directory

---

packages/kit/package.json
pnpm-lock.yaml
sites/kit.svelte.dev/package.json

use a newer version for the site and testing

[chore] upgrade to Vite 2.9.9

---

.changeset/proud-chicken-unite.md
packages/create-svelte/index.js

create-svelte: make initial package.json pass lint

---

packages/kit/.gitignore

Ran into this while running lint for another PR
```
@sveltejs/kit:lint: > @sveltejs/kit@1.0.0-next.354 check-format
@sveltejs/kit:lint: > prettier --check . --config ../../.prettierrc --ignore-path .gitignore
@sveltejs/kit:lint: 
@sveltejs/kit:lint: Checking formatting...
@sveltejs/kit:lint: [warn] src/packaging/test/errors/duplicate-export/.svelte-kit/tsconfig.json
@sveltejs/kit:lint: [warn] src/packaging/test/fixtures/assets/.svelte-kit/tsconfig.json
@sveltejs/kit:lint: [warn] src/packaging/test/fixtures/emitTypes-false/.svelte-kit/tsconfig.json
@sveltejs/kit:lint: [warn] src/packaging/test/fixtures/exports-merge/.svelte-kit/tsconfig.json
@sveltejs/kit:lint: [warn] src/packaging/test/fixtures/exports-replace/.svelte-kit/tsconfig.json
@sveltejs/kit:lint: [warn] …
```

[chore] ignore generated files in packaging test for check-format

---

.changeset/poor-knives-yawn.md
packages/kit/src/vite/build/build_server.js
packages/kit/src/vite/build/build_service_worker.js
packages/kit/src/vite/index.js
packages/kit/src/vite/utils.js

Hopefully fixes #5372. I briefly tested this, and it seemed to work, but it could do with more manual testing and also some automated tests. I'm done for the evening, so if someone gets to this before I do, feel free to take this branch over.

fix loading of conditional Vite configs

---

packages/adapter-static/test/apps/prerendered/vite.config.js
packages/adapter-static/test/apps/spa/vite.config.js
packages/adapter-static/test/utils.js

This is the DRYer alternative to #5398 I was suggesting @benmccann

[chore] improve test setup so that Vite ecosystem CI runs

---

.changeset/forty-points-try.md
packages/kit/package.json
pnpm-lock.yaml

Fixes #5383 and replaces #5396

fix(5383): updated undici

---

.changeset/chilled-moons-sniff.md
packages/kit/src/vite/index.js

see https://github.com/sveltejs/kit/issues/5306#issuecomment-1180808020

fix: skip closeBundle hook during dev to prevent errors on restart

---

packages/kit/types/index.d.ts

document `Output` of `RequestHandler`

---

turbo.json

`pnpm format` is hanging for me locally. No idea why

fix pnpm format

---

.changeset/afraid-llamas-matter.md
packages/kit/package.json
pnpm-lock.yaml

pin vps to 1.0.0-next.49

---

packages/kit/test/apps/basics/src/routes/routing/hashes/target.svelte

fix another firefox test

---

package.json
packages/adapter-static/package.json
packages/create-svelte/package.json
packages/kit/package.json
pnpm-lock.yaml

hopefully this will fix more problems than it introduces :man_shrugging:

[chore] bump Playwright to 1.23.3

---

packages/kit/test/utils.js

Found we can clean this up when I tried to fix Windows failing tests in `vite-3` branch.

cleanup unused ts directives

---

.changeset/real-trainers-collect.md
packages/kit/src/core/config/index.spec.js
packages/kit/types/ambient.d.ts
packages/kit/types/index.d.ts
packages/kit/types/internal.d.ts

Remaining `kit.vite` stuff that were missed

cleanup remnants of `config.kit.vite`

---

packages/kit/src/runtime/server/utils.js

I meant to include this in #5513 — gives people some context for the change when they see this error message, so they don't feel like they're being told to change stuff for no good reason

link to discussion

---

documentation/docs/02-web-standards.md
documentation/docs/16-types.md
documentation/docs/17-seo.md
packages/adapter-cloudflare-workers/README.md
packages/adapter-cloudflare/README.md

Renamed the rest of the request handlers according to #5513

[doc] rename rest of the request handlers

---

CONTRIBUTING.md
documentation/docs/00-introduction.md
packages/create-svelte/README.md
packages/create-svelte/shared/README.md
packages/create-svelte/templates/default/src/routes/about.svelte
packages/kit/README.md

[chore] cleanup lingering references to npm init

---

packages/kit/test/apps/basics/test/test.js

this one just snuck in after fixing all the TypeScript / VS Code warnings in past couple days :smile:

[chore] fix warning in test

---

package.json
packages/adapter-static/package.json
packages/create-svelte/package.json
packages/kit/package.json
pnpm-lock.yaml

fixes compatibility with latest release of Node 18

[chore] bump Playwright to 1.23.4

---

.changeset/twelve-olives-confess.md
.eslintrc.json
packages/kit/src/runtime/client/utils.js
packages/kit/src/runtime/server/index.js
packages/kit/src/vite/build/build_server.js
packages/kit/src/vite/build/utils.js
packages/kit/src/vite/dev/index.js
packages/kit/src/vite/index.js
packages/kit/types/internal.d.ts

use `define` instead of `import.meta.env.VITE_SVELTEKIT_FOO`

---

packages/adapter-auto/package.json
packages/adapter-cloudflare-workers/package.json
packages/adapter-cloudflare/package.json
packages/adapter-netlify/package.json
packages/adapter-node/package.json
packages/adapter-static/package.json
packages/adapter-vercel/package.json
packages/amp/package.json
packages/create-svelte/package.json
packages/kit/package.json

fix `pnpm format`

---

.changeset/silly-otters-knock.md
packages/kit/src/runtime/server/page/render.js
packages/kit/test/apps/basics/src/app.d.ts
packages/kit/test/apps/basics/src/hooks.js
packages/kit/test/apps/basics/src/routes/caching/private/has-session.svelte
packages/kit/test/apps/basics/test/server.test.js

[fix] Ensure private cache when something is returned from getSession hook

---

.changeset/modern-jars-return.md
packages/adapter-node/index.js
packages/kit/src/core/adapt/builder.js
packages/kit/src/core/adapt/builder.spec.js
packages/kit/src/vite/build/utils.js
packages/kit/src/vite/index.js
packages/kit/src/vite/preview/index.js

I accidentally pushed the last commit to `master`. This reverts it

Revert "set Vite's  option"

---

packages/kit/src/node/index.js
packages/kit/test/apps/basics/src/routes/endpoint-output/stream-typeerror.js
packages/kit/test/apps/basics/test/server.test.js

Simpler and less code. Also passes the error from `res.write()` further up.

Rewrite the response stream writer

---

.changeset/small-laws-cheat.md
packages/kit/src/core/adapt/builder.js
packages/kit/src/core/prerender/prerender.js
packages/kit/src/vite/build/build_service_worker.js
packages/kit/test/prerendering/trailing-slash/package.json
packages/kit/test/prerendering/trailing-slash/src/app.d.ts
packages/kit/test/prerendering/trailing-slash/src/routes/page.js
packages/kit/test/prerendering/trailing-slash/src/routes/page.svelte
packages/kit/test/prerendering/trailing-slash/src/routes/standalone-endpoint.json.js
packages/kit/test/prerendering/trailing-slash/src/service-worker.js
packages/kit/test/prerendering/trailing-slash/svelte.config.js
packages/kit/test/prerendering/trailing-slash/test/test.js
pnpm-lock.yaml

fix prerendered path normalisation

---

packages/kit/test/apps/basics/test/client.test.js

this is one of our flakier tests — i think i figured out why

(hopefully) fix a flaky test

---

sites/kit.svelte.dev/src/lib/search/SearchResultList.svelte

increase contrast ratio

---

package.json
pnpm-lock.yaml

turbo just clearly returned me a cached result when it shouldn't have. see if this helps...

[chore] upgrade turbo to 1.3.4

---

.changeset/nasty-trees-cheer.md

changeset for #5683

---

.changeset/polite-dolphins-pay.md
packages/kit/src/core/sync/write_tsconfig.js

Add DOM Iterable to base tsconfig

---

.changeset/metal-seas-dress.md
packages/kit/scripts/special-types/$env+static+private.md

Fix broken link in module documentation
---

(docs) Fix env-dynamic-private link

---

packages/kit/src/vite/build/build_server.js

[chore] use `entries` variable

---

.changeset/loud-parrots-sell.md
packages/migrate/README.md

mostly to check that changesets is wired up correctly

add readme to svelte-migrate

---

documentation/docs/06-hooks.md

remove unused `async` keyword

---

packages/create-svelte/templates/skeleton/package.json

changesets wouldn't create a release PR after #5778, maybe this will help

try to appease changesets

---

.changeset/rare-spiders-ring.md
packages/migrate/migrations/routes/migrate_page_js/index.js

use LayoutLoad inside +layout.js files

---

.changeset/fluffy-crews-fry.md
packages/migrate/migrations/routes/migrate_page_js/samples.md
packages/migrate/migrations/routes/migrate_page_server/samples.md
packages/migrate/migrations/routes/utils.js

[fix] Migrate type comments on arrow functions

---

package.json
packages/adapter-static/package.json
packages/create-svelte/package.json
packages/create-svelte/shared/+playwright/package.json
packages/kit/package.json
pnpm-lock.yaml

hopefully unblocks https://github.com/sveltejs/kit/pull/5437

[chore] upgrade to playwright 1.25.0

---

sites/kit.svelte.dev/src/routes/+page.svelte

updating https://github.com/sveltejs/kit/pull/5868. just going to close that one since I did it in the UI and can't easily rebase it there, though I did enjoy @Conduitry's comment on the original :grin: https://github.com/sveltejs/kit/pull/5868#issuecomment-1211387766
The CTA right now it's a bit split between "Read the introductory blog post to learn more." and "npm create svelte@latest my-app". The blog post is two years old and talks quite a bit about Sapper, the code being private, Snowpack, etc. so it feels rather outdated

[marketing] update homepage CTA

---

packages/kit/test/apps/basics/test/client.test.js
packages/kit/test/apps/basics/test/test.js

hopefully makes a handful of tests more reliable

makes some tests less flaky

---

documentation/docs/01-project-structure.md

#5834, but with a corresponding entry below (I wasn't able to make the suggestion on that PR)

add tests to project structure

---

packages/create-svelte/test/check.js

1) read workspace package.json and take overrides in there
2) generate overrides for all packages in `/packages` with their correct name
This ensures that if you develop locally and have an override for vite, create-svelte tests are executed with that too.
It also fixes a problem for vite-ecosystem-ci that uses autogenerated overrides for vite and @sveltejs/vite-plugin-svelte

test: improve create-svelte tests to work with local overrides

---

.changeset/blue-jobs-laugh.md
packages/adapter-static/test/apps/spa/src/app.d.ts
packages/adapter-static/test/apps/spa/src/global.d.ts
packages/adapter-static/test/apps/spa/src/hooks.js
packages/create-svelte/templates/default/src/app.d.ts
packages/create-svelte/templates/skeleton/src/app.d.ts

Session has been removed in #5946

remove session remnants from template

---

.changeset/loud-moose-tap.md
packages/kit/types/index.d.ts

closes https://github.com/sveltejs/kit/issues/5888

[fix] allow additional keys in svelte.config.js

---

.changeset/sweet-timers-sip.md
packages/create-svelte/templates/default/src/routes/todos/api.ts

remove outdated notes in `api.ts`

---

documentation/docs/05-load.md

[docs] note on parent and waterfalls

---

documentation/docs/17-seo.md

https://github.com/sveltejs/kit/issues/6017#issuecomment-1219670842

fix SEO docs

---

.changeset/old-berries-develop.md
packages/migrate/migrations/routes/migrate_server/index.js

[fix] typo in migration task

---

documentation/docs/01-project-structure.md

clarify `%sveltekit.assets%`

---

.changeset/flat-pears-compare.md
packages/kit/src/runtime/client/client.js

Fixes #5980
Thanks @benperiton for noticing

[fix] silence unknown prop warnings for named layouts

---

.changeset/kind-tools-shop.md
packages/create-svelte/shared/+eslint+prettier/package.json
packages/create-svelte/shared/+prettier/.prettierrc
packages/create-svelte/shared/-eslint+prettier/package.json

[fix] setup prettier plugin-search-dirs so that it works with pnpm

---

packages/create-svelte/templates/skeleton/package.json
pnpm-lock.yaml

I hope this fixes whatever issue we were seeing in #6118. I guess we won't know for sure until this is merged and 6118 is rebased.

use workspace:* for adapter-auto in create-svelte skeleton template

---

.changeset/large-dolls-drop.md
packages/create-svelte/templates/default/src/routes/+page.svelte

This is no longer correct for the new SK routing. This PR updates the root page instructions on the default app to correctly reflect where things should be updated to see results.
- [na] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [na] Ideally, include a test that fails without this PR but passes with it.
- [na] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`
- [na] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

Update create front-page instructions

---

documentation/docs/05-load.md

I was just reading the docs for `#5748` changes and saw this little typo.

[docs] fixed file extension typo

---

documentation/docs/01-project-structure.md
documentation/docs/13-packaging.md
documentation/docs/14-cli.md
documentation/docs/16-types.md
packages/create-svelte/templates/default/package.template.json
packages/kit/src/core/sync/write_tsconfig.js

Final updates to source files after `@sveltejs/package` migration

update references to `svelte-package`

---

sites/kit.svelte.dev/src/lib/search/SearchResultList.svelte
sites/kit.svelte.dev/src/lib/search/search.js

Fix #6182.

---

documentation/docs/03-routing.md

Related: https://github.com/sveltejs/kit/discussions/6172

[docs] clarify use of error/redirect/json in +server.js

---

packages/kit/src/runtime/server/page/index.js

Another minor follow-up to #6174, I knew I've read "compact" somewhere before in the codebase

reuse compact utility

---

documentation/docs/01-project-structure.md
sites/kit.svelte.dev/src/lib/docs/client/docs.css

clarify `<div>%sveltekit.body%</div>`

---

documentation/docs/05-load.md

pending a (hopefully swift) resolution of #5952

warn about `redirect` bug

---

packages/adapter-static/test/utils.js
packages/kit/test/prerendering/basics/vite.config.js
packages/kit/test/prerendering/fallback/vite.config.js
packages/kit/test/prerendering/options/vite.config.js
packages/kit/test/prerendering/paths-base/vite.config.js
packages/kit/test/prerendering/trailing-slash/vite.config.js

this should make failures a bit easier to spot in the wall of CI text

only output logs if something goes titsup

---

documentation/docs/15-configuration.md

A bit weird to have this be the only option that have the default (re)specified in the description

move default value to config block

---

documentation/docs/04-advanced-routing.md

Hopefully clarifies https://twitter.com/BrittneyPostma/status/1562774171977150464

[docs] clarfiy layout inheritance in groups

---

CONTRIBUTING.md

This has got to be the last reference to package command, I made sure to clear my excludes and search the whole repo here

update entry point to `svelte-package`

---

.changeset/heavy-suns-serve.md
packages/kit/src/core/sync/write_root.js

fixes #6264. I got lazy and didn't add a test here, because this code is likely to get swept away after #5875, and it's unlikely to regress in the meantime

set errors on all layout/leaf components

---

.changeset/odd-tools-add.md
packages/create-svelte/templates/default/src/lib/form.ts

we don't need URL object at all, if we are not using it.

---

.changeset/witty-ads-wave.md
packages/kit/src/core/sync/create_manifest_data/index.js
packages/kit/src/core/sync/create_manifest_data/index.spec.js

fix route sorting with groups

---

.changeset/weak-feet-cheer.md
packages/create-svelte/shared/+checkjs/package.json

This is #6037, but for `checkjs`. Closes #5779

svelte-kit sync before checks

---

.changeset/chilled-clouds-move.md
packages/migrate/migrations/routes/migrate_page_server/index.js
packages/migrate/migrations/routes/migrate_page_server/samples.md
packages/migrate/migrations/routes/migrate_server/index.js
packages/migrate/migrations/routes/migrate_server/samples.md
packages/migrate/migrations/routes/utils.js

Small QoL improvement for anyone who is behind a few versions and didn't do that migration yet.

[feat] do uppercase http verbs migration on the fly

---

documentation/docs/80-migrating.md

[docs] fix layout name

---

documentation/docs/80-migrating.md

update migration from sapper

---

.changeset/grumpy-bugs-jog.md
packages/kit/src/core/sync/write_types/index.js
packages/kit/src/core/sync/write_types/index.spec.js

[fix] silence unused type hints in generated proxy files

---

documentation/docs/05-load.md

This probably should have been included in #6398.

[docs] remove warning about `redirect` bug

---

.changeset/popular-bulldogs-repair.md

#6398 missed a changeset for create-svelte, so that wasn't published.

update create-svelte to Vite 3.1.0-beta.1

---

.changeset/cuddly-months-sip.md
packages/kit/src/runtime/server/index.js

add the missing trailing slash - fixes #6396

---

documentation/docs/05-load.md
sites/kit.svelte.dev/src/lib/docs/server/index.js

`LayoutLoad` -> `LayoutServerLoad`

---

.changeset/rare-wolves-deliver.md
packages/adapter-vercel/index.js

Fix `global is not defined` on vercel edge

---

.changeset/spotty-vans-tickle.md
packages/adapter-static/index.js

better error when encountering not-fully-prerenderable routes

---

.github/workflows/ci.yml
packages/adapter-static/package.json
packages/adapter-static/test/utils.js
packages/kit/test/utils.js
pnpm-lock.yaml

alternative / comparison for #6485
no playwright caching

[ci] disable playwright cache and use correct browser in adapter-static test

---

packages/kit/test/apps/basics/test/client.test.js
packages/kit/test/apps/basics/test/test.js

this one keeps failing in firefox

make test less flaky, hopefully

---

packages/kit/test/apps/basics/src/routes/store/navigating/a/+page.js
packages/kit/test/apps/basics/src/routes/store/navigating/b/+page.js

deflake test

---

.changeset/nine-sheep-grab.md
packages/kit/src/core/sync/write_root.js

Fixes #6610
Was not passed to pages in all situations

[fix] pass `form` prop to pages

---

.changeset/eighty-parrots-cry.md
packages/kit/types/ambient.d.ts

[feat] provide SubmitFunction type

---

.changeset/shaggy-cameras-sip.md
packages/kit/src/runtime/server/index.js

closes #6558. no test because it's a safe change and i'm short on time right now

apply 304 logic after handle

---

packages/create-svelte/README.md

Update Readme with the new option when using the `create-svelte` package

docs: add `skeletonlib` to readme

---

.changeset/nasty-hornets-sneeze.md

#6666 didn't include a changeset, this PR adds one.

Add missing changeset for #6666

---

documentation/docs/07-hooks.md

Closes #1753. I added a line of documentation that clarifies that code in hook files runs on startup.

Added comment about hook files and initialization

---

documentation/docs/03-routing.md

clarify when fallback error page is rendered

---

documentation/docs/07-hooks.md

Some examples show comments referencing the old hooks.js

[docs] update `hooks.js` to `hooks.server.js`

---

documentation/docs/06-form-actions.md

[docs] note form prop update default behavior

---

package.json
packages/adapter-netlify/package.json
pnpm-lock.yaml

Closes https://github.com/sveltejs/kit/pull/6596

[chore] upgrade to @rollup/plugin-node-resolve 14.1.0

---

documentation/docs/00-introduction.md

suggestion from @irod22: https://github.com/sveltejs/kit/issues/2100#issuecomment-1247345044

[docs] update introduction with RC info

---

documentation/docs/05-load.md

Is it clearer if all the `*.server` files have a `load` function with ` LayoutServerLoad` or `PageServerLoad` type?

[docs] Update a few types 

---

.changeset/cyan-years-live.md
packages/kit/src/runtime/server/utils.js
packages/kit/test/apps/basics/src/routes/load/server-data-nostore/+page.server.js
packages/kit/test/apps/basics/src/routes/load/server-data-nostore/+page.svelte
packages/kit/test/apps/basics/test/client.test.js

closes #6458. This implements https://github.com/sveltejs/kit/pull/6809#issuecomment-1246958072, minus the `ttl` stuff which should be a separate issue

prevent caching of __data.js files

---

packages/kit/test/apps/basics/test/client.test.js

this is currently the flakiest test. not really sure why it's failing, but maybe `waitForResponse` will help

see if this makes test less flaky

---

.changeset/cuddly-dragons-punch.md
packages/kit/src/runtime/client/client.js
packages/kit/src/runtime/client/fetcher.js
packages/kit/types/index.d.ts

fix fetch type

---

.changeset/orange-cups-itch.md
packages/kit/src/exports/vite/build/build_server.js
packages/kit/src/exports/vite/dev/index.js
packages/kit/src/runtime/server/page/render.js
packages/kit/test/prerendering/basics/test/test.js
packages/kit/types/internal.d.ts

fixes #6561. While I was at it I tidied some stuff up — only creating scripts if they're needed, for example, and making the indentation less wacky in the rendered HTML

register service worker with relative URL

---

.changeset/tasty-lizards-provide.md
packages/kit/postinstall.js

I messed this up — it's reading the wrong `package.json`. gonna merge this and try it out again real quick (basically impossible to test without releasing)

chdir before attempting postinstall

---

.changeset/silver-badgers-travel.md
packages/kit/src/runtime/client/ambient.d.ts
packages/kit/src/runtime/client/client.js
packages/kit/src/runtime/server/page/load_data.js
packages/kit/src/utils/promises.js

[fix] unwrap promises for load returns on the client

---

.changeset/forty-news-smell.md
packages/kit/src/exports/vite/preview/index.js
packages/kit/test/apps/options-2/src/routes/env/+page.svelte
packages/kit/test/apps/options-2/test/test.js

respect env.dir when running preview

---

documentation/docs/06-form-actions.md
packages/kit/types/index.d.ts

[docs] $page.form and Page interface docs

---

documentation/docs/04-advanced-routing.md

People regularly get confused about this, so it makes sense to be more specific in the docs about this.

[docs] clarify layout inheritance

---

.changeset/nasty-spies-heal.md
packages/kit/src/core/sync/write_types/index.js
packages/kit/src/core/sync/write_types/test/layout-advanced/(main)/+page.js
packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/$types.d.ts
packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/(main)/$types.d.ts
packages/kit/test/types/actions.test.ts
packages/kit/test/types/tsconfig.json
packages/kit/types/index.d.ts

- handle form action returning nothing
- handle page.(server).js without load functions (#6346)

[fix] type fixes

---

packages/kit/test/build-errors/prerender.spec.js

I pushed 7cadf2a5c92ac35b17dc30ed9bc3cc46bcbdbf15 into #6979 but just saw that it was failing for master too

adjust test assertion for windows output

---

.changeset/tender-turtles-sip.md
packages/kit/src/core/sync/write_types/index.js
packages/kit/src/core/sync/write_types/test/layout-advanced/_expected/(main)/$types.d.ts

[fix] add `RequestEvent` to `$types` when `+layout.server.js` present

---

packages/kit/test/apps/options/test/test.js

Re-enable tests that were skipped from #4891 waiting for Vite 3

re-enable skipped tests

---

.changeset/afraid-walls-breathe.md
packages/create-svelte/templates/default/.meta.json

Follow-up to https://github.com/sveltejs/kit/pull/6979

chore: fix description of SvelteKit demo app

---

.changeset/tasty-mice-chew.md
documentation/docs/06-form-actions.md
packages/kit/src/runtime/app/forms.js
packages/kit/types/ambient.d.ts

[feat] provide `update` to `use:enhance` callback

---

packages/kit/test/apps/basics/test/client.test.js

part 9,735. Got a clean run locally, though I'm sure in many cases I just got lucky

reduce some flakiness

---

.changeset/eleven-seahorses-report.md
.changeset/sixty-bees-explain.md
.changeset/yellow-laws-prove.md
packages/adapter-cloudflare-workers/CHANGELOG.md
packages/adapter-cloudflare/CHANGELOG.md
packages/adapter-netlify/CHANGELOG.md

Seems like a couple slipped through

patch changesets and changelogs

---

.changeset/tame-mugs-teach.md
packages/kit/src/core/sync/sync.js

It's tripping people up because it's commented out and they don't know what this is about

[fix] auto-update commented PageError

---

documentation/docs/06-form-actions.md

[docs] note 422 error code

---

.changeset/rotten-trees-brush.md
packages/kit/src/runtime/app/forms.js
packages/kit/test/apps/basics/test/test.js

[fix] reset form in use:enhance after successful submit

---

.changeset/rotten-cherries-jump.md
packages/kit/src/core/adapt/builder.js

[fix] remove groups from segments for adapters

---

.changeset/gorgeous-months-shave.md
packages/kit/src/runtime/server/index.js
packages/kit/test/apps/basics/src/routes/cookies/forwarded-in-etag/+page.server.js
packages/kit/test/apps/basics/src/routes/cookies/forwarded-in-etag/+page.svelte
packages/kit/test/apps/basics/test/client.test.js

[fix] forward cookie headers on etag response

---

.changeset/fuzzy-walls-teach.md
packages/adapter-node/index.js

Fixes #7216
Maybe related to #7209

[fix] take into account deep exports for external packages
