- .github/ISSUE_TEMPLATE/bug_report.yml
Having some red squiggles, seems like these are different according to https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
> match valid values from linguist

- packages/adapter-auto/package.json
- packages/adapter-cloudflare-workers/package.json
- packages/adapter-cloudflare/package.json
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-static/package.json
- packages/adapter-vercel/package.json
- packages/amp/package.json
- packages/create-svelte/package.json
- packages/create-svelte/test/check.js
- packages/kit/package.json
- packages/kit/test/apps/amp/package.json
- packages/kit/test/apps/basics/package.json
- packages/kit/test/apps/options-2/package.json
- packages/kit/test/apps/options/package.json
- packages/kit/test/apps/writes/package.json
- packages/kit/test/prerendering/basics/package.json
- packages/kit/test/prerendering/fallback/package.json
- packages/kit/test/prerendering/options/package.json
- packages/kit/test/prerendering/paths-base/package.json
- packages/kit/test/prerendering/trailing-slash/package.json
- packages/kit/test/utils.js
- packages/package/package.json
To make it consistent, we can also omit the `run` part according to its [cli commands](https://pnpm.io/pnpm-cli#commands)
> use pnpm to run scripts

- documentation/docs/16-configuration.md
This just links directly to the `updated` store in the `@app/stores` docs from the `version` option in config.  This is my first PR so let me know if I missed anything.
> Make the link to the `updated` store in the docs scroll directly to it

- sites/kit.svelte.dev/src/lib/search/content.server.js
> fix search

- .changeset/healthy-mirrors-hide.md
- packages/create-svelte/templates/default/src/routes/Header.svelte
> use aria-current instead of active class

- .changeset/eight-donkeys-allow.md
- packages/kit/src/runtime/client/types.d.ts
- packages/kit/test/utils.d.ts
- packages/kit/types/ambient.d.ts
- packages/kit/types/index.d.ts
- packages/kit/types/internal.d.ts
- packages/kit/types/private.d.ts
Used where possible to make the function distinguishable from the other properties when autocomplete is showing, also makes it consistent across the files
> declare function type with named syntax

- packages/kit/test/utils.js
Using https://playwright.dev/docs/locators which are stricter can help us prevent flakiness, they also break loudly and gives a much nicer error message, it would also complain when there's multiple elements that match the same selector
> use locators over direct selectors

- packages/kit/test/apps/basics/src/global.d.ts
- packages/kit/test/apps/basics/src/routes/load/invalidation/forced/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
seen these tests cause a lot of flakiness. i think this should fix it
> reduce test flakiness, maybe

- packages/kit/src/runtime/server/page/render.js
…from merging a long-standing PR https://github.com/sveltejs/kit/pull/6976
> fix: update devalue call to new major that was accidentally reverted 

- .changeset/wet-news-tie.md
- packages/kit/src/runtime/server/fetch.js
- packages/kit/src/runtime/server/page/load_data.js
- packages/kit/test/apps/basics/src/routes/load/cors/server-only/+page.server.js
- packages/kit/test/apps/basics/src/routes/load/cors/server-only/+page.svelte
- packages/kit/test/apps/basics/test/test.js
> allow cross-origin requests from server-only `load` functions

- documentation/docs/20-core-concepts/20-load.md
- packages/kit/types/index.d.ts
Implementation was changed in https://github.com/sveltejs/kit/pull/7338
Documentation was not updated everywhere.
> [docs] Add missing `routeId` slashes

- .changeset/grumpy-eyes-destroy.md
- packages/kit/package.json
- packages/kit/src/exports/vite/build/utils.js
- packages/kit/src/exports/vite/index.js
fixes https://github.com/sveltejs/kit/issues/7485
> [fix] bump required Vite version and address warning

- documentation/docs/40-best-practices/10-accessibility.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/keepfocus/+page.svelte
- packages/kit/types/ambient.d.ts
> [breaking] consistent casing in `goto`

- .changeset/young-ligers-admire.md
- packages/kit/src/runtime/client/client.js
thanks eagle-eye @geoffrich for noticing the docs were broken. slightly surprised this didn't show up in the tests, but we need to get a fix out for this ASAP. can investigate another time
> change node.type to node?.type

- documentation/docs/20-core-concepts/20-load.md
> [docs] Fix typo in 20-load.md

- documentation/docs/20-core-concepts/40-page-options.md
The deleted sentence had the same meaning as its latter sentence, so I kept the latter one.
> [docs] delete a sentence with the same meaning

- documentation/docs/60-appendix/10-migrating.md
Set removeComments to false, some hydration code needs them, so leave them in
Related to #7493
> [docs] update minifier example

- .changeset/many-timers-accept.md
- packages/kit/src/runtime/client/client.js
- packages/kit/types/ambient.d.ts
- packages/kit/types/index.d.ts
> [feat] better navigation interfaces

- .changeset/violet-candles-compare.md
- packages/kit/src/runtime/server/cookie.js
- packages/kit/test/apps/basics/src/app.d.ts
- packages/kit/test/apps/basics/src/hooks.server.js
- packages/kit/test/apps/basics/src/routes/cookies/encoding/+page.server.js
- packages/kit/test/apps/basics/src/routes/cookies/encoding/+page.svelte
- packages/kit/test/apps/basics/src/routes/cookies/encoding/not-decoded-twice/+server.js
- packages/kit/test/apps/basics/src/routes/cookies/encoding/set/+server.js
- packages/kit/test/apps/basics/src/routes/load/fetch-credentialed.json/+server.js
- packages/kit/test/apps/basics/test/test.js
> [fix] better cookie warning checks

- documentation/docs/20-core-concepts/30-form-actions.md
> clarify requirement to update `event.locals` in an action

- .changeset/happy-panthers-perform.md
- packages/kit/src/runtime/client/client.js
> [fix] migration error when using $page.routeId

- .changeset/gentle-shoes-run.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/utils.js
> [fix] prefetch should ignore links ignored by the router

- documentation/docs/30-advanced/20-hooks.md
- documentation/docs/30-advanced/25-errors.md
> Error handling docs

- documentation/docs/20-core-concepts/40-page-options.md
- documentation/docs/60-appendix/30-glossary.md
> clarify that pages with actions cannot be prerendered

- .changeset/hungry-tips-obey.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/before-navigate/prevent-navigation/+page.svelte
- packages/kit/test/apps/basics/src/routes/before-navigate/redirect/+page.js
- packages/kit/test/apps/basics/test/client.test.js
> [fix] don't run beforeNavigate during redirects

- .changeset/real-onions-pull.md
- packages/kit/src/runtime/app/forms.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte
> Workaround for the DOM clobbering for use:enhance

- .changeset/fair-panthers-notice.md
- packages/kit/src/runtime/app/forms.js
> [feat] async function support for `enhance` action

- .changeset/pink-jokes-call.md
- packages/kit/src/runtime/server/index.js
Closes #7609
No test, because trivial and weird to test
> [feat] support throwing redirect in handle

- documentation/docs/20-core-concepts/30-form-actions.md
> [docs] clarify load/action connection in example

- packages/kit/src/core/sync/utils.js
super minor but this fixes the wacky indentation in some generated files, which makes debugging the framework a slightly less chaotic experience
> fix indentation detection

- .changeset/warm-deers-sneeze.md
- packages/kit/types/ambient.d.ts
> [docs] routeId -> route.id

- .changeset/kind-beans-talk.md
- packages/kit/src/core/config/options.js
> fix outdated error

- packages/kit/types/index.d.ts
Reference https://github.com/sveltejs/kit/pull/7338
> [docs] prefix route.id examples with `/`

- .changeset/angry-windows-smell.md
- packages/kit/src/core/generate_manifest/index.js
- packages/kit/src/utils/filesystem.js
fixes https://github.com/sveltejs/kit/issues/7641
> [fix] safely join url segments in manifest

- documentation/docs/30-advanced/10-advanced-routing.md
> layout docs

- .changeset/unlucky-hounds-design.md
- packages/kit/src/exports/node/polyfills.js
> revert #7668

- documentation/docs/20-core-concepts/20-load.md
> clarify merging semantics

- .changeset/friendly-plums-notice.md
- packages/kit/src/exports/vite/build/build_server.js
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/src/runtime/app/environment.js
- packages/kit/src/runtime/client/start.js
- packages/kit/src/runtime/env.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/test/apps/basics/src/routes/app-environment/+page.svelte
- packages/kit/test/apps/basics/svelte.config.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/types/ambient.d.ts
- packages/kit/types/internal.d.ts
> expose `version` from `$app/environment`

- package.json
see if this clears the dumb cache
> [chore] bump pnpm

- .changeset/wicked-kiwis-burn.md
- packages/kit/src/runtime/control.js
- packages/kit/types/index.d.ts
> [fix] adjust interfaces to fix type errors

- .changeset/green-timers-develop.md
- packages/kit/src/exports/vite/index.js
See https://github.com/vitejs/vite/issues/9378#issuecomment-1229771480 for an explanation
Should this close https://github.com/vitejs/vite/issues/9378?
> [chore] don't override printUrls

- .changeset/ninety-colts-protect.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/routing/external-popstate/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
> ignore popstate events from outside the router

- sites/kit.svelte.dev/src/lib/docs/server/index.js
> [docs] don't show TS version of svelte.config.js

- .changeset/wise-spoons-promise.md
- packages/kit/src/exports/vite/utils.js
@dominikg noticed this while trying to implement some new logging and discovering he couldn't configure the log level
> [fix] preserve Vite CLI opts

- .changeset/strange-roses-sell.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/app.html
- packages/kit/test/apps/basics/src/routes/routing/link-outside-app-target/source/+page.svelte
- packages/kit/test/apps/basics/src/routes/routing/link-outside-app-target/state.js
- packages/kit/test/apps/basics/src/routes/routing/link-outside-app-target/target/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
> client-side router ignores links outside app target

- packages/kit/src/exports/vite/graph_analysis/index.js
- packages/migrate/migrations/routes/utils.js
> use string repeat method

- sites/kit.svelte.dev/src/lib/docs/server/index.js
During investigating something else I discovered that prerendering fails, this fixes it
> [docs] get kit site building on windows

- documentation/docs/20-core-concepts/10-routing.md
- [x ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x ] This message body should clearly illustrate what problems it solves.
Closes #7786
> updated .server docs to include links to methods

- .changeset/chilled-drinks-hug.md
- packages/kit/src/runtime/client/client.js
> make touchstart listener passive

- .changeset/eighty-lions-doubt.md
- documentation/docs/30-advanced/20-hooks.md
- packages/kit/src/exports/vite/dev/index.js
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/actions.js
- packages/kit/src/runtime/server/page/index.js
- packages/kit/src/runtime/server/page/respond_with_error.js
- packages/kit/src/runtime/server/utils.js
- packages/kit/types/index.d.ts
- packages/kit/types/internal.d.ts
> [feat] allow handleError to return a promise

- .changeset/clever-pillows-turn.md
- package.json
- packages/kit/package.json
- pnpm-lock.yaml
#7435 without the Playwright updates
> update pnpm and undici

- renovate.json
mostly formatting. plus a bit of upgrading to the latest. shouldn't be any changes to behavior
> [chore] cleanup renovate config

- .github/workflows/ci.yml
- packages/kit/package.json
- turbo.json
> remove kit build script

- documentation/docs/30-advanced/40-service-workers.md
Cache.put takes two arguments but is only supplied one in the example.
> Service Worker docs: Update cache.put arguments in example

- .changeset/fresh-zebras-mate.md
- packages/kit/src/runtime/app/navigation.js
> [fix] add migration hint for renamed methods

- packages/kit/src/runtime/client/utils.js
Just simple type improvements using generics. Makes some of the listings easier to understand and less disgusting
> feat: Make types less gross looking

- .changeset/soft-ladybugs-drum.md
- packages/kit/package.json
> remove errant prepublishOnly script

- pnpm-lock.yaml
- sites/site-kit/package.json
remove an unused dependency and match versions used elsewhere
> [chore] cleanup site-kit dependencies

- sites/site-kit/src/lib/components/Nav.svelte
> [fix] nav dark mode support

- packages/adapter-auto/package.json
- packages/adapter-cloudflare-workers/package.json
- packages/adapter-cloudflare/package.json
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-static/package.json
- packages/adapter-vercel/package.json
- packages/kit/package.json
- packages/package/package.json
- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
I'm getting some weird errors about `@types/node` on another PR, so would like to upgrade this dependency
> [chore] upgrade `@types/node`

- packages/create-svelte/README.md
> [docs] add vitest option

- sites/kit.svelte.dev/src/lib/search/SearchBox.svelte
- sites/kit.svelte.dev/src/lib/search/SearchResults.svelte
> fix search box styles

- sites/kit.svelte.dev/src/routes/home/Svelte.svelte
> style tweaks

- sites/kit.svelte.dev/src/routes/home/Deployment.svelte
> add width/height attributes

- sites/kit.svelte.dev/src/lib/docs/Contents.svelte
- sites/kit.svelte.dev/src/routes/docs/+layout.svelte
- sites/kit.svelte.dev/src/routes/docs/[slug]/+page.svelte
Closes #7919. Also removes a spurious prop warning for the `<OnThisPage>` component.
> [fix] Safari JS/TS toggle in docs

- packages/adapter-vercel/README.md
cc @Rich-Harris, discussed internally
A draft of the Vercel environment variables FYI in advance of removing documentation of their `VITE_` prefixed variants.
> feat: Environment variable FAQ for Vercel adapter

- sites/kit.svelte.dev/src/routes/home/Deployment.svelte
> fix mobile styles

- sites/kit.svelte.dev/src/routes/home/Features.svelte
> remove shape-outside

- sites/kit.svelte.dev/src/lib/docs/server/index.js
- sites/site-kit/src/lib/styles/text.css
> make `<pre>` elements in docs scrollable

- sites/kit.svelte.dev/src/lib/docs/Contents.svelte
- sites/kit.svelte.dev/src/routes/+layout.svelte
- sites/kit.svelte.dev/src/routes/Banner.svelte
- sites/site-kit/src/lib/components/Nav.svelte
> [site] banner

- .changeset/sour-bears-raise.md
- documentation/docs/60-appendix/05-integrations.md
- packages/create-svelte/package.json
- packages/create-svelte/shared/+default+checkjs/svelte.config.js
- packages/create-svelte/shared/+default+typescript/svelte.config.js
- packages/create-svelte/shared/+typescript/package.json
- packages/create-svelte/shared/+typescript/svelte.config.js
- packages/create-svelte/templates/default/package.json
- packages/create-svelte/templates/default/svelte.config.js
- packages/kit/src/exports/vite/index.js
- packages/package/test/fixtures/resolve-alias/svelte.config.js
- pnpm-lock.yaml
I left a couple tests using `svelte-preprocess` just to make sure both work
> [feat] vitePreprocess

- documentation/docs/20-core-concepts/30-form-actions.md
- documentation/docs/40-best-practices/10-accessibility.md
- add labels to inputs in examples
- note that focus management applies to enhanced forms
> Update form docs for a11y

- documentation/docs/60-appendix/05-integrations.md
Updating based on feedback from @kaisermann and @bluwy on Discord. Thanks for the suggestions!
> [docs] improve svelte-preprocess docs

- documentation/docs/30-advanced/40-service-workers.md
- documentation/docs/30-advanced/50-server-only-modules.md
- documentation/docs/60-appendix/10-migrating.md
- packages/kit/types/ambient.d.ts
- packages/kit/types/index.d.ts
- packages/kit/types/private.d.ts
- sites/kit.svelte.dev/src/lib/docs/server/index.js
> don't blindly ignore errors in docs

- documentation/docs/10-getting-started/30-project-structure.md
> clarify test file location

- packages/kit/src/core/prerender/prerender.js
- turbo.json
(latter hopefully fixes some wrong cache hits)
> [chore] fix type error, remove obsolete entry from turbo config

- .changeset/yellow-taxis-itch.md
- packages/kit/src/exports/vite/dev/index.js
> [fix] don't crash Vite dev server on manifest error

- packages/kit/src/core/config/index.spec.js
> [chore] fix failing test

- packages/amp/package.json
so npm data is correct
no changelog as it doesn't affect the code at all.
> chore: update package directory of amp in it's package.json

- packages/kit/src/exports/vite/build/utils.js
- packages/kit/src/exports/vite/index.js
just some minor cleanup I noticed
> [chore] minor Vite cleanup

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
this changes the blockquote styles to match learn.svelte.dev
> bump site-kit

- documentation/docs/30-advanced/20-hooks.md
An example that doesn't throw TS errors
Fixes #7867
> [docs] better handleError code example

- packages/kit/src/exports/vite/index.js
these are really more about compiling than setup. It also fixes Storybook `build` (the original version only worked with `dev` as I hadn't tested against `build`)
closes https://github.com/sveltejs/kit/issues/5397
> [chore] move writeBundle and closeBundle to compile plugin

- .changeset/ninety-cups-prove.md
- packages/adapter-auto/package.json
- packages/adapter-cloudflare-workers/package.json
- packages/adapter-cloudflare/package.json
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-static/package.json
- packages/adapter-vercel/package.json
- packages/amp/package.json
- packages/create-svelte/package.json
- packages/create-svelte/templates/default/package.template.json
- packages/create-svelte/templates/skeleton/package.template.json
- packages/create-svelte/templates/skeletonlib/package.template.json
- pnpm-lock.yaml
> [chore] add peerDependencies, add more specific next version

- .changeset/exit-pre-manually.js
> [chore] add script 

- documentation/docs/20-core-concepts/40-page-options.md
> [docs] note ssr/prerender dependency

- .changeset/fresh-files-study.md
- packages/kit/src/core/sync/write_types/index.js
- packages/kit/src/utils/filesystem.js
- packages/kit/test/prerendering/ssr-false/package.json
- packages/kit/test/prerendering/ssr-false/src/routes/not-prerenderable/+page.server.js
> [fix] remove obsolete generated types correctly

- packages/adapter-auto/package.json
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-static/package.json
- packages/adapter-static/test/apps/prerendered/package.json
- packages/adapter-static/test/apps/spa/package.json
- packages/adapter-vercel/package.json
- packages/kit/test/apps/amp/package.json
- packages/kit/test/apps/basics/package.json
- packages/kit/test/apps/dev-only/package.json
- packages/kit/test/apps/options-2/package.json
- packages/kit/test/apps/options/package.json
- packages/kit/test/apps/writes/package.json
- packages/kit/test/build-errors/apps/prerenderable-incorrect-fragment/package.json
- packages/kit/test/build-errors/apps/prerenderable-not-prerendered/package.json
- packages/kit/test/build-errors/apps/private-dynamic-env-dynamic-import/package.json
- packages/kit/test/build-errors/apps/private-dynamic-env/package.json
- packages/kit/test/build-errors/apps/private-static-env-dynamic-import/package.json
- packages/kit/test/build-errors/apps/private-static-env/package.json
- packages/kit/test/build-errors/apps/server-only-folder-dynamic-import/package.json
- packages/kit/test/build-errors/apps/server-only-folder/package.json
- packages/kit/test/build-errors/apps/server-only-module-dynamic-import/package.json
- packages/kit/test/build-errors/apps/server-only-module/package.json
- packages/kit/test/prerendering/basics/package.json
- packages/kit/test/prerendering/options/package.json
- packages/kit/test/prerendering/paths-base/package.json
- packages/kit/test/prerendering/ssr-false/package.json
- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
(let's see if that makes a difference for changesets)
> [chore] workspace *->^

- .changeset/dull-cows-applaud.md
> chore: rerelease create-svelte

- documentation/docs/20-core-concepts/50-adapters.md
> [docs] Remove "The adapter API may change before 1.0." from Adapter

- documentation/docs/20-core-concepts/20-load.md
The `` comment looks better inside `<slot></slot>` then previous.
> Improved example code

- documentation/docs/10-getting-started/20-creating-a-project.md
Since by just editing files. I don't think that we "may not need to bother reading the rest of this guide!" I thinks that's quite a claim and doesn't fit here.
> Removed "you may not need to bother reading the rest of this guide!"

- documentation/docs/30-advanced/20-hooks.md
> [docs] fix typo in statement about `sequence` helper

- documentation/docs/20-core-concepts/10-routing.md
Added 'then'. It is needed here.
> [docs] clarify order of error page precedence

- documentation/docs/20-core-concepts/20-load.md
> [docs] clarify that server load should be used in example and isn't optional

- documentation/docs/20-core-concepts/10-routing.md
Next should be previous. (I think)
> [docs] remove confusion about next vs previous layout

- documentation/docs/60-appendix/10-migrating.md
Previously, this would result in completely empty HTML output.
> Doc: Fix html-minifier hook example

- documentation/docs/20-core-concepts/20-load.md
#8220 fixed one thing and broke another
> [docs] change `PageServerLoad` to `PageLoad`

- documentation/faq/80-integrations.md
I also moved the middleware FAQ down a bit as it discusses a less common need
> [docs] add an FAQ regarding separate backend

- documentation/faq/80-integrations.md
> fix proxy example

- packages/kit/test/apps/basics/test/client.test.js
> fix some flaky tests

- documentation/docs/30-advanced/20-hooks.md
Documentation update only, no code changes.
> Clarify: `handleFetch` also applies to `fetch` requests from actions

- documentation/docs/30-advanced/25-errors.md
> [docs] add shouldnt throw note about handleError

- packages/kit/test/apps/basics/test/test.js
this is what playwright recommends
> [chore] use locator to click during playwright tests

- .changeset/cyan-mirrors-cry.md
- packages/kit/src/runtime/client/utils.js
- packages/kit/test/apps/basics/src/routes/routing/missing-href/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
> ignore `<a>` elements with no `href`

- .changeset/strange-pens-pump.md
- packages/kit/src/runtime/client/client.js
possibly related to #7071
the "check if version updated" logic was only applied to data loading, not loading the node files itself
no test because I don't know how 😄 a good example where unit-testing this would help
> fix: check version on node fetch fail

- .changeset/nervous-socks-end.md
- packages/kit/src/core/prerender/prerender.js
- packages/kit/test/prerendering/basics/test/test.js
- packages/kit/test/prerendering/ssr-false/src/routes/prerenderable-3/+page.js
- packages/kit/test/prerendering/ssr-false/src/routes/prerenderable-3/+page.svelte
- packages/kit/test/prerendering/ssr-false/test/test.js
> fix: prerender page when prerender set to 'auto' and ssr set to true

- .changeset/pink-bulldogs-remain.md
- packages/adapter-static/README.md
> docs: clarify that you can build SPAs with adapter-static

- .changeset/blue-kings-beg.md
- packages/kit/src/core/postbuild/index.js
- packages/kit/test/prerendering/basics/src/hooks.server.js
> always exit postbuild process

- .changeset/good-zebras-deny.md
- packages/kit/src/runtime/server/page/render.js
as suggested by @dummdidumm here: https://github.com/sveltejs/kit/issues/8492#issuecomment-1382399799
> fix: only run missing page check in dev mode

- .changeset/tricky-steaks-speak.md
- packages/kit/package.json
- pnpm-lock.yaml
> chore: upgrade devalue

- documentation/docs/20-core-concepts/40-page-options.md
Glossary link for `hydration` was just at the end, added it also to the other occurrences.
> docs: linked hydration term to glossary

- packages/kit/test/apps/basics/test/client.test.js
flakes on safari all the time, this hopefully helps (reason: flakes with "navigation interrupted", this fix should wait on the navigation to finish)
> chore: deflake reload test

- .changeset/neat-geckos-end.md
- documentation/docs/50-reference/20-cli.md
- packages/kit/src/cli.js
- packages/kit/src/core/sync/sync.js
> fix: only generate typing files with sync command

- .changeset/curvy-chefs-design.md
- packages/kit/types/ambient.d.ts
> docs: explain how to add ambient typings

- .changeset/lovely-coins-sleep.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/client/utils.js
- packages/kit/test/apps/basics/src/routes/before-navigate/prevent-navigation/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/types/ambient.d.ts
Also some docs on how to know when native confirmation dialog appears
fixes #8482
> fix: ignore target=_blank links

- sites/kit.svelte.dev/src/lib/search/content.server.js
> site: remove hidden code

- packages/adapter-node/README.md
- packages/adapter-static/README.md
- packages/adapter-vercel/README.md
Someone forgot to make some copypaste updates 😆
> fix: copypaste is evil

- .github/workflows/ci.yml
followup to #8585 to prevent collisions
> fix: ci - ensure unique test artifacts and correct matrix definition

- packages/adapter-cloudflare/index.js
fixes a bug in #8422. no changeset because that PR is unreleased, and we can slip this one in as well
> fix cloudflare routes

- .changeset/large-points-push.md
- packages/create-svelte/templates/default/src/app.d.ts
- packages/create-svelte/templates/skeleton/src/app.d.ts
- packages/create-svelte/templates/skeletonlib/src/app.d.ts
> remove obsolete comment from templates

- documentation/docs/10-getting-started/10-introduction.md
It might help people understand SvelteKit more quickly if they're already familiar with Next or Nuxt.
I also rewrote a sentence at the end of this section to lead off with the benefits rather than implementation details.
> docs: mention Next and Nuxt for people coming from other languages

- .changeset/rotten-walls-itch.md
- packages/kit/src/core/env.js
- packages/kit/src/core/postbuild/index.js
- packages/kit/src/core/postbuild/prerender.js
- packages/kit/src/core/sync/write_server.js
- packages/kit/src/runtime/client/start.js
- packages/kit/src/runtime/env-private.js
- packages/kit/src/runtime/env-public.js
- packages/kit/src/runtime/env/dynamic/private.js
- packages/kit/src/runtime/env/dynamic/public.js
- packages/kit/src/runtime/server/index.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/shared.js
- packages/kit/test/apps/basics/.env
- packages/kit/test/apps/basics/src/routes/+layout.server.js
- packages/kit/types/internal.d.ts
> set env vars before postbuild analysis

- .changeset/two-pens-exist.md
- packages/adapter-netlify/index.js
> chore: update link to docs for missing netlify.toml warning

- .changeset/pink-games-perform.md
- packages/kit/src/exports/vite/dev/index.js
...after Vite dependency optimizations
fixes #8523
> fix: reapply exports alignment

- CONTRIBUTING.md
This PR fixes minor issues in CONTRIBUTING.md file:
* removes obsolete sentence about pre-1.0 rule
* fixes minor language issues
> docs: minor fixes in contributing guide

- .changeset/brave-kangaroos-beg.md
- packages/kit/src/runtime/server/page/actions.js
> chore: restrict actions to POST

- sites/kit.svelte.dev/src/lib/search/SearchBox.svelte
- sites/kit.svelte.dev/src/lib/search/search.js
This cleans up some of the type definitions in the search file
> chore: improve search types

- packages/kit/src/utils/fork.js
> chore: simplify `fork` implementation

- documentation/docs/20-core-concepts/20-load.md
- packages/kit/types/index.d.ts
> docs: point out throw caveat

- .changeset/chilly-hats-wait.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/options/source/pages/preloading/+page.svelte
- packages/kit/test/apps/options/source/pages/preloading/code/+page.svelte
- packages/kit/test/apps/options/test/test.js
> fix: take base path into account when preloading code

- packages/kit/types/ambient.d.ts
Referencing old filesystem in a example
> docs: Update ambient.d.ts for preloadData reference

- .changeset/bright-cougars-drop.md
- packages/kit/src/utils/fork.js
closes #8769. no test because i'm in a hurry, but i don't think it needs one honestly — this is fairly self-explanatory code
> fix: forward `process.env` to child process

- packages/kit/test/apps/basics/test/server.test.js
always nice to be able to do some cleanup!
> chore: enable skipped test

- .changeset/ten-bats-retire.md
- packages/kit/types/index.d.ts
> docs: fix typo

- .changeset/ten-spiders-chew.md
- packages/kit/src/core/postbuild/analyse.js
- packages/kit/src/core/sync/write_client_manifest.js
> fix: build error on layouts with missing leaves

- .changeset/twenty-taxis-nail.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/anchor/+page.svelte
- packages/kit/test/apps/basics/src/routes/anchor/anchor/+page.svelte
- packages/kit/test/apps/basics/test/cross-platform/client.test.js
> fix: handle non-ascii anchors when navigating

- .changeset/hip-eggs-raise.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/anchor/+page.svelte
- packages/kit/test/apps/basics/src/routes/anchor/anchor/+page.svelte
- packages/kit/test/apps/basics/test/cross-platform/client.test.js
> handle special chars in anchors when navigating

- .changeset/bright-moles-worry.md
- packages/kit/src/core/postbuild/prerender.js
- packages/kit/src/exports/vite/index.js
Also add "Building app" and "Analysing routes" log. Hopefully clears up some confusion around what happens at build time.
> fix: only show prerendering message when actually prerendering

- .changeset/hot-adults-peel.md
- packages/kit/src/exports/vite/index.js
closes https://github.com/sveltejs/kit/issues/8360
> fix: remove Vite manifest before running adapter

- packages/kit/src/runtime/client/client.js
- packages/kit/types/internal.d.ts
> chore: small refactor on calculating invalid_server_nodes

- .changeset/ninety-hotels-care.md
> docs: fix links in READMEs

- documentation/docs/20-core-concepts/20-load.md
- documentation/docs/20-core-concepts/30-form-actions.md
- packages/kit/types/index.d.ts
Filenames give context without having to scroll around to see which file the doc is referring to.
Also enables TS snippet generation.
I can't seem to make it work in diff MD or index.d.ts. Please advise.
> Add filenames to code snippets

- sites/kit.svelte.dev/src/lib/search/SearchResultList.svelte
> docs: fix html escaping in search results

- sites/kit.svelte.dev/README.md
I believe you need to run `pnpm run update` or the site won't run
> docs: update docs for running site locally

- documentation/docs/20-core-concepts/40-page-options.md
fixes https://github.com/sveltejs/kit/pull/8740#discussion_r1097720180, and also removes mention of Netlify since this isn't supported there yet; it gives the wrong impression
> docs: clarify route level config, fix typo

- .changeset/quiet-boats-add.md
- packages/kit/types/index.d.ts
> docs: clarify version management feature

- .changeset/brown-boxes-beg.md
- packages/kit/src/core/postbuild/analyse.js
- packages/kit/types/internal.d.ts
> fix: pick up config from endpoints

- .changeset/good-carrots-flow.md
- packages/adapter-node/index.js
> fix: use `strictRequires: true` in `adapter-node`

- packages/adapter-netlify/index.js
Realized a bug in #8953 two seconds after merging it. No changeset assuming it still gets in the same patch release as #8953.
> fix: string concatenation

- .changeset/nervous-squids-watch.md
- packages/kit/src/exports/vite/index.js
Fixes #8926 - I made an educated guess about what flags should be included or not, let me know what ones I missed/shouldn't have added :pray:
> Update supported vite cli flags

- .changeset/lucky-toys-help.md
- packages/create-svelte/shared/+playwright+default/tests/test.ts
- packages/create-svelte/shared/+playwright+skeleton/tests/test.ts
- packages/create-svelte/shared/+playwright+skeletonlib/tests/test.ts
using new locator apis new from version 1.27
> fix: use new locator api for demo tests

- .changeset/rotten-hotels-allow.md
- packages/adapter-netlify/index.js
Fixes #8999 
Included a if statement to catch root route
> fix: adapter-netlify redirect for /_data.json

- packages/create-svelte/bin.js
This might be an insignificant change because GitHub redirects the old link, so it works but I thought it would be prudent to update it.
> fix: Update community-maintained integrations link

- documentation/docs/30-advanced/65-snapshots.md
The snapshot docs were missing a label on the textarea, which is bad for a11y.
> docs: add label to snapshot example

- packages/create-svelte/templates/skeleton/package.json
- sites/kit.svelte.dev/package.json
this should stop them from attempting to be published
> add private: true to private packages

- .github/workflows/ci.yml
- packages/kit/test/github-flaky-warning-reporter.js
- packages/kit/test/utils.js
let's see if we can get some useful information on ci flakiness and test results into github ui
> chore: improve playwright test reporting on github ci

- documentation/docs/10-getting-started/40-web-standards.md
- documentation/docs/25-build-and-deploy/40-adapter-node.md
This PR fix two typos on documentation files.
> docs: fix typos

- package.json
just trying something, bear with me...
> add start command to launch site

- .changeset/orange-kangaroos-sniff.md
- packages/package/src/cli.js
> fix: print version when running `svelte-package --version` 

- .changeset/smart-snails-exercise.md
- packages/create-svelte/templates/skeletonlib/package.template.json
Follow-up to https://github.com/sveltejs/kit/pull/8922
> chore(create-svelte): update dependency @sveltejs/package to v2.0.0

- .changeset/tough-points-arrive.md
- packages/adapter-vercel/index.js
> add leading `/` to isr routes

- .changeset/late-rings-warn.md
- packages/kit/src/core/adapt/builder.js
- packages/kit/src/core/adapt/builder.spec.js
fixes https://github.com/sveltejs/kit/issues/9093
> fix: correctly return asset list when building

- packages/kit/types/index.d.ts
> docs: fix typo in example

- packages/package/src/typescript.js
> chore: remove unused set for excluded files

- sites/kit.svelte.dev/src/routes/+layout.svelte
- sites/kit.svelte.dev/src/routes/docs/+layout.svelte
This PR adds a close button to the hackathon banner in the sveltekit docs. The banner currently hides the javascript/typescript toggle for code previews.
> Add close button to hackathon banner

- .changeset/curvy-lobsters-hug.md
- packages/create-svelte/shared/+skeletonlib/README.md
Should help people to onboard faster
> chore: enhance library skeleton readme with some library instructions

- documentation/docs/20-core-concepts/30-form-actions.md
Suggestion for more clearly articulating how this departs from what the user has just focussed on in this section. I was tripped up by this description at first, thinking the action I had written earlier still did something.
> docs: Clarify the behaviour of GET vs POST form actions

- .github/workflows/audit.yml
> ci: add scheduled audit workflow

- .changeset/friendly-pumpkins-reply.md
- packages/adapter-vercel/index.js
> fix: move catch-all-regex to the end

- sites/kit.svelte.dev/src/routes/+layout.svelte
seems like height 0 is not enough
> fix: remove banner completely on X click

- documentation/docs/25-build-and-deploy/40-adapter-node.md
closes https://github.com/sveltejs/kit/issues/9175
> docs: move example to live with corresponding text

- .changeset/real-crews-double.md
- packages/adapter-vercel/index.js
> fix: temporarily disable streaming when ISR is used

- .changeset/small-teachers-smash.md
- packages/create-svelte/shared/+default+checkjs/svelte.config.js
- packages/create-svelte/shared/+default+typescript/svelte.config.js
- packages/create-svelte/shared/+default-typescript/svelte.config.js
- packages/create-svelte/shared/+typescript/svelte.config.js
- packages/create-svelte/shared/-typescript/svelte.config.js
> docs: inform about adapter-auto not supporting all environments

- .changeset/strange-wasps-smash.md
> add dummy changeset

- documentation/docs/20-core-concepts/30-form-actions.md
See an issue I ran into - https://discordapp.com/channels/457912077277855764/1079348742584545320
I had problems calling a form action from route `a` by route `b` - the `form` object and `$page.form` weren't  updated. I was able to solve that issue by using `applyAction` as per explanation of JoyOfCode.
`+page.svelte` in route `/b` calling something in `/a`
```svelte
<script lang="ts">
import { applyAction, enhance, type SubmitFunction } from '$app/forms';
import { page } from '$app/stores';
import type { ActionData } from '../a/$types';
import type { PageData } from './$types';
export let data: PageData;
export let form: ActionData;
const login: SubmitFunction = () => {
return async ({ result }) => {
await applyAction(result);
};
};
$: console.log('Form received', form, form?.test, data); …
```
> docs:  explain usage of applyAction to ensure form/$page.form is updated when calling form action on different route

- documentation/docs/30-advanced/70-packaging.md
> fix typo? in the packaging docs

- sites/kit.svelte.dev/src/routes/+layout.svelte
I wanted to propose adding a mention of prizes to the banner as I think it will get more folks to click through
> site: mention hackathon prize money

- packages/kit/types/index.d.ts
> fix minor typo in configuration section

- .changeset/lemon-pigs-remember.md
- packages/kit/src/exports/vite/utils.js
> fix: correct not found message when setting `paths.base`

- .changeset/tame-hounds-relax.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/page/load_data.js
- packages/kit/src/runtime/shared.js
> feat: warn when calling depends(...) with special URI scheme

- packages/kit/CHANGELOG.md
> fix: Update Kit changelog

- documentation/docs/30-advanced/70-packaging.md
> docs: fix 70-packaging.md

- .changeset/tall-impalas-report.md
- packages/kit/src/runtime/server/page/render.js
- packages/kit/test/apps/options/source/hooks.server.js
> always include `<link rel="stylesheet">` even if excluded from Link headers

- .changeset/tasty-spies-listen.md
- packages/kit/src/exports/vite/index.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/types/index.d.ts
- sites/kit.svelte.dev/src/lib/docs/server/index.js
- sites/kit.svelte.dev/src/lib/docs/server/render.js
closes #9225, and adds some docs explaining how to set `version.name` to the current commit hash
> omit hash from global name during dev

- .changeset/gold-ways-repair.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/before-navigate/prevent-navigation/+page.svelte
- packages/kit/test/apps/basics/test/cross-platform/client.test.js
> run `beforeNavigate` callbacks after cancelled unloading navigation

- .changeset/happy-panthers-leave.md
- packages/kit/src/exports/vite/preview/index.js
closes #8839. No tests as we don't really have a great place to put them
> redirect when previewing prerendered pages

- .changeset/loud-ghosts-worry.md
Our release job is failing. This should fix it
> chore: fix invalid changeset

- .changeset/lemon-mayflies-design.md
- documentation/docs/20-core-concepts/30-form-actions.md
- packages/kit/src/runtime/app/forms.js
- packages/kit/types/ambient.d.ts
> feat: expose submitter to `use:enhance` `SubmitFunction`

- .changeset/many-shrimps-rush.md
- packages/adapter-vercel/index.js
fixes https://twitter.com/Rich_Harris/status/1636389475885666309
> throw error if isr route uses edge runtime

- .changeset/great-ways-begin.md
- packages/kit/src/exports/vite/build/utils.js
Prevents an infinite loop which makes debugging such errors harder
> fix: throw error when file can't be found in Vite manifest

- .changeset/forty-pandas-mate.md
- packages/kit/src/runtime/server/index.js
fixes https://github.com/sveltejs/learn.svelte.dev/issues/348. right now, if your `hooks.server.js` gets into a broken state, SvelteKit loses control over the response
> gracefully handle failure to load hooks.server.js

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
- sites/kit.svelte.dev/src/routes/+layout.svelte
makes the nav look like this
instead of like this
> make full hostname appear in nav

- packages/kit/types/ambient.d.ts
also link to state management docs
> docs: clarify wording for $app/stores

- .changeset/spotty-parents-run.md
- packages/kit/src/core/sync/create_manifest_data/index.js
- packages/kit/src/core/sync/create_manifest_data/index.spec.js
This is a continuation of #9488
closes #9380 
closes #9501
added the names of the conflicting files to the error message
> fix: prevent routes/layouts from having conflicting files through resets or different extensions

- packages/kit/src/runtime/client/utils.js
> fix: better handling for network errors resulting from version polls

- .changeset/curly-items-speak.md
- packages/kit/src/core/postbuild/prerender.js
> provide better error when prerendered routes conflict with each other

- .changeset/fuzzy-coats-pay.md
- packages/kit/package.json
- pnpm-lock.yaml
- renovate.json
resolves #9427 
revert #9591 and upgrade undici to latest as per https://github.com/sveltejs/kit/issues/9427#issuecomment-1516012883
> chore: revert undici pin and upgrade

- packages/adapter-node/src/handler.js
Noticed this while investigating the memory leak issue, doesn't really affect anything right now cause the ssr handler doesn't call next but something about belts and braces. Marking this as chore and no changeset cause this doesn't affect users.
> chore: fix off by one in adapter-node's sequence handler

- packages/adapter-static/test/test.js
- packages/kit/src/runtime/server/cookie.spec.js
- packages/kit/src/utils/url.spec.js
- packages/kit/test/apps/amp/test/test.js
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/basics/test/cross-platform/client.test.js
- packages/kit/test/apps/basics/test/cross-platform/test.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/apps/options/test/test.js
- packages/kit/test/prerendering/basics/test/test.js
- packages/kit/test/prerendering/options/test/test.js
- packages/kit/test/utils.d.ts
- packages/kit/test/utils.js
- replace inverted `assert.ok`s with `assert.not` to make failure messages less confusing
- replace `assert.ok(string.includes` 
- add helper for getComputedStyle that fails with selector not found instead of just: expected some string got null
> chore: improve error reporting for tests

- .changeset/red-hats-love.md
- packages/kit/package.json
- pnpm-lock.yaml
Release notes here: https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/CHANGELOG.md
> feat: upgrade vite-plugin-svelte for resolve improvements and warnings

- documentation/docs/25-build-and-deploy/40-adapter-node.md
Add some extra info to the adapter-node polyfill option's docs.
> docs: expand `adapter-node` polyfill docs

- .changeset/tricky-versions-break.md
- packages/create-svelte/shared/+playwright+typescript/playwright.config.ts
- packages/create-svelte/shared/+playwright-typescript/playwright.config.js
Feels wrong to undo my own efforts from #7826 but hey, at least Playwright can't break it again with trusty ole regex.... *cough*
fixes #9793
> fix: default playwright globs

- .changeset/smooth-trees-invent.md
forgot the change set for https://github.com/sveltejs/kit/pull/9768
> changeset for #9768

- sites/kit.svelte.dev/src/routes/+layout.svelte
Copy of https://github.com/sveltejs/sites/pull/475
> change banner to svelte summit

- packages/kit/src/core/generate_manifest/index.js
- packages/kit/src/exports/vite/build/build_server.js
- packages/kit/src/exports/vite/build/utils.js
- packages/kit/src/exports/vite/index.js
- packages/kit/test/apps/basics/src/routes/data-sveltekit/preload-data/target/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
> feat: remove entrypoints for a smaller bundle size

- sites/kit.svelte.dev/vercel.json
> chore: [site] fix deployments

- .changeset/silent-hairs-rule.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/actions/form-errors/adjacent-error-boundary/+error.svelte
- packages/kit/test/apps/basics/src/routes/actions/form-errors/adjacent-error-boundary/+page.server.js
- packages/kit/test/apps/basics/src/routes/actions/form-errors/adjacent-error-boundary/+page.svelte
- packages/kit/test/apps/basics/test/test.js
> fix: realign state.branch on the client on hydration

- .changeset/tender-beds-smile.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js
- packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/setup.js
> fix: client state stale after invalidate

- documentation/docs/30-advanced/20-hooks.md
- documentation/docs/30-advanced/25-errors.md
> docs: fix sentry code examples

- documentation/docs/20-core-concepts/20-load.md
Adds an extra description for when you want to use a load function totally on the client-side for SPAs and other purposes.
> document use case for using load in client-side only contexts

- .changeset/lovely-rings-thank.md
- packages/kit/src/runtime/client/client.js
> fix: call focus with focusVisible set to false

- packages/kit/src/utils/url.spec.js
see here for a description of the issue: https://github.com/lukeed/uvu/pull/230#pullrequestreview-1419106999
> chore: fix test assertion that wasn't actually checking anything

- documentation/docs/20-core-concepts/40-page-options.md
add forgotten piece from #9877
> docs: document that `entries` also work in `+server.js` files

- packages/kit/test/build-errors/prerender.spec.js
another one caused by https://github.com/lukeed/uvu/pull/230
> chore: fix another test that wasn't actually running

- packages/kit/test/build-errors/prerender.spec.js
I thought I'd worked around https://github.com/lukeed/uvu/pull/230 in https://github.com/sveltejs/kit/pull/9886, but it seems like I didn't quite manage
> chore: fix test for real this time

- packages/kit/test/build-errors/prerender.spec.js
The third installation of the assert.throws saga, see #9887
> chore: fix test for real for real this time

- .changeset/honest-news-hunt.md
- packages/adapter-cloudflare/index.js
Copies WASM files in Cloudflare instead of trying to load them. Closes #9890.
> fix: Set `loader: { '.wasm': 'copy' }` in esbuild config in `adapter-cloudflare`

- packages/kit/test/apps/basics/src/routes/actions/enhance/old-property-access/+page.svelte
- packages/kit/test/apps/basics/test/test.js
> fix: Flaky test

- .changeset/lemon-lamps-approve.md
- packages/kit/types/index.d.ts
> fix: type `vitePlugin` in config

- renovate.json
this should work better than #9958
> tell renovate to ignore @types/node

- sites/kit.svelte.dev/src/routes/+layout.svelte
Svelte Summit has been over for awhile now
> site: remove banner

- .changeset/heavy-eels-wash.md
- packages/kit/src/runtime/server/page/csp.js
> fix: do not add content-security-policy meta element if content is empty

- documentation/docs/20-core-concepts/30-form-actions.md
> docs: replace deprecated properties in docs for enhance

- .changeset/chilled-suns-battle.md
- packages/migrate/README.md
added a changeset so we can update the docs on npm
> docs: update migration tool README

- .changeset/tame-kangaroos-film.md
- .gitignore
- packages/kit/src/exports/vite/build/build_service_worker.js
> fix: don't copy public folder in service worker build

- packages/create-svelte/package.json
- pnpm-lock.yaml
looks like a leftover from https://github.com/sveltejs/kit/pull/9219
> chore: remove unused devDependency

- sites/kit.svelte.dev/src/routes/+layout.svelte
I think it's a good idea to give a link to learn.svelte.dev on the navbar.
> docs: update documentation Navbar to include 'Learn'

- .changeset/great-beans-retire.md
- packages/kit/src/utils/routing.js
- packages/kit/src/utils/routing.spec.js
This is a continuation of #9979. Fixes #9974.
> fix: ensure optional routes with matchers and catch-all match correctly

- package.json
> chore: eslint cache

- documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
I fund the description about env variables not clear and confusing
> docs: clarify cloudflare env usage

- packages/kit/test/prerendering/basics/test/tests.spec.js
- packages/kit/test/prerendering/options/test/tests.spec.js
- packages/kit/test/prerendering/test-utils.js
> chore: handle hydration attributes in prerendering tests

- documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
Clarify what is meant by "this adapter".
- [ X] This message body should clearly illustrate what problems it solves.
> docs: clarify "this adapter"

- .changeset/gentle-lobsters-punch.md
- packages/create-svelte/shared/+checkjs/package.json
- packages/create-svelte/shared/+eslint/package.json
- packages/create-svelte/shared/+prettier/package.json
- packages/create-svelte/shared/+typescript/package.json
- packages/create-svelte/templates/default/package.template.json
- packages/create-svelte/templates/skeleton/package.template.json
- packages/create-svelte/templates/skeletonlib/package.template.json
> breaking: install Svelte 4

- .changeset/tame-boats-attend.md
- packages/migrate/migrations/svelte-4/migrate.js
> fix: handle missing fields in migrate script

- .changeset/khaki-doors-flow.md
- packages/kit/src/runtime/client/client.js
- packages/kit/test/apps/basics/src/routes/load/invalidation/multiple-batched/+page.js
- packages/kit/test/apps/basics/src/routes/load/invalidation/multiple-batched/+page.svelte
- packages/kit/test/apps/basics/test/client.test.js
> fix: batch synchronous invalidate invocations

- documentation/docs/20-core-concepts/10-routing.md
- documentation/docs/20-core-concepts/20-load.md
- documentation/docs/20-core-concepts/30-form-actions.md
- documentation/docs/20-core-concepts/50-state-management.md
- packages/kit/CHANGELOG.md
closes #10210 
rename re-run occurrencies to rerun for consistency
> chore: change re-run to rerun for consistency in docs

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
closes https://github.com/sveltejs/kit/issues/10326
> site: upgrade to imagetools 5.0.5

- .changeset/cold-boxes-build.md
- packages/migrate/migrations/svelte-4/migrate.js
- packages/migrate/migrations/svelte-4/migrate.spec.js
- packages/migrate/package.json
- pnpm-lock.yaml
> fix(migrate): do not downgrade versions

- documentation/docs/20-core-concepts/10-routing.md
Quick typo fix. Loving reading through the docs so far. Very concise!
> docs: fix typo on routing page

- documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
- documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
Clarifies that you can use wrangler to test the built kit site if you want to test `platform.env`
Closes #10389
> clarify platform.env with cloudflare adapters in docs

- documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
- documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
- Build on #10390 and add "testing locally" docs
- Move the note on why the pages adapter is preferred to the workers adapter page
- Sync changes from #10096 to bindings section on pages adapter to workers adapter
- Add information on typing KVNamespace etc
> docs: update Cloudflare documentation

- documentation/docs/25-build-and-deploy/99-writing-adapters.md
> docs: remove outdated types link

- packages/kit/src/core/adapt/builder.js
> chore: remove pre-1.0 remnants

- .changeset/fresh-drinks-care.md
- .changeset/honest-items-deny.md
- .changeset/soft-mayflies-hug.md
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-vercel/package.json
- packages/create-svelte/package.json
- packages/create-svelte/shared/+vitest/package.json
- packages/create-svelte/templates/default/package.json
- packages/kit/package.json
- packages/kit/test/build-errors/package.json
- packages/kit/test/prerendering/basics/package.json
- packages/kit/test/prerendering/options/package.json
- packages/kit/test/prerendering/paths-base/package.json
- packages/migrate/package.json
- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
Version bumps that aren't covered by existing semver ranges
> chore: upgrade dependencies

- documentation/docs/25-build-and-deploy/99-writing-adapters.md
> fix/:Rename sveltekit helper

- packages/kit/src/exports/public.d.ts
Addressing #10141
Add a unit to `Config.inlineStyleThreshold` documentation with link to supporting MDN documentation.
> Add unit to inlineStyleThreshold documentation

- sites/kit.svelte.dev/src/routes/+layout.svelte
Change Svelte.dev link to not go to Kit site.
> fix(sites): update svelte.dev link

- documentation/docs/20-core-concepts/20-load.md
> docs: add note about redirects in streamed promises

- CONTRIBUTING.md
> fix: CONTRIBUTING.md link directly to the pnpm.io site

- sites/kit.svelte.dev/src/routes/docs/[slug]/+page.svelte
> site: fix edit on github link

- .changeset/purple-boxes-wash.md
- packages/adapter-netlify/package.json
- pnpm-lock.yaml
It's a major version of `@netlify/functions`, but I couldn't find any breaking changes in it - only a piece of added functionality, so I added a changeset here to make this a minor version of the adapter
> chore: upgrade to @netlify/functions v2

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
fixes background color to get perfect accessibility score
> site: bump site-kit

- .changeset/thick-camels-rest.md
- packages/kit/src/runtime/client/client.js
> fix: mark aborted/cancelled navigation as handled

- documentation/docs/30-advanced/10-advanced-routing.md
fix: Updated route name from `/blog` to `/about` to match the directory structure depicted below the explanation in **(group)** section under **Advanced Layouts**.
> docs: consistent route for layout groups example

- documentation/docs/25-build-and-deploy/80-adapter-netlify.md
Netlify Edge Functions were GA'd a while ago (see https://www.netlify.com/blog/edge-functions-general-availability). This PR mirrors that into the SvelteKit docs :)
---
> chore: Remove "beta" wording from Netlify Adapter docs

- sites/kit.svelte.dev/src/routes/+layout.svelte
> chore(site): fix scroll restoration

- documentation/docs/25-build-and-deploy/50-adapter-static.md
Minor tweak to example in docs ...
Makes the github action to deploy a static site to github pages _slightly_ easier (can be copy-pasted) by removing need to edit the repo name, and auto-configuring github pages.
> docs: improve deploy-to-github-pages action example

- documentation/docs/25-build-and-deploy/40-adapter-node.md
Express.js repository should be linked, not the [expressjs.com](https://expressjs.com/) website repo.
> docs: fix express github url

- .changeset/proud-worms-press.md
- packages/kit/src/runtime/client/client.js
> fix: follow whatwg fetch spec for handling redirect loops

- packages/kit/src/exports/public.d.ts
> fix typos in type definition descriptions

- documentation/docs/25-build-and-deploy/50-adapter-static.md
You must add this so that the link in the src attribute of the image components don't break whenever a user refreshes the page in a site that is statically built (eg using Github Pages).
> docs: update recommended GitHub pages config

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
- sites/kit.svelte.dev/src/routes/docs/[slug]/+page.svelte
- sites/kit.svelte.dev/src/routes/home/Hero.svelte
- sites/kit.svelte.dev/src/routes/search/+page.svelte
The prettier config needs some cleanup in general, but I'll wait until prettier 3.1 is released for the rest so that we can upgrade the rest of the packages to prettier 3
> chore(site): run prettier on .svelte files

- packages/create-svelte/templates/default/README.md
The netlify and vercel links were broken. This PR removes the netlify one as it no longer exists and updates the vercel one to the correct URL.
> remove broken links from `create-svelte` template README.md

- README.md
Added missing link to the new `@sveltejs/enhanced-img` package.
> add `@sveltejs/enhanced-img` to top-level readme

- .changeset/wet-glasses-tie.md
- packages/create-svelte/shared/+eslint+prettier/package.json
As suggested by @hyunbinseo in https://github.com/sveltejs/kit/pull/10410#pullrequestreview-1729877724
> chore: upgrade eslint-config-prettier

- .changeset/many-seals-pull.md
- packages/adapter-vercel/index.d.ts
- packages/adapter-vercel/index.js
fixes #11063
Also relaxed the checks in the adapter a bit, so we don't need to adjust it as often - Vercel will fail the build itself with a descriptive error if the value is wrong
> feat: add support for nodejs20.x to vercel adapter

- documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
closes https://github.com/sveltejs/kit/issues/11149
Cloudflare Pages functions work a bit differently than directly deploying to a Cloudflare Worker. As such, it should be helpful to link to the Cloudflare Pages version for the bindings documentation. This lists the instructions for linking a binding to a project through the Cloudflare dashboard which is different compared to Workers (where you can just add it to a wrangler.toml file).
> docs: link to Cloudflare Page bindings documentation

- documentation/docs/30-advanced/20-hooks.md
- documentation/docs/30-advanced/25-errors.md
- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
> fix(site): snippet related errors

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
- sites/kit.svelte.dev/src/routes/+layout.server.js
- sites/kit.svelte.dev/src/routes/+layout.svelte
- sites/kit.svelte.dev/src/routes/docs/+layout.svelte
This uses the exported `fetchBanner` from site-kit to fetch the centralized banner info from svelte.dev. This makes sure the banners on all 3(learn coming soon) sites never get out of sync
> feat: Centralized banner

- .changeset/long-cheetahs-explain.md
- packages/kit/src/runtime/client/client.js
- packages/kit/src/runtime/server/page/load_data.js
- packages/kit/src/utils/promises.js
- packages/kit/test/apps/basics/test/cross-platform/test.js
> chore: deprecate top level promise await behaviour

- .github/workflows/ci.yml
https://github.com/sveltejs/kit/pull/11243/files#r1421422119
> error on uncommitted types

- packages/kit/package.json
- pnpm-lock.yaml
fixes the `@throws` thing in https://github.com/sveltejs/kit/pull/11165#issuecomment-1843064052
> chore: bump `dts-buddy`

- documentation/docs/25-build-and-deploy/55-single-page-apps.md
- packages/kit/src/exports/public.d.ts
- packages/kit/types/index.d.ts
> docs: document the behaviour of paths on fallback pages

- sites/kit.svelte.dev/src/app.html
- sites/kit.svelte.dev/static/opensearch.xml
Adds support for [SiteSearch](https://support.google.com/chrome/answer/95426)
> feat: OpenSearch

- documentation/docs/20-core-concepts/20-load.md
Fixed a minor typo in the documentation 
api.domain.dom WILL NOT receive cookies  was changed to api.domain.com WILL NOT receive cookies
> fixed minor typo in 20-load.md

- documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md
Update package scope for `vitePreprocess`
> docs: update `@svelte/` -> `@sveltejs/`

- .changeset/happy-hotels-kiss.md
- packages/migrate/migrations/sveltekit-2/index.js
Fix broken URL to non-existing migration guide with working one.
> chore: fix broken upgrade link

- documentation/docs/30-advanced/67-shallow-routing.md
> docs: fixed missing import and typo in Shallow Routing

- .changeset/angry-donuts-suffer.md
- packages/migrate/migrations/sveltekit-2/index.js
- packages/migrate/migrations/sveltekit-2/migrate.js
- packages/migrate/utils.js
> fix: handle jsconfig.json

- packages/migrate/README.md
- Add the missing newly added `sveltekit-2` migration.
- Use table to organize migrations, update broken link.
---
> docs: add sveltekit-2 migration

- packages/kit/src/exports/vite/index.js
we don't need this any more, logs are preserved automatically
> chore: remove vite logging hack

- .changeset/chilled-colts-judge.md
- packages/migrate/migrations/sveltekit-2/migrate.js
closes https://github.com/sveltejs/kit/issues/11401
> fix: correct link to docs

- documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md
Update dependencies based on the migration [script].
[script]: https://github.com/sveltejs/kit/blob/main/packages/migrate/migrations/sveltekit-2/migrate.js#L20-L25
> docs: svelte-kit v2 adapter dependencies

- packages/kit/src/runtime/app/env.js
this is a hangover from pre-1.0
> i don't think we need this any more

- documentation/docs/20-core-concepts/30-form-actions.md
> fix form actions docs

- packages/kit/src/runtime/client/client.js
Fixes https://github.com/sveltejs/kit/issues/11526
> fix go to top of page a href links

- .changeset/early-seas-remain.md
- packages/kit/src/runtime/client/client.js
very small change that makes navigate callbacks treeshakeable and mangleable
> chore: reduce client bundle size

- packages/kit/src/exports/public.d.ts
- packages/kit/types/index.d.ts
related #11545
Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.
> docs: note embedded mode limitations

- playgrounds/basic/vite.config.js
AFAICT nothing works without this
> chore: allow access to source code

- packages/kit/test/apps/basics/src/hooks.server.js
> chore: remove HttpError instanceof hack

- .github/PULL_REQUEST_TEMPLATE.md
just to make things a bit neater and more standardized
> chore: tidy up PR template a bit

- .changeset/tall-dots-agree.md
- packages/kit/src/runtime/client/client.js
- packages/kit/types/index.d.ts
> fix: amend onNavigate type

- documentation/docs/30-advanced/20-hooks.md
seen some confusion about this
> clarify hook order

- packages/kit/test/apps/basics/src/routes/interactivity/toggle-element/+page.svelte
- packages/kit/test/apps/basics/src/routes/load/invalidation/route/server/+layout.server.js
- packages/kit/test/apps/basics/src/routes/navigation-lifecycle/before-navigate/prevent-navigation/+page.svelte
- packages/kit/test/apps/basics/src/routes/scroll/top/+page.svelte
- packages/kit/test/apps/basics/src/routes/shadowed/dynamic/[slug]/+page.server.js
- packages/kit/test/apps/basics/test/client.test.js
- packages/migrate/package.json
continuing the work started in #11606
> chore: squelch warnings in test suite

- .github/workflows/ci.yml
- package.json
- scripts/sync-all.js
squelch some more annoying warnings
> chore: sync all test apps before testing

- .changeset/gold-cycles-whisper.md
- packages/package/package.json
- packages/package/test/fixtures/javascript/expected/internal/index.d.ts
- packages/package/test/fixtures/javascript/expected/internal/index.js
- packages/package/test/fixtures/javascript/expected/internal/runes.svelte.d.ts
- packages/package/test/fixtures/javascript/expected/internal/runes.svelte.js
- packages/package/test/fixtures/javascript/src/lib/internal/index.js
- packages/package/test/fixtures/javascript/src/lib/internal/runes.svelte.js
- packages/package/test/fixtures/typescript-esnext/expected/runes.svelte.d.ts
- packages/package/test/fixtures/typescript-esnext/expected/runes.svelte.js
- packages/package/test/fixtures/typescript-esnext/src/lib/runes.svelte.ts
- packages/package/test/fixtures/typescript-nodenext/expected/runes.svelte.d.ts
- packages/package/test/fixtures/typescript-nodenext/expected/runes.svelte.js
- packages/package/test/fixtures/typescript-nodenext/src/lib/runes.svelte.ts
- pnpm-lock.yaml
...to support generating types for `.svelte.ts` files
Related: https://github.com/sveltejs/language-tools/issues/2241
Also added 5.0-next as a peer dep so people don't get warnings when installing
---
> chore: bump svelte2tsx dependency 

- .changeset/swift-houses-kiss.md
- packages/create-svelte/shared/+eslint+svelte5/package.json
Installs `eslint-plugin-svelte` version `^2.36.0-next.4` when selecting Svelte 5
Closes #11530
---
> fix(create-svelte): install eslint-plugin-svelte@next for svelte5

- .changeset/shy-spiders-remember.md
- packages/adapter-auto/index.js
> fix: better error message when using `read` with `adapter-auto`

- documentation/docs/25-build-and-deploy/40-adapter-node.md
Update docs due [PR](https://github.com/sveltejs/kit/pull/11589)
---
> docs: update for BODY_SIZE_LIMIT from 0 to Infinity

- .changeset/config.json
- .github/workflows/ci.yml
- .github/workflows/release.yml
update triggers and changesets base branch
---
> chore(release): update workflows in version-1 to be able to release

- package.json
changesets tags with latest by default, even if the number is not the highest available major . to prevent this, tag with something else (there is no "no tag at all" option)
---
> chore(release): fix npm tag version-1

- documentation/docs/20-core-concepts/10-routing.md
Added a note about the dependency of +layout.svelte on +layout.ts.
---
> docs: mention that rest of example follows

- .changeset/sharp-impalas-repair.md
- packages/adapter-node/src/index.js
> fix: adapter-node v5 regression

- sites/kit.svelte.dev/src/app.html
see https://stackoverflow.com/a/45941439
> site: fix twitter card

- documentation/docs/25-build-and-deploy/90-adapter-vercel.md
Make the Vercel images config documentation more noob friendly.
---
> docs: show how options are passed on `adapter-vercel` page

- documentation/docs/60-appendix/10-faq.md
Very minor, but should be hooks.server, not hooks, see: https://github.com/sveltejs/kit/issues/12018
(documentation change only)
---
> docs: correct mistake on database setup guide

- documentation/docs/40-best-practices/07-images.md
ref https://github.com/sveltejs/kit/issues/11535. leaving that issue open though so that we can add better validation around unexpected input
> docs: highlight that enhanced-img only works with local files

- sites/kit.svelte.dev/src/lib/server/docs/index.js
this is copying Rich's fix from https://github.com/sveltejs/svelte/pull/11005
> chore: address vite warning

- packages/create-svelte/CHANGELOG.md
> docs: changelog reference the wrong pull request

- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- pnpm-lock.yaml
seeing if I can figure out why https://github.com/sveltejs/kit/pull/12298 is failing
> chore(deps): update dependency @rollup/plugin-commonjs to v26

- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
mainly just bug fixes: https://github.com/sveltejs/site-kit/blob/master/packages/site-kit/CHANGELOG.md
> chore(site): upgrade to site-kit 6.0.0-next.64

- documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
- documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
Fixes https://github.com/sveltejs/kit/issues/12282
---
> docs: correct example of persist usage

- documentation/docs/25-build-and-deploy/40-adapter-node.md
Adds the missing annotation to one of the code examples which were introduced with the latest `adapter-node` update.
---
> fix: add missing annotation that breaks the docs

- documentation/docs/20-core-concepts/40-page-options.md
close #12286 as referred in [this comment](https://github.com/sveltejs/kit/issues/12286#issuecomment-2143426474).
---
> docs: explain hmr with csr disabled

- documentation/docs/25-build-and-deploy/90-adapter-vercel.md
> docs: add JS syntax highlighting for Vercel images config example

- packages/kit/src/runtime/server/fetch.js
> chore: fix comment grammar

- packages/kit/test/apps/basics/package.json
- pnpm-lock.yaml
only updating the test since site is blocked and will go away
> chore: upgrade to marked 13

- packages/kit/src/runtime/app/forms.js
- packages/kit/types/index.d.ts
> docs: typo for use:enhance update function

- pnpm-lock.yaml
This runs `pnpm dedupe` on the dependencies - this is something I'd like us to get in the habit of after various dependency updates. This removes old versions of dependencies when there are already newer versions in the tree that will also satisfy the semver ranges.
---
> chore: deduplicate dependencies

- documentation/docs/10-getting-started/index.md
- documentation/docs/10-getting-started/meta.json
- documentation/docs/20-core-concepts/index.md
- documentation/docs/20-core-concepts/meta.json
- documentation/docs/25-build-and-deploy/index.md
- documentation/docs/25-build-and-deploy/meta.json
- documentation/docs/30-advanced/index.md
- documentation/docs/30-advanced/meta.json
- documentation/docs/40-best-practices/index.md
- documentation/docs/40-best-practices/meta.json
- documentation/docs/50-reference/index.md
- documentation/docs/50-reference/meta.json
- documentation/docs/60-appendix/index.md
- documentation/docs/60-appendix/meta.json
- sites/kit.svelte.dev/src/lib/server/docs/index.js
Matches the `main` branch of svelte.dev to help share infrastructure across them
> chore(site): refactor meta.json to index.md

- packages/kit/test/apps/basics/test/test.js
have to wait for the navigation to finish...
> chore: fix another flaky test

- .changeset/many-hornets-appear.md
- .github/workflows/release.yml
- packages/adapter-auto/package.json
- packages/adapter-cloudflare-workers/package.json
- packages/adapter-cloudflare/package.json
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- packages/adapter-static/package.json
- packages/adapter-vercel/package.json
- packages/amp/package.json
- packages/create-svelte/package.json
- packages/enhanced-img/package.json
- packages/kit/package.json
- packages/migrate/package.json
- packages/package/package.json
We can set an environment variable for all the packages (https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools)
> chore: configure provenance env var

- .changeset/five-mangos-kneel.md
- packages/kit/package.json
to include 4.0.0-next for svelte5
---
> chore(deps): extend peer range of vite-plugin-svelte 

- .changeset/mean-horses-doubt.md
- packages/create-svelte/shared/+checkjs/package.json
- packages/create-svelte/shared/+typescript/package.json
renovate bot does not seem to update dependencies in the create-svelte template.
- https://github.com/sveltejs/kit/pull/12638
---
> chore: bump svelte-check to v4

- package.json
- pnpm-lock.yaml
remove another 100 lines from our lockfile
> chore: upgrade changesets

- .changeset/rotten-kangaroos-enjoy.md
- packages/adapter-node/package.json
- pnpm-lock.yaml
should make it compatible with deno
> chore: upgrade polka to 1.0.0-next.28

- .changeset/great-worms-think.md
- packages/create-svelte/shared/+eslint+prettier+typescript/eslint.config.js
- packages/create-svelte/shared/+eslint+typescript/eslint.config.js
Fixes https://github.com/sveltejs/kit/issues/12720
Used the `config()` helper function. An exported type can be used as well:
https://typescript-eslint.io/packages/typescript-eslint#config
```ts
// eslint.config.mjs
// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
/** @type {import('@typescript-eslint/utils').TSESLint.FlatConfig.ConfigFile} */
export default [
eslint.configs.recommended,
...tseslint.configs.recommended,
{
/*... */
},
// ...
];
```
---
> chore: update typescript-eslint configs

- .changeset/shy-hounds-wash.md
- packages/migrate/migrations/svelte-5/migrate.js
- packages/migrate/migrations/svelte-5/migrate.spec.js
> fix: use `next` versions for `svelte` and `vite-plugin-svelte`

- packages/kit/test/apps/basics/src/routes/load/server-log-search-param/+page.server.js
- packages/kit/test/apps/basics/src/routes/load/server-log-search-param/+page.svelte
- packages/kit/test/apps/basics/test/server.test.js
adds a test for https://github.com/sveltejs/kit/pull/12763 for the sake of completeness
---
> chore: add test for #12763

- .changeset/fuzzy-bats-dance.md
- packages/enhanced-img/package.json
- pnpm-lock.yaml
ref https://github.com/sveltejs/kit/issues/12686
> chore: upgrade svelte-parse-markup

- documentation/docs/25-build-and-deploy/30-adapter-auto.md
> Updating SST docs link

- .changeset/grumpy-ducks-occur.md
- packages/adapter-node/package.json
- packages/adapter-static/package.json
- packages/adapter-static/test/apps/prerendered/package.json
- packages/adapter-static/test/apps/spa/package.json
- packages/kit/package.json
- pnpm-lock.yaml
Part of ongoing work to better support Deno: https://github.com/denoland/deno/issues/17248
> chore: upgrade to sirv 3.0

- documentation/docs/40-best-practices/05-performance.md
`@sveltejs/enhanced-image` is referenced when the package is now called `@sveltejs/enhanced-img`
---
> docs: @sveltejs/enhanced-img reference

- .changeset/gold-experts-talk.md
- packages/adapter-netlify/package.json
- packages/adapter-node/package.json
- pnpm-lock.yaml
> chore: upgrade @rollup/plugin-commonjs to 28.0.1

- packages/migrate/README.md
The `svelte-5` migration now exists.
---
> docs: add svelte-5 migration

- .changeset/early-emus-pump.md
- CONTRIBUTING.md
- documentation/docs/10-getting-started/20-creating-a-project.md
- documentation/docs/10-getting-started/30-project-structure.md
- documentation/docs/25-build-and-deploy/30-adapter-auto.md
- documentation/docs/30-advanced/70-packaging.md
- documentation/docs/60-appendix/20-integrations.md
- documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md
- packages/kit/README.md
- packages/migrate/README.md
- packages/migrate/migrations/svelte-5/index.js
- packages/migrate/migrations/sveltekit-2/index.js
- packages/package/README.md
New package available at https://www.npmjs.com/package/sv
> docs: demonstrate sv migrate over prior commands

- documentation/docs/40-best-practices/05-performance.md
I think Svelte 5 is already in production.
---
> docs: remove svelte 5's preview status in performance

- documentation/docs/40-best-practices/03-auth.md
> docs: fix links

- .github/workflows/release.yml
> chore: no longer need template ssh key

- .changeset/rare-glasses-smell.md
- packages/migrate/migrations/svelte-5/index.js
- packages/migrate/migrations/svelte-5/migrate.js
Fixes #12880, relies on https://github.com/sveltejs/svelte/pull/13929
---
> fix: prefer ts in unclear migration situations if `tsconfig.json` found

- documentation/docs/20-core-concepts/20-load.md
- documentation/docs/20-core-concepts/30-form-actions.md
- documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md
A number of these have snuck in over the years. This replaces them with regular spaces.
---
> chore: replace non-breaking spaces

- .github/workflows/docs-preview-create-request.yml
- .github/workflows/docs-preview-delete-request.yml
- documentation/docs/10-getting-started/10-introduction.md
this will, in theory, result in preview deployments for PRs that change the docs
> chore: setup docs previews

- .changeset/serious-rats-jump.md
- packages/kit/src/exports/public.d.ts
- packages/kit/types/index.d.ts
> fix: update links in JSDoc

- documentation/docs/60-appendix/20-integrations.md
see the discussion in https://github.com/sveltejs/cli/issues/312
> docs: update vitePreprocess section for Svelte 5

- .prettierrc
- eslint.config.js
- packages/kit/.prettierignore
> chore: add ignores to eslint and prettier

- .github/workflows/ci.yml
This PR adds the adapters, svelte-package, and enhanced-img for publishing to pkg.pr.new
---
> chore: publish other packages to pkg.pr.new

- packages/kit/test/apps/amp/package.json
- packages/kit/test/apps/basics/package.json
- packages/kit/test/apps/dev-only/package.json
- packages/kit/test/apps/embed/package.json
- packages/kit/test/apps/no-ssr/package.json
- packages/kit/test/apps/options-2/package.json
- packages/kit/test/apps/options/package.json
- packages/kit/test/apps/writes/package.json
- packages/kit/test/build-errors/apps/prerender-entry-generator-mismatch/package.json
- packages/kit/test/build-errors/apps/prerenderable-incorrect-fragment/package.json
- packages/kit/test/build-errors/apps/prerenderable-not-prerendered/package.json
- packages/kit/test/build-errors/apps/private-dynamic-env-dynamic-import/package.json
- packages/kit/test/build-errors/apps/private-dynamic-env/package.json
- packages/kit/test/build-errors/apps/private-static-env-dynamic-import/package.json
- packages/kit/test/build-errors/apps/private-static-env/package.json
- packages/kit/test/build-errors/apps/server-only-folder-dynamic-import/package.json
- packages/kit/test/build-errors/apps/server-only-folder/package.json
- packages/kit/test/build-errors/apps/server-only-module-dynamic-import/package.json
- packages/kit/test/build-errors/apps/server-only-module/package.json
- packages/kit/test/build-errors/apps/service-worker-dynamic-public-env/package.json
- packages/kit/test/build-errors/apps/service-worker-private-env/package.json
- packages/kit/test/build-errors/apps/syntax-error/package.json
- packages/kit/test/prerendering/basics/package.json
- packages/kit/test/prerendering/options/package.json
- packages/kit/test/prerendering/paths-base/package.json
- playgrounds/basic/package.json
- pnpm-lock.yaml
one less thing depending on chokidar 3...
> chore: upgrade to svelte-check 4.1.1

- packages/kit/src/runtime/client/client.js
- packages/kit/types/index.d.ts
closes https://github.com/sveltejs/kit/issues/12863
---
> docs: reword `beforeNavigate` description so that it includes navigations to the same URL

- .changeset/angry-pumas-develop.md
- packages/adapter-node/src/index.js
```diff
- Listening on 0.0.0.0:3000
+ Listening on http://0.0.0.0:3000
```
Allows the listening on address to be clickable on the VS Code terminal.
---
> chore: update node-adapter listening address

- .changeset/flat-onions-speak.md
forgot to add a changeset for #13148
---
> chore: forgot to add changeset

- documentation/docs/20-core-concepts/50-state-management.md
Closes [#13160 ](https://github.com/sveltejs/kit/issues/13160)
> docs: fix faulty example code

- packages/kit/src/runtime/client/client.js
this extracts some stuff out of #13191 so that the diff in that PR more cleanly expresses the changes that are happening, for posterity's sake
> chore: prepare hash based routing

- packages/kit/src/exports/public.d.ts
- packages/kit/types/index.d.ts
> add since tag

- documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
Fixes the link to the Cloudflare docs on deploying a SvelteKit site.
---
> docs: fix link to Cloudflare docs

- documentation/docs/10-getting-started/10-introduction.md
- documentation/docs/40-best-practices/03-auth.md
> chore: Inconsequential change to docs to test sync

- .changeset/neat-mirrors-rush.md
- packages/package/package.json
- packages/package/src/index.js
- pnpm-lock.yaml
Closes #13380
Not sure if I should add a changeset for this, I thought it's better not to?
---
> chore: update to chokidar 4.0.3

- documentation/docs/25-build-and-deploy/90-adapter-vercel.md
fixes sveltejs/svelte.dev#1122
---
> docs: fix code block example in adapter-vercel

- documentation/docs/98-reference/54-types.md
See https://github.com/sveltejs/svelte.dev/issues/1113
I've updated it to match the latest generated `tsconfig.json` from `npx sv create`. Missing explanations from a maintainer.
---
> docs: update `tsconfig.json` explanation

- package.json
See also https://github.com/sveltejs/svelte/pull/15258 and https://github.com/sveltejs/svelte.dev/pull/1155
> chore: allow running pnpm 10

- package.json
- pnpm-lock.yaml
upgrades `eslint-plugin-n` to get a big speedup from https://github.com/eslint-community/eslint-plugin-n/issues/404
> chore: speed up linting

- documentation/docs/60-appendix/10-faq.md
a recent PR broke doc deploys, this fixes it
> chore: fix 10-faq.md

- .changeset/tame-weeks-punch.md
- packages/adapter-cloudflare-workers/package.json
- packages/adapter-cloudflare/package.json
- pnpm-lock.yaml
closes https://github.com/sveltejs/kit/pull/12452
> feat: support wrangler 4

- .changeset/shaggy-rats-laugh.md
- packages/adapter-auto/adapters.js
bumps the major versions for the Cloudflare and Netlify adapters
Still not sure if the changeset should be a patch or a major. The [last time](https://github.com/sveltejs/kit/pull/13142/files) this was done it was a major.
---
> feat: update Cloudflare and Netlify adapter major versions

- .changeset/sour-moles-heal.md
- packages/adapter-vercel/index.js
This is just #13674, but an internal branch (not a fork) so that pkg.pr.new works correctly, which I need in order to test this
> feat: `adapter-vercel` o11y

- .changeset/chilly-dancers-deliver.md
- packages/kit/src/runtime/server/data/index.js
- packages/kit/src/runtime/server/page/render.js
- packages/kit/src/runtime/server/utils.js
Fixes #13708, hopefully. I haven't tested this thoroughly. I think this was just an oversight when refactoring the serialization of page data.
---
> fix: regression when serializing server data

- documentation/docs/30-advanced/20-hooks.md
The async example of the reroute hook is missing `async`. 
---
> Update reroute async example

- packages/package/README.md
The command to create an app was mistakenly `npm sv create` in the `@sveltejs/package` readme, which is not a valid command and returns this:
```
Unknown command: "sv"
To see a list of supported npm commands, run:
npm help
```
---
> docs: fix npx sv create command

- documentation/docs/20-core-concepts/10-routing.md
- documentation/docs/25-build-and-deploy/40-adapter-node.md
- documentation/docs/25-build-and-deploy/99-writing-adapters.md
- documentation/docs/30-advanced/20-hooks.md
- packages/adapter-auto/index.js
- packages/adapter-cloudflare/test/apps/pages/package.json
- packages/kit/src/exports/public.d.ts
- packages/kit/src/exports/vite/preview/index.js
- packages/kit/src/runtime/server/endpoint.js
- packages/kit/types/index.d.ts
a few small tweaks extracted from #12973 to make that PR slightly smaller
> minor doc tweaks etc

- .changeset/heavy-roses-grab.md
- .changeset/odd-ants-sneeze.md
- packages/adapter-cloudflare/package.json
- packages/adapter-cloudflare/test/apps/pages/package.json
- packages/adapter-cloudflare/test/apps/workers/package.json
- packages/adapter-netlify/package.json
- packages/adapter-vercel/package.json
- pnpm-lock.yaml
Removes a duplicate version of esbuild from our lockfile
> chore: update wrangler

- packages/package/src/validate.js
Just fix a minor grammatical misspelling
> fix: grammar

- .github/workflows/ci.yml
We just got hit by a brownout for `windows-2019` runners. Hopefully the slowness issues have been fixed; if not we'll be hosed soon...
---
> chore: Update Windows CI to latest

- package.json
- packages/adapter-auto/package.json
- packages/adapter-netlify/package.json
- packages/adapter-netlify/tsconfig.json
- packages/adapter-node/package.json
- packages/adapter-vercel/package.json
- packages/enhanced-img/package.json
- packages/kit/package.json
- packages/kit/test/build-errors/package.json
- packages/kit/test/prerendering/basics/package.json
- packages/kit/test/prerendering/options/package.json
- packages/kit/test/prerendering/paths-base/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR performs a few maintenance tasks:
- Updates Vitest to 3.2.1 so that we no longer get errors when running type checking on the enhanced-img package.
- Downgrades pnpm to 10.11.1 to get rid of the false positive pnpm warnings
```sh
 WARN  Skip adding @playwright/test to the default catalog because it already exists as ^1.51.1. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding @playwright/test to the default catalog because it already exists as ^1.51.1. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding @playwright/test to the default catalog because it already exists as ^1.51.1. Please use `pnpm update` to update the catalogs.
 WARN  Skip adding @playwright/test to the default catalog because it already exists as ^1.51.1. Please use `pnpm update` …
```
> chore: update Vitest to 3.2.3

- packages/kit/test/ambient.d.ts
- packages/kit/test/apps/basics/test/client.test.js
- packages/kit/test/apps/basics/test/cross-platform/test.js
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/build-errors/server-only.spec.js
- packages/kit/test/build-errors/syntax-error.spec.js
- packages/kit/test/prerendering/basics/test/tests.spec.js
- packages/kit/test/types/actions.test.ts
- packages/kit/test/utils.d.ts
- packages/kit/test/utils.js
This PR gets rid of all the red lines in our Playwright tests. It also updates the Playwright utils type definitions for our SvelteKit helpers which got out of date at some point.
---
> chore: fix Playwright TypeScript errors

- .changeset/loud-eyes-beam.md
- packages/kit/src/core/sync/write_root.js
Was missing on the deepest leaf
Fixes #14011
---
> fix: add missing params property

- .changeset/warm-rats-say.md
- packages/adapter-cloudflare/index.js
- packages/adapter-cloudflare/utils.js
- packages/adapter-cloudflare/utils.spec.js
> fix: support assets-only workers in wrangler validation

- packages/kit/src/runtime/app/server/remote.js
- packages/kit/types/index.d.ts
fixes https://github.com/sveltejs/kit/discussions/13897#discussioncomment-13870177
> remote functions: await form result

- packages/kit/src/exports/public.d.ts
- packages/kit/src/runtime/app/server/remote.js
- packages/kit/src/runtime/client/remote.svelte.js
- packages/kit/src/runtime/server/remote.js
- packages/kit/src/types/internal.d.ts
- packages/kit/types/index.d.ts
makes `form` return values non-callable
> make forms non-callable

- packages/kit/src/runtime/client/remote-functions/command.svelte.js
console.log slipped in in #14170
> remove log

- .changeset/four-suns-refuse.md
- packages/kit/src/exports/public.d.ts
- packages/kit/types/index.d.ts
fix for #14048
---
- [] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.
> Add types to NavigationTarget

- documentation/docs/25-build-and-deploy/40-adapter-node.md
This PR changes one of the link protocols from http to https
---
> docs: switch to https link

- .changeset/all-days-nail.md
- packages/kit/src/exports/vite/index.js
Fixes #14069. I didn't add a test because it seems like overkill in this case
---
> fix: don't treat `$lib/server.ts` or `$lib/server_whatever.ts` as server-only modules, only `$lib/server/**`

- packages/kit/src/types/synthetic/$env+dynamic+private.md
fixes https://svelte.dev/docs/kit/$env-dynamic-private
> docs: fix quotemark

- documentation/docs/30-advanced/68-observability.md
I absolutely knew we were going to miss one of these... just wasn't sure where :laughing:
---
> chore: Correct o11y available-since date in docs

- .changeset/thin-hornets-read.md
- packages/kit/src/runtime/app/server/remote/form.js
- packages/kit/test/apps/basics/src/routes/remote/form/+page.svelte
- packages/kit/test/apps/basics/test/test.js
> fix: ensure uniqueness of `form.for(...)` across form functions

- documentation/docs/60-appendix/10-faq.md
> use standard example.com domain in docs

- documentation/docs/25-build-and-deploy/80-adapter-netlify.md
> fix(docs): replace dead link to Netlify Edge Functions docs

- documentation/docs/20-core-concepts/60-remote-functions.md
> Fix comment for Zod coercion in remote functions

- .changeset/all-tables-eat.md
- documentation/docs/20-core-concepts/60-remote-functions.md
- packages/kit/src/exports/public.d.ts
- packages/kit/src/runtime/app/server/remote/form.js
- packages/kit/test/apps/basics/src/routes/remote/form/validate/+page.svelte
- packages/kit/test/apps/basics/src/routes/remote/form/validate/form.remote.ts
- packages/kit/test/apps/basics/test/test.js
- packages/kit/test/types/remote.test.ts
- packages/kit/types/index.d.ts
Not all validation can happen via the schema, this introduces a way to do it imperatively
---
> feat: imperative form validation
