sveltejs/kit

.changeset/nasty-elephants-grab.md, packages/kit/src/core/postbuild/crawl.js, packages/kit/src/core/postbuild/crawl.spec.js, packages/kit/src/core/postbuild/fixtures/base/input.html, packages/kit/src/core/postbuild/fixtures/base/output.json, packages/kit/src/core/postbuild/fixtures/basic-srcset/output.json, packages/kit/src/core/postbuild/fixtures/ids/output.json, packages/kit/src/core/postbuild/prerender.js, packages/kit/src/utils/url.spec.js, packages/kit/test/prerendering/paths-base/src/app.html, packages/kit/test/prerendering/paths-base/src/routes/+page.svelte, packages/kit/test/prerendering/paths-base/src/routes/a/b/c/+page.svelte, packages/kit/test/prerendering/paths-base/src/routes/a/b/d/+page.svelte, packages/kit/test/prerendering/paths-base/svelte.config.js, packages/kit/test/prerendering/paths-base/test/test.js, packages/kit/types/index.d.ts
closes #8559. Note that in order to use `<base>` successfully, you must use `config.kit.paths.relative: false`, otherwise SvelteKit will attempt to load JavaScript modules relative to the base rather than to the current page.
=> respect `<base>` when crawling

.changeset/loud-ghosts-worry.md, packages/kit/src/utils/routing.js, packages/kit/src/utils/routing.spec.js
Due to multiple matching routes, exec is called for [[param1=required]]/[param2=param2]/[param3] even though we’ve provided 3 parameters which should correlate to the /[param2=param2]/[param3]/[param4] route.
The code flow was finishing with a buffer size of 0, which was incorrectly telling Kit that the route was a match. As such it wasn't attempting to parse other routes to check for a match, despite the fact there was still a required parameter that hadn't been matched.
This situation doesn’t appear to be covered under current unit tests as the tests load one route at a time. I've added a new Playwright test to cover this scenario.
Fixes https://github.com/sveltejs/kit/issues/9304
=> fix: required parameters placed after missing optional parameters are no longer skipped

.changeset/eighty-dots-watch.md, packages/kit/src/runtime/server/cookie.js
=> remove buggy cookie path detection

.changeset/strange-garlics-pump.md, packages/kit/src/utils/streaming.js, packages/kit/src/utils/streaming.spec.js
=> fix: deal with fast consecutive promise resolutions when streaming

.changeset/lemon-beers-yawn.md, packages/kit/src/exports/vite/dev/index.js
Fixes #5019
Importing CSS modules causes flash of unstyled content, as an object is returned from Vite causing it to be injected as `[object Object]` inside the style tag.
Importing with `?inline`, allows Vite to returns the CSS  as string which can be used inside the style tag.
=> Avoid FOUC when using CSS modules in dev

.changeset/itchy-jobs-leave.md, packages/adapter-netlify/README.md, packages/adapter-vercel/README.md
=> don't discourage use of `adapter-vercel`

.changeset/dirty-pianos-try.md, packages/kit/src/runtime/server/respond.js, packages/kit/test/apps/options/test/test.js
=> return 308s instead of 301s when normalising paths

.changeset/good-countries-enjoy.md, packages/kit/src/runtime/client/client.js
=> pause on debugger for full page reloads in dev

.changeset/gorgeous-dolphins-join.md, packages/kit/src/runtime/client/client.js
closes #9098. Since we're already using `beforeunload`, there's no real reason not to persist state there as well. This _does_ mean that non-Firefox browsers will persist the state twice, but... that's probably fine?
=> persist DOM state on beforeunload

.changeset/stupid-goats-retire.md, packages/kit/src/core/sync/write_types/index.js, packages/migrate/migrations/routes/utils.js, sites/kit.svelte.dev/src/lib/docs/server/index.js
=> chore: replace deprecated property access in preparation for TS 5.0

.changeset/late-berries-glow.md, packages/kit/src/core/postbuild/crawl.js, packages/kit/src/core/postbuild/fixtures/basic-srcset/input.html, packages/kit/src/core/postbuild/fixtures/basic-srcset/output.json
=> fix: #9369, newline after comma in srcset attribute cause build failure

.changeset/metal-pugs-wink.md, packages/kit/src/core/sync/write_tsconfig.js
closes #9412  
Extending multiple tsconfigs in a tsconfig would previously result in a crash, now that works here, vite also needs changes though https://github.com/vitejs/vite/issues/12380
=> Allow extending multiple other tsconfig in tsconfigs, typescript 5.0

.changeset/khaki-schools-invent.md, packages/adapter-node/src/handler.js
Fixes #9393
During gradual deployment of an app with multiple instances, it is possible to load the main page from one server and the second request for static content goes to a server that has the old code deployed on it.
The old server, with the old code, does not yet have the new file, therefore it returns 404. So far, so good.
The problem arises, that with the return of 404, it also sends cache-control header with a high max-age and immutable. The browser and intermediate CDNs cache this response as much as they can.
Therefore even after the new server gets the new app, the CDNs and the browser need to force cache clear in order to be able to get the new static files.
It would make sense that unless the response is `200`, the cache header is not sent
I have not managed to write a test …
=> fix(adapter-node): only send cache header when static resource is 200

documentation/docs/30-advanced/30-link-options.md
Tweak the wording and add additional information around `data-sveltekit-keepfocus`
- add note at the top about these options also applying to forms, so that it's not surprising when we use a form for one of the options when the section is called "link options"
- link existing focus reset docs
- remove "focus will be reset to the body" -- I think it's better just to link the existing focus reset docs
- more context on why using this on links or elements that don't exist on the new page is bad practice
=> docs: update data-sveltekit-keepfocus docs

documentation/docs/20-core-concepts/10-routing.md
=> docs: mention the types without types feature

.changeset/dull-bears-destroy.md, packages/kit/src/runtime/client/client.js
Also directly trigger native navigation for external links to prevent wrong invocation of `handleError`
closes https://github.com/sveltejs/kit/issues/9399
=> fix: don't start debugger on 404s 

.changeset/lucky-paws-work.md, packages/kit/src/runtime/client/client.js
It's quite hard to get SvelteKit into an unrecoverably broken state during dev — to the extent that I can't reliably reproduce it — but it's not impossible. learn.svelte.dev seems particularly prone to it, due to some quirk of the setup, though I've seen it happen in a normal project too.
This seems like a pretty comprehensive fix: if something causes an unexpected error, reload the page on the next HMR event. learn.svelte.dev is noticeably more reliable with this change.
=> reload after error

.changeset/weak-crews-report.md, packages/kit/types/index.d.ts
Fixes https://github.com/sveltejs/kit/issues/9483
This PR adds an additional `submitter` typing to the duplicate of `SubmitFunction` in `kit/types/index.d.ts`. The main feature was added [here](https://github.com/sveltejs/kit/pull/9425).
=> fix(kit): add `submitter` type to `SubmitFunction` input argument

.changeset/great-wasps-tan.md, packages/kit/src/runtime/server/utils.js
At present, if you make a change that results in a fallback error page loading (e.g. introducing a syntax error in a `+page.server.js`), SvelteKit doesn't recover from the error.
With this change, HMR is activated, meaning that when you fix the error the page reloads. Together with #9440, this makes debugging much more pleasant.
=> add HMR to fallback error pages in dev

.changeset/early-pigs-boil.md, packages/adapter-vercel/index.js
Follow-up to #9182 — we disable streaming mode for ISR routes, but we don't consider `config.isr` when splitting functions in the first place. This means that if you have an SSR route and an ISR route that share the same config, one of two things will happen, depending on the order in which they're encountered during build:
* the SSR route won't use streaming
* the ISR route will 'fall back' to SSR
Both are undesirable. This fixes it
=> create separate functions for ISR routes

.changeset/stupid-trains-push.md, packages/kit/src/core/sync/write_types/index.js, packages/kit/src/core/sync/write_types/index.spec.js, packages/kit/src/core/sync/write_types/test/actions/+page.server.js, packages/kit/types/index.d.ts
partially implements #7161
This PR adds stronger type definitions for `SubmitFunction` to the types genereted inside `$types.d.ts`. Unfortunately it is currently not possible to distinguish between `Success` and `Invalid` with the current `Kit` helper types. This could be implemented in a future version.
=> expose stronger typed `SubmitFunction`

.changeset/unlucky-garlics-yell.md, packages/kit/src/runtime/server/page/actions.js
When you send the wrong content type to an action, SvelteKit throws a helpful error, but it's missing the parentheses at the end:
```
Actions expect form-encoded data (received application/json;
^ Whoops
```
This PR adds it. That's all! Thanks!
=> fix: balance parentheses in error about wrong content type for action

.changeset/large-pandas-swim.md, packages/create-svelte/templates/skeletonlib/package.template.json
Apologies, there's no linked issue for this - I've just made this change in a ton of SK projects that use the lib skeleton template. IMO tests shouldn't be bundled in the distributed package. Curious if others here agree!
=> fix(create): exclude tests in package.template.json

.changeset/grumpy-years-know.md, packages/kit/src/exports/vite/index.js
closes https://github.com/sveltejs/kit/issues/9306
FYI @bmeurer
=> feat: set `sourcemapIgnoreList` to filter out non-source directories

sites/kit.svelte.dev/src/routes/home/Hero.svelte
Fixes the SvelteKit hero text on homepage. Previous PR #9607 broke it, made it unresponsive. This makes it responsive
=> fix(site): Responsive home page SvelteKit headng

sites/kit.svelte.dev/vercel.json
fixes https://github.com/sveltejs/kit/issues/9449
Utilises Vercel's trailing slash redirect https://vercel.com/docs/concepts/projects/project-configuration#false to correctly redirect `/docs/` to `/docs`.
=> fix(site): enable Vercel trailing slash redirects

.changeset/swift-ads-itch.md, packages/kit/src/exports/node/index.js, packages/kit/test/apps/basics/src/routes/endpoint-output/head-write-error/+server.js, packages/kit/test/apps/basics/test/server.test.js
=> fix: prevent unhandled exception crashes for invalid header values

documentation/docs/30-advanced/70-packaging.md
Fixes #9653. `tsconfig/jsconfig.json` reads like a file path. Changed to `(tsconfig|jsconfig).json`
=> docs: Fixing the fact that tsconfig/jsconfig.json reads like a file path on the packaging page

pnpm-lock.yaml, sites/kit.svelte.dev/package.json
4.1.1 updates the data-lsp style for text in code snippets(the underline for text elements which give TS info on hover)
Before it used a hard value, now it uses --sk-back-5, which is visible in both light and dark mode yet subtle enough
=> chore(site): update `site-kit` to 4.1.1

packages/kit/src/exports/vite/build/build_server.js, packages/kit/src/exports/vite/dev/index.js, packages/kit/types/internal.d.ts
As far as I can tell, this variable is unused. `kit.svelte.dev` works without it and all the tests pass without it
=> chore: fix TODO by removing unused variable

.changeset/shiny-eels-greet.md, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/utils.js, packages/kit/test/apps/basics/src/routes/before-navigate/prevent-navigation/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js
fixes https://github.com/sveltejs/kit/issues/9611
This is a breaking change that causes the client to ignore download links instead of treating them as an external link.
This fixes the issue of the internal `navigating` flag being incorrectly set, leading to missing subsequent `beforeNavigate()` calls.
The `navigating` flag prevents the `beforeunload` event from triggering a second round of `beforeNavigate()` callbacks when an external link is clicked. Because the external link causes the page to unload, Kit doesn't care that the `navigating` flag isn't reset to false. In our download link case, the page isn't unloaded, causing subsequent navigations to not call `beforeNavigate()`. Therefore, we should treat download and external links differently by opting out of the same logic as …
=> fix: prevent `beforeNavigate()` for download links

.changeset/modern-years-tell.md, packages/kit/src/runtime/server/page/actions.js, packages/kit/src/runtime/server/respond.js, packages/kit/test/apps/basics/src/hooks.server.js, packages/kit/test/apps/basics/src/routes/actions/redirect-in-handle/+page.server.js, packages/kit/test/apps/basics/src/routes/actions/redirect-in-handle/+page.svelte, packages/kit/test/apps/basics/test/test.js
=> fix: handle redirect thrown in handle hook in response to form action

.changeset/great-stingrays-flash.md, packages/kit/src/runtime/server/page/render.js, packages/kit/src/runtime/server/respond.js, packages/kit/test/apps/options-2/test/test.js
fixes #9341.
In #9220, we changed the logic for resolving asset paths to accommodate the `relative: true` option, and included [special handling](https://github.com/sveltejs/kit/pull/9220/files#r1120243235) for the case where you're rendering the root page when `base` is set — if the base path is `/a/b/c` and you render `/a/b/c`, then the relative path (somewhat counter-intuitively) needs to be `./c` for links to work.
Turns out that was a mistake, because the root should always end with a trailing slash — if you prerender that page, it will be output as `<output>/index.html`, and relative paths will thus be incorrectly converted to `<output>/c/...`.
The fix is to remove the special case handling, and ensure that `/a/b/c` always redirects to `/a/b/c/`. This is much simpler and more …
=> always add trailing slash to base path

.changeset/tall-bags-sparkle.md, packages/kit/src/core/config/index.spec.js, packages/kit/src/core/config/options.js, packages/kit/src/core/postbuild/prerender.js
Closes #9592 by adding a line to both prerender error handlers explaining how to suppress or customize their handling.
I wasn't sure where to add a test for this, but happy to add one if someone knows a good location.
=> feat: improve error message for `handleHttpError` and `handleMissingId`

.changeset/flat-trainers-fold.md, packages/kit/src/runtime/client/fetcher.js, packages/kit/test/apps/basics/src/routes/load/window-fetch/outside-load/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js
fixes https://github.com/sveltejs/kit/issues/7992
Only Chrome-like browsers have a short stack trace, leading to a correct fetch warning. However, Safari and Firefox both have a stack trace from the beginning of the client-side initialisation, leading to false positive warnings.
The fix is to cut off the stack trace at the point where the `load` function is invoked/mentioned. This makes the stack traces for Firefox and Safari similar to Chrome.
=> fix: prevent false positive warnings for `fetch` in Firefox and Safari

.changeset/old-teachers-shout.md, packages/kit/src/core/adapt/builder.js
fixes #9463
bug was introduced in #8740
I see this as a bug fix, I don't think anyone relies on `generateManifest` generating a manifest that is only usable for SvelteKit which includes prerendered routes.
=> fix: don't include prerendered routes in default generateManifest

pnpm-lock.yaml, sites/kit.svelte.dev/package.json, sites/kit.svelte.dev/src/routes/home/Deployment.svelte, sites/kit.svelte.dev/src/routes/home/Hero.svelte, sites/kit.svelte.dev/src/routes/home/Try.svelte, sites/kit.svelte.dev/tsconfig.json
Updates site-kit to 5.0
Advantage: Smaller tokens.css. Try.svelte becomes smaller
Breaking: No more `/theme` export
=> feat: Bump site-kit to 5.0

packages/kit/src/exports/vite/dev/index.js, packages/kit/src/exports/vite/index.js, packages/kit/src/runtime/server/page/render.js, packages/kit/types/index.d.ts, packages/kit/types/internal.d.ts
A first step for https://github.com/sveltejs/kit/issues/3882. It's easier to deal with `imports`, `stylesheets`, and `fonts` than `app.imports`, `app.stylesheets`, `app.fonts`, `start.imports`, `start.stylesheets`, and `start.fonts`. This will become more true when we potentially have only a single entry point, so it makes the interface more generic and easier to deal with in that case.
=> chore: refactor client build data

packages/kit/src/runtime/client/client.js
While working on #9605, I realised that the `update(...)` function in `client.js` is really quite badly designed. It's used for both navigations and invalidations, but it spends so much time deciding which of those things it's dealing with that it really shouldn't be a single function.
In fact, in the invalidation case almost none of the logic is actually used. We can move that stuff into the `invalidate` function, and inline the entirety of `update` into `navigate`. This means less indirection, and easier-to-follow code.
This change will make it easier to add a `complete` promise to the `Navigation` interface.
No tests or changeset necessary.
=> Refactor `navigate`

pnpm-lock.yaml, sites/kit.svelte.dev/package.json, sites/kit.svelte.dev/src/routes/home/Hero.svelte
Fixes a couple a11y issues on the SvelteKit site - see https://github.com/sveltejs/site-kit/pull/107 for details on the site-kit a11y fixes
Fixes:
- SvelteKit logo on homepage was not properly labelled 
- Dark mode toggle was incorrectly nested inside a `<ul>` (site-kit fix)
- Dark mode toggle was not labelled properly (site-kit fix)
- Mobile navigation did not have background set (site-kit fix)
=> fix(site): give logo image a label and bump site-kit

pnpm-lock.yaml, sites/kit.svelte.dev/package.json, sites/kit.svelte.dev/src/lib/Image.svelte, sites/kit.svelte.dev/src/routes/home/Hero.svelte, sites/kit.svelte.dev/src/routes/home/Showcase.svelte, sites/kit.svelte.dev/vite.config.js
This demonstrates a bit better what an `Image.svelte` might look like outside of this project and is also generally cleaner and less code
The `vite-imagetools` setup is still a bit complicated, but I have an idea to simplify that quite a bit: https://github.com/JonasKruckenberg/imagetools/issues/536
=> chore: cleanup image component

.changeset/flat-planes-kneel.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/package.json, packages/kit/test/apps/basics/src/routes/routing/hashes/a/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js, packages/kit/test/apps/basics/test/cross-platform/test.js
fixes https://github.com/sveltejs/kit/issues/9546
Checks for the `replacestate` attribute when clicking on a hash link.
=> fix: correctly replace state when using `data-sveltekit-replacestate` with a hash link

package.json, packages/create-svelte/package.json, packages/kit/package.json, pnpm-lock.yaml
pinned to 1.30.0. newer versions fail on firefox
=> chore: upgrade playwright to 1.30.0

.changeset/eighty-yaks-thank.md, .changeset/quiet-turkeys-occur.md, packages/adapter-cloudflare-workers/package.json, packages/adapter-cloudflare/package.json, packages/adapter-netlify/package.json, packages/adapter-node/package.json, packages/adapter-static/package.json, packages/adapter-vercel/package.json, packages/kit/package.json, pnpm-lock.yaml
fixes https://github.com/sveltejs/kit/issues/9549
fixes https://github.com/sveltejs/kit/issues/9427
=> chore: update dependencies

.changeset/tender-cows-travel.md, packages/kit/src/runtime/server/index.js
ref #9785 
People may have custom errors without a stack and logging just the stack as a string misses out on some pretty terminal formatting from node, along with stuff like `Error.cause`.
=> fix: log whole error object in default handleError

.changeset/weak-poets-return.md, packages/create-svelte/shared/+eslint+prettier+typescript/.eslintrc.cjs, packages/create-svelte/shared/+eslint+typescript/.eslintrc.cjs
close: https://github.com/sveltejs/kit/pull/9749#issuecomment-1526868297
I tested with `create-svelte version 4.1.0`, but I didn't get error even without `ignorePatterns: ['*.cjs']`.
I think kit users can add this config if needed.
=> chore: remove `ignorePatterns: ['*.cjs']` from template `.eslintrc.cjs`

.changeset/perfect-walls-mix.md, packages/kit/src/exports/vite/dev/index.js
As noted on discord, in dev mode the hydration script inserted into pages is rendered as
`import("./D:\\some\\path\\kit\\sites\\kit.svelte.dev\\.svelte-kit/generated/client/app.js")`
which works for our current intents and purposes, hence why this is marked as a chore instead of a fix, but it just looks plain weird and might confuse users.
This PR makes it so that these paths have correct facing slashes and the /@fs/ prefix on both Linux and Windows.
=> chore: fix path to app script on windows

.changeset/wet-maps-hug.md, packages/kit/src/exports/hooks/sequence.js, packages/kit/src/exports/hooks/sequence.spec.js, packages/kit/types/ambient.d.ts
preload and filterSerializedResponseHeaders
fixes #8061
=> fix: handle all options in sequence function

.changeset/tame-tigers-shout.md, packages/kit/src/runtime/app/forms.js, packages/kit/src/runtime/app/navigation.js, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/singletons.js, packages/kit/src/runtime/client/types.d.ts
fixes #7257
Testing it would require creating a new project I think, and even then it likely wouldn't be deterministic so no tests for this one.
=> fix: make $app/navigation more resilient to bundler reordering

packages/kit/types/index.d.ts, sites/kit.svelte.dev/scripts/types/index.js
current: 
fixed (simply changing the docs isn't sufficient, because `// @errors: 7031` then becomes visible):
=> only inject artificial error annotation in js blocks

.changeset/wise-toes-poke.md, packages/kit/src/exports/vite/index.js
fixes #9843 
This ensures there is a key for these files in the manifest. Surely there has got to be a better way than this but just leaving it here in case the problems are more widespread and needs a fix overnight. Slightly less efficient than not having these entry points but still beats what we had before.
=> fix: file not found in manifest during build

.changeset/tough-masks-judge.md, packages/kit/src/runtime/client/client.js
As of #8466, we wait for a `setTimeout` to complete before navigation can finish. This causes a flash between the page being updated and a subsequent `snapshot.restore(...)`, which feels somewhat janky (scroll positions aren't immediately recovered, etc).
I'm honestly not sure if the tests will pass on all browsers if we just do the `setTimeout` without awaiting its completion, but opening this PR is the easiest way to find out.
=> reset focus synchronously

.changeset/nine-scissors-boil.md, packages/create-svelte/templates/skeletonlib/src/app.html
Closes #9859 
I couldn't immediately think of a reason we weren't doing this, so I just went ahead and added it. If there's a legit issue with adding it, we can just close this and the associated issue.
=> fix: Preload in lib template

.changeset/shy-pears-invent.md, packages/kit/src/runtime/client/client.js
This shouldn't have any effect on users I think. But it gets rid of some flakiness in our tests.
=> fix/chore: only skip hydration with vite overlay if current page is an error

.changeset/olive-dogs-bathe.md, packages/kit/src/runtime/server/cookie.js, packages/kit/src/runtime/server/cookie.spec.js, packages/kit/src/runtime/server/fetch.js, packages/kit/src/runtime/server/respond.js
Closes #9901 
Bypasses setting Kit defaults on cookies parsed from fetch response headers. To illustrate what the problem was:
- Set a cookie in `+server.ts`: `cookies.set('foo', 'bar', { httpOnly: false })`
- `fetch` this endpoint from `+page.server.ts`
- As part of `fetch`, parse the cookies from the headers
- `httpOnly` isn't set (because `false === unset`)
- Adding this cookie to the cookies causes the default `httpOnly: true` to be added
The better solution here is not to apply defaults to cookies we parse from fetch response headers. _If_ these cookies were set through `cookies.set` in a `+server.ts` endpoint, we've already set the defaults, and if they're not, we shouldn't touch them anyway.
=> fix: Don't set defaults when parsing cookies from headers

packages/create-svelte/test/check.js
This targets PR #9910. Has some nice speed gains locally but need to test that it doesn't misbehave on CI.
=> #9910 with concurrency

.changeset/eleven-ravens-turn.md, packages/kit/src/exports/vite/dev/index.js, packages/kit/test/apps/basics/src/routes/css/+page.svelte, packages/kit/test/apps/basics/src/routes/css/_manual.css, packages/kit/test/apps/basics/test/cross-platform/test.js
fixes #9924
I pulled it out of one the vite tests but the `?direct` option doesn't seem well documented. I'll add tests and changesets after a resolution on this.
=> fix: avoid inlining raw/url CSS imports

.changeset/hot-actors-hope.md, packages/kit/src/utils/fork.js
use `workers` instead of `child_process`
related:
https://github.com/denoland/deno/issues/17248
@benmccann would you be able to review this PR?
=> feat: prerender & analyse in worker rather than subprocess to support Deno

packages/kit/src/utils/fork.js
#9919 and #9899 don't work in combination, because Vitest defaults to running everything in a worker thread (https://github.com/vitest-dev/vitest/issues/2882), causing `isMainThread` to have the wrong value.
The easiest way to fix this is to use the previous mechanism for detecting whether we're in the 'main' thread or not — an environment variable that we control.
=> avoid using `isMainThread`, since it interacts poorly with vitest

.changeset/odd-crews-own.md, packages/kit/src/runtime/app/forms.js, packages/kit/test/apps/basics/src/routes/actions/enhance/old-property-access/+page.server.js, packages/kit/test/apps/basics/src/routes/actions/enhance/old-property-access/+page.svelte, packages/kit/test/apps/basics/test/test.js, packages/kit/test/apps/dev-only/package.json, packages/kit/types/ambient.d.ts
Closes #9845.
Adds a deprecation warning when accessing `data` and `form` in both the `submit` argument to `enhance` _and_ the callback returned from that `submit` argument.
=> feat: unshadow `form` and `data` in `enhance`

.changeset/brave-peaches-buy.md, packages/adapter-cloudflare-workers/index.js
Copies WASM files in Cloudflare instead of trying to load them.
Related to #9909
=> fix: Set loader: { '.wasm': 'copy' } in esbuild config in `adapter-cloudflare-workers`

.changeset/fast-dancers-grab.md, documentation/docs/25-build-and-deploy/90-adapter-vercel.md, packages/adapter-vercel/index.d.ts, packages/adapter-vercel/index.js
Until today, it was necessary to specify which environment variables were needed inside a Vercel edge function, unless it could determine them statically (by detecting use of `process.env.<SOMETHING>`). That restriction has been removed, which means `$env/dynamic/private` and `$env/dynamic/public` will work the same on Vercel as on other platforms.
Marked this as a breaking change, since projects that currently use `envVarsInUse` will experience typechecking errors if they've set it up correctly.
=> remove `envVarsInUse`

.changeset/olive-rings-eat.md, packages/adapter-vercel/index.js
Copies WASM files on Vercel instead of trying to load them.
Related to https://github.com/sveltejs/kit/pull/9909, fixes #9930
=> fix: Set `loader: { '.wasm': 'copy' }` in esbuild config in `adapter-vercel`

.changeset/tidy-worms-reflect.md, packages/adapter-cloudflare/src/worker.js
This PR aims to implement more defensive caching behavior as proposed in #9884.
CC @0x221A
=> only cache response if response has cache-control header

.changeset/shaggy-moons-sort.md, documentation/docs/20-core-concepts/20-load.md, packages/kit/src/core/config/index.spec.js, packages/kit/src/core/config/options.js, packages/kit/src/core/sync/write_server.js, packages/kit/src/runtime/server/data/index.js, packages/kit/src/runtime/server/page/index.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/src/runtime/server/page/respond_with_error.js, packages/kit/test/apps/basics/test/client.test.js, packages/kit/test/apps/options/source/pages/server-fetch-invalidate/+page.server.js, packages/kit/test/apps/options/source/pages/server-fetch-invalidate/+page.svelte, packages/kit/test/apps/options/source/pages/server-fetch-invalidate/count.json/+server.js, packages/kit/test/apps/options/svelte.config.js, packages/kit/test/apps/options/test/test.js, packages/kit/test/prerendering/basics/test/tests.spec.js, packages/kit/types/index.d.ts, packages/kit/types/internal.d.ts
Closes #9803. This is a breaking change for security purposes.
This PR prevents server `load` function from implicitly depending on URLs passed to `fetch`. This is because dependencies from server `load` functions have to be sent to the client in order to be invalidated, which can leak secrets (if they're in the search params, for example).
If you understand the risk and want to keep the old behavior, you can set `config.kit.dangerZone.trackServerFetchesPotentiallyExposingSecrets` to `true`.
TODO:
=> security: Stop automatically adding URLs from server-side `load` `fetch` calls to dependencies

documentation/docs/10-getting-started/10-introduction.md
I noticed that this heading is pretty long and wraps in the righthand menu bar. Seems like it'd be nice to make it a bit shorter
=> docs: shorten heading

renovate.json
The previous `packageRule` only matches a criteria, but doesn't specify what to do with it. I've updated the intent so that Vite majors will not be bumped by Renovate, using `"enabled": false`.
=> chore: prevent renovate bump vite major

.changeset/afraid-bikes-count.md, packages/adapter-cloudflare/ambient.d.ts, packages/adapter-cloudflare/src/worker.js
Cloudflare provides a CF object on the incoming Request ([docs](https://developers.cloudflare.com/workers/runtime-apis/request/#incomingrequestcfproperties))
The CF object contains geolocation info similar to Vercel's X-Vercel-IP-*.
Since it is specific to Cloudflare, it is preferable to add it to the platform property.
Without this CF object, it is currently not possible to get the user location (edge function location)
It will also close this issue https://github.com/sveltejs/kit/issues/5447
=> adds cloudflare cf object to platform property

sites/kit.svelte.dev/src/lib/docs/server/index.js
es2022 is used everywhere else in the codebase. We should be consistent
=> docs: use es2022 for shiki

.changeset/serious-bulldogs-beam.md, packages/kit/src/runtime/client/singletons.js, packages/kit/src/runtime/client/utils.js
=> fix: avoid creating update check timer on the server

.changeset/purple-books-guess.md, packages/kit/src/exports/public.d.ts
borderline whether this needs a changeset, but since it affects the inline documentation on hover i figured we may as well. supersedes #10036
=> fix preload inline docs

.changeset/cool-snakes-join.md, packages/kit/src/runtime/client/client.js
Fixes #8725.
This PR fixes an outstanding issue with routing hash links in Firefox. Specifically, clicking a link that contains as hash and where the link is the same as the current page URL, Firefox clears the history `state`, causing browser navigation to fail thereafter. In order to tackle this, we need to detect where the URL for a hash link is the same and manually prevent any client-side routing to take place. Instead we just apply the same scrolling heuristics – fixing the issue in FF.
=> fix: prevent history change when clicking same hash link

.changeset/tricky-laws-camp.md, documentation/docs/30-advanced/30-link-options.md, packages/kit/src/runtime/client/utils.js
Closes #9396
Requires [this](https://github.com/sveltejs/svelte/blob/3bc791bcba97f0810165c7a2e215563993a0989b/elements/index.d.ts#L554) and [this](https://github.com/sveltejs/kit/blob/9d8376f22d0d8db42327ce422ccb44d32cc91c04/documentation/docs/30-advanced/30-link-options.md?plain=1#L125) to be updated if the SvelteKit maintainers are okay with merging this.
=> feat: allow link options to be set to true and false

.changeset/nervous-balloons-speak.md, packages/adapter-vercel/index.js
We were `continue`-ing an inner loop when we intended to `continue` an outer loop.
Closes #10071
=> fix: Stop warning users that crons don't match paths when they actually do

.changeset/new-peaches-count.md, documentation/docs/20-core-concepts/30-form-actions.md, packages/kit/src/utils/exports.js, packages/kit/src/utils/exports.spec.js
~Found out we can export `actions` in a layout file but it isn't mentioned anywhere in the docs.~
I don't think we're suppose to export actions from a layout file. https://github.com/sveltejs/kit/pull/10046#issuecomment-1565286897
This PR changes the list of valid exports to disallow the `actions` export from a `+layout.server` file (matching the language tools behaviour).
=> fix: disallow exporting `actions` from a `+layout.server` file

.changeset/rich-candles-wait.md, packages/kit/src/core/config/default-error.html
The CSS rule `body { height: 100vh }` on the default error-page will cause vertical scrollbars if the default body-margin isn't removed.
I didn't include a changelog because it is such a minor change. (But I can add one if you want.)
Open `@sveltejs/kit/src/core/config/default-error.html` and verify that there are no vertical scrollbars.
=> fix: remove scrollbars on default error page

.changeset/strange-lizards-drive.md, packages/kit/src/utils/routing.js, packages/kit/src/utils/routing.spec.js
I found that since version 1.3.6 a matcher on a rest parameter is not called anymore if an optional parameter before it is empty. I'm using the optional for localization and the following rest parameter has a matcher.
Example route:
`[[locale=locale]]/[...rest=page]`
For `/en/test`, the `page` matcher will be called with param `test`.
For `/test`, the `page` matcher was not called since version 1.3.6.
=> fix: rest matcher skipped if optional is empty

.changeset/tricky-bikes-tan.md, packages/kit/src/runtime/server/page/load_data.js, packages/kit/test/apps/basics/test/test.js
Fixes compatibility with libraries that call the fetch API as `fetch(new Request(...someParams))` without an `init` argument
One of these libraries is https://github.com/sindresorhus/ky (https://github.com/sindresorhus/ky/blob/main/source/utils/timeout.ts)
=> fix: fetch doesn't respect headers from 1st arg if its type is Request

.changeset/chilly-gorillas-switch.md, packages/kit/package.json, packages/kit/src/core/adapt/builder.js, packages/kit/src/core/sync/create_manifest_data/index.js, packages/kit/src/core/utils.js, pnpm-lock.yaml
This change makes kit a bit smaller so that learn.svelte.dev will load just a bit faster. Removes 3 deps weighing in at a total of 41k
I was surprised to see `tiny-glob` as a dependency because I thought removed all glob deps in https://github.com/sveltejs/kit/pull/2430, but maybe we missed one or it got added back
=> chore: remove tiny-glob dependency

.changeset/tiny-insects-repeat.md, documentation/docs/30-advanced/70-packaging.md, packages/migrate/migrations/package/migrate_pkg.js, packages/migrate/migrations/package/migrate_pkg.spec.js
The root import should be named `index.d.ts` rather than `index`. This little typo has lead to [a](https://github.com/skeletonlabs/skeleton/issues/1581) [whole](https://github.com/melt-ui/melt-ui/blob/fa4c5ff9c78094fc342cdbdb9d20fd87b8502f12/package.json#LL40C4-L40C4) [lot](https://github.com/grail-ui/grail-ui/blob/619274bcd525e9df0c06c59107166e3ce0b61b07/packages/grail-ui/package.json#L227) [of](https://github.com/ciscoheat/sveltekit-superforms/blob/0dd821ec6cb16694a52a5548a41c6a523b0a1607/package.json#LL70C6-L70C7) svelte packages adding `index` to their `typesVersions` map, causing them all to have incorrect auto-import paths. 
Here's a quick example if you've never experienced this before: 
In all of these cases, `/index` is appended to the end of the import path. 
While having to …
=> docs: Fixed root import name for `typeVersions`

.changeset/strange-cameras-work.md, packages/package/package.json
Cannot update a Svelte library to Svelte v4 due to peer-dependency issue.
```shell
npx svelte-migrate svelte-4
npm install
```
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @sveltejs/package@2.0.2
npm ERR! Found: svelte@4.0.0
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^3.44.0" from @sveltejs/package@2.0.2
npm ERR! node_modules/@sveltejs/package
npm ERR!   dev @sveltejs/package@"^2.0.0" from the root project
```
Hopefully this fixes the problem?
```diff
{
"name": "@sveltejs/package",
"peerDependencies": {
-   "svelte": "^3.44.0"
+   "svelte": "^3.44.0 || ^4.0.0"
}
}
```
---
=> chore: bump svelte peer-dependency

.changeset/proud-cobras-rhyme.md, packages/kit/src/runtime/app/forms.js, packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte, packages/kit/test/apps/basics/test/test.js
fixes https://github.com/sveltejs/kit/issues/10092
Allows the submit event to go through (to close the dialog) if the form method is set to dialog.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#usage_notes
=> fix: correctly close dialog when using enhanced forms

documentation/docs/20-core-concepts/50-state-management.md
This closes https://github.com/sveltejs/kit/issues/8282 (or at least clarifies it).
Also mentioned here: https://github.com/sveltejs/svelte/pull/8605#issuecomment-1568965421.
After spending half a workday trying to make sense of what I thought was a bug on my end, I hope this prevents others from going through the same ordeal.
=> docs: Clarify the impact of updating contextual store values in SSR

.changeset/metal-toes-talk.md, packages/kit/src/exports/index.js, packages/kit/src/exports/index.spec.js
fixes https://github.com/sveltejs/kit/issues/10140,
rest params can be empty according to https://kit.svelte.dev/docs/advanced-routing#rest-parameters
Although @MrTango, your reproduction will continue to not work because you are supplying `slug` instead of `path`
=> fix: allow rest params to be empty in resolvePath

.changeset/flat-berries-stare.md, packages/migrate/migrations/svelte-4/index.js
For some reason {folders.value.join(',')} as part of the glob doesn't work and returns less files fixes #10228
=> fix: ensure glob finds all files in folders

documentation/docs/60-appendix/30-glossary.md
Only fixes a small typo in the documentation
=> fix typo in 30-glossary.md

.changeset/tough-weeks-join.md, packages/kit/src/exports/public.d.ts
Closes #10237
This makes it clear in the docs that `$navigating.type` is only 'form' when a `<form method="GET">` has been submitted, not for POSTs.
Added a patch changeset since #10037 did for a similar change
=> docs: specify that the 'form' navigation type only applies to method="GET"

documentation/docs/25-build-and-deploy/50-adapter-static.md
Closes #10248
There was some confusion over whether `trailingSlash` should be set in the config. We already link to the page options documentation, this also specifies "root layout" as suggested in https://github.com/sveltejs/kit/issues/10248#issuecomment-1610124698.
=> docs: specify trailingSlash should be set in root layout

documentation/docs/10-getting-started/40-web-standards.md
Add an example to the documentation for setting an outgoing response header, earlier on in the documentation, as it is mentioned in the prose right before.
Reading the existing documentation leads to the idea that you might be able to do something like `event.response.headers.set` but `setHeaders` isn't mentioned until later.
I think it would be an improvement to show the example earlier than later, but I'm torn between the current PR and something more like:
```js
// create a json response
const response = json({
// retrieve a specific header
userAgent: event.request.headers.get('user-agent')
});
// set a custom header on the response
response.headers.set('x-custom-header', 'potato');
return response;
```
=> docs: add example for setting outgoing header

.github/workflows/release.yml, package.json
`sveltejs/svelte` calls `changeset version`. I'm not sure why https://github.com/sveltejs/kit/pull/9969 omitted that
=> chore: align changesets setup with svelte core

.changeset/funny-brooms-fold.md, packages/adapter-node/src/handler.js
This fixes #10284 by moving the check for the presence of the header specified in `ADDRESS_HEADER` inside the `getClientAddress` function. The old behavior is that non-prerendered requests without the appropriate header will instantly crash the server. The new behavior is that `getClientAddress()` will throw an exception, like with the other checks.
=> fix: do not crash server if specified `ADDRESS_HEADER` is missing from a request

.changeset/few-llamas-raise.md, packages/adapter-node/ambient.d.ts, packages/adapter-node/index.d.ts, packages/adapter-node/index.js, packages/adapter-node/package.json, packages/adapter-node/rollup.config.js, packages/adapter-node/src/env.js, packages/adapter-node/src/handler.js, packages/adapter-node/src/index.js, packages/adapter-node/src/shims.js, pnpm-lock.yaml
Reverts sveltejs/kit#10041 which broke builds because of https://github.com/rollup/rollup/issues/4708
=> Revert "chore: remove build step for adapter node"

.changeset/violet-dryers-nail.md, packages/kit/src/exports/vite/index.js
Even after https://github.com/sveltejs/svelte/pull/8868 is merged this is still a bit better for performance in the case that you're not using relative paths.
=> perf: only have Vite generate relative paths when required

.changeset/shy-colts-sniff.md, packages/kit/src/exports/vite/preview/index.js
=> feat: better error message for preview if build output doesn't exist

.changeset/famous-points-complain.md, packages/package/package.json, packages/package/src/config.js, packages/package/src/typescript.js, packages/package/test/fixtures/javascript/expected/Test.svelte.d.ts, packages/package/test/fixtures/javascript/expected/Test2.svelte.d.ts, packages/package/test/fixtures/javascript/expected/internal/Test.svelte.d.ts, packages/package/test/fixtures/resolve-alias/expected/Test.svelte.d.ts, packages/package/test/fixtures/svelte-3-types/expected/Test.svelte, packages/package/test/fixtures/svelte-3-types/expected/Test.svelte.d.ts, packages/package/test/fixtures/svelte-3-types/expected/index.d.ts, packages/package/test/fixtures/svelte-3-types/expected/index.js, packages/package/test/fixtures/svelte-3-types/package.json, packages/package/test/fixtures/svelte-3-types/src/lib/Test.svelte, packages/package/test/fixtures/svelte-3-types/src/lib/index.ts, packages/package/test/fixtures/svelte-3-types/svelte.config.js, packages/package/test/fixtures/svelte-3-types/tsconfig.json, packages/package/test/fixtures/svelte-kit/expected/Test.svelte.d.ts, packages/package/test/fixtures/typescript/expected/Plain.svelte.d.ts, packages/package/test/fixtures/typescript/expected/Test2.svelte.d.ts, packages/package/test/index.js, packages/package/test/watch/expected/Test.svelte.d.ts, pnpm-lock.yaml
When the (peer)dependency states that only Svelte 4 is allowed, invoke the dts generation script with the Svelte 4 shims instead of the Svelte 3 shims. The noticable difference is that then SvelteComponent instead of the deprecated SvelteComponentTyped will be used to declare the component typings. closes #10223
=> feat: use Svelte 4 typings when packaging if dependencies allow it

.changeset/strange-colts-work.md, packages/create-svelte/templates/skeleton/src/lib/index.ts
people keep getting confused that the alias is not available, so make it available from the start by creating the lib folder in the skeleton template, too
=> fix: create lib folder in skeleton project

.changeset/violet-pans-scream.md, packages/kit/src/runtime/server/respond.js, packages/kit/test/apps/basics/src/routes/immutable-headers/+page.js, packages/kit/test/apps/basics/src/routes/immutable-headers/+server.js, packages/kit/test/apps/basics/test/server.test.js
Fixes #10366, related to #10030.
According to the `fetch()`-specification, a header can have an `immutable`-guard which will throw a `TypeError` if the header is changed:
https://fetch.spec.whatwg.org/#headers-class
When using `fetch()`, the spec requires the response header to be `immutable` (see step 12/4):
https://fetch.spec.whatwg.org/#fetch-method
This is implemented in undici (used by Node.js for native fetch() under the hood):
https://github.com/nodejs/undici/blob/22bdbd8c7820035276b4e876daccef513c29f5c4/lib/fetch/headers.js#L234-L239
Since PR https://github.com/sveltejs/kit/pull/9993, a `TypeError` is thrown when using native `fetch()` because SvelteKit is trying to change the header from the fetch-response-object.
=> fix: don't fail on immutable headers when using native fetch

documentation/docs/20-core-concepts/20-load.md
I ran into this on NGINX and spent quite a bit of time trying to find a solution. Since the important comment about streaming was not obvious.
Is the most common way to run applications on the Node server. Maybe we should add an additional description by solving this issue with NGINX on the [Troubleshooting](https://kit.svelte.dev/docs/adapter-node#troubleshooting) section on Node servers docs?
With NGINX it's will work by adding special header:
```js
export async function load({ setHeaders }) {
setHeaders({
'X-Accel-Buffering': 'no'
});
...
}
```  
Related issue: https://github.com/sveltejs/kit/issues/9534#issuecomment-1592802223
---
=> docs: clarify cases where streaming don't work

.changeset/funny-items-deny.md, packages/kit/src/exports/vite/index.js, packages/kit/test/apps/basics/test/client.test.js
fixes https://github.com/sveltejs/kit/issues/10358
fixes https://github.com/sveltejs/kit/issues/10379
~This PR disables [Vite's module preload](https://vitejs.dev/config/build-options.html#build-modulepreload) for JS files only (Vite still injects CSS) which adds the preloads on [startup](https://github.com/vitejs/vite/blob/1292ad08a06e2ae8c44307797ba533f64a602759/packages/vite/src/node/plugins/importAnalysisBuild.ts#L121-L128) in addition to the preloads already [added by Kit](https://github.com/sveltejs/kit/blob/b251b235b321b9c75236429cc3a1ac2415475775/packages/kit/src/runtime/server/page/render.js#L240). I'm not currently aware of any side-effects disabling this may have so this PR might be somewhat naive.~
This PR matches the Vite base path setting …
=> fix: prevent duplicate `<link>` module preloads

packages/migrate/README.md
Minor DX nit: I often look up a package on NPM for the link to the Changelog. Other Svelte(Kit) packages already do this (e.g., `@sveltejs/kit`, `@sveltejs/package`).
=> docs(migrate): add link to changelog

documentation/faq/60-read-package-json.md
We should encourage usage of `node:`
=> docs: use `node:` prefix in example

.changeset/selfish-walls-rhyme.md, packages/kit/src/core/adapt/builder.js, packages/kit/src/exports/vite/index.js
fixes https://github.com/sveltejs/kit/issues/9961
This moves the server assets copying to client assets closer to the `vite build` process instead of as part of the adapter process. This ensures server assets are always included in `.svelte-kit/output/client` so that `vite preview` serves them correctly.
=> fix: make server assets accessible during `vite preview`

sites/kit.svelte.dev/src/app.html
=> site: fix copy button alignment

.changeset/shy-turtles-fail.md, packages/kit/src/exports/index.js
Tiny update to `redirect` to allow passing URL objects as is:
```js
const location = new URL(`https://${site}/route`);
location.searchParams.set('param1', env.PUBLIC_THING);
throw redirect(307, location); // instead of location.href
```
=>  feat: accept `URL` in `redirect`

.changeset/eighty-cats-wave.md, packages/adapter-cloudflare/index.js, packages/kit/src/exports/public.d.ts
fixes https://github.com/sveltejs/kit/issues/10290
Correctly includes the `base` path config setting when resolving the path to the `_app` directory.
=> fix: account for `config.kit.paths.base` when building with `adapter-cloudflare`

.changeset/real-otters-report.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/client/client.js
To exclude a member of string literal union type, `Exclude` utility type should be used instead of `Omit`. Using `Omit` turns the union type into just `string`
=> fix: the type of Navigation.type

.changeset/brave-paws-cheer.md, packages/kit/src/core/sync/create_manifest_data/index.js, packages/kit/src/core/sync/write_client_manifest.js, packages/kit/src/core/sync/write_server.js
closes https://github.com/sveltejs/kit/issues/10528
Outputs a terminal warning if a route filename is missing a `+` or if the default hooks filename (`src/hooks.server`) mistakenly has a `+` prefix.
=> feat: add warning for possible route filename typos

documentation/docs/60-appendix/05-integrations.md
I was surprised this wasn't already on the integrations page
=> docs: mention that you can use Vite plugins

.changeset/seven-poems-invite.md, packages/package/src/index.js, packages/package/test/index.js, packages/package/test/watch/expected/post-error.svelte
=> fix: prevent crash on errors in watch mode

packages/kit/package.json, pnpm-lock.yaml
https://github.com/sveltejs/kit/pull/10641 was failing because the original 0.2.0 release of `dts-buddy` had a bug. This uses 0.2.4 so passes the CI
=> chore: upgrade to dts-buddy 0.2.4

.changeset/weak-vans-change.md, packages/kit/src/runtime/client/client.js
* https://github.com/sveltejs/kit/issues/9542#issuecomment-1682306310
* https://github.com/getsentry/sentry-javascript/issues/8818
* https://github.com/getsentry/sentry-javascript/issues/8610
Our Sentry SvelteKit SDK exposes `wrap(Server)LoadWithSentry` functions that users can manually or with the help of our VIte plugin, automatically wrap around their `load` functions. In these functions we access the load event's `route.id` value to create a span that tracks the duration of a `load` function and what happens inside it (e.g. fetch calls).
This is currently problematic because SvelteKit internally tracks accesses to `route.id` by [setting a getter (client side)](https://github.com/sveltejs/kit/blob/32afba695088b946aefe96da75b36de9b0667fbe/packages/kit/src/runtime/client/client.js#L452-L4 …
=> fix: use Proxy to track usage of client-side load `event.route`

documentation/docs/20-core-concepts/20-load.md
As a new Svelte / JS developer, the existing warning "Make sure you're not catching the thrown redirect" wasn't clear enough for me to understand that "catching" meant an try/catch block.
This is an attempt to be more explicit and to hopefully help other junior developers.
=> docs: clarify why not to throw a redirect within a try/catch

documentation/docs/20-core-concepts/30-form-actions.md
The Type for this section is invalid in most typescript configurations since there really is no way of typing `this` for the event. So, Typescript users  may get unnecessarily frustrated copying this code.
Update docs section to use currentTarget which  will make this docs section valid in typescript code.
As for the actual style of the fix I tried to keep it simple though it is kindof ugly with the chaining. So, please make an edit if you have a solution that more fits the style of the docs
I came across this while implementing something similar in my own code. I used this typing and it worked.
=> docs: fix type for form action example

packages/adapter-netlify/package.json, packages/adapter-node/package.json, packages/kit/test/apps/basics/package.json, packages/kit/test/apps/writes/package.json, pnpm-lock.yaml
This removes `rimraf` as a devdep from several packages. This also lets us drop 17 other transitive dependencies. No user-visible changes, and no changeset.
=> chore: remove rimraf devDependency

.changeset/flat-bugs-joke.md, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/runtime/server/page/render.js, packages/kit/src/utils/url.js
Fixes https://github.com/sveltejs/kit/issues/10657
=> fix: allow calling `fetch` for any scheme

.changeset/happy-pots-protect.md, packages/create-svelte/templates/default/.npmrc, packages/create-svelte/templates/skeleton/.npmrc, packages/create-svelte/templates/skeletonlib/.npmrc
In pnpm [v8.7.0](https://github.com/pnpm/pnpm/releases/tag/v8.7.0), the `resolution-mode` is now set to `highest` by default.
Thus, I believe it is possible to remove the settings previously made in [this PR](https://github.com/sveltejs/kit/pull/9781)
=> chore: remove `resolution-mode=highest` in template `.npmrc`

.changeset/tricky-geckos-poke.md, packages/kit/src/utils/routing.js, packages/kit/src/utils/routing.spec.js
I have a route with multiple optional params, but both have matchers that are exclusive to each other. That means for a given URL, there is no ambiguity which param matches.
Consider this example:
```
Route:           /[user]/[[type=type]]/[[page=page]]
Matcher `type`:  (param) => ["overview", "finished", "pending"].includes(param)
Matcher `page`:  (param) => /^\d+$/.test(param) && Number(param) > 0
Link:            "/daniel/2"
Expected Params: { user: "daniel", page: "2" }
Actual Result:   No match, SvelteKit raises 404
```
Looking at the code and the test cases, I think this might have been an accidental oversight, just due to the pretty complex routing algorithm.
This fix now allows the variant where all values have been matched and all params have been used.
---
=> fix: allow optional param in middle of route

.changeset/silver-crews-drop.md, packages/create-svelte/templates/default/src/routes/sverdle/+page.svelte
The code responsible for computing  `classnames` and `description` objects 
```
$: {
classnames = {};
description = {};
data.answers.forEach((answer, i) => {
...
} 
``` 
is executed every time the `data` variable is updated, (i.e. when the player types a letter). 
This code needs to be executed only when a new answer is added to the game. 
I created a variable `currentGuess` to store the letters of the current row, this prevent from updating the `data` object constantly.
This PR also fix this bug :
- It's possible to submit the form by pressing the `Enter` key even if there is less than five letters on the current row.
=> feat: improve sverdle reactivity

documentation/docs/20-core-concepts/40-page-options.md
We no longer prerender by default when SSR is turned off.
=> docs: remove section about prerender by default when SSR is off

.changeset/clean-panthers-remain.md, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/runtime/server/utils.js, packages/kit/src/runtime/shared-server.js, packages/kit/src/types/internal.d.ts
fixes https://github.com/sveltejs/kit/issues/10138
This PR fixes the server stack trace by mutating the error object with `vite.ssrFixStacktrace` rather than using a Proxy. It also fixes the stack trace output by Vite in the server logs and the vite HMR overlay by passing in the option when loading user code as SSR modules.
Thanks to @dmoebius we know that `console.log`, etc. bypasses proxies (for some strange reason). We can also safely use `vite.ssrFixStacktrace` without worrying about repeatedly fixing the same error object because it memoizes the error objects fixed. This optimisation wasn't available when `vite.rewriteStacktrace` was first exposed (but it has been now for some time!).
No test because I can't figure out how to capture the output of `console.log` and Vite's own …
=> fix: correct line numbers when console logging stack traces

documentation/docs/10-getting-started/30-project-structure.md
Page refers to service-worker.js, but it was missing in the visualization of the src tree
=> docs: add missing service-worker.js location in src tree visualization

.changeset/gorgeous-shrimps-bow.md, packages/kit/src/exports/vite/graph_analysis/index.js, packages/kit/src/exports/vite/graph_analysis/index.spec.js, packages/kit/src/exports/vite/index.js, packages/kit/src/exports/vite/utils.js, packages/kit/test/apps/dev-only/test/test.js, packages/kit/test/build-errors/env.spec.js
also use `\0virtual:` instead of `\0` for clarity
I initially implemented this as part of https://github.com/sveltejs/kit/pull/9787, but it's not related to that PR at all and doesn't belong there. Pulling it out into this separate PR will help clean that one up quite a bit
=> fix: strip virtual module prefix from error messages

packages/adapter-static/package.json, packages/adapter-static/test/apps/prerendered/package.json, packages/adapter-static/test/apps/spa/package.json, packages/create-svelte/templates/default/package.json, packages/kit/package.json, packages/kit/test/apps/amp/package.json, packages/kit/test/apps/basics/package.json, packages/kit/test/apps/dev-only/package.json, packages/kit/test/apps/embed/package.json, packages/kit/test/apps/options-2/package.json, packages/kit/test/apps/options/package.json, packages/kit/test/apps/writes/package.json, packages/kit/test/build-errors/apps/prerender-entry-generator-mismatch/package.json, packages/kit/test/build-errors/apps/prerenderable-incorrect-fragment/package.json, packages/kit/test/build-errors/apps/prerenderable-not-prerendered/package.json, packages/kit/test/build-errors/apps/private-dynamic-env-dynamic-import/package.json, packages/kit/test/build-errors/apps/private-dynamic-env/package.json, packages/kit/test/build-errors/apps/private-static-env-dynamic-import/package.json, packages/kit/test/build-errors/apps/private-static-env/package.json, packages/kit/test/build-errors/apps/server-only-folder-dynamic-import/package.json, packages/kit/test/build-errors/apps/server-only-folder/package.json, packages/kit/test/build-errors/apps/server-only-module-dynamic-import/package.json, packages/kit/test/build-errors/apps/server-only-module/package.json, packages/kit/test/build-errors/apps/syntax-error/package.json, packages/kit/test/prerendering/basics/package.json, packages/kit/test/prerendering/options/package.json, packages/kit/test/prerendering/paths-base/package.json, playgrounds/basic/package.json, pnpm-lock.yaml, sites/kit.svelte.dev/package.json
I need this for a new image plugin I'm writing. I wanted to do this separate this out so as to not make the image plugin PR too large and distracting to review. This is just for local development and testing, so no changeset since it's not user visible
=> chore: upgrade to Vite 4.4.9

.changeset/young-wolves-sing.md, packages/kit/src/core/adapt/builder.js, packages/kit/src/core/adapt/builder.spec.js, packages/kit/src/exports/vite/index.js
fixes https://github.com/sveltejs/kit/issues/10268
I can't reproduce the original issue on my system but this simple fix makes it worth leaving the Vite manifest file alone?
We can just remove it when copying files so it doesn't get exposed publicly. https://github.com/sveltejs/kit/issues/8360 https://github.com/sveltejs/kit/pull/8815
This would also make it forwards compatible with whatever vite files get generated in the future since Vite 5 will put all these files in the `.vite` folder. https://github.com/vitejs/vite/issues/9636#issuecomment-1441958636 https://github.com/vitejs/vite/pull/14230/files
=> fix: move Vite file removal to adapter methods

packages/adapter-netlify/package.json, packages/adapter-node/package.json, packages/adapter-vercel/package.json, packages/create-svelte/package.json, packages/kit/package.json, packages/kit/test/build-errors/package.json, packages/kit/test/prerendering/basics/package.json, packages/kit/test/prerendering/options/package.json, packages/kit/test/prerendering/paths-base/package.json, packages/migrate/package.json, pnpm-lock.yaml, sites/kit.svelte.dev/package.json
Having two versions of vitest and chai in the monorepo is making `lint` fail on my latest PR. Upgrade across the board so that we only have a single version
=> chore: update vitest to 0.34.5

.changeset/bright-cycles-argue.md, packages/adapter-static/test/apps/prerendered/src/app.html, packages/adapter-static/test/apps/spa/src/app.html, packages/create-svelte/templates/default/src/app.html, packages/create-svelte/templates/skeleton/src/app.html, packages/kit/test/apps/amp/src/app.html, packages/kit/test/apps/basics/src/app.html, packages/kit/test/apps/dev-only/src/app.html, packages/kit/test/apps/options-2/src/app.html, packages/kit/test/apps/options/source/template.html, packages/kit/test/apps/writes/src/app.html, packages/kit/test/build-errors/apps/prerender-entry-generator-mismatch/src/app.html, packages/kit/test/build-errors/apps/prerenderable-incorrect-fragment/src/app.html, packages/kit/test/build-errors/apps/prerenderable-not-prerendered/src/app.html, packages/kit/test/build-errors/apps/private-dynamic-env-dynamic-import/src/app.html, packages/kit/test/build-errors/apps/private-dynamic-env/src/app.html, packages/kit/test/build-errors/apps/private-static-env-dynamic-import/src/app.html, packages/kit/test/build-errors/apps/private-static-env/src/app.html, packages/kit/test/build-errors/apps/server-only-folder-dynamic-import/src/app.html, packages/kit/test/build-errors/apps/server-only-folder/src/app.html, packages/kit/test/build-errors/apps/server-only-module-dynamic-import/src/app.html, packages/kit/test/build-errors/apps/server-only-module/src/app.html, packages/kit/test/build-errors/apps/syntax-error/src/app.html, packages/kit/test/prerendering/basics/src/app.html, packages/kit/test/prerendering/options/src/app.html, packages/kit/test/prerendering/paths-base/src/app.html, playgrounds/basic/src/app.html, sites/kit.svelte.dev/src/app.html
This PR reverts #5706. #5706 removed the `initial-scale=1` specification from the `<meta name="viewport" >` tags used for templating, on the basis that specification was no longer needed, since browsers should default to `1`. 
However, Chrome-based browsers don't do this, causing design and accessibility issues:
[Screencast from 27-09-23 14:33:39.webm](https://github.com/sveltejs/kit/assets/13798767/e54993ba-df94-48f5-bd38-227a1274e825)
- `pnpm test` runs successfully, didn't lint or check.
=> fix: specified 'initial-scale=1' on all viewport meta tags

.changeset/eleven-ads-destroy.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/test/cross-platform/client.test.js
fixes https://github.com/sveltejs/kit/issues/10607
We weren't updating the `page.url` store when the user navigates between same route history entries. This caused the `$page.url.hash` to not reflect the correct value.
=> fix: correctly update `$page.url.hash` when navigating history

.changeset/neat-chicken-turn.md, packages/kit/src/runtime/client/client.js
Fixes https://github.com/sveltejs/kit/issues/10512
Maybe also this? https://github.com/sveltejs/kit/issues/10700
When navigating with `popstate` , there is an early return if only `#` part of the url changed.
This ignores the edgecase where quick navigation ends on the same page, e.g. `A` -> `B` -> `A`
In this case:
1. `popstate` to `B` calls `navigate()`
2. `popstate` back to `A` returns early doing nothing
3. The first `navigate()` starts rendering
4. We end up with `B` rendered, but `A` in the address bar 
`popstate` event handler should update the navigation token before anything else happens
---
=> fix: `popstate` navigation wasn't cancelling ongoing `navigation()` calls when landing on the same page

.changeset/sharp-birds-invent.md, packages/kit/src/runtime/client/fetcher.js, packages/kit/test/apps/basics/src/routes/load/window-fetch/patching/+page.js, packages/kit/test/apps/basics/src/routes/load/window-fetch/patching/+page.svelte, packages/kit/test/apps/basics/test/client.test.js
This PR makes `initial_fetch` and `subsequent_fetch` use the patched `window.fetch` function instead of the unpatched and stored away `native_fetch` function. 
This change brings one big benefit: Additional behaviour added by libraries (like Sentry but there are many others)  that patch `window.fetch` is now also invoked in `event.fetch` calls within client-side universal `load` functions. 
Additionally, this provides a way for libraries to instrument fetch in load functions _without_ causing unintended cache misses (see https://github.com/getsentry/sentry-javascript/issues/8174)
Kit patches `window.fetch` for two reasons:
- to warn about directly calling `window.fetch` it in `DEV` mode (this we should leave as-is)
- to clean the cache 
I'm not sure if I'm missing something but cleaning …
=> fix: use `window.fetch` in `load` functions to allow libraries to patch it

documentation/docs/20-core-concepts/30-form-actions.md
The question of how to utilise `use:enhance` without causing an invalidation comes up fairly often. I think a few changes in the documentation could make this clearer.
https://github.com/sveltejs/kit/issues/10750#issuecomment-1726420768
https://github.com/sveltejs/kit/discussions/10702
https://github.com/sveltejs/kit/discussions/9467
=> docs: clarify customizing `use:enhance` behaviour

documentation/docs/25-build-and-deploy/90-adapter-vercel.md
https://vercel.com/changelog/serverless-functions-can-now-run-up-to-5-minutes
=> docs: update new `maxDuration` value for Pro plan

.changeset/great-bags-heal.md, packages/kit/src/core/sync/write_types/index.js, packages/kit/src/core/sync/write_types/index.spec.js, packages/kit/src/core/sync/write_types/test/param-type-inference/optional/[[optionalNarrowedParam=narrowed]]/+page.js, packages/kit/src/core/sync/write_types/test/param-type-inference/params/narrowed.js, packages/kit/src/core/sync/write_types/test/param-type-inference/params/not_narrowed.js, packages/kit/src/core/sync/write_types/test/param-type-inference/required/+layout.js, packages/kit/src/core/sync/write_types/test/param-type-inference/required/[narrowedParam=narrowed]/+page.js, packages/kit/src/core/sync/write_types/test/param-type-inference/required/[regularParam=not_narrowed]/+page.js, packages/kit/src/core/sync/write_types/test/param-type-inference/spread/[...spread=narrowed]/+page.js
closes #8137 - Just not for `$page.params`
Currently all route parameters always have type `string`. This type is correct, but often broader than it needs to be.
If a matcher is used on a route parameter, and that matcher is annotated with a guard check, we can infer the type much more narrowly.
```ts
// src/params/ab.ts
export const match = (param) : param is "a" | "b" => param == "a" || param == "b";
```
```ts
// src/routes/[myParam=ab]/+page.ts
export async function load({params}) {
params.myParam //Has type "a" | "b"
}
```
=> Infer route parameter type from matcher's guard check if applicable

.changeset/fast-donuts-own.md, packages/kit/package.json, pnpm-lock.yaml
https://github.com/sveltejs/kit/security/dependabot/9
=> chore: bump undici to address security issue

packages/create-svelte/package.json, pnpm-lock.yaml, sites/kit.svelte.dev/package.json
https://github.com/sveltejs/kit/pull/10879 is currently failing. I expect that due to the `dts-buddy` upgrade. This splits off what I think are the working ones to help narrow it down
=> chore: upgrade two deps

packages/kit/test/prerendering/paths-base/vite.config.js
I missed an extra place to tweak from https://github.com/sveltejs/kit/pull/10896
There's a test that tests an SVG image `src`, but it got inlined and the regex failed to match:
https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6609512793/job/17949784254#step:8:2876
=> chore: additional vite 5 test compatibility

.changeset/mean-cheetahs-tell.md, packages/kit/src/exports/node/polyfills.js
This is somewhat of a quickfix for #10918 by not applying the undici polyfills above the versions where we no longer need to apply it. Pinging @Conduitry as he might have some thoughts on this and was very hesitant towards similar things in the past. We could also bump the minimum required version to ensure people get a more up-to-date/robust version of undici.
=> fix: only apply some polyfills below node 18.11

documentation/docs/60-appendix/01-faq.md
While helping some beginners with their first Svelte(Kit) project I encountered some major confusion around using client-only libraries with SSR. I have tried to improve this section of the documentation based on that feedback.
Some notes:
1. English do be difficult, feel free to correct my mediocre writing skills :)
2. The warning added in 880d610c1c60f519ecc6e2b6212076f84b6aedfd would've saved us a lot of time debugging, but perhaps it's a better fit for [the section on `onMount`](https://svelte.dev/docs/svelte#onmount)?
3. The example added in 5c62f9bf5d1332f55abea5e88e7d291ce5fd8902 suffers from sveltejs/svelte#9323, so I feel like a comment explaining what's going on is appropriate. I'm not sold on this particular format though, any suggestions?
4. Git's diff came out a little weird …
=> docs: expand & clarify FAQ entry on using client-only libraries

.changeset/tricky-radios-stare.md, packages/kit/src/exports/node/polyfills.js
fixes #10946 
Quick fix that ensures `File` is always polyfilled rather than just pre Node 18.11.0. The global was only added in Node 20, while `buffer.File` was only added in Node 18.13.0
https://nodejs.org/dist/latest-v20.x/docs/api/globals.html#class-file
=> fix: ensure `File` is pollyfilled for Node 18.11+

package.json, packages/adapter-netlify/package.json, packages/kit/package.json, pnpm-lock.yaml
need a newer version of rollup for the `@sveltejs/enhanced-image` type checking
need a newer version of eslint to fix a peer dependency warning
=> chore: upgrade rollup and eslint

package.json
this broke vite-ecosystem-ci and also caused problems for nuxt and vite releases
https://discord.com/channels/804011606160703521/1169865487144992778
=> fix: bump pnpm to 8.10.2 to avoid issue with broken arborist in 8.10.0

.changeset/eight-moons-kick.md, packages/kit/src/runtime/server/page/index.js, packages/kit/test/prerendering/basics/src/routes/shadowed-get/ssr-off/+page.server.js, packages/kit/test/prerendering/basics/src/routes/shadowed-get/ssr-off/+page.svelte, packages/kit/test/prerendering/basics/test/tests.spec.js
fixes https://github.com/sveltejs/kit/issues/10983
This PR adds a check to see if we're prerendering and SSR is turned off to avoid responding with CSR only too early. With this check in place, the `should_prerender` check can now be reached and generate the `__data.json` file.
=> fix: generate `__data.json` when prerendering and SSR is turned off

.changeset/small-readers-decide.md, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/utils.js
this is a very small thing, but it turns out that repeatedly accessing `location.origin` (when evaluating `<a>` elements to know if they're external etc) has a small but measurable impact. since it can't change, we can cache it on startup
=> cache location.origin on startup

documentation/docs/30-advanced/60-images.md
As per issue https://github.com/sveltejs/kit/issues/11014, the official documentation for the new image preprocessor provides an incorrect import statement. This PR fixes the statement.
=> docs(images): update incorrect import statement

.changeset/silver-suns-yell.md, packages/adapter-cloudflare-workers/files/entry.js
fixes https://github.com/sveltejs/kit/issues/10937
This PR applies the same adapter-cloudflare fix from https://github.com/sveltejs/kit/pull/8733 which I forgot to add to adapter-cloudflare-workers in the past. This should fix the trailing slash issue in the aforementioned issue where the trailing slash of `/base/` was being stripped too early and therefore, would never match with the prerendered page `/base/`.
=> fix: apply `adapter-cloudflare` trailing slash fix to `adapter-cloudflare-workers`

.changeset/shy-islands-hammer.md, packages/create-svelte/bin.js, packages/create-svelte/index.js, packages/create-svelte/scripts/build-templates.js, packages/create-svelte/scripts/update-template-repo-contents.js, packages/create-svelte/shared/+checkjs/package.json, packages/create-svelte/shared/+svelte5/package.json, packages/create-svelte/shared/+typescript/package.json, packages/create-svelte/templates/default/package.template.json, packages/create-svelte/templates/skeleton/package.template.json, packages/create-svelte/templates/skeletonlib/package.template.json, packages/create-svelte/test/check.js, packages/create-svelte/types/internal.d.ts, packages/kit/CHANGELOG.md
=> feat: add option to try out Svelte 5 beta

.changeset/wise-moose-bathe.md, packages/enhanced-img/src/preprocessor.js, packages/enhanced-img/test/Input.svelte, packages/enhanced-img/test/Output.svelte, packages/enhanced-img/test/preprocessor.spec.js
I accidentally pushed the changeset for this to `master` already :confused:  https://github.com/sveltejs/kit/commit/4426daebe1d345f60554225e3f12ea932b0110e4
So I'm going to go ahead and merge this as soon as the tests are green to avoid separating the change from its changset by too much. Feel free to leave comments though - I can address in a followup
I'd had most of this code in an earlier version of the image PR, but it accidentally got removed when I rewrote it to resolve the image inside the preprocessor as an optimization. https://github.com/sveltejs/kit/pull/10788/commits/5050172d89b99960f3fc7ffe72b78374c3eca038#diff-f318d5cf67f7e975aecc26dfb6056ae55058442cf36dd7e6f53c4a292edeb2d9
=> fix: auto-import of svg images

.changeset/great-toys-hang.md, packages/enhanced-img/package.json, pnpm-lock.yaml
I just fixed this in `vite-imagetools`. It's been annoying me for the past year, so I probably should have tracked it down earlier :laughing: But now that we have more users, I decided it was time!
=> fix: refresh in dev mode when an image changes

.changeset/great-dryers-grin.md, packages/kit/src/runtime/server/page/index.js, packages/kit/test/apps/basics/src/routes/prerendering/no-ssr/+page.js, packages/kit/test/apps/basics/src/routes/prerendering/no-ssr/+page.svelte, packages/kit/test/apps/basics/test/test.js
fixes https://github.com/sveltejs/kit/issues/11031
https://github.com/sveltejs/kit/pull/10988 introduced a regression where the response during prerendering would always have SSR enabled. This PR fixes this by setting it according to the SSR page option.
=> fix: prerender pages that use browser globals and have SSR turned off

.changeset/unlucky-knives-bake.md, packages/kit/src/runtime/client/client.js
fixes https://github.com/sveltejs/kit/issues/8751
This PR handles the edge case where loading the data of a non-existent prerendered dynamic route returns a 404 HTML page instead of JSON data. No test because our /basics test app has a root server layout load function, which causes it to do a native navigation instead, returning a 404 SSR response. The error only occurs when there is no root server layout load.
=> fix: prevent JSON parse error when loading data

.changeset/violet-moons-tease.md, packages/enhanced-img/src/preprocessor.js, packages/enhanced-img/test/Output.svelte
The fix was changing `const name = ASSET_PREFIX + images.size;` to `const name = ASSET_PREFIX + imports.size;`. You can see the test output is better now
I also noticed that `details.name` was unused, so simplified things by removing that field.
=> fix: avoid creating conflicting import statements

.changeset/slow-students-run.md, packages/enhanced-img/src/preprocessor.js, packages/enhanced-img/test/Output.svelte
In JS files, Vite compiles `__VITE_ASSET_xxx_` to `" + new URL("../path", import.meta.url) + "`. This was being inlined directly into the client-side components, meaning the client components were rendering `<img src=" + new URL("../path", import.meta.url) + ">`. This fixes that.
=> @sveltejs/enhanced-img: Fix client component compilation

.changeset/gold-meals-listen.md, packages/adapter-cloudflare-workers/files/entry.js, packages/adapter-cloudflare/src/worker.js, packages/kit/src/exports/vite/preview/index.js, packages/kit/test/apps/basics/src/routes/routing/prerendered/+layout.js, packages/kit/test/apps/basics/src/routes/routing/prerendered/trailing-slash/always/+page.js, packages/kit/test/apps/basics/src/routes/routing/prerendered/trailing-slash/ignore/+page.js, packages/kit/test/apps/basics/svelte.config.js, packages/kit/test/apps/basics/test/server.test.js
fixes https://github.com/sveltejs/kit/issues/11138
Adds a check for the URL query string then adds it to the redirect location. Previously, the redirect location was just the pathname, so the query string was always omitted when we redirected. This affected `vite preview`, `adapter-cloudflare`, and `adapter-cloudflare-workers`. The added test only tests for `vite preview` (we have no cloudflare adapter tests).
=> fix: retain URL query string for trailing slash redirects to prerendered pages

packages/package/.gitignore, packages/package/.prettierignore
Running the `test` before running `lint` results in:
```
│ [warn] test/fixtures/javascript/dist/index.d.ts
│ [warn] test/fixtures/javascript/dist/internal/index.d.ts
│ [warn] test/fixtures/javascript/dist/internal/Test.svelte.d.ts
│ [warn] test/fixtures/javascript/dist/Test.svelte.d.ts
│ [warn] test/fixtures/javascript/dist/Test2.svelte.d.ts
│ [warn] test/fixtures/resolve-alias/dist/baz.d.ts
│ [warn] test/fixtures/resolve-alias/dist/sub/bar.d.ts
│ [warn] test/fixtures/resolve-alias/dist/sub/foo.d.ts
│ [warn] test/fixtures/resolve-alias/dist/Test.svelte
│ [warn] test/fixtures/resolve-alias/dist/Test.svelte.d.ts
│ [warn] test/fixtures/resolve-alias/dist/utils/index.js
│ [warn] test/fixtures/svelte-3-types/dist/Test.svelte
│ [warn] test/fixtures/svelte-3-types/dist/Test.svelte.d.ts
│ [warn] …
```
=> fix: ignore `dist` folders from `lint` check

documentation/docs/20-core-concepts/40-page-options.md
Closes https://github.com/sveltejs/kit/issues/10914
List the consequences of `csr=false`.
- The webpage should work with HTML and CSS only.
- `<script>` tags inside all Svelte components are removed.
- `<form>` elements cannot be [progressively enhanced](form-actions#progressive-enhancement).
- Links are handled by the browser with full-page navigation.
---
=> docs: add csr warning list

packages/kit/src/exports/vite/index.js, packages/kit/src/exports/vite/preview/index.js, packages/kit/test/apps/basics/test/server.test.js, packages/kit/test/apps/options-2/test/test.js, packages/kit/test/utils.js
https://github.com/vitejs/vite/pull/14818 broke a lot of tests. I mostly fixed it here: https://github.com/sveltejs/kit/commit/43a745ad5f516c48f08718ae256e73d9e47ef0eb.
I don't know what's causing the remaining failures, but I think it's also something related to the base path - if I remove the base path from the failing tests then they start working. You can reproduce them with:
```
cd packages/kit/test/apps/options-2
pnpm build
pnpm test:build
```
When I run `pnpm preview` in that directory everything seems to work and it looks like `started` is added to the `body`, so I don't know why the tests are failing with a timeout looking for `started`.
=> fix: finish getting Vite 5 working

packages/kit/src/exports/index.js, sites/kit.svelte.dev/scripts/types/index.js
unblocks https://github.com/sveltejs/kit/pull/11165
Correctly parses the `{@link ...}` JSDoc tags when converting the types to docs for the website.
=> docs: resolve `@link` JSDoc tags

.changeset/twenty-ducks-reply.md, package.json, packages/adapter-node/package.json, packages/adapter-node/src/index.js, packages/create-svelte/package.json, packages/enhanced-img/package.json, packages/kit/package.json, pnpm-lock.yaml
rennovate wants to upgrade these in https://github.com/sveltejs/kit/pull/10938, but we can't merge that PR because it's trying to upgrade `dts-buddy` which requires TypeScript 5. Let's just upgrade these as part of Kit 2 and then rennovate will automatically close that PR when `version-2` becomes the main branch
=> chore: upgrade dependencies

documentation/docs/30-advanced/20-hooks.md, documentation/docs/30-advanced/25-errors.md
Sentry now has a sveltekit package: https://docs.sentry.io/platforms/javascript/guides/sveltekit/
Update from using "@sentry/node" and "@sentry/svelte" to "@sentry/sveltekit";
=> docs: refer to `@sentry/sveltekit` rather than `@sentry/node`

.changeset/silent-games-taste.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/app/navigation.js, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/utils.js, packages/kit/test/apps/basics/src/routes/goto/+page.svelte, packages/kit/test/apps/basics/test/client.test.js, packages/kit/test/apps/basics/test/cross-platform/client.test.js, packages/kit/test/utils.d.ts
=> breaking: disallow external navigation using `goto`

.changeset/hungry-kings-collect.md, packages/adapter-auto/package.json, packages/adapter-cloudflare-workers/package.json, packages/adapter-cloudflare/package.json, packages/adapter-netlify/package.json, packages/adapter-node/package.json, packages/adapter-static/package.json, packages/adapter-vercel/package.json, packages/amp/package.json, pnpm-lock.yaml
I don't think there were any changes to the adapter API, so we don't need a new major. I made this a `minor` since Kit 2 seemed sort of like a new feature. That means Kit 1 users can keep getting new adapter bug fixes.
=> feat: allow SvelteKit 2 as peer dependency

.changeset/soft-colts-tell.md, documentation/docs/20-core-concepts/20-load.md, packages/kit/src/runtime/server/fetch.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/test/apps/basics/src/routes/streaming/+page.svelte, packages/kit/test/apps/basics/src/routes/streaming/server-error/+page.server.js, packages/kit/test/apps/basics/src/routes/streaming/server-error/+page.svelte, packages/kit/test/apps/basics/test/client.test.js
Ensures that people using `fetch` directly in their load functions don't run into uncaught promise errors with streaming. Also adds some docs for this case.
related to #9785
=> fix: make sure promises from fetch handle errors

documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
I got the following message when deploying to cloudflare workers so we should update the deployment command in the docs.
```sh
❯ wrangler publish
⛅️ wrangler 3.19.0
-------------------
▲ [WARNING] `wrangler publish` is deprecated and will be removed in the next major version.
Please use `wrangler deploy` instead, which accepts exactly the same arguments.
```
=> docs: update wrangler cli deployment command

.changeset/real-carrots-share.md, packages/kit/src/runtime/server/cookie.js, packages/kit/src/runtime/server/cookie.spec.js, packages/kit/src/runtime/server/utils.js
This prints a warning if you call `cookies.set(...)` or `cookies.delete(...)` without specifying a `path`, as part of #9299.
I think we should change the behaviour of `path: ''` in SvelteKit 2.0 as well. Currently, it's equivalent to leaving it unspecified. It would be more useful (and more consistent with other places where paths are resolved) if it meant 'the current path' instead — the fact that it doesn't is a quirk of how cookie headers are serialized, rather than something deliberate. As such, I've also added a warning that it will change. (I expect very few people are doing `path: ''` today.)
In development, the warning also points to the callsite, making it easy to fix.
=> chore: deprecate pathless cookie, warn on `path: ''`

.changeset/hungry-moles-turn.md, packages/adapter-cloudflare-workers/index.d.ts
The types for the cloudflare workers adapter plugin method requires an object as a parameter. This PR makes that optional so it's in tune with the docs https://kit.svelte.dev/docs/adapter-cloudflare-workers#usage
```diff
import adapter from '@sveltejs/adapter-cloudflare-workers';
export default {
kit: {
-		adapter: adapter({ })
+		adapter: adapter()
}
};
```
=> fix: make adapter plugin param type optional

.changeset/twenty-birds-eat.md, packages/kit/src/core/config/index.spec.js, packages/kit/src/core/config/options.js, packages/kit/src/core/sync/write_server.js, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/server/data/index.js, packages/kit/src/runtime/server/page/index.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/src/runtime/server/page/respond_with_error.js, packages/kit/src/types/internal.d.ts, packages/kit/test/apps/basics/test/client.test.js, packages/kit/test/apps/options/svelte.config.js, packages/kit/test/apps/options/test/test.js
We had to make a breaking change in #9945, so we added this option to give people who knew it was safe an easy way to keep their apps running while they implemented fixes. Since we're releasing 2.0, we can remove this security-related override.
Closes #11234
=> breaking: Remove `dangerZone.trackServerFetches`

.changeset/cold-walls-film.md, packages/adapter-cloudflare-workers/index.js
fixes https://github.com/sveltejs/kit/issues/11210
Previously, the prerendered manifest didn't set the base path so it looked like this:
```js
export const prerendered = {
'/base/about': 'about.html'
}
```
However, this is incorrect because it is stored in the KV with the key `/base/about.1asdf34.html` (ignore the hash, cloudflare handles it). This is also because we upload the build output such that the public files live in the base folder `.cloudflare/public/base/about.html`.
Therefore, the new manifest when a base path is set should look like this:
```js
export const prerendered = {
'/base/about': '/base/about.html'
}
```
=> fix: correctly map prerendered pages when base path is set

.changeset/poor-parrots-own.md, documentation/docs/20-core-concepts/20-load.md, packages/create-svelte/templates/default/src/routes/sverdle/+page.server.ts, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/server/cookie.js, packages/kit/src/runtime/server/cookie.spec.js, packages/kit/src/runtime/server/fetch.js, packages/kit/src/runtime/server/page/types.d.ts, packages/kit/src/utils/url.js, packages/kit/src/utils/url.spec.js, packages/kit/test/apps/basics/src/hooks.server.js, packages/kit/test/apps/basics/src/routes/cookies/delete/+server.js, packages/kit/test/apps/basics/src/routes/cookies/encoding/not-decoded-twice/+server.js, packages/kit/test/apps/basics/src/routes/cookies/encoding/set/+server.js, packages/kit/test/apps/basics/src/routes/cookies/enhanced/basic/+page.server.ts, packages/kit/test/apps/basics/src/routes/cookies/forwarded-in-etag/+page.server.js, packages/kit/test/apps/basics/src/routes/cookies/nested/a/+page.server.js, packages/kit/test/apps/basics/src/routes/cookies/serialize/+server.js, packages/kit/test/apps/basics/src/routes/cookies/set-in-layout/+layout.server.js, packages/kit/test/apps/basics/src/routes/cookies/set-more-than-one/+page.server.js, packages/kit/test/apps/basics/src/routes/cookies/set/+server.js, packages/kit/test/apps/basics/src/routes/headers/set-cookie/+layout.server.js, packages/kit/test/apps/basics/src/routes/headers/set-cookie/sub/+page.server.js, packages/kit/test/apps/basics/src/routes/shadowed/redirect-get-with-cookie/+page.server.js, packages/kit/test/apps/basics/src/routes/shadowed/redirect-post-with-cookie/+page.server.js
=> breaking: require `path` when setting/deleting/serializing cookies

.changeset/eighty-files-sell.md, packages/kit/src/runtime/server/cookie.js
per https://github.com/sveltejs/kit/issues/9299#issuecomment-1848596296, this resolve relative (same-domain) cookie paths before storing them locally. It doesn't affect the behaviour of cookies in the browser, but means that if you do this...
```js
cookies.set('a', 'b', { path: '.' });
console.log(cookies.get('a'));
```
...it will correctly log `b` instead of trying to retrieve the cookie from headers. Super niche bug that AFAIK no-one has hit, but now that we're explicitly recommending that people use relative paths, it makes sense to fix it.
Tested locally, didn't add one to this PR because it's covered in `version-2`.
=> resolve relative cookie paths before storing

.changeset/swift-clocks-kneel.md, packages/kit/package.json, packages/kit/src/exports/index.js, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/control.js, packages/kit/test/types/actions.test.ts, packages/kit/test/types/load.test.ts, packages/kit/types/index.d.ts
- add ActionFailure interface and use that publicly instead of the class. Prevents the false impression that you could do "instanceof" on the return type, fixes #10361
- add uniqueSymbol to ActionFailure instance so we can distinguish it from a regular return with the same shape
- fix setup to actually run test/types
Someone with a non-windows machine has to check in the type diff (and double check it) because I can't do it properly. There's a bug in `dts-buddy` somewhere that break path resolving on Windows (I'm guessing a missing `\` to `/` conversion).
=> fix: Adjust fail method and ActionFailure type

.changeset/eight-pens-help.md, .changeset/loud-plants-move.md, .changeset/mean-trees-notice.md, packages/kit/src/core/postbuild/analyse.js
alternative to #11239 that addresses https://github.com/sveltejs/kit/pull/11239#issuecomment-1849086963
=> breaking: stricter route validation, more correct config resolution

.changeset/smart-buttons-return.md, packages/kit/src/core/sync/sync.js, packages/kit/src/core/sync/write_non_ambient.js, packages/kit/src/core/sync/write_tsconfig.js, packages/kit/src/core/sync/write_tsconfig.spec.js
This makes it possible to delete these from svelte/elements in Svelte 5 and have them controled in SvelteKit, decoupling the two
closes #10534
Don't think this is really a breaking change, but let's have it as part of 2.0 just to be sure.
=> feat: provide SvelteKit html typings

.changeset/nervous-mails-tickle.md, packages/kit/src/exports/index.js, packages/kit/src/runtime/app/paths.js, packages/kit/test/apps/options/source/pages/resolve-route/+page.svelte, packages/kit/test/apps/options/source/pages/resolve-route/[foo]/+page.svelte, packages/kit/test/apps/options/test/test.js, packages/kit/types/index.d.ts
#10282. after this is merged into `master`, and `master` is merged into `version-2`, we can open another PR that removes `resolvePath`
=> feat: `resolveRoute` function

.changeset/warm-impalas-thank.md, packages/kit/src/runtime/client/client.js
=> deprecate preloadCode calls with multiple arguments

.changeset/old-rockets-film.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/load/invalidation/depends/+page.svelte, packages/kit/test/apps/basics/test/client.test.js
=> fix: reset invalid resources after successful invalidation

packages/migrate/migrations/routes/migrate_page_js/index.spec.js, packages/migrate/migrations/routes/migrate_page_server/index.spec.js, packages/migrate/migrations/routes/migrate_scripts/index.spec.js, packages/migrate/migrations/routes/migrate_server/index.spec.js, packages/migrate/migrations/routes/utils.js, packages/migrate/migrations/sveltekit-2/migrate.js, packages/migrate/migrations/sveltekit-2/migrate.spec.js, packages/migrate/migrations/sveltekit-2/svelte-config-samples.md, packages/migrate/migrations/sveltekit-2/tsconfig-samples.md, packages/migrate/migrations/sveltekit-2/tsjs-samples.md, packages/migrate/utils.js
The cookie migration hints added in #11199 were broken — they didn't change anything in the SvelteKit demo app, because the ancestor check only cared about arrow function expressions that were assigned to a variable. Fixing the ancestor check revealed a separate bug — we need to batch up the changes, otherwise we get an error like this:
> InvalidOperationError: Attempted to get information from a node that was removed or forgotten.
By collecting the nodes that need to be commented first, and _then_ commenting them, the operation succeeds, but it leaves us with stupid-looking whitespace that's inconsistent with the surroundings:
If we can fix that, great, otherwise I really think we're better off relying on the combination of type and runtime errors here. It's just not worth it.
=> chore: fix cookie migration hints, and also disable them

.changeset/honest-terms-help.md, packages/kit/src/runtime/server/page/actions.js, packages/kit/test/apps/basics/test/test.js
per [discussion 11248](https://github.com/sveltejs/kit/discussions/11248), this PR adds a fix so HTTP status code 415 "Unsupported Media Type" is returned (instead of 500).
The problem with returning 500 is that it's the wrong error message and not something that should be reported to for example Sentry.
fixes #11251
=> fix: actions wrong return 415

packages/kit/src/utils/promises.js, packages/kit/test/apps/basics/test/test.js
Hey everyone, I know "simple typo" PRs aren't super-popular, but this irked me and I wanted to un-irk it.
Changes the following message
> In SvelteKit 2.0, these will longer be awaited automatically.
to
> In SvelteKit 2.0, these will no longer be awaited automatically.
(adds a missing `no`.)
Thanks!
=> Fix promises auto-await deprecation warning

.changeset/happy-beds-run.md, packages/kit/src/runtime/server/cookie.js, packages/kit/src/runtime/server/page/index.js, packages/kit/src/utils/url.js, packages/kit/test/prerendering/basics/src/routes/page.html/+page.server.js, packages/kit/test/prerendering/basics/src/routes/page.html/+page.svelte
This is a possible solution to #8676. It's _technically_ breaking insofar as it clobbers any routes that happen to end with `.html__data.json`, but given how unlikely that is it's not really breaking.
It solves the problem (that you can't prerender both `foo.html` and `foo.html/__data.json`) by making the files siblings — the data is generated as `foo.html__data.json` instead. This requires no configuration changes, and very little complexity in terms of implementation — no 'is it prerendered?' or 'what do we do with cookies?' questions, just a simple 'does the route end with `.html`?' check.
=> generate __data.json files as siblings of .html files

.changeset/warm-otters-compete.md, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/control.js, packages/kit/src/runtime/server/respond.js, packages/kit/src/runtime/server/utils.js
Fixes #10898 
This change will show an error message "Internal Error" when reproducing the issue discussed above.
=> fix: Show Internal Error when rendering default Error page when a runtime error occurs on a 404 page

documentation/docs/20-core-concepts/20-load.md
This adds information from #6315 to the docs. A new user may assume layout load functions always run, run sequentially before page files, or both. This provides anyone searching "auth" some quick info to prevent them from falling into that trap.
=> docs: implications for authentication

.changeset/bright-buttons-flash.md, documentation/docs/30-advanced/30-link-options.md, packages/kit/src/runtime/client/constants.js, packages/kit/src/runtime/client/utils.js
closes https://github.com/sveltejs/kit/pull/10460
Explanation: https://github.com/sveltejs/kit/pull/10460#issuecomment-1660448867
We should update the language tools as well. I think the original PR from @alesvaupotic originates from the extension incorrectly stating that `"false"` is not a valid value (although it is for the non-preloading link options).
=> fix: add `"false"` value to preload link options

documentation/docs/20-core-concepts/50-state-management.md
A commonly returning error on Discord is related to state preservation in pages due to misunderstandings how pages relate to components in regards to reactivity. While this language is not perfect, at least the title of the section will now mention "Page state is preserved" making it hopefully easier to find.
=> docs: clean up some confusion about state management and pages.

.changeset/swift-deers-draw.md, packages/kit/src/constants.js, packages/kit/src/core/postbuild/analyse.js, packages/kit/src/runtime/server/endpoint.js, packages/kit/src/runtime/server/utils.js
fixes https://github.com/sveltejs/kit/issues/10984
Previously, the endpoint metadata would never be populated as described in the issue. However, I think it was only used in the Vercel adapter to fire off some warning https://github.com/sveltejs/kit/blob/20d2fe7dc5b9d181788889c45aea1e3745222c82/packages/adapter-vercel/index.js#L562-L593
=> fix: correctly analyse exported endpoint methods during build

.changeset/moody-hornets-own.md, packages/kit/src/utils/fork.js
According to the docs, `terminate` seems to effectively stop all execution in the thread, as soon as possible. This seems to break some long running process — which was working with `child_process` before — when prerendering, either because the ample amounts of prerendered pages/routes, the huge amount of data that needs to be (pre)processed for each routes, or a combination of both.
Substituting `terminate` with `unref` would allow the worker to exit when it finds that it's the only active one in the event system, this would allow the long running process that seems to happen after `terminate` is called to finish without being interrupted.
The error thrown by the `terminate` method also seems to be very vague and random, trying to `await` it seems to give a more helpful message along …
=> fix: call worker `unref` instead of `terminate`

documentation/docs/30-advanced/40-service-workers.md
When introducing a service-worker into my SvelteKit application, I encountered some issues after copying the code from the docs at https://kit.svelte.dev/docs/service-workers#inside-the-service-worker.
1. When adding the code into a service-worker.ts file, with the recommended triple-slash directives the code was not entirely type-safe. The main issue was that the `respond` function could return `Promise<Response | undefined>` instead of `Promise<Response>`, which conflicts with the argument type of `event.respondWith`. See: https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith#syntax. The example is updated so that if the `cache.match` returns `undefined`, then it does not return that `undefined` value, and instead continues on to try and make the fetch. In the case …
=> docs: update service-worker example to be type-safe when in ts + handle offline better

.changeset/warm-sloths-cry.md, packages/kit/src/runtime/server/page/actions.js, packages/kit/test/apps/basics/test/test.js
When posting to a form action, that does not exist, the server returned 500(!)
With this fix, it will return 404 error "not found".
The problem with returning 500 is that it's the wrong error message and not something that should be reported to for example Sentry.
This is something I found, in relation to [discussion 11248](https://github.com/sveltejs/kit/discussions/11248).
=> fix: action not found should return 404

.changeset/twelve-paws-remember.md, packages/kit/src/core/postbuild/fixtures/base/output.json, packages/kit/src/core/postbuild/fixtures/basic-href/output.json, packages/kit/src/core/postbuild/fixtures/href-with-character-reference/output.json, packages/kit/src/core/postbuild/fixtures/ids/output.json, packages/kit/src/core/postbuild/fixtures/include-rel-external/output.json, packages/kit/src/core/postbuild/fixtures/meta/output.json, packages/kit/src/core/postbuild/fixtures/unquoted-attributes/output.json, packages/kit/src/utils/url.js, packages/kit/src/utils/url.spec.js, packages/kit/test/apps/basics/src/routes/cookies/encoding/set/+server.js
Our `resolve` utility was returning incorrect results in the case where `path` was just a `.` character, leading to confusion such as https://github.com/sveltejs/kit/pull/11273#issuecomment-1852182542.
This implementation delegates to `new URL(...)`, so it's more or less guaranteed to be correct whatever edge cases we throw at it
=> breaking: fix path resolution

.changeset/smart-crabs-lick.md, packages/kit/src/core/config/index.js
Part of #11291. This _only_ redacts stack traces when the config is malformed — other errors will keep their stack traces
=> feat: redact internal stack trace when reporting config errors

.changeset/fast-radios-tell.md, packages/kit/src/runtime/server/page/actions.js, packages/kit/test/apps/basics/test/test.js
We shouldn't have merged #11255 and #11278. They were reasonable changes on the face of it, but they were the wrong fix. Instead, we should have a way to include a status code with unexpected errors. This PR doesn't implement that, as it needs further discussion on #11287.
=> fix: revert recent error changes

.changeset/dull-eyes-check.md, .changeset/loud-parrots-flow.md, documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md, packages/kit/src/core/sync/write_tsconfig.js, packages/kit/src/core/sync/write_tsconfig.spec.js, packages/migrate/migrations/sveltekit-2/migrate.js
- don't generate baseUrl anymore and don't adjust paths anymore depending on whether or not the user has paths in their tsconfig.json
- more strict validation: warn on baseUrl/paths and suggest kit.alias instead
closes #11286
also added a changeset for `svelte-migrate` because none was generated yet.
- [ x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
=> breaking: remove baseUrl fallback from generated tsconfig

.changeset/violet-rockets-smoke.md, packages/kit/src/runtime/app/navigation.js, packages/kit/types/index.d.ts
=> fix: correct documentation for `beforeNavigate`

documentation/docs/20-core-concepts/20-load.md, documentation/docs/30-advanced/25-errors.md
- note that error/redirect throws, and document SvelteKit 1.x behavior
- fix promise behavior description and note SvelteKit 1.x behavior
=> docs: fix wording, note SvelteKit 1.x behavior

.changeset/tricky-rats-pull.md, package.json, packages/adapter-static/index.js, packages/create-svelte/package.json, packages/create-svelte/shared/+eslint+prettier/package.json, packages/create-svelte/shared/+prettier/package.json, packages/kit/src/core/adapt/builder.js, packages/kit/src/core/sync/write_tsconfig.js, packages/kit/src/exports/hooks/sequence.js, packages/kit/src/exports/node/index.js, packages/kit/src/exports/public.d.ts, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/exports/vite/preview/index.js, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/src/runtime/server/page/render.js, packages/kit/src/runtime/server/respond.js, packages/kit/src/utils/routing.js, packages/kit/test/utils.js, packages/kit/types/index.d.ts, packages/migrate/package.json, packages/package/src/utils.js, pnpm-lock.yaml, sites/kit.svelte.dev/package.json
I updated the templates in `create-svelte` as well because 3.0.0 will actually be broken and won't work. It shouldn't matter for most users as they'll still get the latest unless they're on an older version of pnpm, but better safe than sorry
This PR will fix the lint errors on https://github.com/sveltejs/kit/pull/9847
=> chore: upgrade to prettier 3.1.1

packages/kit/src/exports/vite/dev/index.js, packages/kit/test/apps/basics/test/cross-platform/server.test.js, packages/kit/test/apps/basics/test/server.test.js
Not sure how this eluded us up till now, but I _think_ there's a case sensitivity bug that manifests on platforms like Mac OS. Moving the relevant test into a cross-platform file to see if it shows up in CI as well.
I hope I'm mistaken, because if not this is presumably an issue with Vite 5, possibly bypassing our middleware? Investigating
=> add failing cross-platform server test

.changeset/fast-eyes-deny.md, documentation/docs/20-core-concepts/20-load.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/test/apps/basics/src/routes/untrack/server/+layout.server.js, packages/kit/test/apps/basics/src/routes/untrack/server/[x]/+page.server.js, packages/kit/test/apps/basics/src/routes/untrack/server/[x]/+page.svelte, packages/kit/test/apps/basics/src/routes/untrack/universal/+layout.js, packages/kit/test/apps/basics/src/routes/untrack/universal/[x]/+page.js, packages/kit/test/apps/basics/src/routes/untrack/universal/[x]/+page.svelte, packages/kit/test/apps/basics/test/client.test.js, packages/kit/types/index.d.ts
=> feat: add untrack to load functions

packages/migrate/migrations/sveltekit-2/index.js, packages/migrate/migrations/sveltekit-2/migrate.js
prevents `svelte-migrate` crashing on encountering a `workspace:` dependency
=> chore: check range is valid

.changeset/hip-spoons-crash.md, .changeset/silly-frogs-love.md, packages/adapter-auto/adapters.js, packages/adapter-auto/package.json, packages/adapter-cloudflare-workers/package.json, packages/adapter-cloudflare/package.json, packages/adapter-netlify/package.json, packages/create-svelte/templates/default/package.template.json, packages/create-svelte/templates/skeleton/package.template.json, packages/create-svelte/templates/skeletonlib/package.template.json, packages/migrate/migrations/sveltekit-2/migrate.js, pnpm-lock.yaml
Bumping all the adapters to require SvelteKit 2, because a) esbuild changes and we want to be careful b) easier to do minors using new capabilities c) adapter-auto is more robust in installing correct versions then
No changeset for the migration script because that's not released yet.
=> breaking: require SvelteKit 2 for all adapters

.changeset/brave-nails-sip.md, packages/migrate/migrations/sveltekit-2/migrate.js
Fix more broken links from https://kit.svelte.dev/docs/v2-migration-guide to https://kit.svelte.dev/docs/migrating-to-sveltekit-2
=> chore: update broken links

.changeset/grumpy-insects-flow.md, packages/migrate/utils.js, packages/migrate/utils.spec.js
`svelte-migrate@1.3.2` does not sort packages after insertion.
As the result, `@sveltejs/vite-plugin-svelte` is placed in the last row.
```jsonc
{
"devDependencies": {
"@sveltejs/adapter-auto": "^3.0.0",
"@sveltejs/kit": "^2.0.0",
"eslint": "^8.55.0",
"eslint-config-prettier": "^9.1.0",
"eslint-plugin-svelte": "^2.35.1",
"prettier": "^3.1.1",
"prettier-plugin-svelte": "^3.1.2",
"svelte": "^4.2.8",
"svelte-check": "^3.6.2",
"typescript": "^5.3.3",
"vite": "^5.0.0",
// Appended at the end. Not alphabetically sorted.
"@sveltejs/vite-plugin-svelte": "^3.0.0"
}
}
```
In this PR, `dependencies` and `devDependencies` are sorted alphabetically.
```javascript
['dependencies', 'devDependencies'].forEach((key) => {
if (key in pkg) {
// Method used in the PR
pkg[key] = …
```
=> chore: sort packages after insert

.changeset/honest-badgers-itch.md, packages/migrate/migrations/sveltekit-2/index.js, packages/migrate/migrations/sveltekit-2/migrate.js, packages/migrate/migrations/sveltekit-2/tsjs-samples.md
Migrating users should manually update cookie path arguments.
Also fixes cookie migration logic, fixes #11327
---
=> fix: note `@migration` comments, fix cookie migration

.changeset/twelve-yaks-travel.md, documentation/docs/25-build-and-deploy/80-adapter-netlify.md, documentation/docs/25-build-and-deploy/90-adapter-vercel.md, packages/adapter-vercel/index.js
=> fix: update adapter-vercel supported node versions

documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md
When migrating to SvelteKit v2, I encountered the same problem as #10229. It turns out I had an old version of `svelte-migrate` installed. Based on sveltejs/svelte#8814, update the migration docs to use `svelte-migrate@latest` instead.
Perhaps `svelte-migrate` should also be updated to add a hint about this instead of outputting something like `You must specify one of the following migrations: package, routes`, so that the docs don't always need to mention `svelte-migrate@latest`.
=> docs: use @latest on the migrate command in v2 migration guide

.changeset/stupid-eels-rule.md, packages/create-svelte/shared/+prettier/.prettierignore
Prettier 3 uses the `.gitignore`, so we don't need to specify anything that's already in that file
=> chore: simplify `.prettierignore`

.changeset/lovely-plums-move.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js
fixes https://github.com/sveltejs/kit/issues/11317
https://github.com/sveltejs/kit/pull/10763 introduces a bug where the trailing slash option at the root page is set to always. This PR checks if a base config is set before setting trailing slash to always for the root page.
=> fix: correctly trailing slash redirect when navigating from root page

.changeset/forty-owls-hear.md, packages/create-svelte/shared/+playwright+vitest/package.json
=> fix: use correct vitest version in playwright + vitest template

.changeset/brave-waves-accept.md, packages/kit/src/exports/vite/index.js
=> fix: adjust missing inner content warning with svelte v5

.changeset/new-hounds-retire.md, packages/create-svelte/shared/+default+checkjs/package.json, packages/create-svelte/shared/+default+typescript/package.json
closes https://github.com/sveltejs/kit/issues/11350
I don't remember the history of this, but `npm run check` and `pnpm run check` both pass without it
=> fix: remove unnecessary @types/cookie package

.changeset/cool-moles-fetch.md, packages/migrate/bin.js
Sometimes we forget to add `@latest` to the svelte-migrate instructions. This PR updates the error for a missing migration to suggest re-running with latest.
Of course, people on older versions won't get this helpful error, but maybe it will be useful eventually.
Related: #11359, #11360
Example of new error:
=> fix: suggest running svelte-migrate with latest if migration does not exist

.changeset/late-queens-build.md, documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md, packages/kit/src/runtime/app/navigation.js, packages/kit/src/runtime/client/client.js
This reinstantiates the `state` parameter for the `options` argument to `goto`. In the original shallow routing PR, this was mentioned as the alternative, and it may make sense to do it this way instead of requiring people to do `await goto(..); replaceState({ ..})` instead of just `goto(..., { state: { .. } })`. It also means the page store is updated directly, and doesn't have a tick were it's empty.
Open for debate if we really want to do this, but the change itself is rather easy so I thought I'd open the PR. Probably needs a test if we reinstantiate.
=> fix: reinstantiate state parameter for goto

.changeset/brave-waves-accept.md, packages/kit/src/exports/vite/index.js
Reverts sveltejs/kit#11380 so that we can cut a release with the other changes
=> Revert "fix: adjust missing inner content warning with svelte v5"

.prettierrc
Finally found out why my pushes keep failing. The pre-push lint is erroring on those test artefact files when running local tests.
=> chore: ignore vite config timestamp files when prettier linting

.changeset/mighty-rockets-work.md, packages/kit/src/runtime/app/navigation.js, packages/kit/types/index.d.ts
=> fix: goto type include state

.changeset/serious-pears-joke.md, packages/kit/src/exports/vite/index.js, packages/kit/src/exports/vite/preview/index.js
closes https://github.com/sveltejs/kit/issues/11368
finish dealing with the fallout of https://github.com/vitejs/vite/pull/14818. revert the earlier attempts to deal with it and remove the base middleware instead
=> fix: ensure assets are served gzip in preview

.changeset/green-cycles-shake.md, .changeset/tricky-meals-perform.md, packages/kit/src/exports/vite/build/build_service_worker.js
Reverts sveltejs/kit#11129 — there's a better workaround that doesn't result in an IIFE wrapper
=> Revert "fix: build service workers in IIFE format"

.changeset/polite-rice-burn.md, packages/enhanced-img/src/index.js, packages/enhanced-img/src/preprocessor.js
Give some better feedback if users put the file in the wrong directory
=> fix: throw an error if image cannot be resolved

.changeset/giant-planets-sing.md, packages/kit/src/exports/vite/index.js
Alright, v2 of #11380 
Svelte 5 can still use `<slot>` and `+layout` can now accept "named slots" with snippets. I think we can safely assume _some_ content will be rendered, as long as a `{@render` tag exists in the markup, without having to check which snippet(s) also exists in the script.
Closes #11127
=> fix: adjust missing inner content warning

sites/kit.svelte.dev/src/routes/docs/[slug]/+page.svelte, sites/kit.svelte.dev/src/routes/home/Deployment.svelte, sites/kit.svelte.dev/src/routes/schema.json
GitHub does not redirect `/edit` routes to the renamed master branch.
This causes a '404 - page not found' error in the GitHub website.
- https://github.com/sveltejs/kit/edit/master/documentation/docs/10-getting-started/10-introduction.md
- https://github.com/sveltejs/kit/edit/main/documentation/docs/10-getting-started/10-introduction.md
=> fix: edit this page on GitHub anchor

documentation/docs/20-core-concepts/30-form-actions.md
The site current builds to fail locally because of this. It seems it's succeeding on the CI due to caching
=> docs: update cookie examples with path

.changeset/perfect-eyes-brush.md, packages/kit/src/core/postbuild/analyse.js, packages/kit/src/core/postbuild/fallback.js, packages/kit/src/core/postbuild/prerender.js, packages/kit/src/core/sync/write_server.js, packages/kit/src/exports/vite/index.js, packages/kit/src/runtime/server/index.js, packages/kit/src/types/ambient.d.ts, packages/kit/src/types/internal.d.ts, packages/kit/test/apps/options/source/hooks.server.js, packages/kit/types/index.d.ts
In SvelteKit 2, we disallow access to `$env/dynamic/[public|private]` during prerendering so that you can't bake stale values into your app. We do it slightly overzealously, however — they are also disallowed during the _analysis_ phase, which is an unnecessary restriction.
This PR distinguishes between the two phases. It also bails out of prerendering early if no prerenderable routes were found during the analysis phase, meaning that if you're not prerendering anything it's safe to access dynamic env vars in (for example) `hooks.server.js`.
Closes #11341, closes #11425.
=> fix: only disallow dynamic env access when prerendering

.changeset/silver-hornets-eat.md, packages/create-svelte/shared/+eslint+prettier+typescript/.eslintrc.cjs, packages/create-svelte/shared/+eslint+prettier-typescript/.eslintrc.cjs, packages/create-svelte/shared/+eslint+typescript/.eslintrc.cjs, packages/create-svelte/shared/+eslint-typescript/.eslintrc.cjs, packages/create-svelte/shared/+eslint/package.json
This PR adds a dev dependency for `@types/eslint` and bumps the eslint package versions. The flat config file had a JSDoc type annotation but didn't include the types package, so we weren't getting the autocomplete. The type has also been changed to non-flat config too.
=> fix: set ESLint config type to `Config` instead of `FlatConfig`

.changeset/silly-panthers-talk.md, packages/package/src/validate.js
`import.meta.env` requires Vite to work - not just a bundler
`esm-env` doesn't provide environment variables, but standard variables representing what environment you're running in and I think that's an important distinction
=> fix: improve warning when encountering import.meta.env

documentation/docs/40-best-practices/20-seo.md
You no longer have to do this when using `svelte-preprocess`, so we can remove this section from the docs. We should almost remove the option from `svelte-preprocess` as it has no effect: https://github.com/sveltejs/svelte-preprocess/pull/622
=> docs: remove outdated section from SEO docs

README.md, documentation/docs/25-build-and-deploy/20-adapters.md, documentation/docs/60-appendix/20-integrations.md, documentation/docs/60-appendix/50-additional-resources.md
This PR updates the [sveltesociety.dev](https://sveltesociety.dev/) links to use URL query params to filter tags, rather than the previous URL fragment.
For example, https://sveltesociety.dev/packages#svelte-kit-adapters becomes https://sveltesociety.dev/packages?tag=sveltekit-adapters
=> docs: update `sveltesociety.dev` links

documentation/docs/20-core-concepts/50-state-management.md
Further discussion can be found in this issue https://github.com/sveltejs/kit/issues/8282.
My interpretation of the current documentation is that changes to the value of the store won't ever propagate if the page is rendered server-side.
The sentence about hydration at the end of the paragraph does technically challenge this interpretation, but I believe the updated version is much clearer about the behavior.
If any of the terminology is incorrect, feel free to correct it. I'm especially unsure about the use of "CSR". I'm not sure if this is technically "hydration" or something else.
=> Clarify docs on context-based store value propagation behavior during SSR

.changeset/breezy-pens-exercise.md, packages/create-svelte/templates/default/src/routes/sverdle/+page.server.ts
We recommend `path: '/'` for most cases in the docs, but the demo uses `path: ''` instead. I think it's better to be consistent.
=> fix: set path: '/' in demo

.changeset/giant-years-drum.md, packages/kit/src/runtime/server/page/csp.js, packages/kit/src/runtime/server/page/csp.spec.js
This PR adds functionality for automatically adding CSP-directives that are required only if they're used:
- `script-src-elem` 
- `style-src-attr` 
- `style-src-elem` 
error thrown because of missing nonce/hash when `script-src-elem` is used:
error thrown because of missing nonce/hash if `style-src-attr` and/or `style-src-elem` is used:
`style-src-attr` and `style-src-elem` is also automatically added during dev so things work locally.
=> [security]: automatically add nonce or hash to `script-src-elem`, `style-src-attr` & `style-src-elem` csp directive if necessary

.changeset/good-carrots-repeat.md, packages/kit/src/runtime/client/client.js
=> fix: set `{ stream: true }` when calling `decoder.decode` on multiple chunks

documentation/docs/30-advanced/67-shallow-routing.md, packages/kit/src/runtime/client/client.js
The serialization capabilities of history.state are basically identical to those of devalue.stringify . As such, the indirection of saving the data in the session storage isn't necessary, which also saves 1kb compressed / 3kb uncompressed because of the no longer needed devalue functions.
Merge target is #11340
=> chore: apply state to history.state directly

packages/enhanced-img/src/index.js
the dynamic import was a holdover from when `vite-imagetools` was optional
this might help us get a better idea of what's going on in https://github.com/sveltejs/kit/issues/11528
=> chore: statically import vite-imagetools

.changeset/kind-seas-tell.md, packages/kit/src/utils/routing.js
We missed @gtm-nayan's [last comment](https://github.com/sveltejs/kit/pull/11551/files/1406830927b7e6bc4df55bb9125c4775fce606bb#r1446180087) on https://github.com/sveltejs/kit/pull/11551. Addressing it now
=> fix: restore invalid route error message during build process

package.json
https://github.com/sveltejs/kit/pull/10629#discussion_r1393031332 got merged I'm guessing without seeing the pending comments I had there. Generating the types on `postinstall` doesn't make sense anymore because now they're checked in. Please don't make me build packages that I'm not working on when I install dependencies
=> chore: remove postinstall script

.changeset/short-crews-give.md, packages/adapter-node/src/handler.js
Fixes #11381. Briefly tested locally. The last I knew, there was not a good way to test adapted output.
Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.
=> fix: correctly handle BODY_SIZE_LIMIT=0 in Node adapter

documentation/docs/25-build-and-deploy/50-adapter-static.md
Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.
---
adding the following instruction: make sure `.nojekyll` exists without the github page config.
My note: the `.nojekyll` instruction is missing in [#10083](https://github.com/sveltejs/kit/pull/10083). People that do not use custom github pages config will be confused (like me). I read that before, and I noticed that the instruction is missing. Moreover, people debugging will read this very popular [thread](https://stackoverflow.com/questions/75497065/sveltekit-deployment-on-gh-pages-doesnt-work-only-html-is-shown-css-and-js) and get mislead because the instruction to add `.nojekyll` is missing.
=> docs: .nojekyll in static folder.

.changeset/chatty-swans-pretend.md, packages/adapter-node/src/handler.js, packages/kit/src/exports/node/index.js
**Summary**
This pull request updates the environment variable handling in our SvelteKit application to support floating-point values for the BODY_SIZE_LIMIT. Previously, the BODY_SIZE_LIMIT was parsed using parseInt, which limited it to integer values. By switching to parseFloat, we can now define more precise limits, improving the flexibility of our application's configuration.
**Changes**
Changed the parsing method for BODY_SIZE_LIMIT from parseInt to parseFloat. This allows the use of both integers and floating-point numbers, providing more granular control over the body size limit.
**Impact**
Enhanced Flexibility: Users can now specify decimal values in the BODY_SIZE_LIMIT environment variable, enabling more precise control over request body size limits.
Backward Compatibility: …
=> fix: Update body_size_limit to use Number instead of parseInt

.changeset/thin-chairs-live.md, packages/kit/src/exports/vite/index.js
per https://github.com/sveltejs/kit/issues/11578#issuecomment-1885683203, the current message isn't very helpful when you have a missing peer dependency
---
=> fix: better missing peer dep error

.changeset/rare-lizards-wonder.md, packages/enhanced-img/src/preprocessor.js
Fixes https://github.com/sveltejs/kit/issues/11561
Images cache keys are wrong for relative paths
---
- [ x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.
=> fix: correct images cache key to avoid collisions when images have same name

packages/kit/test/apps/amp/tsconfig.json, packages/kit/test/apps/basics/tsconfig.json, packages/kit/test/apps/dev-only/tsconfig.json, packages/kit/test/apps/embed/tsconfig.json, packages/kit/test/apps/no-ssr/tsconfig.json, packages/kit/test/apps/options-2/tsconfig.json, packages/kit/test/apps/options/tsconfig.json, packages/kit/test/apps/writes/tsconfig.json, packages/kit/test/build-errors/apps/prerender-entry-generator-mismatch/tsconfig.json, packages/kit/test/build-errors/apps/prerenderable-incorrect-fragment/tsconfig.json, packages/kit/test/build-errors/apps/prerenderable-not-prerendered/tsconfig.json, packages/kit/test/build-errors/apps/private-dynamic-env-dynamic-import/tsconfig.json, packages/kit/test/build-errors/apps/private-dynamic-env/tsconfig.json, packages/kit/test/build-errors/apps/private-static-env-dynamic-import/tsconfig.json, packages/kit/test/build-errors/apps/private-static-env/tsconfig.json, packages/kit/test/build-errors/apps/server-only-folder-dynamic-import/tsconfig.json, packages/kit/test/build-errors/apps/server-only-folder/tsconfig.json, packages/kit/test/build-errors/apps/server-only-module-dynamic-import/tsconfig.json, packages/kit/test/build-errors/apps/server-only-module/tsconfig.json, packages/kit/test/build-errors/apps/service-worker-dynamic-public-env/tsconfig.json, packages/kit/test/build-errors/apps/service-worker-private-env/tsconfig.json, packages/kit/test/build-errors/apps/syntax-error/tsconfig.json, packages/kit/test/prerendering/basics/tsconfig.json, packages/kit/test/prerendering/options/tsconfig.json, packages/kit/test/prerendering/paths-base/tsconfig.json, packages/kit/test/tsconfig.json
am trying to make the test output less chaotic, so it's easier to diagnose failures. step one: get rid of the 'You have specified a baseUrl and/or paths in your tsconfig.json...' warnings. It looks like `"paths"` is no longer necessary (not sure why it ever was)
=> chore: remove unnecessary tsconfig paths config

.github/workflows/ci.yml, package.json, packages/enhanced-img/package.json
See also #11606, #11608
The test output is much easier to read if tests run serially. Since the `kit` tests take much longer to run than the others, it makes sense to separate them out into their own job and have all the others in a separate job
=> chore: restructure CI stuff

.changeset/old-masks-thank.md, .changeset/rude-countries-sing.md, packages/adapter-cloudflare-workers/files/entry.js, packages/adapter-cloudflare/index.js, packages/adapter-cloudflare/placeholders.d.ts, packages/adapter-cloudflare/src/worker.js
https://github.com/sveltejs/kit/pull/10454#issuecomment-1885678689. ~~haven't actually tested this yet~~ tested, it works
---
=> fix: serve files in _app from function, if not already handled

.changeset/soft-falcons-cover.md, packages/kit/src/exports/vite/index.js, packages/kit/src/runtime/server/page/render.js
Ref #11364. There is a [very serious Safari bug](https://bugs.webkit.org/show_bug.cgi?id=242740) that apparently very few people have encountered outside SvelteKit, possibly because few frameworks use native ESM with top-level await. That is likely to change over time, and I hope Webkit can prioritise a fix for this issue.
In the meantime we have no choice but to work around it. I don't see a better alternative than this PR, which eagerly loads the dynamic `env.js` module when on a prerendered page, such that `${global}.env` is populated by the time any user code tries to read it.
This is less good than fetching it lazily, and it only mitigates the issue (since top-level await could appear in user code, and it's likely we'll find other uses for it within the framework in future), but for …
=> fix: work around safari bug

.changeset/gold-rocks-compare.md, packages/adapter-cloudflare/index.d.ts, packages/adapter-cloudflare/index.js
Alternative to #9762. Closes #9386. Instead of generating an SPA-style fallback page, we render a plaintext `Not Found` page, which is sufficient for the case where a request is made for a missing asset that is covered by an `exclude` rule. For all other requests, we will hit the worker, which will generate the correct 404 page.
Today:
- [/missing](https://kit-5ry.pages.dev/missing)
- [/_app/immutable/missing](https://kit-5ry.pages.dev/_app/immutable/missing)
With this PR:
- [/missing](https://b91f918d.kit-5ry.pages.dev/missing) (same as before)
- [/_app/immutable/missing](https://b91f918d.kit-5ry.pages.dev/_app/immutable/missing) (plaintext 404)
---
=> breaking: generate plaintext 404.html for Cloudflare Pages, instead of SPA-style fallback

documentation/docs/20-core-concepts/20-load.md
The note is saying that AWS Lambda doesn't support streaming with promises.
Neither does Firebase and it's a popular deployment target so users should know about this.
---
=> docs: Add info that Firebase also doesn't support stream loading.

.changeset/bright-moose-brake.md, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/fetcher.js
Some other libraries might hook into `history.replaceState/pushState` to do additional work. This no longer works since the introduction of shallow routing because we're stashing away the original history methods. This PR adjusts the DEV time check logic so that this is no longer necessary.
Fixes #11499
Fixes https://github.com/vercel/analytics/issues/121
---
=> fix: don't stash away original `history` methods so other libs can monkeypatch it

.changeset/thin-rules-travel.md, packages/kit/src/core/adapt/builder.js
I'm tweaking the docs in https://github.com/sveltejs/kit/pull/11637 to recommend using a name other than `index.html`, but it'd still be useful to log a warning for existing projects or for people who don't read the docs (i.e. everyone).
I thought about making it throw an error, but it doesn't stop the project from working and probably wouldn't be considered backwards compatible to do so. It also risks the user turning off prerendering to solve the error, which could be counter-productive.
=> fix: log a warning if fallback page overwrites prerendered page

.changeset/old-ravens-learn.md, packages/adapter-cloudflare-workers/index.js, packages/adapter-cloudflare/index.js
This is a companion to #10544. Cloudflare workers let you import from `node:path`, but not from `path`. This is annoying to fix if you're not the one writing the import (i.e. it's in a dependency). We can trivially fix it with `esbuild` config.
---
=> feat: support compatible node modules without prefixes

.changeset/light-tips-hang.md, packages/adapter-cloudflare-workers/index.js, packages/adapter-cloudflare/index.js
Follow-up to #10544 and #11672. Replaces this...
...with this:
I think that's probably a more useful error since it explains what the problem is, rather than prompting you to adjust configuration you don't control.
---
=> feat: more helpful errors when using incompatible node modules

playgrounds/README.md
`git update-index` doesn't really work, and the [git documentation](https://github.com/git/git/blob/1b13e9032f039c8cdb1994dd092ff2ed32af5cf5/Documentation/git-update-index.txt#L552-L567) explicitly recommends against using it for this purpose. I've experienced no end of problems with it.
If I had my druthers we'd just remove the `playgrounds` directory altogether. Since that's apparently an unpopular move, I'll settle for updating the README with instructions for using the sandbox, which is much more flexible.
=> chore: remove bad advice

.changeset/fluffy-schools-develop.md, packages/kit/src/runtime/app/server/index.js, packages/kit/src/runtime/client/fetcher.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/src/runtime/utils.js, packages/kit/test/apps/basics/src/routes/read-file/auto.txt, packages/kit/test/apps/basics/src/routes/read-file/url.txt, packages/kit/test/apps/basics/test/test.js
kind of incredible that `atob` and `btoa`, aside from the spectacularly shite naming, straight up don't work. clown shoes ass platform.
anyway, this fixes the weird characters identified in #11679. thanks @danielzsh and @tmarsik42 for the invaluable sleuthing here, this could have taken a while to figure out
~~ugh i guess i should add a test~~
---
=> fix: properly decode base64 strings inside `read`

.changeset/smart-jeans-repeat.md, packages/kit/src/core/postbuild/analyse.js
feature checking fails for a server route without an explicit config, if the feature-checking function assumes `config` is an object. this fixes it
---
=> fix: default route config to `{}` for feature checking

.changeset/fluffy-insects-build.md, documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md, packages/kit/src/exports/vite/index.js
closes https://github.com/sveltejs/kit/issues/11658
please review the question in https://github.com/sveltejs/kit/issues/11658#issuecomment-1900722813 while deciding whether this is safe
=> fix: respect `build.target` config supplied by user

package.json, packages/adapter-static/package.json, packages/create-svelte/package.json, packages/kit/package.json, packages/kit/test/apps/basics/test/cross-platform/client.test.js, pnpm-lock.yaml, renovate.json
We had pinned Playwright due to https://bugzilla.mozilla.org/show_bug.cgi?id=1832341. Finally getting around to adding a workaround for it since it seems like it's not getting fixed
=> chore: upgrade playwright

.changeset/smooth-kids-cover.md, packages/kit/src/exports/node/index.js
Right now, it's possible to crash a Node server by including a body with a `GET` request. This fixes it
---
=> fix: ignore bodies sent with non-PUT/PATCH/POST requests 

documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md
https://stackoverflow.com/questions/75194714/window-location-type-string-is-not-assignable-to-type-location-stri
=> docs: address TypeScript issue in migration guide

.changeset/four-insects-play.md, packages/kit/src/exports/node/index.js
Apparently people are sending bodies with their `DELETE` requests, and #11708 was a breaking change as a result. This changes it to just ignore bodies for `GET` and `HEAD`, since that's what causes Undici to lose its cool.
---
=> fix: only disallow body with GET/HEAD requests

.changeset/fresh-points-smoke.md, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/utils/filesystem.js, packages/kit/test/apps/basics/src/routes/read-file/+page.server.js, packages/kit/test/apps/basics/src/routes/read-file/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/test.js, packages/kit/test/apps/basics/test/test.js, packages/kit/test/apps/read-file-test.txt
Windows absolute paths look like `/@fs/C:/..` - when stripping the fs prefix, we need to remove the additional slash after the fs
---
=> fix: strip `/@fs` prefix correctly on Windows when invoking `read()` in dev mode

packages/kit/src/core/adapt/index.js, packages/kit/src/exports/public.d.ts, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/exports/vite/index.js, packages/kit/src/exports/vite/preview/index.js, packages/kit/src/types/internal.d.ts, packages/kit/types/index.d.ts
- the Emulator type is not a class export
- make validated config types more correct by leaving adapter types as optional
Leftovers from #11730, no changeset because the thing is not released yet.
Through this I noticed that `export class Server` is similarly incorrect; I guess it just doesn't matter really in practise because only adapters use that for their types.
---
=> chore: clean up emulator types

.changeset/stale-games-shake.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/test/client.test.js
=> Fix: treated shallow are as such

.changeset/mighty-spies-explain.md, packages/kit/src/exports/index.js, packages/kit/types/index.d.ts
Keep the status codes as `number` because restricting to certain numbers makes it unnecessarily hard to use compared to the benefits (we have runtime errors already to check for invalid codes). Closes #11780
---
=> fix: relax status code types

documentation/docs/25-build-and-deploy/50-adapter-static.md
Update workflow example to latest versions
---
=> docs: update static adapter deploy to pages workflow

sites/kit.svelte.dev/src/lib/server/docs/index.js
Add some missing properties for the correct creation of href for the first items of "On this page" component of the [Sveltekit Docs](https://kit.svelte.dev/docs/introduction). Currently doesn't create that reference in the first item and prevent navigation to the top of the page.
More info on [issue](https://github.com/sveltejs/kit/issues/11830)
---
Only affects website
🥹Junior dev PR
> I'm not sure how to do that. I've done it manually and I hope is done properly.
=> fix: path missing in first item of "On this page" component for Docs site

documentation/docs/25-build-and-deploy/30-adapter-auto.md
Hey just correcting a dead link I found while reading the docs
---
=> docs: Corrected dead link for SST

.changeset/mighty-radios-know.md, packages/create-svelte/shared/+eslint+typescript/package.json, packages/create-svelte/shared/+eslint/package.json
[typescript-eslint v7](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/) has been released.
1. This will bump the required Node.js version to `^18.18.0`, beyond the SvelteKit's current `>=18.13`
2. In https://github.com/sveltejs/kit/pull/11453, the `@types/eslint` package's version was set to exact. Caret has been added.
---
=> chore: bump typescript-eslint to v7

.changeset/large-meals-speak.md, packages/kit/package.json, pnpm-lock.yaml
This is against the `version-1` branch. It will stop users still on v1 from getting pinged by security audit tools. See https://github.com/advisories/GHSA-3787-6prv-h9w3
SvelteKit v2 is unaffected as it does not depend on `undici` directly. Instead users should make sure they're using a patched version of Node.js.
=> chore(deps): upgrade and unpin undici

.changeset/loud-kangaroos-leave.md, packages/kit/src/runtime/client/client.js
fixes https://github.com/sveltejs/kit/issues/11671
The warning currently incorrectly fires when we use `history.pushState()` internally such as clicking on a link. You can test this in a [stackblitz starter project](sveltekit.new). This is because one of the early exit conditions in the warning method is failing incorrectly.
`import.meta.url` returns the `client.js` file with a query parameter when loading it from `node_modules`. This causes the substring search for the module filename in the error stack to always return false (because of the query params that are not present in the error stack) https://github.com/sveltejs/kit/blob/53412fd74120e452f5e538ed142374a462d2419e/packages/kit/src/runtime/client/client.js#L79
The solution is to simply return the URL without the query parameters if …
=> fix: prevent false positive `history.pushState` warnings

documentation/docs/25-build-and-deploy/90-adapter-vercel.md
https://vercel.com/changelog/serverless-functions-can-now-run-up-to-5-minutes
pro plans are now 300 seconds
=> docs: link to max duration vercel docs

.changeset/angry-gorillas-peel.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/load/invalidation/invalidate-then-goto/+layout.server.js, packages/kit/test/apps/basics/src/routes/load/invalidation/invalidate-then-goto/+page.server.js, packages/kit/test/apps/basics/src/routes/load/invalidation/invalidate-then-goto/+page.svelte, packages/kit/test/apps/basics/test/client.test.js
Current was not updated after invalidation, which resulted in the previous values getting used on next navigation
fixes #11446
We also didn't set `force_invalidate` back to `false`
fixes #10123
---
=> fix: prevent stale values after invalidation

.changeset/sixty-files-lay.md, packages/kit/src/core/sync/write_tsconfig.js, packages/kit/src/core/sync/write_tsconfig.spec.js
I was unable to setup https://typescript-eslint.io/rules/no-misused-promises/ in a SvelteKit project without this. I might have been able to tweak the esconfig settings to get it to work, but either way it seemed like the `svelte.config.js` should be there if the `vite.config.js` is there
=> fix: tsconfig includes should cover svelte.config.js

.changeset/clean-dots-switch.md, documentation/docs/30-advanced/70-packaging.md, packages/package/src/cli.js, packages/package/src/index.js, packages/package/src/types.d.ts, packages/package/src/typescript.js, packages/package/test/fixtures/tsconfig-specified/expected/runes.svelte.d.ts, packages/package/test/fixtures/tsconfig-specified/expected/runes.svelte.js, packages/package/test/fixtures/tsconfig-specified/package.json, packages/package/test/fixtures/tsconfig-specified/src/lib/runes.svelte.ts, packages/package/test/fixtures/tsconfig-specified/svelte.config.js, packages/package/test/fixtures/tsconfig-specified/tsconfig.build.json, packages/package/test/fixtures/tsconfig-specified/tsconfig.json, packages/package/test/index.js
closes #9373
Adds the option `tsconfig` to svelte-package, allowing to specify which tsconfig / jsconfig to use during the packaging.
---
=> feat: support specifying the tsconfig in svelte-package

.changeset/odd-masks-check.md, documentation/docs/30-advanced/40-service-workers.md, packages/kit/src/core/sync/write_tsconfig.js
Removing this was an accidental breaking change as part of #10994, strictly speaking. The new solution isn't ideal but very few people will use `$env/static/public` so it's probably fine. The one drawback is that `ambient.d.ts` is now semi-public (I guess it always was in some way).
fixes #11721
---
=> fix: exclude service worker from tsconfig again

.changeset/afraid-ghosts-yell.md, packages/kit/src/core/sync/write_tsconfig.js, packages/kit/src/core/sync/write_tsconfig.spec.js, packages/kit/src/types/private.d.ts, packages/kit/types/index.d.ts
The inclusion of `svelte.config.js` is a breaking change since it's type-checked now and that can break projects which did type-check without errors previously
closes #11906
Also relaxes the report-uri types, fully qualified urls are also ok
closes #11905
---
=> fix: revert tsconfig change, fix types

.changeset/strong-rocks-perform.md, documentation/docs/25-build-and-deploy/40-adapter-node.md, packages/adapter-node/index.js
I'd like to merge this together with https://github.com/sveltejs/kit/pull/11653 where we're already doing a major version bump in `adapter-node`.
I was looking at a major SvelteKit project and they were just using the default options and not precompressing assets, which would have made their site much faster. It made me wonder why we weren't doing it by default as I believe we should have our defaults align with making sites fast. This feature was originally introduced in https://github.com/sveltejs/kit/pull/1693. It was made `false` by default there as they were worried about adding to build time. I tried building the site with both `true` and `false` and there was minimal if any difference in speed, so I don't think we should let that block us
Should we just remove the option and always …
=> breaking: precompress by default

documentation/docs/25-build-and-deploy/40-adapter-node.md
closes https://github.com/sveltejs/kit/issues/9593
=> docs: describe how to compress adapter-node responses

.changeset/good-roses-design.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/data-sveltekit/preload-data/offline/+layout.server.js, packages/kit/test/apps/basics/src/routes/data-sveltekit/preload-data/offline/+page.svelte, packages/kit/test/apps/basics/src/routes/data-sveltekit/preload-data/offline/slow-navigation/+page.server.js, packages/kit/test/apps/basics/test/client.test.js
fixes https://github.com/sveltejs/kit/issues/9508
Adds a conditional check to differentiate between a preload (`data-sveltekit-preload-data`) running `load_route` and a `load_route` from actual navigation. We only want to load the root error page for actual navigations and not preloads.
---
=> fix: prevent navigation when preloading fails due to network error

.changeset/lucky-chefs-sleep.md, documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md, documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
cleanup for https://github.com/sveltejs/kit/pull/11732 by adding a changeset and documentation.
@dario-piotrowicz I tried not to add too much to avoid overcomplicating it but there may be some important details worth mentioning in the docs or a better structure to explain things.
---
=> chore: docs and changeset for #11732

pnpm-lock.yaml
closes https://github.com/sveltejs/kit/security/dependabot/13
=> chore: upgrade undici

.changeset/sweet-weeks-pretend.md, packages/create-svelte/shared/+checkjs/jsconfig.json, packages/create-svelte/shared/+typescript/tsconfig.json
When running create-svelte, I noticed that the Typescript generated project had a comment truncated compared to an identical JSDoc generated project. I've added the truncated portion as there's no indication that this was intention in the original commit, 9b24b9c. I've included a screenshot of that commit to make it clear (you can see how the jsconfig has both links, but the tsconfig has only the one.)
---
=> fix: truncated comment when running create-svelte

documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md, documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
part of https://github.com/sveltejs/kit/issues/11990
This PR updates the Cloudflare adapter docs to mention that the emulated bindings are local-only. @dario-piotrowicz  had his concerns about this source of confusion (and rightly so). I should have been more specific in the initial docs.
---
=> docs: specify emulated bindings are local-only

documentation/docs/25-build-and-deploy/40-adapter-node.md
Link name and link address was switched in adapter-node#compressing-responses.
I hope it's fine to just open a PR for such a small thing.
---
=> docs: fix custom server link in adapter-node compressing responses section

.changeset/sweet-otters-glow.md, packages/kit/src/runtime/client/client.js
Should fix https://github.com/sveltejs/svelte/issues/10929
When using Svelte 5, we're always calling `hydrate(...)` instead of `mount(...)`, even if the landing page was `ssr = false`. This PR fixes it.
Later, we can go a little bit further: by creating two entry points (one that references `hydrate`, one that references `mount`), and serving the `mount` entry point for `ssr = false` pages, we can take advantage of treeshaking to make the client bundle smaller in these cases. But it's probably not worth doing that until Svelte 5 is stable.
---
=> skip hydrate if ssr: false

.changeset/weak-seas-approve.md, documentation/docs/40-best-practices/07-images.md, packages/enhanced-img/package.json, pnpm-lock.yaml
Changelog here: https://github.com/JonasKruckenberg/imagetools/blob/main/packages/vite/CHANGELOG.md#change-log
This now caches image transformations by default. Closes https://github.com/sveltejs/kit/issues/11120
Together with the latest version of Vite, fixes encoding issues. Closes https://github.com/sveltejs/kit/issues/11874
=> chore(deps): upgrade vite-imagetools to v7

.changeset/loud-pens-mate.md, packages/package/src/utils.js
closes https://github.com/sveltejs/svelte/issues/10766
no test because this needs Svelte 5 to work, which we don't use in this repo yet.
---
=> fix: don't strip `lang="ts"` tag in Svelte 5

.changeset/chilly-wombats-roll.md, packages/create-svelte/shared/+eslint+prettier+typescript/eslint.config.js, packages/create-svelte/shared/+eslint+prettier-typescript/eslint.config.js, packages/create-svelte/shared/+eslint+typescript/eslint.config.js, packages/create-svelte/shared/+eslint-typescript/eslint.config.js
By default, `svelte-package` creates a directory that is not `package` but `dist`, so we need to change it.
---
=> fix: set the correct for the ESLint config ignores

.changeset/sixty-walls-act.md, packages/create-svelte/templates/default/src/routes/sverdle/+page.svelte, packages/kit/test/apps/basics/src/routes/anchor-with-manual-scroll/anchor-afternavigate/+page.svelte, packages/kit/test/apps/basics/src/routes/anchor-with-manual-scroll/anchor-onmount/+page.svelte, packages/kit/test/apps/basics/src/routes/data-sveltekit/noscroll/+page.svelte, packages/kit/test/apps/basics/src/routes/data-sveltekit/noscroll/target/+page.svelte, packages/kit/test/apps/basics/src/routes/iframes/nested/parent/+page.svelte, packages/kit/test/apps/basics/src/routes/no-ssr/margin/+page.svelte, packages/kit/test/apps/basics/src/routes/routing/+page.svelte, packages/kit/test/apps/basics/src/routes/scroll/cross-document/a/+page.svelte, packages/migrate/migrations/self-closing-tags/index.js, packages/migrate/migrations/self-closing-tags/migrate.js, packages/migrate/migrations/self-closing-tags/migrate.spec.js, packages/migrate/package.json, pnpm-lock.yaml, sites/kit.svelte.dev/src/routes/home/Video.svelte
Companion to sveltejs/svelte#11114. This adds an npx svelte-migrate self-closing-tags migration that replaces all the self-closing non-void elements in your .svelte files.
Alternative to #12102 with the following adjustments:
- doesn't migrate slots that are not real custom element slots (will make diff much less noisy)
- doesn't migrate when namespace is foreign
- leaves tag-like strings inside scripts/styles etc alone
---
=> feat: add self-closing-tags migration

.changeset/tall-goats-warn.md, packages/create-svelte/shared/+skeletonlib+svelte5/package.json
If you create a library with Svelte 5 today, it still has Svelte 4 as a peer dependency
=> fix: set peerDependencies based on chosen Svelte version

packages/create-svelte/shared/+default+checkjs/svelte.config.js, packages/create-svelte/shared/+default+typescript/svelte.config.js, packages/create-svelte/shared/+default-typescript/svelte.config.js, packages/create-svelte/shared/+typescript/svelte.config.js, packages/create-svelte/shared/-typescript/svelte.config.js
WebStorm notified me of a typo in the `svelte.config.js` file after creating a new project with `create-svelte`. I also cross-checked with languagetool.org and they both said that a comma was missing, so I added it :)
A very dumb PR but I hope it's enough.
---
=> chore: fixed typo in all svelte configs of create-svelte

.changeset/smart-donkeys-destroy.md, packages/migrate/migrations/self-closing-tags/migrate.js, packages/migrate/migrations/self-closing-tags/migrate.spec.js
Fixes an issue where a non-self-closing element would have their children skipped when running the `svelte-migrate self-closing-tags` migration script.
for example:
```svelte
<div>
<i /> 
</div>
```
---
=> fix: Continue traversing a non-self-closing element's children

.changeset/wicked-kangaroos-swim.md, packages/kit/src/core/sync/write_tsconfig.js, packages/kit/src/core/sync/write_tsconfig.spec.js
fixes https://github.com/sveltejs/kit/issues/12169
Appends a `"./"` to the generated tsconfig path so that aliases to files in `.svelte-kit/...` don't cause the user's tsconfig.json to complain about non-relative paths.
---
=> fix: ensure generated tsconfig paths start with `./` if aliasing to `./svelte-kit`

.changeset/pink-tigers-whisper.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/routing/+page.svelte, packages/kit/test/apps/basics/src/routes/routing/next-paint/+page.svelte, packages/kit/test/apps/basics/test/client.test.js
By default, SvelteKit preloads the data and code needed to navigate when you touch or hover over a link. As a consequence, it's often the case that navigation can occur immediately following a click event, with no delay for network activity.
Ironically, this means that navigation becomes _less_ responsive, not more, because the browser doesn't get a chance to repaint before the navigation occurs and the page is re-rendered, which can cause dropped frames on slower devices. Because of this, the Interaction to Next Paint (INP) metric suffers, which harms the Core Web Vitals (CWV) score of SvelteKit apps.
This PR adds a tiny pause inside the `click` handler before navigation. The combination of `requestAnimationFrame` and `setTimeout` allows the browser to repaint, but without creating a …
=> fix: yield main thread before navigating

.changeset/twelve-singers-bake.md, packages/create-svelte/bin.js
I don't think we ever really meant to make JSDoc the default or didn't put much thought into having it be the default. We've said that JSDoc is nice for libraries to avoid shipping sourcemaps, etc. But the calculus for applications is different and we should probably have TypeScript be the default there.
=> feat: make TypeScript the default for apps

.changeset/silent-planes-cry.md, packages/adapter-auto/package.json, packages/kit/package.json, packages/migrate/package.json, pnpm-lock.yaml
`import-meta-resolve` 4.0.0 uses the `fs.Stats` constructor, which is deprecated in Node 22, resulting in cryptic console spam when e.g. running `npx svelte-migrate self-closing-tags` if a local Svelte installation can't be found. It's fixed in 4.1.0
---
=> fix: bump import-meta-resolve

.changeset/cool-grapes-remain.md, packages/enhanced-img/types/ambient.d.ts, packages/enhanced-img/types/index.d.ts
---
Currently the type of an enhanced import is `string`, which is wrong. You can easily verify by logging the imported value. The correct type is `Picture`.
=> fix: use correct type for '*?enhanced' imports

documentation/docs/40-best-practices/07-images.md
Closes https://github.com/sveltejs/kit/issues/12213
It's probably better to use `eager: true` to avoid having to `await` the result
=> docs: more details for using import.meta.glob with enhanced-img

.changeset/sixty-dingos-invent.md, packages/create-svelte/shared/+playwright+default/tests/test.ts, packages/create-svelte/shared/+playwright+skeleton/tests/test.ts, packages/create-svelte/shared/+playwright+skeletonlib/tests/test.ts, packages/create-svelte/shared/+playwright/tests/test.ts
When you create a `Library project` with `playwrite` using `create-svelte`,  the default test case fails because the content of the H1 in a new `Library project` is different.
---
=> fix: update default playwright test case for lib-project

.npmrc, package.json, pnpm-lock.yaml
hopefully we can remove `package-manager-strict = false` at some point, but it looks like we need it for now
=> chore: upgrade to pnpm 9

pnpm-lock.yaml, sites/kit.svelte.dev/package.json, sites/kit.svelte.dev/src/routes/+layout.svelte
privacy-compliant way to track performance metrics on our sites
=> chore: enable Vercel speed insights on site

.changeset/rude-hairs-roll.md, packages/kit/src/core/postbuild/prerender.js, packages/kit/test/prerendering/basics/src/routes/prerender-origin/+page.svelte, packages/kit/test/prerendering/basics/src/routes/prerender-origin/[dynamic]/+page.svelte, packages/kit/test/prerendering/basics/svelte.config.js, packages/kit/test/prerendering/basics/test/tests.spec.js
Closes #12271 
Until now the crawler would not recoginze links that start with the value of `config.prerender.origin` as internal links & would not crawl them. This PR fixes that. 
For example: A link `<a href="https://my-site/base/some-page"` would not be crawled, even if `prerender.origin` was set to `https://my-site` in `svelte.config.js`. 
This is important since `<link rel="alternate"` requires links to be absolute URIs that include the protocol, so until now it was impossible for the crawler to discover pages that were linked to in valid `<link rel="alternate"` links. 
---
=> fix: crawl hrefs that start with `config.prerender.origin`

packages/kit/src/core/postbuild/fixtures/base/input.html, packages/kit/src/core/postbuild/fixtures/basic-href/input.html
Replaces the old `data-sveltekit-prefetch` attribute with `data-sveltekit-preload-code` in certain tests. This removes all mention of the attribute from the repository. (other than changelogs, of course)
---
=> chore: replace `-prefetch` with `-preload-code` in tests

.changeset/stupid-lies-remain.md, packages/adapter-vercel/index.d.ts, packages/adapter-vercel/index.js, packages/adapter-vercel/tsconfig.json
The `include` in the `tsconfig.json` was causing the index file in `adapter-vercel` not to be type checked. I removed it to type check all files. I added `images` to the edge config to get it to pass. @dummdidumm could you verify if that's correct?
=> fix: remove `images` from route-level config

.changeset/modern-deers-grab.md, eslint.config.js, packages/adapter-auto/index.js, packages/adapter-netlify/index.js, packages/create-svelte/index.js, packages/enhanced-img/src/index.js, packages/kit/postinstall.js, packages/kit/src/cli.js, packages/kit/src/core/sync/sync.js, packages/kit/src/core/sync/write_types/index.js, packages/kit/src/core/sync/write_types/index.spec.js, packages/kit/src/exports/hooks/sequence.spec.js, packages/kit/src/exports/node/index.js, packages/kit/src/exports/vite/build/build_service_worker.js, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/exports/vite/index.js, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/fetcher.js, packages/kit/src/runtime/client/utils.js, packages/kit/src/runtime/server/page/index.js, packages/kit/src/runtime/server/page/load_data.spec.js, packages/kit/src/runtime/server/page/respond_with_error.js, packages/kit/src/utils/fork.js, packages/kit/test/utils.js, packages/migrate/migrations/self-closing-tags/index.js, packages/package/src/index.js
#12284, without all the breaking changes and stuff
there's a cryptic error, i have no idea what this means:
```
/Users/rich/Development/SVELTE/KIT/kit/packages/adapter-vercel/index.js
0:0  error  Parsing error: "parserOptions.programs" has been provided for @typescript-eslint/parser.
The file was not found in any of the provided program instance(s): packages/adapter-vercel/index.js
```
=> chore: cleanup promise handling

eslint.config.js, packages/kit/test/apps/amp/playwright.config.js, packages/kit/test/apps/basics/src/routes/errors/init-error-endpoint/+server.js, packages/kit/test/apps/basics/src/routes/untrack/server/[x]/+page.server.js, packages/kit/test/apps/basics/src/routes/untrack/universal/[x]/+page.js
Turns out that eslint non-global ignores need a trailing `/**/*` while global ignores don't. Not the most intuitive API...
=> chore: reduce number of eslint global ignores

.changeset/witty-bees-hope.md, packages/kit/src/utils/http.js, packages/kit/src/utils/http.spec.js
Currently, using something like `Accept: application/my-custom-type,application/json;q=0.9` correctly returns errors as JSON. However, once you add a space to it, e.g. like `Accept: application/my-custom-type, application/json;q=0.9`, any errors messages returned use HTML instead of JSON.
According to [RFC 9110][1], in the HTTP Accept header, there can be OWS (optional whitespace, e.g. zero to unlimited SP (space) or HTAB (horizontal tab)) between the `;` and `,` characters.
If you go to [RFC 9110 § 12.5.1 Accept ¶ 3](https://www.rfc-editor.org/rfc/rfc9110#section-12.5.1-3):
> ```
>   Accept = #( media-range [ weight ] )
> 
>   media-range    = ( "*/*"
>                      / ( type "/" "*" )
>                      / ( type "/" subtype )
>                    ) parameters
> ```
Where …
=> fix: handle whitespace in HTTP Accept header

documentation/docs/10-getting-started/40-web-standards.md
Vercel Functions now have an isomorphic "web handler" signature, which means you can use the Web APIs mentioned in either runtime. For example:
```
export function GET(request: Request) {
return new Response('Hello World!');
}
```
https://vercel.com/docs/functions/quickstart
=> docs: Update web standards

.changeset/new-pianos-smash.md, packages/adapter-netlify/package.json, packages/adapter-node/package.json, pnpm-lock.yaml
This updates the version of `@rollup/plugin-commonjs` in the Node and Netlify adapters to remove their deprecated dependencies on `glob` and `inflight`.
=> chore: update to @rollup/plugin-commonjs@26

.changeset/tough-dingos-repeat.md, packages/adapter-auto/package.json, packages/adapter-cloudflare-workers/package.json, packages/adapter-cloudflare/package.json, packages/adapter-netlify/package.json, packages/adapter-node/package.json, packages/adapter-static/package.json, packages/adapter-vercel/package.json, packages/amp/package.json, packages/create-svelte/package.json, packages/enhanced-img/package.json, packages/kit/package.json, packages/migrate/package.json, packages/package/package.json
sveltekit is not showing up on npm search. thanks to @hyunbinseo for pointing this out in https://github.com/sveltejs/kit/pull/11846
=> chore: add keywords for discovery in npm search

documentation/docs/60-appendix/20-integrations.md
- Separate into the most used integrations and "Additional integrations"
- List `svelte-add` command directly on page
- Remove link to svelte add directory (https://github.com/svelte-society/sveltesociety.dev/commit/c549e9cd5708aa9045e994c451507eea5045b9ce)
- Remove explanation of what preprocessor is. It's too much info and the important info on the page gets lost. We can add a better explanation on svelte.dev and link there in the future. For now I just rewrote the vitePreprocess description to be understandable without that intro paragraph
=> docs: overhual integrations page

sites/kit.svelte.dev/scripts/types/index.js
- make sure an undefined `tag.comment` doesn't result in the actual string "undefined"
- make sure name property gets a proper string in more cases
=> docs: type generation script fixes

.changeset/old-jars-work.md, packages/create-svelte/bin.js
Rather than telling people about a web page, we should try to help them remember what the command is
It also removes the noisy output, which just buries the info we want people to see. People aren't going to remember those URLs when they want to find the docs. They'll just google it.
=> chore: remove noisy output and update text about svelte-add

.changeset/tough-actors-hope.md, packages/kit/src/runtime/app/server/index.js
I was wrong in #12341 — it _is_ necessary to decode asset URLs in prod, because files can be emitted with e.g. spaces in them. No test because it'd be finicky and annoying and I'm tired, but this has been tested locally and is very unlikely to regress
---
=> fix: always decode asset URLs

.changeset/lovely-dancers-search.md, packages/kit/postinstall.js, packages/kit/src/core/sync/utils.js, packages/kit/src/exports/vite/index.js, packages/kit/src/utils/import.js, scripts/sync-all.js
It's currently impossible to develop a Svelte 5 project with a linked SvelteKit installation, because the `sync` script wrongly believes it's dealing with Svelte 4 (which is a dev dependency inside SvelteKit). This fixes it.
I added a changeset because it's a change, but it doesn't actually require a release since the problem it solves only arises when you're working with the repo directly.
---
=> fix: determine local Svelte version more reliably

.changeset/cuddly-mails-argue.md, packages/adapter-node/src/index.js
Because the timer IDs are always cleaned up and set to `undefined` while the custom cleanup hook is running, it can happen that a shutdown timeout is created twice.
---
=> fix: do not create more than one shutdown timeout

documentation/docs/20-core-concepts/40-page-options.md
There's some info missing regarding prerendering and ssr needing to both be enabled to have links discoverable by the prerenderer. This causes users some trouble as they need to discover this for themselves. https://github.com/sveltejs/kit/discussions/8688#discussioncomment-9465858
It may have been in our docs at some point but got removed as shown by the documentation link in this older issue that does not work https://github.com/sveltejs/kit/issues/9913#issuecomment-1552089872
---
=> docs: note that the prerenderer can't crawl pages that have SSR disabled

documentation/docs/50-reference/40-types.md
Clarifies that Typescript is required as a dependency for generated types to be created. When the dependency is missing they are silently omitted. This requirement may not be obvious to those who are running a vanilla JavaScript project and have not used the scaffolding script (e.g. because they migrated from an earlier version of SvelteKit).
I came across this issue because I migrated from an alpha version and spent a while scratching my head before realising why the new generated types were not working for me.
---
=> docs: update requirements for generated types

documentation/docs/25-build-and-deploy/40-adapter-node.md
- Node.js v20 LTS started in v20.9.0: [release post](https://nodejs.org/en/blog/release/v20.9.0)
- The `--env-file` flag was added in Node.js v20.6.0: [release post](https://nodejs.org/en/blog/release/v20.6.0)
- It is the advised way of importing environment variables: [official guide](https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs)
---
=> docs: replace `dotenv` with `--env-file`

documentation/docs/30-advanced/10-advanced-routing.md
Fixes https://github.com/sveltejs/kit/issues/11934
---
=> docs: update pattern matcher type

.changeset/angry-spies-rule.md, packages/adapter-cloudflare/index.js
Close #12321 
I don't know if it was the best choice, but I opted for throw error only if `_routes.json` exists and there are no configured routes in svelte.config.
Let me know if you think Changelogs should be generated.
I don't think it's related, but `pnpm test` fails on
```diff
Watching src/lib for changes...
✘ • • • •   (14 / 15)
FAIL  "watches for changes"
Expected values to be deeply equal:  (equal)
Actual:
--<script·lang="ts">export·let·answer:·number</script>
Expected:
++<script>export·let·answer;
++</script>
@sveltejs/package@2.3.2 test: `uvu test "^index.js$"
```
---
=> feat: throw error if routes are configured in _routes.json

documentation/docs/30-advanced/67-shallow-routing.md
On Windows, `Ctrl` clicking an anchor opens it in a new tab.
Checking for `e.metaKey` only checks for the Windows key.
```js
// bail if opening a new tab, or we're on too small a screen
if (e.metaKey || innerWidth < 640) return;
// Added ctrlKey check
if (e.metaKey || e.ctrlKey || innerWidth < 640) return;
```
Originally suggested in [Huntabyte's video](https://youtu.be/B19DEGEclfk?si=nXxc_4_C-U_sdxeb&t=365) starting at 6:00.
---
=> docs: consider ctrl clicking an anchor

.changeset/great-hats-cough.md, documentation/docs/25-build-and-deploy/40-adapter-node.md, packages/adapter-node/src/handler.js
This PR adds unit suffixes support to the adapter-node `BODY_SIZE_LIMIT` environment variable.
Currently, achieving large byte values is only achievable with the exact byte value, and using exponents (like `1e6` to be parsed by Number) results in a byte value in base 10.
Nginx and Cloudflare both use base 2 for byte calculations (1024 based):
Nginx (source code): https://hg.nginx.org/nginx/file/default/src/core/ngx_parse.c
Cloudflare (forum question): https://community.cloudflare.com/t/is-max-upload-size-mb-1024-or-1000/239102
Adding unit suffixes to the byte values will make it easier to write and comprehend large byte values, as they can be written such as `100M` instead of `104857600`
Nginx also supports the size units `K` and `M` (https://nginx.org/en/docs/syntax.html) so it would be …
=> feat: add unit suffix support for `BODY_SIZE_LIMIT`

documentation/docs/60-appendix/25-debugging.md
Closes #7781, relates to #1144
- Add breakpoint debugging documentation to the 'appendix' section
While testing with the Node.js inspector, I tried to enable server-side breakpoint debugging, but was not successful. The sourcemaps are being generated, but only client-side code connect to chrome devtools. VSCode breakpoint debugging works well.
I'm hoping there could be a way to debug server-side code within chrome devtools as well, which would help developers who aren't using VSCode, but I'm unsure whose domain this falls in: SvelteKit, Vite, or something else.
---
=> docs: add breakpoint debugging guide

documentation/docs/60-appendix/25-debugging.md
#12212 added a guide for debugging svelte applications.
while vscode is probably the most used editor and thus deserves an official guide in the documentation, I thought maybe it could be helpful to point users of other editors to helpful community resources that explain how to debug with other IDEs.
I included guides for `webstorm` and `neovim`. (full disclosure: I am the author of the neovim guide, however I think it's the only one out there. hope this doesn't come over as shady self promotion)
---
- [ x Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`
=> docs: add `Other Editors` section to debugging documentation

documentation/docs/20-core-concepts/10-routing.md
I had to coach a Svelte newcomer about this recently, and created this "chart" for him to better understand what file he *actually* needed to create and the differences between them, without him having to read the whole docs (he is not super proficient in English unfortunately).
Turns out he understood it quite well, so I think it can be a good addition for other people that might need a quick reference 🙏
---
- ~[ ] Ideally, include a test that fails without this PR but passes with it.~ (N/A: docs)
- ~[ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`~ (N/A: docs)
- ~[ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add …
=> docs: summarize behavior of routes files

.changeset/slimy-eyes-pull.md, packages/kit/src/utils/filesystem.js, packages/kit/src/utils/filesystem.spec.js
Server side code inside a `src/hooks.server` folder can result in the build trying to import the code into client side code, usually causing the build to break.
Reproduction: https://www.sveltelab.dev/egkmtnbmy05petz (execute `npm run build`)
It's due to the file suffix being stripped off so `hooks.server` matches a search for `hooks` when the code is looking for universal hooks. This makes the suffix matching stricter to only strip `.js` or `.ts` (AFAICT, those are the only things that should ever be matched with this fn).
Fixes: https://github.com/sveltejs/kit/issues/11754
---
=> fix: prevent `hooks.server` code being imported into client during build

documentation/docs/30-advanced/70-packaging.md
Small typo [here on the svelte-package docs](https://kit.svelte.dev/docs/packaging#options) that has `-o/--o` instead of `-o/--output`. The CLI --help prints the correct info and the flag works as expected.
---
=> docs: typo for svelte-package --output flag

package.json, pnpm-lock.yaml
removes 20 or 30 packages by switching to `eslint-plugin-n`
=> chore: switch to `eslint-plugin-n` and upgrade dependencies

packages/adapter-netlify/package.json
Hey there 👋 
The build script for the `@sveltejs/adapter-netlify` currently fails on Windows, because of the `cp` command, which is only available in unix shells:
Changing `cp` to `fs.cpSync` makes the script cross-platform.
---
=> chore: make build script runnable on Windows

packages/kit/package.json, pnpm-lock.yaml
The types are included in `sade` directly now
=> chore: remove deprecated package

.changeset/silver-bears-melt.md, packages/adapter-cloudflare-workers/index.js, packages/adapter-cloudflare/index.js, packages/adapter-netlify/index.js, packages/adapter-vercel/index.js
closes https://github.com/sveltejs/kit/pull/11219
fixes https://github.com/sveltejs/kit/issues/11220
Copies `.ttf` and `.woff` font files when bundling edge functions since those are the most common font files included with packages. Alternatively, we could use the same list of assets as [Vite](https://github.com/vitejs/vite/blob/22b299429599834bf1855b53264a28ae5ff8f888/packages/vite/src/node/optimizer/esbuildDepPlugin.ts#L25-L48).
---
=> fix: copy `.eot`, `.otf`, `.ttf`, `.woff`, and `woff2` font files when bundling

.changeset/afraid-llamas-build.md, packages/enhanced-img/package.json, packages/enhanced-img/types/ambient.d.ts
#12224 changes the default export of `*?enhanced` modules from a value of type `string` into a value of type `Picture` (from `vite-imagetools`). However, this change caused the `ambient.d.ts` file to no longer be an ambient module. [According to the TypeScript docs](https://www.typescriptlang.org/docs/handbook/modules/reference.html#ambient-modules), top-level imports and exports automatically upgrade the ambient context into a module context. That means the `declare module '*?enhanced'` is no longer applied "ambiently", but now requires an explicit import somehow. This breaks `svelte-check` and other static analysis tooling because TypeScript would report that any module imported as `*?enhanced` have no existing type declarations.
The fix is quite simple: simply move the top-level …
=> fix(enhanced-img): preserve ambient context for `*?enhanced` imports

renovate.json
Hi there, I noticed a few things could be fixed in the `renovate.json` config:
- This repository was deprecated: https://github.com/whitesource/merge-confidence
- It is no longer necessary to manually enable merge-confidence, since it is enabled automatically when the renovate bot is used: https://docs.renovatebot.com/merge-confidence/#enabling-and-disabling
- This preset was renamed to `"config:recommended"` in this PR: https://github.com/renovatebot/renovate/pull/21136
---
=> ci(renovate): Update renovate `"extends"` config

.changeset/slow-beans-develop.md, packages/create-svelte/shared/+typescript/package.json, packages/create-svelte/templates/skeletonlib/package.template.json
[`tslib`](https://github.com/Microsoft/tslib) was added to the Svelte codebase in https://github.com/sveltejs/svelte/pull/920 but the [`--importHelpers`](https://www.typescriptlang.org/tsconfig/#importHelpers) option since disappeared from the `tsconfig` during the split in https://github.com/sveltejs/svelte/pull/2994. This option as well as [downlevelling](https://www.typescriptlang.org/tsconfig/#downlevelIteration) are also not set by `create-svelte`. 
So this library is unused, and there is no need to keep it. This PR removes it.  
---
- [x ] This message body should clearly illustrate what problems it solves.
- [ x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.
=> fix: remove unnecessary `tslib` dependency

packages/kit/test/apps/basics/test/client.test.js
I think our tests have been flaky ever since https://github.com/sveltejs/kit/pull/11311
It's an easy fix, but I didn't know this test was flaky because GitHub was burying the logs. Thankfully @eltigerchino realized there were other errors in the logs that I didn't see
`page.click` won't wait for the navigation to complete where as `clicknav` will
=> chore: fix flaky test

.changeset/dry-mirrors-shout.md, packages/adapter-cloudflare-workers/files/entry.js, packages/adapter-cloudflare-workers/index.js, packages/adapter-cloudflare-workers/placeholders.d.ts, packages/adapter-cloudflare/index.js, packages/adapter-cloudflare/placeholders.d.ts, packages/adapter-cloudflare/src/worker.js
fixes https://github.com/sveltejs/kit/issues/12060
Exports the base path of the project so we can remove the base path from the request URL pathname when matching against the static asset filenames in the manifest that are saved without the base path.
might add some tests later just because the path matching has proven to be error prone
---
=> fix: correctly match asset filenames if base path is set

packages/kit/test/apps/basics/test/cross-platform/client.test.js
Let's see if waiting for the download event makes it less flaky.
EDIT: seems less flaky? will try re-running the CI a couple of times. Seems to only error on other flaky tests.
---
=> chore: fix flaky download test

.changeset/yellow-queens-shop.md, eslint.config.js, packages/create-svelte/shared/+eslint+prettier+typescript/eslint.config.js, packages/create-svelte/shared/+eslint+prettier-typescript/eslint.config.js, packages/create-svelte/shared/+eslint+typescript/eslint.config.js, packages/create-svelte/shared/+eslint-typescript/eslint.config.js, packages/create-svelte/shared/+eslint/package.json
Fixes https://github.com/sveltejs/kit/issues/12109
`@types/eslint` v9 has been released.
The `FlatConfig` type is [deprecated](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/23fde1f04766f759428a6302a9ee107200391429/types/eslint/index.d.ts#L1280-L1281
).
```ts
/** @deprecated  Use `Config` instead of `FlatConfig` */
type FlatConfig = Config;
```
---
=> chore: bump @types/eslint to v9

.changeset/lemon-pugs-film.md, packages/create-svelte/templates/default/package.json, packages/create-svelte/templates/default/package.template.json, pnpm-lock.yaml
I don't really understand why we need the dependency in both `package.json` and `package.template.json`?
=> chore: upgrade to @fontsource/fira-mono v5 and @neoconfetti/svelte v2

.changeset/cyan-hounds-refuse.md, packages/kit/src/core/sync/write_root.js
Closes #12573
Again i'm not really sure if and where i should add a test for this. Also for the moment i did not rename `constructors` to something else in svelte 5 because there was still the possibility to share some code but i'm willing to completely split the two branches if we feel like.
=> fix: use dynamic components in `root.svelte` instead of `svelte:component` for svelte 5

.changeset/thick-spies-hope.md, packages/create-svelte/shared/+svelte5/package.json, packages/create-svelte/test/check.js
this helps to avoid a peer warning during npm install where vite-plugin-svelte@3 still depends on svelte-hmr for svelte4 support, but svelte-hmr does not have a peer range supporting svelte5 (it can't, hmr support is built into svelte5 instead).
Also svelte5 users should use vite-plugin-svelte@4 because that has better support.
---
=> chore(deps): use vite-plugin-svelte 4 in svelte5 template of create-svelte

.changeset/serious-eyes-rule.md, packages/create-svelte/templates/skeletonlib/package.template.json
The library template is still using publint v0.1.
There is not CLI breaking changes from v0.1 to v0.2.
https://github.com/bluwy/publint/releases/tag/v0.2.0
---
=> chore: bump publint to v0.2

.changeset/red-ladybugs-press.md, packages/kit/src/core/sync/write_tsconfig.js
The [docs](https://kit.svelte.dev/docs/service-workers) state that the service worker can be located at `src/service-worker.js` or as an `index.js` file within the `src/service-worker` directory.
Without this fix users who place the file within the directory run into Typescript errors like [#11721](https://github.com/sveltejs/kit/issues/11721)
Follow up to [#11727](https://github.com/sveltejs/kit/pull/11727)
Question for maintainers: Should all js/ts files in the `service-worker` directory be excluded or only `index.js|ts|d.ts`? 
---
=> fix: exclude service worker directory from tsconfig

.changeset/shiny-suns-scream.md, packages/kit/src/runtime/server/respond.js
This ought to fix #11996
Only if `DEV`, config is an empty object and prerender is set to `false` so that `event.platform` can be emulated.
I believe this will improve the development experience by preventing 500 errors and allowing development to occur in a more local development environment similar to the production environment.
---
=> fix: emulate `event.platform` during development even if route is undefined

documentation/docs/20-core-concepts/20-load.md
closes https://github.com/sveltejs/kit/issues/12654
---
=> docs: clarify load `parent()` behaviour

.changeset/big-vans-destroy.md, packages/kit/src/runtime/client/client.js
Adjusts the behavior to that of the new `mount`/`hydrate` APIs and also fixes #12248
=> fix: asynchronously instantiate components when using Svelte 5

.changeset/friendly-wasps-return.md, packages/enhanced-img/src/preprocessor.js, packages/enhanced-img/test/Output.svelte
Depends on variable inlining being implemented in Svelte 5. See https://github.com/sveltejs/svelte/pull/13075
=> perf: hoist vite asset declarations to module block

.changeset/great-cooks-hunt.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/routing/form-target-blank/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js
fixes https://github.com/sveltejs/kit/issues/11931
This PR ensures that our client submit event listener allows the browser to make a native form submission to open a new tab if a form or button has the `target="_blank"` or `formtarget="_blank"` attribute. This should open the form response in a new tab for both GET and POST submissions.
Afaik the other `target` values such as `_parent` and `_top` should function similarly to `_self` where we just want to update the current page without refreshing (even if Kit is in an iframe).
---
=> fix: allow native form submission for `<form target="_blank">` and `<button formtarget="_blank">` 

.changeset/strong-peaches-arrive.md, packages/kit/package.json, pnpm-lock.yaml
Adds support for returning typed arrays and array buffers from `load` functions. Not something to over-use, since it uses base64 encoding which is 33% larger than the raw data, but useful when you need it.
Thanks for @LorisSigrist for implementing this in https://github.com/Rich-Harris/devalue/pull/69. No test because it's a `devalue` feature
---
=> feat: support typed arrays in `load` functions

.changeset/breezy-ravens-reply.md, packages/kit/src/runtime/client/client.js
closes #11466 ~~and #11492~~
Not sure if this needs a test.
IMO, this error should be thrown in production as well. Any opinions?
---
=> fix: better error message when calling push/replaceState before router is initialized

documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
Fixed a very slight indentation problem with the Cloudflare Worker adapter docs, where spaces were used for indentation instead of tabs. Previously, two lines of the example configuration were mis-aligned.
---
=> docs: whitespace in cloudflare worker adapter docs

.changeset/dry-feet-wink.md, packages/migrate/migrations/svelte-5/index.js, packages/migrate/migrations/svelte-5/migrate.js
Companion PR for https://github.com/sveltejs/svelte/pull/13504
if we decide to merge we can pass the filename to allow the migration script to migrate `svelte:self` which is deprecated in svelte 5. I've tested it locally and it seems to work fine but i'm not sure if i should add some proper test (and where.
=> feat: pass filename to `migrate`

.changeset/warm-moose-argue.md, packages/migrate/migrations/svelte-5/index.js
closes https://github.com/sveltejs/svelte/issues/13462
=> fix: prompt SvelteKit 2 migration during Svelte 5 migration if necessary

.changeset/curly-crews-hide.md, packages/adapter-vercel/index.d.ts
The default is not node18 as advertised but guessed at build time with the `get_default_runtime` function
---
=> fix: updated `@default` annotation for runtime

.changeset/rude-shirts-raise.md, packages/kit/src/utils/url.js
fixes https://github.com/sveltejs/kit/issues/11482
Since `URL.searchParams` is an object too, we needed to make the tracked property loggable, similar to the `URL` object itself. This prevents the crashing when logging it in the server load.
---
=> fix: add node custom inspect for `URL.searchParams`

.changeset/tame-steaks-deliver.md, packages/kit/package.json, pnpm-lock.yaml
reverts https://github.com/sveltejs/kit/pull/12746 . The major contains a breaking change where `:` characters are no longer allowed in cookie names
---
=> chore: revert cookie upgrade

packages/kit/src/exports/vite/dev/index.js
Vite should handle an error here, so we shouldn't need our own handling
=> chore: remove unnecessary try/catch

.changeset/spotty-bananas-act.md, packages/kit/src/exports/public.d.ts, packages/kit/src/types/synthetic/$lib.md, packages/kit/types/index.d.ts
Links in JSDoc comments can't be root-relative, they need to be relative to https://kit.svelte.dev
---
=> use absolute links in JSDoc comments

documentation/docs/20-core-concepts/30-form-actions.md
This PR aims to improve the documentation by explicitly stating that `use:enhance` is only compatible with forms using `method="POST"`. Despite the fact that using `use:enhance` with other methods should [throw an error](https://github.com/sveltejs/kit/blob/feb01542edd542366043bc4f3b1994e3fdb46345/packages/kit/src/runtime/app/forms.js#L73), this limitation isn't clearly communicated in the current documentation.
This lack of clarity has led to misuse in several prominent projects, including:
- [storybook](https://github.com/storybookjs/storybook/blob/next/code/frameworks/sveltekit/template/stories_svelte-kit-skeleton-ts/Forms.svelte#L5)
- [sveltekit-superforms](https://github.com/ciscoheat/sveltekit-superforms/blob/429708d579b161a6461c82837f839bef1f1badfc/src/routes/(v2)/v2/spa-action-2/%2 …
=> docs: clarify `use:enhance` compatibility with `method="POST"`

.changeset/large-planes-tan.md, packages/kit/src/constants.js, packages/kit/src/exports/vite/index.js
This reverts commit 3591411e880ed5337123c66365433afe8c2f747b.
#12700 did introduce a bug where the file name stays the same, but the contents of a file can change because of a changed version. Revert for now and take another look at tackling this later.
Fixes #12771
Reopens #12260
=> Revert "fix: replace version in generateBundle (#12700)"

.changeset/polite-games-smash.md, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/runtime/server/utils.js
@paoloricciuti 's solution in https://github.com/sveltejs/kit/pull/10638 helps catch the anonymous Vite error (shown below) that appears in web containers such as stackblitz, sveltekit.new , etc. Instead, it returns the original unfixed stack trace in the event that it is unable to fix the stack trace.
```
Error: `line` must be greater than 0 (lines start at line 1)
```
Although, the returned stack trace line number reported is unfixed, it's better than not having any useful errors reported.
---
=> fix: catch stack trace fixing errors thrown in web containers

.changeset/calm-fireants-hug.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/routing/hashes/a/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js
fixes https://github.com/sveltejs/kit/issues/10234
By avoiding preloading pages where the URL pathname and search params (the load ID) are unchanged, we also avoid mistakenly caching navigation results for hash URLs. Currently, these are ID'd the same as URLs without hashes, causing navigation to lose track of the current URL (hence the original issue).
This should be a good solution because:
1. if we're on already on the page we don't need new load results for it.
2. even if the load results are suppose to be different for the same URL, clicking on a link that leads to the exact same URL already does nothing.
---
=> fix: only preload link if the URL differs from current page

.changeset/kind-rabbits-talk.md, packages/migrate/migrations/svelte-4/migrate.js, packages/migrate/migrations/sveltekit-2/migrate.js, packages/migrate/package.json, pnpm-lock.yaml
The error made it seem like `.getParent()` started returning ImportDeclaration or JSDoc, so I'm checking if it's returning an ImportDeclaration. I don't know if this is right and VS Code was only showing the ImportDeclaraction being returned and not the JSDoc so please check if this is the correct fix
=> chore: upgrade to ts-morph 23

.changeset/young-toes-flow.md, packages/migrate/migrations/svelte-4/migrate.js, packages/migrate/migrations/sveltekit-2/migrate.js, packages/migrate/package.json, pnpm-lock.yaml
Supports TypeScript 5.6 and removes a bunch of dependencies
=> chore: upgrade to ts-morph 24

.changeset/breezy-poems-act.md, packages/adapter-node/rollup.config.js
This adjusts the bundling of the Node adapter so that imports from bundled dependencies (sirv, totalist) are converted into their `node:` versions, without needing code changes in those libraries. Fixes #12783.
---
=> fix: use `node:` imports in adapter-node to support Deno

.changeset/clean-wolves-bathe.md, documentation/docs/30-advanced/70-packaging.md, packages/create-svelte/templates/skeletonlib/package.template.json
We should encourage good practices by default. This makes a huge difference when I applied it to `site-kit`
Also removed "-" from "side-effects": https://english.stackexchange.com/questions/364613/side-effects-or-side-effects
=> feat: mark scripts in libraries as being side effect free by default

documentation/docs/25-build-and-deploy/90-adapter-vercel.md
Added note to the Vercel page to make it explicit that page render options cannot be used with Vercel ISR config.
---
=> docs: add note to vercel isr on prerender page options conflict

.changeset/unlucky-cars-swim.md, packages/kit/src/runtime/client/client.js
this patch adds a function that tries to update the service worker (if it exists), and calls it when sveltekit detects that a new version has been deployed.
i'm not sure if this is the right place to put this -- i considered putting it in the body of check(), but it feels wrong to me. if you think it's a good idea, let me know and i'll update it.
closes #3667
---
=> feat: update service worker when new version is detected

packages/kit/src/exports/public.d.ts, packages/kit/types/index.d.ts
Adds an example to the CSP documentation of the `report-uri` directive which is required and found similarly in our own kit test app. Currently, using the [example provided by the docs](https://kit.svelte.dev/docs/configuration#csp), gives this error message:
```sh
Error: `content-security-policy-report-only` must be specified with either the `report-to` or `report-uri` directives, or both
at new CspReportOnlyProvider (/home/chewteeming/my-app/node_modules/.pnpm/@sveltejs+kit@2.6.4_@sveltejs+vite-plugin-svelte@3.1.2_svelte@4.2.19_vite@5.4.8__svelte@4.2.19_vite@5.4.8/node_modules/@sveltejs/kit/src/runtime/server/page/csp.js:319:11)
at new Csp (/home/chewteeming/my-app/node_modules/.pnpm/@sveltejs+kit@2.6.4_@sveltejs+vite-plugin-svelte@3.1.2_svelte@4.2.19_vite@5.4.8__svelte@4.2.19_vite@5.4.8 …
```
=> docs: add report uri directive to CSP example

.changeset/smooth-dogs-travel.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/anchor/anchor/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js
This PR adds a missing `decodeURIComponent(hash)` in the same hash scrolling code to make sure non ascii hashes scroll properly. This exists for normal clicking code but is missing in the same hash code.
I have no idea how to write a test for this but here is code that can be checked in the playground:
<details>
<summary>Code</summary>
```ts
<nav>
<a href="#一">一</a>
<a href="#2">2</a>
<a href="#three">three</a>
<a href="#go-to-encöded">Anchor demo (non-ASCII)</a>
<a href="#go-to-.=">Anchor demo (special characters)</a>
<a href="#4">四</a>
<a href="#五five">五</a>
</nav>
<div class="scroll-container">
<div class="scroll-page" id="一"><a href="#一">一</a></div>
<div class="scroll-page" id="2">2</div>
<div class="scroll-page" id="three">three</div>
<div class="scroll-page" …
```
=> fix: decode hash when clicking on same hash to correctly scroll on non ascii hashes

.changeset/many-cats-breathe.md, packages/kit/src/runtime/server/page/index.js
Fixes #11757.
As described in #11757, when SSR is disabled the values / errors returned from form actions get lost, because the CSR shell is always empty.
This behaviour is correct but can be confusing, if one forgets `use:enhance` on the form (been there, done that).
As proposed in https://github.com/sveltejs/kit/issues/11757#issuecomment-2013135714, I've added warnings that explain why the desired behaviour didn't occur and how to fix it.
I'm also not sure if such warning needs a test, if yes, I'll try to add it. :)
---
=> fix: add warning for form action responses lost without SSR

.changeset/curvy-bugs-wait.md, packages/migrate/migrations/svelte-5/migrate.js, packages/migrate/migrations/svelte-5/migrate.spec.js
Adds `svelte-eslint-parser` to the list of migratable dependencies. One of the problem we might face is that people are just using this in the eslint config transitively but i guess it's still better have it than not.
---
=> chore: add `svelte-eslint-parser` to list of migratable dependencies

.changeset/eighty-starfishes-rule.md, packages/migrate/migrations/svelte-5/index.js, packages/migrate/migrations/svelte-5/migrate.js, packages/migrate/migrations/svelte-5/migrate.spec.js
We can now use latest for `svelte` and `@sveltejs/vite-plugin-svelte` in the migration tool!
---
=> fix: migrate `svelte` and `vite-plugin-svelte` to latest

.changeset/shy-seals-draw.md, packages/migrate/migrations/svelte-5/migrate.js
I just ran the migration tool on my small site and this was the only issue I encountered :smile:
=> fix: bump enhanced-img version to avoid peer dep warning

.changeset/serious-geckos-itch.md, packages/adapter-auto/index.js
Adds support for Bun package manager with `@sveltejs/adapter-auto`. 
Initially, I considered adding `svelte-adapter-bun` to the plugin list, but since Bun works seamlessly with Node.js, it wasn't necessary!
---
=> feat: `adapter-auto` support `bun add`

documentation/docs/10-getting-started/10-introduction.md, documentation/docs/20-core-concepts/10-routing.md, documentation/docs/20-core-concepts/20-load.md, documentation/docs/20-core-concepts/30-form-actions.md, documentation/docs/20-core-concepts/40-page-options.md, documentation/docs/20-core-concepts/50-state-management.md, documentation/docs/30-advanced/10-advanced-routing.md, documentation/docs/30-advanced/20-hooks.md, documentation/docs/30-advanced/25-errors.md, documentation/docs/30-advanced/50-server-only-modules.md
6c6e86df4ece3eb18e29782ea55400b6946a8908 (and maybe others, not sure) broke some links. This PR fixes some of them, but not all — not sure how many are still broken just yet because of #12859
=> docs: fix links

.changeset/healthy-planets-dance.md, packages/kit/src/runtime/server/page/actions.js
closes #12787
Adds a check to see if the data being returned is a `Response` object (such as with the helper method `json()`), then replies with a more helpful error message.
---
=> fix: explain why `json()` cannot be used in form actions

.changeset/dry-cows-smash.md, packages/kit/src/exports/vite/index.js, packages/kit/test/apps/dev-only/test/test.js
closes https://github.com/sveltejs/kit/issues/12550
Uses the `resolveId` hook to get the importer name before including it in the error message when loading the illegal import in the `load` hook.
However, I couldn't figure how to get this working for server only imports since those don't trigger the `resolveId` hook. (at least when I was running console logs to see if it did trigger it).
---
=> fix: include importer in illegal import error message

.changeset/eight-insects-live.md, packages/kit/src/runtime/server/fetch.js
closes https://github.com/sveltejs/kit/issues/12868
This PR reverts a part of the change from https://github.com/sveltejs/kit/pull/12113. The issue is caused by the `read` implementation trying to read the static asset from the server during a `fetch`, but it doesn't work since the static asset isn't packaged with the serverless function. I think having the distinction between `fetch` and `read` is good here.
https://github.com/sveltejs/kit/blob/dcbe4222a194c5f90cfc0fc020cf065f7a4e4c46/packages/kit/src/runtime/server/fetch.js#L100-L110
---
=> fix: revert using server read for load function fetch

documentation/docs/20-core-concepts/10-routing.md, documentation/docs/20-core-concepts/20-load.md, documentation/docs/20-core-concepts/30-form-actions.md, documentation/docs/20-core-concepts/50-state-management.md, documentation/docs/25-build-and-deploy/90-adapter-vercel.md, documentation/docs/30-advanced/10-advanced-routing.md, documentation/docs/30-advanced/65-snapshots.md, documentation/docs/30-advanced/67-shallow-routing.md, documentation/docs/98-reference/26-$lib.md, packages/kit/src/exports/public.d.ts, packages/kit/types/index.d.ts
closes https://github.com/sveltejs/svelte.dev/issues/549
fixes some leftovers, adds a few callouts to legacy syntax
=> docs: more Svelte 5 conversion

documentation/docs/20-core-concepts/20-load.md
> Setting the same header multiple times (even in separate load functions) is an error
> you can only set a given header once.
No, the same header can be set on a server `handle` function.
In-fact, it will override it. (which is expected and intended)
```ts
// src/routes/+page.server.ts
export const load = ({ setHeaders }) => {
setHeaders({ Server: 'A' });
};
```
```ts
// src/hooks.server.ts
import type { Handle } from '@sveltejs/kit';
export const handle: Handle = async ({ event, resolve }) => {
const response = await resolve(event);
response.headers.set('Server', 'B');
return response;
};
```
Specifying that `setHeaders` cannot be called twice with the same key will clarify this.
---
=> docs: elaborate on duplicate setHeaders calls

.changeset/fast-crews-smash.md, packages/kit/src/runtime/client/client.js
closes https://github.com/sveltejs/kit/issues/12510
Adds the suggested check for the `event.defaultPrevented` property to the client `ontouchstart` and `onmousedown` events akin to our `onclick` listener. See the well explained thoughts in https://github.com/sveltejs/kit/issues/12510#issue-2433697602
---
=> fix: avoid preload if event default was prevented

documentation/docs/20-core-concepts/20-load.md
Follow-up for:
- https://github.com/sveltejs/kit/issues/12473
- https://github.com/sveltejs/kit/pull/12474
Explicitly commented that:
1. the `setHeaders` function only has effect on the server
2. the HTML response will have the response headers set
Assumption:
- If the universal load function ran on the server, it's probably SSR.
---
=> docs: elaborate on setHeaders in SSR

documentation/docs/20-core-concepts/20-load.md, documentation/docs/20-core-concepts/30-form-actions.md
Small PR to clear the 'In Svelte 4' bug in docs : 
In `Loading data` and `Form actions`
---
=> docs: delete the 'In Svelte 4' redundancy in the doc.  

.github/workflows/sync-request.yml
this means that merges to `main` will trigger docs PRs on svelte.dev
=> chore: add sync request workflow

.changeset/spicy-cars-cheer.md, packages/adapter-vercel/index.js, packages/migrate/migrations/svelte-5/migrate.js, packages/migrate/migrations/svelte-5/migrate.spec.js, packages/migrate/migrations/sveltekit-2/migrate.js, packages/migrate/utils.js
fixes https://github.com/sveltejs/svelte/issues/13816
---
=> fix: prevent duplicate imports

.changeset/stale-moons-walk.md, packages/enhanced-img/src/preprocessor.js, packages/enhanced-img/test/Input.svelte, packages/enhanced-img/test/Output.svelte
New enhanced-img update does not traverse into RegularElement AST nodes, completely breaking all `<enhanced:img />` elements not at the top level. This fixes that.
---
=> fix: fix nested images in enhanced-img

.github/workflows/docs-preview-create-request.yml, .github/workflows/docs-preview-delete-request.yml
This allows preview deployments to be created for PRs from external contributors
=> chore: use pull_request_target instead of pull_request event in workflows

.changeset/unlucky-walls-drum.md, packages/kit/src/exports/node/index.js, packages/kit/src/exports/vite/index.js
closes https://github.com/sveltejs/kit/issues/11365
cc: @Conduitry @benmccann 
This PR gets the Vite HTTPS working again by filtering out two types of keys from the incoming request headers object before we pass it to a new `Request` object. Doing so prevents the two errors we currently encounter as shown below.
1. When there's a symbol key in the request headers:
```sh
TypeError: Request constructor: init.headers is a symbol, which cannot be converted to a DOMString.
at webidl.errors.exception (node:internal/deps/undici/undici:3384:14)
at webidl.converters.DOMString (node:internal/deps/undici/undici:3650:29)
at webidl.converters.ByteString (node:internal/deps/undici/undici:3658:35)
at Object.record<ByteString, ByteString> (node:internal/deps/undici/undici:3567:30)
at …
```
=> fix: set no-op proxy config to get Vite HTTPS working

.changeset/thick-mails-wonder.md, packages/kit/src/exports/public.d.ts, packages/kit/src/types/ambient.d.ts, packages/kit/types/index.d.ts
necessary to fix https://github.com/sveltejs/svelte.dev/pull/791, will expedite a release once green
=> fix: update broken links in JSDoc

documentation/docs/60-appendix/10-faq.md
basically every part of this FAQ is outdated
closes https://github.com/sveltejs/kit/issues/12985
=> docs: remove outdated FAQ

.github/workflows/ci.yml, CONTRIBUTING.md
to help test new features like the websocket PR
=> chore: setup pkg.pr.new

documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md, documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md, documentation/docs/30-advanced/25-errors.md
Not sure this is the right change but the file name doesn't look right without it.
Before:
After:
---
=> docs: fix title for the code block

.changeset/shy-needles-warn.md, packages/kit/src/exports/node/index.js, packages/kit/src/exports/vite/index.js, packages/kit/src/exports/vite/preview/index.js
closes https://github.com/sveltejs/kit/issues/11365
=> fix: support custom servers using HTTP/2 in production

documentation/docs/20-core-concepts/10-routing.md, documentation/docs/20-core-concepts/20-load.md, documentation/docs/20-core-concepts/30-form-actions.md, documentation/docs/30-advanced/67-shallow-routing.md
Use svelte 5 syntax for event handler in documentation.
---
=> docs: use svelte 5 syntax

.changeset/long-rivers-stare.md, documentation/docs/25-build-and-deploy/90-adapter-vercel.md, packages/adapter-vercel/index.js
Also adjust the validation logic to not care at all when building on Vercel, to not have to update the adapter each time right away. Closes #13040
=> chore: support building with Node 22

.changeset/ninety-dragons-carry.md, packages/kit/src/exports/vite/dev/index.js
In the logic where SvelteKit loads the CSS to prevent FOUC in dev, it constructs URLs like `/path/Foo.svelte?svelte=&type=css&lang.css=&inline=`, which isn't great for Vite because it checks if a module is CSS via `/\.(css|less|...)(?:$|\?)/`, which wouldn't have matched the constructed URL.
With the Vite quirk aside (which fixing it is probably a separate breaking topic in Vite), this PR updates so it looks like this instead: `/path/Foo.svelte?inline&svelte=&type=css&lang.css`, which Vite will be happy about. This is also what [Astro does](https://github.com/withastro/astro/blob/bde49f186e4d620ce0c926353db38215e33dceef/packages/astro/src/vite-plugin-astro-server/css.ts#L39-L45) which had also worked well.
The reason why it always worked before (and unnoticed) is because …
=> fix: update inline css url in dev

.prettierrc, packages/kit/.prettierignore
of test apps
this saves time on ecosystem-ci and also on user machines if they ran tests and then format.
`rangeEnd: 0` is a better hack than `requirePragma` because that prevents prettier from reading the file looking for the pragma
---
=> fix: ensure prettier doesn't process build output or test results

.changeset/funny-lies-beam.md, packages/kit/src/runtime/client/client.js
When we encouter an error while rerunning the loaders on hydration, we need to remove the contents that were server-rendered and start fresh with the root error page. Else Svelte 5 (which is more strict with this) will fail because it tries to walk an entirely different DOM tree. Svelte 4 didn't suffer from this because it just threw away the old code, but it was still wrong to have to do it in the first place.
Fixes https://github.com/sveltejs/svelte/issues/14437
=> fix: don't hydrate when falling back to error page

packages/kit/test/apps/basics/test/cross-platform/client.test.js
I had warnings on these lines in VS Code
=> chore: remove unnecessary awaits

documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md, documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
#12991 caused the docs to fail to deploy — not quite sure why the preview link in that PR succeeded. This _should_ fix it, according to my local testing (though will need to be accompanied by a change on svelte.dev installing `@cloudflare/workers-types`)
=> fix cloudflare docs

.changeset/few-lamps-work.md, packages/adapter-vercel/package.json, pnpm-lock.yaml
Allows for better dependency deduping to remove `@rollup/pluginutils@4` from the dependency tree
=> chore: upgrade @vercel/nft to 0.27.7

.changeset/fifty-cars-lie.md, packages/kit/src/core/sync/create_manifest_data/index.spec.js, packages/kit/src/core/sync/create_manifest_data/sort.js
fixes #13095
This PR changes the RegExp to ensure that routes such as `/[[optional]]/(group)` are treated the same as `[[optional]]`. Previously, `/[[optional]]/(group)` was being treated the same as `/` which is incorrect since it has an optional segment. It wasn't recognised as `/[[optional]]` because the RegExp didn't consider the route group preceding it (it only looked for the end of the string).
---
=> fix: correctly match route groups preceding optional parameters

documentation/docs/20-core-concepts/10-routing.md
The documentation for layout in Routing section has an extra dash in the syntax, this PR corrects it
---
=> Update 10-routing.md: removed extra dash

.changeset/wild-flies-run.md, packages/enhanced-img/src/preprocessor.js, packages/enhanced-img/test/Output.svelte
See https://github.com/sveltejs/svelte/pull/14374 released in 5.2.6: https://github.com/sveltejs/svelte/blob/main/packages/svelte/CHANGELOG.md#526
Also removes Svelte 4 support since we already bumped the peer dep version to Svelte 5
This simplifies the code a bit and results in smaller output when absolute URLs are used. However, SvelteKit uses relative URLs by default and it doesn't help there
=> perf: directly inline values since Svelte no longer inlines

.changeset/sour-pigs-talk.md, packages/kit/src/core/sync/write_server.js
Follow-up to #13103 ...after #13104 was merged the `init` hook was not exported from `get_hooks` anymore. This fixes it.
---
=> fix: export `init` hook from `get_hooks`

.changeset/brown-bats-mate.md, packages/kit/src/utils/filesystem.js, packages/kit/src/utils/filesystem.spec.js
fixes https://github.com/sveltejs/kit/issues/13100
This PR adds a check to see if an index file exists in the related directory before resolving to that path. Directories without an index file should correctly fallback to the non-directory path.
---
=> fix: correctly resolve hooks entry file when directory exists

documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md, packages/adapter-cloudflare-workers/index.js
closes #13121
The behavior in this PR is a little different from the code in the issue.
Here, the adapter will now also attempt to use `wrangler.json` if:
* The `wrangler.json` file exists.
* The `config` is set to default (`wrangler.toml`).
---
=> Support wrangler.json configuration file in adapter-cloudflare-workers

documentation/docs/20-core-concepts/10-routing.md
closes https://github.com/sveltejs/kit/issues/12401
This PR adds a note to suggest using the server handle hook instead of a server layout file.
Also removes a redundant "Note that" phrasing when the docs already annotate blockquotes with "Note"
---
=> docs: explain that `+layout` files do not affect `+server.js`

.changeset/rotten-cheetahs-complain.md, packages/kit/src/exports/vite/build/build_service_worker.js, packages/kit/src/exports/vite/index.js
closes https://github.com/sveltejs/kit/issues/11790
This PR passes the user's Vite `build.minify` config value to the Vite build for the service worker.
---
=> fix: adhere to Vite `build.minify` setting when building service worker

documentation/docs/20-core-concepts/30-form-actions.md
In the forms section of the sveltekit docs, the example uses the legacy bar syntax (`onsubmit|preventDefault`). This fixes that.
---
=> docs: avoid invalid Svelte syntax

.changeset/ninety-taxis-bathe.md, packages/kit/src/runtime/server/page/actions.js, packages/kit/test/apps/basics/test/server.test.js
closes https://github.com/sveltejs/kit/issues/11876
This PR adds the route ID in the error message during development so it's more obvious which route the error means.
---
=> chore: specify the route ID in the error message during development when making a form action request to a route without form actions

.changeset/neat-buses-collect.md, packages/kit/src/runtime/app/state/client.js, packages/kit/src/runtime/app/state/server.js, packages/kit/test/apps/basics/src/routes/state/navigating/+layout.svelte, packages/kit/types/index.d.ts, playgrounds/basic/src/routes/+layout.svelte, playgrounds/basic/src/routes/[slug]/+page.svelte
follow-up to #13140. sorry, messed this up — sneaking in a fix before anyone starts using `navigating.current`
---
=> fix: replace navigating.current.x with navigating.x

.changeset/empty-mugs-press.md, packages/kit/src/utils/filesystem.js, packages/kit/src/utils/filesystem.spec.js
fixes https://github.com/sveltejs/kit/issues/13184
https://github.com/sveltejs/kit/pull/13144 caused a regression where it incorrectly resolved to the directory name when the `hooks.js file` doesn't exist. This happened because it couldn't distinguish between file names and directory names when looking for a matching file without the .js / .ts extension (`hooks/` and `hooks.js` would both equal to `hooks`, but `hooks/` would return first).
This didn't happen before https://github.com/sveltejs/kit/pull/13144 because we'd return early whenever a directory name matched. Therefore, the file name search would only contains files, not files and directory names.
This PR fixes that by only checking for file names again.
---
=> fix: correctly resolve no hooks file when a similarly named directory exists

.changeset/odd-mirrors-fold.md, packages/kit/scripts/generate-dts.js, packages/kit/src/runtime/app/state/client.js, packages/kit/src/runtime/app/state/index.js, packages/kit/src/runtime/app/state/package.json
Alternative to #13181, fixes #13179
Uses the same approach as the other virtual modules to differentiate between client and server
Note that I haven't tested this out with an actual Vite 5 project yet (if someone could that would be great; I probably won't have much time to do so)
---
=> fix: correctly resolve `$app/state` (alternative)

.changeset/smooth-weeks-rhyme.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/state/url/+page.svelte, packages/kit/test/apps/basics/test/client.test.js
fixes #13187. should probably get a test before we merge it and don't have time for it just now, but wanted to push the fix up anyway
---
=> fix: create new URL when calling `goto(...)`, to handle case where URL is mutated

.changeset/four-llamas-join.md, packages/adapter-static/index.js
Without this, apps with `router.type === 'hash'` will fail to build with `adapter-static`
---
=> fix: allow dynamic routes with missing fallback in hash mode

.changeset/rude-plants-rest.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/reroute/basic/b/+page.svelte, packages/kit/test/apps/basics/test/client.test.js, packages/kit/test/apps/basics/test/server.test.js, packages/kit/test/apps/hash-based-routing/test/test.js, packages/kit/types/index.d.ts
=> fix: do not mutate URL during reroute logic

.changeset/angry-geckos-dream.md, packages/kit/src/runtime/server/page/csp.js, packages/kit/src/runtime/server/page/render.js
I forgot to account for CSP when adding inline styles for `bundleStrategy: 'inline'`.
No test in this PR because there are no tests for `bundleStrategy: 'inline'` anyway, and life is too short to worry about such things during the Christmas break
Also, hashes were being printed twice, inexplicably (if harmlessly) — this fixes that
---
=> fix: add CSP hashes/nonces to inline styles when using

documentation/docs/10-getting-started/10-introduction.md, documentation/docs/20-core-concepts/50-state-management.md, documentation/docs/60-appendix/50-additional-resources.md
same as https://github.com/sveltejs/svelte/pull/14825
=> chore: make some links root-relative

.changeset/clever-phones-reply.md, packages/kit/src/utils/routing.js
closes https://github.com/sveltejs/kit/issues/13238
this avoids loading the dev check so it doesn't care if we tell it we're in dev or prod mode
=> fix: silence dev/prod warning during sync

.changeset/dirty-bees-act.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/store/subscribe/+layout.svelte, packages/kit/test/apps/basics/test/client.test.js
fixes https://github.com/sveltejs/kit/issues/13200
This PR ensures page store subscribers are correctly notified by creating a new object whenever we update the page store. I'm not sure why but when the same page object is used, it doesn't notify subscribers.
There was also another bug where a popstate event would cause subscribers to get notified twice because we were calling `root.$set({ page })` in addition to `stores.page.notify()` when updating the URL.
---
=> fix: correctly notify page store subscribers

documentation/docs/20-core-concepts/40-page-options.md
closes https://github.com/sveltejs/kit/issues/11310
This PR adds a note to the page option docs under the `ssr` section to indicate that page options still need to be evaluated on the server, so users shouldn't import browser API code in +page or +layout files.
---
=> docs: note that universal page and layout files still run on the server when `ssr = false`

packages/kit/src/runtime/client/client.js, packages/kit/types/index.d.ts
similar to https://github.com/sveltejs/kit/pull/13133
`afterNavigate` also triggers on navigations to the same URL, not just new URLs. This PR replaces "a new URL" with "a URL" to make that reflect the fact.
---
=> docs: reword `afterNavigate` description so that it includes navigations to the same URL

.changeset/sixty-rabbits-smell.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/navigation-lifecycle/after-navigate-properly-removed/+layout.svelte, packages/kit/test/apps/basics/src/routes/navigation-lifecycle/after-navigate-properly-removed/a/+page.svelte, packages/kit/test/apps/basics/src/routes/navigation-lifecycle/after-navigate-properly-removed/b/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js
closes #13240
the callbacks of `afterNavigate` do in fact get removed, just from the wrong array.
[here](https://github.com/sveltejs/kit/blob/619c00e0798d1fe2434e36cf4b0a800ade8112d6/packages/kit/src/runtime/client/client.js#L1471) `after_navigate_callbacks` gets re-assigned a new array, but [here](https://github.com/sveltejs/kit/blob/619c00e0798d1fe2434e36cf4b0a800ade8112d6/packages/kit/src/runtime/client/client.js#L1718) the `splice()` is done on an old reference.
to fix this i switched to a `Set`, and also changed to `const` to warn any future change. Sets keep the insertion order.
---
=> fix: correctly remove navigation callbacks when returning function in onNavigate

.changeset/gold-tips-cover.md, packages/kit/src/runtime/server/page/index.js, packages/kit/test/apps/options-2/src/routes/trailing-slash-server/+page.svelte, packages/kit/test/apps/options-2/src/routes/trailing-slash-server/prerender/+page.server.js, packages/kit/test/apps/options-2/src/routes/trailing-slash-server/prerender/+page.svelte, packages/kit/test/apps/options-2/test/test.js
fixes https://github.com/sveltejs/kit/issues/13255
This PR ensures that the `__data.json` file is prerendered when the `trailingSlash` option is set from a `+page.server` or `+layout.server` file although no server load exists. The data file is needed because the client relies on the server data to get the `trailingSlash` option value.
---
=> fix: prerender data when there's no server load but `trailingSlash` option is set from the server

documentation/docs/30-advanced/25-errors.md
needs adjustment because without it since https://github.com/sveltejs/svelte.dev/pull/1094 it won't build anymore
=> docs: fix code snippet

.changeset/slimy-cows-listen.md, packages/kit/src/core/sync/write_types/index.js
fixes https://github.com/sveltejs/kit/issues/13280
Similar to https://github.com/sveltejs/kit/pull/5907 we need to import the param matchers file ending with `.js` so that when the `moduleResolution` is set to something strict such as `NodeNext` (the default for libraries) the type inference isn't lost when it can't resolve the param matcher file due to the lack of a file extension.
---
=> fix: make param matcher generated type import with a `.js` extension

.changeset/khaki-melons-add.md, packages/kit/package.json, packages/kit/src/utils/routing.js, pnpm-lock.yaml
closes https://github.com/sveltejs/kit/issues/13273
=> fix: upgrade `esm-env` to remove warning when `NODE_ENV` is not set

packages/kit/src/exports/public.d.ts, packages/kit/types/index.d.ts
closes https://github.com/sveltejs/kit/issues/13285
This PR clarifies that the `kit.config.output.bundleStrategy` option only affects JS and CSS files while also including an example of how to inline assets through Vite's config.
---
=> docs: clarify how to inline assets

documentation/docs/30-advanced/20-hooks.md
closes https://github.com/sveltejs/kit/issues/9965
Adds a note that the `building` variable should be used to check that the app isn't building before executing some code only available when not prerendering or building.
---
=> docs: mention the `building` variable to execute non-prerenderable code in server handle

.changeset/six-goats-ring.md, packages/adapter-cloudflare-workers/index.js, packages/adapter-cloudflare/index.js
fixes https://github.com/sveltejs/kit/issues/12305
closes https://github.com/sveltejs/kit/pull/12306
This is an alternative to https://github.com/sveltejs/kit/pull/12306 . Instead of creating the emulator every time the Vite dev and preview middlewares are invoked, we await Cloudflare's platform proxy only when the adapter emulated platform is accessed, rather than much earlier when `adapter.adapt` is invoked.
We could still use the newly added test from https://github.com/sveltejs/kit/pull/12306
---
=> fix: prevent vitest from hanging

.changeset/angry-months-speak.md, packages/kit/src/runtime/client/client.js
When loading a non-SSR page and pressing the browser's back button while the page is still loading, it's possible for `current.url` to still be the default value of `null`, which then causes the `popState` function to throw the following uncaught error:
```
Uncaught (in promise) TypeError: Cannot destructure property 'href' of 'object null' as it is null.
at strip_hash (url.js?v=3a24e001:84:30)
at client.js?v=3a24e001:2227:52
```
This is from
https://github.com/sveltejs/kit/blob/e41a8e24b71cb9e9ee249ddfe732a3d0721d40bf/packages/kit/src/runtime/client/client.js#L2234
See #12924 for a reproduction/example videos.
---
- Fixes #12924
- I'm struggling to write an E2E test for this, so I might skip this if that's okay.
=> fix: fix `popState` race-condition when not using SSR

.changeset/tricky-books-study.md, packages/kit/src/core/sync/utils.js, packages/kit/src/utils/import.js
Simplifies code a bit around usage locations in our own code, and solves some issues people may have with their setups closes #11578
---
=> fix: fall back to importing dynamic dependencies relative to SvelteKit package

packages/kit/src/runtime/app/forms.js, packages/kit/types/index.d.ts
fixes #13020 by adding a line describing the enhance `update` options.
---
=> docs: add options for enhance update

.changeset/ten-onions-talk.md, documentation/docs/20-core-concepts/10-routing.md, documentation/docs/20-core-concepts/20-load.md, documentation/docs/20-core-concepts/30-form-actions.md, documentation/docs/20-core-concepts/50-state-management.md, documentation/docs/25-build-and-deploy/90-adapter-vercel.md, documentation/docs/98-reference/54-types.md, packages/kit/src/core/sync/write_types/index.js
Closes #12726
This PR is a re-do of #12967 which went stale, addressing comments and properly updating the documentation.
---
=> feat: provide PageProps, LayoutProps types

.changeset/wet-dancers-kneel.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/server/cookie.js, packages/kit/types/index.d.ts
Using class method function types causes SvelteKit users to get TypeScript ESLint errors if they're using the [@typescript-eslint/unbound-method][1] rule (included by default in the `recommended-type-checked` config).
For example:
```
/home/projects/stackblitz-starters-1y7qpk/src/routes/sum/+layout.ts
3:42  error  Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead  @typescript-eslint/unbound-method
```
Switching SvelteKit's public types to arrow functions fixes https://github.com/sveltejs/kit/issues/12622.
I haven't enabled the `@typescript-eslint/unbound-method` rule in this PR. However, I've got a separate PR …
=> fix: use arrow function types over bound functions

.changeset/green-flowers-heal.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/client/utils.js, packages/kit/types/index.d.ts
fixes https://github.com/sveltejs/kit/issues/13287
This PR fixes the client-side external link evaluation so that when using the hash router, accessing `/index.html` is considered an internal link. This prevents the page from reloading infinitely because the router incorrectly considered `/index.html` an external link.
There's also a slight doc change. Instead of suggesting all links start with `/#/`, suggesting links start with `#` allows the router to preserve the `/index.html` pathname. For example, links to `/about` should be `#/about` instead of `/#/about` so that it navigates to `/index.html#/about`.
---
=> fix: correctly detect internal links when hash router is used

.changeset/quick-crabs-camp.md, packages/kit/src/exports/index.js, packages/kit/types/index.d.ts
Hey! Small QOL improvement, I often google HTTP status codes to know which one I should use. I picked the three values that should cover 99% of use cases; `302 Found` is not in there because its behavior is [disambiguated by 303 and 307](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302).
---
=> docs: added most common status codes to redirect() doc

.changeset/nine-parrots-smoke.md, packages/kit/src/runtime/server/endpoint.js
Related to https://github.com/sveltejs/kit/issues/10855 (If we have no plans to extend `use:enhance` to work with non-SvelteKit form actions then this closes that issue entirely).
This PR adds an dev-only error if someone uses an enhanced form and POSTs to an internal API handler. It makes it more obvious they shouldn't be used together compared to "Unexpected end of JSON input" when it fails to parse a response body.
---
=> chore: error during development when using `use:enhance` with `+server`

.changeset/funny-moles-scream.md, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/fetcher.js, packages/kit/test/apps/basics/src/routes/load/window-fetch/patching-server-load-ii/+page.server.js, packages/kit/test/apps/basics/src/routes/load/window-fetch/patching-server-load-ii/+page.svelte, packages/kit/test/apps/basics/src/routes/load/window-fetch/patching-server-load/+page.server.js, packages/kit/test/apps/basics/src/routes/load/window-fetch/patching-server-load/+page.svelte, packages/kit/test/apps/basics/test/client.test.js
This PR is a follow up on #10009 which ensured that the `fetch` function from the `load` event would call `window.fetch` so that libraries (like Sentry but there are many others) can patch it. Unfortunately, I missed back then that there's another kind of `fetch` request made by SvelteKit: Whenever a user navigates to a route that contains a server-load function, a request is made to fetch the server-load data. 
This PR ensures that this server-load data request is also patchable by basically using the same mechanism introduced in #10009. I also added a test that would prior to this change fail.
---
=> fix: use `window.fetch` for server load fetch requests

.changeset/wild-coins-live.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/hash-based-routing/test/test.js
fixes https://github.com/sveltejs/kit/issues/13318
This PR decodes the URL when the hash router is enabled and the user enters the URL through the browser address bar (during app initialisation and the `hashchange` event). We need to do this because Safari seems to encode any extra hashes in the URL (only when accessed through the file protocol?). So, entering `/#/#about` in the address bar becomes `/#/%23about` which the client router incorrectly thinks is a route instead of just an ID.
---
=> fix: decode URL before navigating when hash router is enabled

.changeset/nasty-spoons-kick.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/load/invalidation/depends-goto/+layout.js, packages/kit/test/apps/basics/src/routes/load/invalidation/depends-goto/+page.js, packages/kit/test/apps/basics/src/routes/load/invalidation/depends-goto/+page.server.js, packages/kit/test/apps/basics/src/routes/load/invalidation/depends-goto/+page.svelte, packages/kit/test/apps/basics/test/client.test.js, packages/kit/types/index.d.ts
=> feat: Add ability to invalidate a custom identifier on goto()

.changeset/blue-foxes-clean.md, packages/kit/src/exports/vite/index.js, packages/kit/test/apps/basics/test/test.js
This shortens references to JS files in SSR, JS, and HTTP headers. Less bytes referring to these files. Also, the chunks often pick combine multiple files and pick the name of one individual file to use for the chunk, which can be misleading
Reducing the size of asset names reduced the size of the JS on my image-heavy page by 6.5% after brotli compression, but we couldn't come to agreement to shorten those
=> perf: shorten file names

.changeset/great-badgers-sing.md, packages/kit/src/exports/vite/build/build_server.js
This PR seems to fix following issue with symbolic links in the routes https://github.com/sveltejs/kit/issues/8100
Minimal issue reproduction is available here: https://github.com/yukipastelcat/sveltekit-symlinks
Symbolic links in the reproduction repository will be created automatically during build, but my plugin is flaky, so you might need to run `npm run build` for the second time to reproduce the issue.
---
`pnpm test` command does not exist, so I ran `pnpm test:kit` instead, some tests are failing, but they also do it in the `main` branch.
=> fix: use resolve_symlinks for node.universal and node.server

packages/kit/src/runtime/server/page/load_data.spec.js
I saw a notice buried in the logs that this line will start failing in Vitest 3. I can't actually do the Vitest 3 upgrade yet due to other issues, so thought I'd send this separately so that we don't forget about it
=> chore: add missing `await`

packages/kit/src/utils/import.js
supplements https://github.com/sveltejs/kit/pull/12532 (hopefully before https://github.com/sveltejs/kit/pull/13316 is merged)
fixes https://github.com/sveltejs/kit/issues/13331
While testing the fix from https://github.com/sveltejs/kit/pull/12532 with the reproduction from https://github.com/sveltejs/kit/issues/13331 I found that the `resolve` function throws an uncaught error on line 13
https://github.com/sveltejs/kit/blob/0142dd8e12fc2cc36a137368f0edea90b0e62964/packages/kit/src/utils/import.js#L13
This PR ensures that the resolve error is caught then tries the relative import, similar to the previous behaviour of importing svelte/compiler https://github.com/sveltejs/kit/pull/12532/files#diff-61bc3314d549d23c68f49ea0467f8856c97f8f5f3e150b4b529668f0cbaad7a1 before …
=> fix: catch error when resolving peer dep

packages/kit/src/runtime/client/client.js, packages/kit/test/apps/hash-based-routing/test/test.js
quick fix for https://github.com/sveltejs/kit/pull/13321 (hopefully before https://github.com/sveltejs/kit/pull/13316 is released)
This PR ensures only the hash of the URL is decoded so that any encoded hash character in the query parameters remains encoded.
---
=> fix: only decode URL hash instead of entire URL

packages/adapter-auto/package.json, packages/adapter-netlify/package.json, packages/adapter-node/package.json, packages/adapter-vercel/package.json, packages/enhanced-img/package.json, packages/kit/package.json, packages/kit/src/core/sync/write_types/index.spec.js, packages/kit/test/build-errors/env.spec.js, packages/kit/test/build-errors/package.json, packages/kit/test/build-errors/prerender.spec.js, packages/kit/test/build-errors/server-only.spec.js, packages/kit/test/build-errors/syntax-error.spec.js, packages/kit/test/prerendering/basics/package.json, packages/kit/test/prerendering/options/package.json, packages/kit/test/prerendering/paths-base/package.json, pnpm-lock.yaml
Most tests passing now with 3.0.1
Don't merge until all are passing though. The Windows test failure appears to be persistent
=> chore: upgrade to vitest 3

packages/kit/src/exports/public.d.ts, packages/kit/types/index.d.ts
The `Page` type is currently described as the shape of the `$page` store. This PR changes that to include the `page` state object as well with links to both.
---
=> docs: mention `page` state object when describing `Page` type

packages/kit/src/runtime/app/state/index.js, packages/kit/types/index.d.ts
Add documentation to `$app/state`'s `page` to clarify rune requirement.
Submitted as a svelte newbie because I was having difficulty understanding why my page was not updating. Found several sources that suggested what I was doing should work, and I nearly created a duplicate of #13305 because I was confident I had found a bug.
#13305
---
=> docs: document derived use of $app/state's page

.changeset/many-gorillas-shout.md, packages/package/src/utils.js, packages/package/test/fixtures/resolve-alias/expected/not.d.ts, packages/package/test/fixtures/resolve-alias/expected/not.js, packages/package/test/fixtures/resolve-alias/expected/sub/bar.d.ts, packages/package/test/fixtures/resolve-alias/expected/sub/bar.js, packages/package/test/fixtures/resolve-alias/src/lib/not.ts, packages/package/test/fixtures/resolve-alias/src/lib/sub/bar.ts
This PR refines the **alias** resolution process to correctly handle import and export statements. Previously, alias replacement was applied too broadly, affecting non-import strings. Now, the RegExps specifically target `import/export` statements.
Prevents accidental replacements of non-import strings that resemble imports (e.g., `const text = "from 'alias'"`).
---
=> fix: svelte-package resolve alias

.github/workflows/ci.yml
This PR ensures the `build` script runs before we publish the packages to pkg.pr.new so that the necessary files are included for the Node, Netlify, and Cloudflare adapters. This is necessary since the `prepublish` script doesn't automatically run when publishing. Similarly, the Svelte CI runs its `build` script before publishing too https://github.com/sveltejs/svelte/blob/de94159238080076150d28fbea5f399690821bf1/.github/workflows/pkg.pr.new.yml#L21-L22
---
=> chore: run build step before `pkg-pr-new publish`

.changeset/bright-scissors-grow.md, packages/kit/src/runtime/server/respond.js
=> fix: do not replace headers on fetch requests with error state

.changeset/forty-houses-collect.md, packages/kit/src/runtime/client/utils.js, packages/kit/test/apps/hash-based-routing/src/routes/anchor/+page.svelte, packages/kit/test/apps/hash-based-routing/test/test.js
fixes https://github.com/sveltejs/kit/issues/13320
This PR enables relative hash links to be used with the hash router so that links such as `#example` get recognised as a link to the current page. We do this by assuming links that have a hash value starting with `#/` links to a route while anything else is probably linking to an element with an id on the current page.
---
=> fix: correctly handle relative anchors when hash router is enabled

.changeset/cyan-dancers-tap.md, packages/kit/src/utils/filesystem.js, packages/kit/src/utils/filesystem.spec.js
fixes https://github.com/sveltejs/kit/issues/13350
https://github.com/sveltejs/kit/pull/13188 caused a regression where `index.js` and `index.ts` files would not be resolved as entries because of the additional `isFile()` check that was added to prioritise matching files over folders.
https://github.com/sveltejs/kit/blob/2ca09ce6ff1b5dbd5bb2ac0099b6b1d2a45ea3f0/packages/kit/src/utils/filesystem.js#L187
This PR fixes it by including the .js and .ts extensions when checking if an index file exists. Previously, it only checked without the extensions, hence the condition never passed.
---
=> fix: correctly check index file exists when resolving an entry

documentation/docs/30-advanced/20-hooks.md
Fixes https://github.com/sveltejs/kit/issues/11883. Stumbled on it again after 5 months.
---
=> docs: handle immutable headers error

documentation/docs/25-build-and-deploy/90-adapter-vercel.md
fixes https://github.com/sveltejs/kit/issues/13370
Apparently `Math.random().toString()` doesn't produce a random string that's long enough for 32 characters so this PR changes that to ensure the input is big enough to get 32 characters.
---
=> docs: fix 32 character long generation code snippet

.changeset/rich-pants-beam.md, packages/kit/src/runtime/server/respond.js, packages/kit/src/runtime/server/validate-headers.js, packages/kit/src/runtime/server/validate-headers.spec.js, packages/kit/test/apps/dev-only/src/routes/headers/invalid/+server.js
Fix for [#12784](https://github.com/sveltejs/kit/issues/12784)
Adds validation for common HTTP headers in dev mode to help catch invalid values early:
- Validates cache-control directives against standard values
- Validates content-type format
- Only active in dev mode
run `pnpm dev` from `test/apps/basics` and navigate to [http://localhost:5173/headers/invalid](http://localhost:5173/headers/invalid). In your console you'll see:
```
[SvelteKit] Invalid cache-control directive "totally-invalid". Did you mean one of: max-age, public, private, no-cache, no-store, must-revalidate, proxy-revalidate, s-maxage, immutable, stale-while-revalidate, stale-if-error, no-transform, only-if-cached, max-stale, min-fresh
[SvelteKit] Invalid content-type value "not-a-real-type"
```
---
=> feat: validate values for `cache-control` and `content-type` headers in dev mode

.changeset/nine-llamas-fetch.md, .changeset/slow-penguins-play.md, packages/kit/src/core/adapt/builder.js, packages/kit/src/core/generate_manifest/index.js, packages/kit/src/exports/public.d.ts, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/exports/vite/index.js, packages/kit/src/runtime/server/fetch.js, packages/kit/src/runtime/server/respond.js, packages/kit/test/apps/basics/src/hooks.server.js, packages/kit/test/apps/basics/src/routes/prerendering/prerendered-endpoint/api-with-param/[option]/+server.js, packages/kit/test/apps/basics/src/routes/prerendering/prerendered-endpoint/proxy/+server.js, packages/kit/test/apps/basics/test/server.test.js, packages/kit/types/index.d.ts
Server-side `fetch()` (e.g. when `isSubRequest: true`) currently has a few bugs when called on a `prerendered` route.
1. When a non-prerendered route also matches the same URL as the prerendered route, the non-prerendered routes are taking precedence (e.g. if `export const prerender = 'auto'`)
2. Prerendered routes still have `hooks.server.js` run on them, but only when `isSubRequest: true`
I've fixed both of these issues by adding a `prerendered_routes: Set<string>` to the manifest. Then, we instantly call a real HTTP `fetch()` if the path matches, just like when calling server-side `fetch()` on assets (when the adapter doesn't support reading assets from the file-system).
During dev/build, there are no `prerendered_routes`, so it's left empty in the manifest (although that does mean the …
=> fix: skip calling `respond` for server-side `fetch` on prerendered pages

.changeset/shaggy-ravens-unite.md, packages/kit/src/exports/vite/build/build_server.js, packages/kit/test/apps/options/source/components/SharedCSS.svelte, packages/kit/test/apps/options/source/pages/inline-assets/+page.svelte, packages/kit/test/apps/options/source/pages/resolve-route/+page.svelte
We didn't take into account that the list of CSS files could also contain references to non-entry-point files that are below the threshold.
fixes https://github.com/sveltejs/kit/pull/13068#discussion_r1933373266
---
=> fix: ignore non-entry-point CSS files during inlining

.changeset/lovely-starfishes-impress.md, documentation/docs/20-core-concepts/30-form-actions.md, packages/kit/src/runtime/server/endpoint.js
This PR reverts https://github.com/sveltejs/kit/pull/13197 since it cause an error for users that used [SuperForm's helper](https://superforms.rocks/api#actionresulttype-data-options--status) that made `+server` responses compatible with `use:enhance`.
EDIT: In hindsight, we should probably update the `use:enhance` docs https://svelte.dev/docs/kit/form-actions#Progressive-enhancement to explain that it should only be used with SvelteKit form actions to address the original issue.
---
=> chore: revert dev error when using `use:enhance` with `+server`

documentation/docs/20-core-concepts/10-routing.md
Slightly move up the note about how SvelteKit handles links under code blocks actually containing links. 
Where it stands now is among `load` and `data` introduction which should focus on exactly this, else it's a bit overwhelming (also there is no `<a>` tag in the code blocks just above). 
---
=> docs: move links handling note under navigation code blocks

documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md
part of https://github.com/sveltejs/kit/issues/13385
This PR removes the recommendation to configure the name of the `_env.js` file through the `publicModule` option since it doesn't exist. It also corrects the name of the public module file from `_env.js` to `env.js` (without the underscore) since that's the name the codebase actually uses.
https://github.com/search?q=repo:sveltejs/kit%20ir%7D/env.js&type=code
---
=> docs: remove mention of non-existent `publicModule` option

.changeset/healthy-bees-repeat.md, packages/adapter-vercel/index.js
Went missing during a refactoring in #13383
=> fix: correct edge function path for route resolution endpoint

.changeset/sharp-games-rule.md, packages/kit/src/runtime/server/page/server_routing.js
It is necessary to adhere to this setting because rewrites that SvelteKit cannot see may otherwise lead to incorrect relative paths.
Example:
- route resolution request to _app/route.js
- rewrite to _app/route/foo.js
- SvelteKit only sees the later, returning a relative `import('../immutable/...`) which is wrong, because the actual relative path would be `import('./immutable/...)`
Tested manually that it works correctly; automated test feels unnecessary
---
=> fix: make route resolution imports root-relative if `path.relative` option is `false`

.changeset/chilled-timers-give.md, packages/adapter-cloudflare/index.js
Fixes #13385
The original rule of `/_app/*` broke apps with pre-rendered pages and pages using dynamic environment variables simultaneously, because it excludes `/_app/env.js`, which is loaded in pre-rendered pages. This fixes it by only excluding the assets generated by Vite.
---
=> fix: make `<build>` route exclusion rule only exclude static assets

.changeset/clean-dancers-type.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/app/forms.js, packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte, packages/kit/types/index.d.ts
Allow for form action submit function callbacks to be asynchronous functions.
Closes #13419 
---
- Not sure if I need to do this for a type change?
=> fix: form action submit function callback return type

eslint.config.js, packages/adapter-node/src/handler.js, packages/kit/src/core/postbuild/prerender.js, packages/kit/src/core/postbuild/queue.js, packages/kit/src/core/postbuild/queue.spec.js, packages/kit/src/exports/node/index.js, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/exports/vite/preview/index.js, packages/kit/src/runtime/app/forms.js, packages/kit/src/runtime/client/bundle.js, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/fetcher.js, packages/kit/src/utils/streaming.spec.js, packages/kit/test/utils.js, packages/package/test/index.js
Adding this actually caught a couple of (actual) dangling promises in our codebase. There are a few instances where I'm not _positive_ whether the promise should or shouldn't be awaited -- but this rule also improves that use case. Being forced to `void x` your promises that you _want_ to ignore provides explicit signal for people later, so they don't have to wonder whether you meant to let it dangle or not.
---
=> chore: Add `@typescript-eslint/no-floating-promises`

documentation/docs/98-reference/54-types.md
Current documentation mixes `+server.js` and `+page.server.js` descriptions.
I have unified it to the former. Maybe latter is more desirable?
```ts
// src/routes/[foo]/[bar]/[baz]/+page.server.ts (or js)
// Invalid export 'GET'
export const GET = () => {};
```
---
=> docs: fix endpoint filename, types

.changeset/mighty-kiwis-laugh.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/data-sveltekit/preload-code/+page.svelte, packages/kit/test/apps/basics/src/routes/data-sveltekit/preload-data/+page.svelte, packages/kit/test/apps/basics/test/client.test.js
fixes https://github.com/sveltejs/kit/issues/13466
This PR changes the link preload behaviour so that it only ignores a link which has already triggered a preload. Previously, it would start ignoring a link the moment it was hovered on. This caused a link that only preloads on `mousedown` to always be ignored since a user's mouse would hover on the link first, causing it to be ignored on the subsequent `mousedown` event. This PR also fixes the data-sveltekit-preload tests that did not manage to catch this regression by changing the tests to use playwright mouse hover simulation instead of programmatically dispatching the `mouseover` event which didn't complete before firing the other events.
---
=> fix: correctly preload links on `mousedown`/`touchstart`

.changeset/eight-walls-melt.md, packages/adapter-netlify/index.js
The file import from an absolute path without a `file:///` isn't compatible with Windows, and it's also unnecessary since the content is generated a few lines above.
---
=> fix: avoid file import that is incompatible with Windows

.changeset/stupid-clocks-turn.md, packages/adapter-netlify/index.js, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/exports/vite/index.js, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/entry.js, packages/kit/src/runtime/client/utils.js, packages/kit/src/runtime/server/page/server_routing.js, packages/kit/src/types/internal.d.ts, packages/kit/test/apps/basics/test/cross-platform/test.js, packages/kit/types/index.d.ts
When implementing server-side route resolution we didn't think of the CSS associated with the entry points of the pages. Since Vite isn't involved in that chain, it can't automatically wire up the imports correctly, so we gotta add code to load them ourselves.
Fixes #13491
=> fix: load CSS when using server-side route resolution

.changeset/ten-planes-relax.md, packages/kit/src/exports/vite/build/build_server.js, packages/kit/test/apps/options/source/pages/inline-assets/+page.server.js, packages/kit/test/apps/options/source/pages/inline-assets/import-meta/+page.svelte
fixes https://github.com/sveltejs/kit/issues/13423
This PR fixes the case where we fail to find a server stylesheet when Vite associates a page's CSS with a different chunk instead of the component itself. This can happen when the page is imported by another file. So, we need to crawl the imports property in the manifest for CSS too.
---
=> fix: correctly map shared entry-point CSS files during inlining

packages/kit/src/exports/vite/dev/index.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/src/types/internal.d.ts, packages/kit/types/index.d.ts
`universal_id` and `server_id` aren't required and those files may not be present
eslint in VSCode was telling me it has to be `Array<>` rather than `[]`. Not sure why the command line doesn't apply the same rule
=> chore: fix node ID types

.changeset/silver-pigs-report.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/data-sveltekit/preload-data/+page.svelte, packages/kit/test/apps/basics/src/routes/data-sveltekit/preload-data/target/+page.server.js, packages/kit/test/apps/basics/test/client.test.js
fixes https://github.com/sveltejs/kit/issues/13466 (for real this time)
https://github.com/sveltejs/kit/pull/13486 previously fixed the preload on tap not working by ensuring we do not skip checking the link until a preload has triggered. However, there's also the case where we have both preload link options: preload code on hover and preload data on tap.
This PR ensures that we still preload data on tap even after a successful preload on hover if the preload on hover was only preloading code.
---
=> fix: preload data on tap after code was preloaded on hover

.changeset/tough-mangos-develop.md, packages/kit/src/exports/index.js, packages/kit/src/exports/index.spec.js, packages/kit/types/index.d.ts
Provides people a way to normalize a raw URL that could contain SvelteKit-internal data. One use case would be that you want to use middleware in front of, but outside of SvelteKit
Extracted from #13477
---
=> feat: provide `normalizeUrl` helper

packages/kit/src/exports/index.js, packages/kit/types/index.d.ts
This PR notes the SvelteKit version the `normalizeUrl` helper was added in. Not sure if this is that useful but I noticed it was missing.
---
=> docs: add `@since` annotation for the `normalizeUrl` helper

packages/kit/src/runtime/server/page/actions.js, packages/kit/src/types/internal.d.ts, packages/kit/src/utils/options.js, packages/kit/types/index.d.ts
In https://github.com/sveltejs/kit/pull/13535 I corrected the IDs to be optional, but I missed that the nodes themselves also weren't marked as optional. In `dev.js` and `build_server.js` they aren't necessarily filled out and everywhere they are accessed they are first checked
=> chore: fix types for universal and server fields

.changeset/thin-parents-pull.md, documentation/docs/30-advanced/20-hooks.md, packages/kit/src/runtime/client/client.js
Reroute is supposed to be idempotent, i.e. the same income (i.e. URL) should have always the same outcome. With the introduction of async reroute, a crucial advantage of preloading is now lost: Reroute is called on preload, then on the actual click reroute is called again. That means that if it is async and fetches from the backend, two fetches will be made, which means the actual navigation is slowed down by a few miliseconds. Therefore we introduce a cache which solves this problem.
---
=> chore: cache reroute results

documentation/docs/60-appendix/10-faq.md
Current SvelteKit package requires Node.js 18.13+.
[Import Attributes](https://nodejs.org/docs/latest/api/esm.html#import-attributes) (previously Import Assertions) was implemented in Node.js 16.14.
For example, this example works in Node.js 22:
```js
// svelte.config.js
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import pkg from './package.json' with { type: 'json' };
console.log(pkg);
```
---
=> docs: update `package.json` import

.changeset/nine-glasses-build.md, packages/kit/src/runtime/server/fetch.js, packages/kit/src/runtime/server/respond.js, packages/kit/src/runtime/server/utils.js, packages/kit/test/apps/basics/src/hooks.js, packages/kit/test/apps/basics/src/routes/reroute/prerendered/+page.svelte, packages/kit/test/apps/basics/src/routes/reroute/prerendered/destination/+page.svelte, packages/kit/test/apps/basics/src/routes/reroute/prerendered/destination/+page.ts, packages/kit/test/apps/basics/test/client.test.js, packages/kit/test/apps/basics/test/server.test.js
When rerouting to a path that is a prerendered page, the runtime would previously return a 404, because said path does not point to a route in the manifest. This adds a check for this specifically to do a fetch to the prerendered page in that case.
---
=> fix: allow reroute to point to prerendered route 

documentation/docs/20-core-concepts/10-routing.md
This PR removes the typescript error from one of the docs routing code snippets by adding the type to the request handler.
---
=> docs: add type to request handler

packages/kit/src/exports/public.d.ts, packages/kit/types/index.d.ts
I couldn't get symlinks to work so I'm just winging it :/
---
=> docs: explain why route id can be null

documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
It appears that the SvelteKit adapters for Cloudflare are distinct, with `@sveltejs/adapter-cloudflare` specifically designed for Cloudflare Pages, whereas `@sveltejs/adapter-cloudflare-workers` is intended for Cloudflare Workers. 
This pull request aims to rectify a documentation inconsistency in the `@sveltejs/adapter-cloudflare` documentation page, rather than proposing a rename to `@sveltejs/adapter-cloudflare-pages`, which would indeed help to avoid confusion.
The current documentation for `@sveltejs/adapter-cloudflare` suggests that it should be used to emulate Cloudflare Workers-specific values during local development. However, given that this adapter is actually tailored for Cloudflare Pages, this information seems to be inaccurate.
---
- [ X ] This message body should clearly …
=> docs: fix naming in 60-adapter-cloudflare.md

.changeset/flat-cows-cough.md, packages/kit/src/exports/vite/build/build_server.js, packages/kit/src/exports/vite/build/utils.js, packages/kit/src/types/internal.d.ts, packages/kit/test/apps/basics/src/routes/css/dynamic/+page.svelte, packages/kit/test/apps/basics/src/routes/css/dynamic/Dynamic.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js
fixes https://github.com/sveltejs/kit/issues/13546
This PR changes server nodes from always loading dynamically imported component's styles and fonts to only loading them if they are used during SSR (to avoid FOUC). This fixes lazy loading of components on the client, only retrieving the styles when needed.
We can tell which deps are used during SSR by analysing the deps of the node with both the server manifest and the client manifest, then comparing the results. If a style or font is missing from the server deps, it's probably only used on the client. Therefore, it should be safe to load lazily.
---
=> fix: lazily load CSS for CSR dynamically imported components

.changeset/silent-tables-raise.md, packages/adapter-cloudflare/index.js
fixes https://github.com/sveltejs/kit/issues/13621
This PR reverts the changes made in https://github.com/sveltejs/kit/pull/13610 which causes the server-side dependencies to not be resolved correctly by Wrangler when it bundles the server files. In the first place, writing the server files to the build output wasn't useful since the dependencies aren't there too.
---
=> fix: revert writing server files to the cloudflare build directory

.changeset/angry-ravens-eat.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/no-ssr/after-navigate/+page.svelte, packages/kit/test/apps/basics/test/client.test.js, packages/kit/test/apps/basics/test/cross-platform/client.test.js, packages/kit/types/index.d.ts
fixes https://github.com/sveltejs/kit/issues/13573
This PR changes the unexpected behaviour of `afterNavigate` being called twice when SSR is disabled to only once (same as when SSR is enabled). It was being called twice: once with type 'enter' and again with type 'goto' because we initialised the app and used `goto` under the hood to render the page client-side. Now, it should only be called once with type 'enter'. This also adjusts the docs to state that a navigation with type 'enter' is when the app starts and not just when it's hydrated.
---
=> fix: only call `afterNavigate` once on start when SSR is disabled

documentation/docs/40-best-practices/06-icons.md, documentation/docs/40-best-practices/07-images.md
I think this fits better as a separate page and is more discoverable. It doesn't really make sense to talk about CSS-based icons on the images page and none of these get optimized.
I had wanted to make this a separate page originally, but didn't have enough content. I added some more to it, so that it looks decent as its own page now. I tested locally to ensure it renders nicely
=> docs: flesh out icons section and make standalone page

pnpm-lock.yaml
not that big of a help by itself because vercel nft is still pulling in `glob`, but getting closer!
=> chore: upgrade minizlib to remove rimraf dependency

documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md
This PR fixes the Cloudflare docs page changes from https://github.com/sveltejs/kit/pull/13634
Having a title such as ``_headers` and `_redirects`` causes svelte.dev to render a part of the title as italic and discards the `_` character. This causes the sub-menu link for that section to be rendered incorrectly so SvelteKit reports a missing ID.
---
=> docs: avoid using titles that have `_` in them

.changeset/curvy-dodos-clean.md, packages/adapter-auto/adapters.js
made this a major as it's a breaking change for people deploying to cloudflare and matches what we've done in the past: https://github.com/sveltejs/kit/blob/main/packages/adapter-auto/CHANGELOG.md
=> chore: upgrade `@sveltejs/adapter-cloudflare` to version 7

packages/kit/test/build-errors/tsconfig.json, packages/kit/test/tsconfig.json, packages/kit/tsconfig.json
this should hopefully make the editor experience more stable, as the chance of the world being loaded in is minimized. Previously (I think) the import of the general utils file from any of the project's test files meant that as soon as you open _one_ test project, _all_ the test projects at once were loaded into memory, including stuff from `.svelte-kit`, because the general test config didn't have an include config. Also removes an unnecessary duplicate from the kit root tsconfig
=> chore: tweak tsconfig includes

.changeset/olive-mugs-search.md, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/runtime/control.js
We previously used a grotesque hack that would ensure the `HttpError` etc classes would be the same between what Vite imports via its transformation toolchain and what you get from a regular node import.
Turns out we don't need that anymore - since #9242 SvelteKit is guaranteed to always be loaded through the Vite toolchain.
This investigation was triggered by https://github.com/vitest-dev/vitest/pull/7783 - removing this might alleviate the pressure on Vitest, though we still do some `vite.ssrLoadModule` suspicously close to the `configureServer` hook, so we'll see.
> At first thought we can leverage the imports map of the `package.json` instead. Through that, Vite would (hopefully?) not load these into its own toolchain, instead defer to the regular node loader to get the module. But …
=> chore: get rid of class-replacement hack

.changeset/bright-houses-kick.md, .changeset/gentle-parrots-clap.md, packages/adapter-cloudflare/index.js
fixes https://github.com/sveltejs/kit/issues/13667
This PR uses the non-posix `relative()` method so that it correctly resolves when used with Windows paths that may be provided through the Wrangler configuration. It also converts the path to a POSIX path before embedding them into the worker script since backslashes get interpreted as escape characters and are lost in the process.
Also includes a minor fix where if the user had `pages_build_output_dir` set in their wrangler configuration, the adapter wasn't writing the worker to that directory (Cloudflare Pages expects the worker and assets to be in the same directory).
---
=> fix: correctly resolve paths provided through Wrangler config on Windows

.github/workflows/pkg.pr.new-comment.yml, .github/workflows/pkg.pr.new.yml
I suspect this might publish all packages on every push, which probably isn't what we want (it should just publish the packages that have actually changed). Not entirely sure how best to make that happen but we can iterate on it
=> add pkg.pr.new workflows

.changeset/ninety-planets-remember.md, packages/kit/src/runtime/app/server/event.js, packages/kit/src/runtime/server/utils.js, packages/kit/test/apps/basics/src/hooks.server.js, packages/kit/test/apps/basics/src/routes/get-request-event/with-error/+error.svelte, packages/kit/test/apps/basics/src/routes/get-request-event/with-error/+page.server.js, packages/kit/test/apps/basics/test/test.js, packages/kit/types/index.d.ts
Resolves #13654: Allow `HandleServerError` hook to access `getRequestEvent`.
=> fix: allow `HandleServerError` hook to access the ` getRequestEvent`

.changeset/thirty-foxes-study.md, packages/kit/src/core/sync/write_client_manifest.js, packages/kit/src/exports/vite/index.js
Rollup is quite aggressive about warning on missing imports — if you have something this...
```js
import * as foo from './foo.js';
if (foo.bar) {
foo.bar();
}
```
...it will yell at you if `foo.js` doesn't export `bar`. This is a useful warning, unless the import is in code the user doesn't control, such as the generated `app.js` referencing `client_hooks.handleError` (which is known to be harmless).
This PR squelches those warnings.
---
=> Squelch rollup warnings

.changeset/red-pugs-smell.md, packages/package/src/config.js, packages/package/src/validate.js
This PR updates the package logic to avoid throwing an error when package.json is missing in the current directory.
Uses the `load_pkg_json` function instead of `readFileSync`.
I found this issue when packaging for a monorepo
---
=> fix: handle missing package.json gracefully

packages/kit/test/apps/basics/test/server.test.js
Borked on Windows, given that the other tests related to symlinks are just skipped I figured this one should be too.
https://github.com/sveltejs/kit/blob/1c6c7c92e7abd6c65e099f60a58d6cf3a0e5ea60/packages/kit/test/apps/basics/test/setup.js#L4-L8
https://github.com/sveltejs/kit/blob/1c6c7c92e7abd6c65e099f60a58d6cf3a0e5ea60/packages/kit/test/apps/basics/test/cross-platform/test.js#L940-L947
---
=> fix: skip symlink test on windows

documentation/docs/10-getting-started/30-project-structure.md
There is no toggle on the bottom of the page now, so removing the sentence referencing it to avoid confusion. Because this is a documentation-only issue, I don't think there are any tests to run.
---
=> Removed reference to js/ts toggle.

package.json, packages/adapter-cloudflare/package.json, packages/adapter-static/package.json, packages/kit/package.json, packages/kit/test/apps/basics/test/cross-platform/test.js, packages/kit/test/apps/writes/src/routes/new-route/zzzz1662642734866/+page.svelte, pnpm-lock.yaml, pnpm-workspace.yaml
Necessary to run tests on Ubuntu 24.04 (LTS), see microsoft/playwright#30368.
I also deleted a test artifact I noticed while fighting [this](https://github.com/sveltejs/kit/blob/c51fb554416e0c4a21655c1d79e834f69743d1d5/packages/kit/test/apps/writes/test/test.js#L33) apparently already flaky test. Seems to have been accidentally committed in #6811.
---
=> chore(deps): update playwright

.changeset/silly-ears-visit.md, packages/adapter-vercel/index.js
This adds the `edge-light` condition to the `esbuild.build()` command used to bundle code for Vercel's Edge Runtime. I noticed that the condition wasn't respected when marking some dependencies as `ssr.external` even though the packages supported Edge Runtime via the `edge-light` condition.
This change brings the compilation more in line with Next.js, as it leverages the `edge-light` condition.
Adding the `conditions` configuration also requires manually adding `module` because it is [only defaulted if nothing is configured](https://esbuild.github.io/api/#how-conditions-work).
---
- I didn't see any tests for the adapters.
=> feat: use edge-light condition when building for Vercel Edge Runtime

documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md, documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
This PR includes a small change to the display titles of the adapter-cloudflare and adapter-cloudflare-workers doc pages to better distinguish them in the nav bar and page itself.
Cloudflare Pages -> Cloudflare
Cloudflare Workers -> Cloudflare Workers Sites
---
=> docs: change "Cloudflare Pages" title to just "Cloudflare"

documentation/docs/40-best-practices/07-images.md
I ran into an issue where enhanced images were not displaying correctly: https://discord.com/channels/457912077277855764/1368186315367256094
Turns out the import order of the plugin matters. The documentation does not indicate this.
Add a comment to make it clear that enhancedImages() must be declared first.
---
=> Clarify positioning of enhancedImages plugin

packages/kit/src/exports/index.js, packages/kit/types/index.d.ts
There's nothing on https://svelte.dev/docs/kit/@sveltejs-kit#fail that says it's related to forms. If you were just looking at that page you might have a hard time knowing when to call `error` and when to call `fail`
=> docs: expand docs for fail method

documentation/docs/25-build-and-deploy/30-adapter-auto.md
I believe the package for svelte-kit-sst got moved to their v2 repo, doesn't seem to be a reference to it from the main sst repo.
Below is what I could find, searching on their repos if we want to link to the repo of the adapter.
https://github.com/sst/v2/tree/master/packages/svelte-kit-sst
This is the commit I think from the name change sst's end:
https://github.com/sst/v2/commit/16b44a2f82d98893e6844437e6bdaceba12199ee#diff-ff22a9d0ec942b2bba9ac0ca733969802315c0ced93e45c444fecd2e30168c22
---
=> docs: fix link for sst adapter 30-adapter-auto.md

.changeset/smooth-rockets-complain.md, packages/kit/src/core/postbuild/analyse.js, packages/kit/src/exports/vite/build/build_server.js, packages/kit/src/exports/vite/dev/index.js, packages/kit/src/exports/vite/index.js, packages/kit/src/exports/vite/static_analysis/index.js, packages/kit/test/apps/basics/src/routes/node-analysis/+page.js, packages/kit/test/apps/basics/src/routes/node-analysis/+page.server.js
fixes https://github.com/sveltejs/kit/issues/13785
This PR ensures the `$env` and `$app/environment`, etc. are set before we evaluate the `+page.server`/`+layout.server` files so that they have the correct values when we are analysing the page options of each node. It now also uses the static analysis cache when we build the server nodes again. This lets us avoid evaluating the server files again where those internal variables aren't set.
---
=> fix: set `$env` and `$app/environment` variables before analysing server nodes

documentation/docs/20-core-concepts/40-page-options.md, documentation/docs/25-build-and-deploy/60-adapter-cloudflare.md, documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md
We don't use bold text for emphasis, we use italics. Some of these things shouldn't be emphasised anyway
=> docs: remove unused bolding

documentation/docs/60-appendix/10-faq.md
we don't use `<h4>` on the site
=> docs: remove h4

eslint.config.js
The `typescript-eslint` docs recommend using `projectService` over `project`: https://typescript-eslint.io/packages/parser/#project
My own testing shows `projectService` to be slightly faster.
**With `project`:**
real	0m36.047s
user	1m10.914s
real	0m29.111s
user	0m56.673s
real	0m29.084s
user	0m53.078s
real	0m31.287s
user	1m3.867s
real	0m28.033s
user	0m53.280s
**With `projectService`:**
real	0m36.333s
user	1m10.211s
real	0m29.553s
user	0m56.994s
real	0m27.674s
user	0m53.531s
real	0m27.125s
user	0m49.013s
real	0m26.967s
user	0m49.587s
=> chore: switch to typescript-eslint projectService setting

packages/kit/src/runtime/client/client.js
If SSR is disabled, the scroll position won't be restored when the page is reloaded. This happens because `scrollTo` is called before the page is rendered, meaning the target scroll position does not yet exist. Conversely, when SSR is enabled, `scrollTo` works as expected since the page is already rendered, and the scroll position exists.
I wasn't sure if the order of scrolling and hydrating mattered, so I did not move the `scrollTo` behind the `if (hydrate)` block.
---
=> fix: recover scroll position on reload of SPAs

.changeset/smooth-trains-applaude.md, packages/package/src/typescript.js
=> fix: handle non-semver-style dependency versions

packages/kit/src/runtime/client/client.js
This PR fixes a regression caused by https://github.com/sveltejs/kit/pull/10856 which broke hash router navigation.
We can't apply the same fix for hash routing because `location.replace` doesn't work since the browser interprets the entire hash as the element it should focus but we're using it as a pathname replacement. `element.focus()` doesn't work on Safari and Ubuntu Firefox so that's moot too.
=> fix: avoid setting sequential focus navigation starting point when using hash router

documentation/docs/40-best-practices/03-auth.md
Very small PR to fix the link to [locals](https://svelte.dev/docs/kit/hooks#Server-hooks-locals) from the [auth](https://svelte.dev/docs/kit/auth) page as it is currently pointing to the handle section above
---
=> docs: correct link to locals

.changeset/tall-kids-sit.md, .changeset/tricky-deers-poke.md, packages/kit/src/runtime/client/client.js, packages/kit/test/apps/basics/src/routes/reset-focus/+page.js, packages/kit/test/apps/basics/src/routes/reset-focus/+page.svelte, packages/kit/test/apps/basics/test/cross-platform/client.test.js, packages/kit/test/apps/hash-based-routing/src/routes/focus/+page.svelte, packages/kit/test/apps/hash-based-routing/src/routes/focus/a/+page.svelte, packages/kit/test/apps/hash-based-routing/test/test.js
fixes https://github.com/sveltejs/kit/issues/13883 and sequential focus navigation in hash routing apps.
This PR ensures our sequential focus navigation setting works in hash routing apps by avoiding client-side navigation when using `location.replace()` to set the focus. It also moves the existing logic to obtain the URL hash (based on the routing mode) to its own function and limits the number of times we split the URL string to up to three parts (as Dominik put it, `https://example.com/#<apphash>#<otherhash>`, so if there are more `#` characters in `<otherhash>`, they won't go missing)
---
=> fix: sequential focus navigation starting point regression and hash routing

documentation/docs/30-advanced/20-hooks.md
Fixes #13847 
The docs say you have to return `false` which is only partially correct; any falsey value will opt out of encoding
---
=> chore: Correct transport docs

.changeset/tough-beers-drum.md, packages/kit/src/exports/vite/index.js
Previously, `rolldown-vite` didn't support `manualChunks`, so we had to use a workaround. Now that it's implemented in https://github.com/rolldown/rolldown/issues/4311 we can simplify our config options a bit.
---
- we already have a test for checking that single apps have a single bundled JS file
=> chore: always use `manualChunks` for bundling single and inline apps

packages/package/package.json, packages/package/test/fixtures/resolve-alias/tsconfig.json, packages/package/tsconfig.json
The types/index.d.ts file was removed in https://github.com/sveltejs/kit/pull/8922/files#diff-0da28c3df913a524b1ad3527d3eff1584499e19a9dd2708748ba4db6f306ac08 but the tsconfig and package.json still references it. Also, one of the fixtures' tsconfig.json was complaining about not having any input files so I added the .ts files to it.
---
=> chore: remove references to non-existent types folder

.changeset/tiny-masks-watch.md, packages/kit/CHANGELOG.md
fixes https://github.com/sveltejs/kit/issues/12521
https://github.com/sveltejs/kit/pull/13850/files#diff-453fcd4d91c0dc6f0ba469918674295a92f8450956c5bc4836fb2e46de274ae2 was merged but the changeset specified Kit instead of svelte-package. We should merge this so a new release of svelte-package will include the fix. I've already edited the GitHub release notes to remove the previous entry from the Kit release.
---
=> chore: add changeset for non-semver-style dependency handling

.changeset/nasty-forks-drum.md, packages/kit/src/runtime/client/client.js
Fixes regression from #13914 where `untrack` is imported, without checking if it exists in the `svelte` package. 
---
=> fix: use fallback if `untrack` doesn't exist in svelte package

documentation/docs/10-getting-started/30-project-structure.md, documentation/docs/25-build-and-deploy/40-adapter-node.md, documentation/docs/25-build-and-deploy/70-adapter-cloudflare-workers.md, documentation/docs/25-build-and-deploy/90-adapter-vercel.md, documentation/docs/30-advanced/70-packaging.md, documentation/docs/60-appendix/10-faq.md
This PR fixes the syntax highlighting for shell command code blocks in the docs. Using `sh` doesn't actually highlight them since we've configured Shiki to only recognise `bash` in svelte.dev.
---
=> docs: fix syntax highlighting for shell commands

.changeset/stupid-oranges-know.md, packages/kit/src/exports/vite/build/build_service_worker.js, packages/kit/src/exports/vite/index.js
`@ts-expect-error` only works when we have rollup vite installed. It wouldn't work with rolldown vite installed since there wouldn't be any error. https://github.com/sveltejs/kit/pull/13964#discussion_r2192549148
---
=> chore: replace `@ts-expect-error` with `@ts-ignore` so it doesn't error when `rolldown-vite` is installed

.changeset/flat-eggs-start.md, packages/kit/src/exports/vite/index.js
I _think_ this fixes #13975, but tbh it's hard to tell because a linked copy of `kit` doesn't exhibit the bug. Hopefully we can test it out with a pkg.pr.new install once it's available
---
=> fix: force `$app/*` modules to be bundled

CONTRIBUTING.md
Closes https://github.com/sveltejs/kit/issues/13958
---
=> chore: replace "pnpm test" with "pnpm test:kit" in CONTRIBUTING.md

.changeset/young-planes-exist.md, packages/kit/src/exports/vite/index.js
This was an accidental removal in #13971, we still need it: Without this SvelteKit will be prebundled on the client, which means we end up with two versions of Redirect etc. Also see https://github.com/sveltejs/kit/issues/5952#issuecomment-1218844057
No test because it's only testeable when SvelteKit is resolved as a npm package, Vite seems to do resolving slightly different within a monorepo
Fixes #13976
=> fix: re-add `@sveltejs/kit` to `optimizeDeps.exclude`

.changeset/mean-horses-divide.md, packages/kit/src/exports/public.d.ts, packages/kit/types/index.d.ts
This PR changes our Config type to extend the VPS Config type instead of trying to duplicate it like we are now.
TODO:
---
=> fix: extend Svelte Config type

.changeset/rude-jeans-yell.md, packages/enhanced-img/package.json, packages/enhanced-img/src/vite-plugin.js, packages/enhanced-img/test/markup-plugin.spec.js
This PR updates enhanced-img to the changes in vite-plugin-svelte that allow transforming svelte files
see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/advanced-usage.md#transform-svelte-files-with-vite-plugins
---
=> refactor: enhanced-img with v-p-s6 preprocessor support

.changeset/long-bars-rush.md, packages/kit/src/core/sync/write_root.js, packages/kit/src/core/sync/write_types/index.js, packages/kit/test/apps/basics/src/routes/params-prop/+layout.svelte, packages/kit/test/apps/basics/src/routes/params-prop/[x]/+page.svelte, packages/kit/test/apps/basics/test/test.js
Closes #13904, though it looks like we need a corresponding update in language-tools @dummdidumm — if only `params` is used, it's typed as `any`...
...whereas if `data` is also used then we get a squiggly:
We can of course use the type explicitly:
---
=> feat: typed `params` prop for page/layout components

.changeset/tricky-pants-kick.md, packages/kit/src/core/config/index.js
Running with the default configuration can be confusing when the user expects a Svelte config file to be used that is in a different location or was deleted/moved by accident.
The most obvious setting needed is an adapter.
---
=> fix: log no svelte config found message

packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/app/server/remote.js, packages/kit/src/runtime/client/remote.svelte.js, packages/kit/types/index.d.ts
Adds a `RemoteCommand` type to mirror `RemoteQuery` and `RemoteFormAction`
- necessary if users are passing around `command`s and need to type them
- also simplifies a bunch of stuff
---
=> Add RemoteCommand type

packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/app/server/remote.js, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/remote.svelte.js, packages/kit/test/apps/basics/src/routes/remote/+page.svelte, packages/kit/test/apps/basics/test/client.test.js, packages/kit/test/types/remote.test.ts, packages/kit/types/index.d.ts
This addresses some of the notes in #13986:
- `RemoteFormAction` is now `RemoteForm` (I also think we should make this non-callable, but didn't make that change here in case there's a reason that it needs to be)
- the return value of `query` is now a `RemoteQueryFunction`; for `prerender`, `RemotePrerenderFunction`. These return a `RemoteQuery` and `RemoteResource` respectively. A `RemoteQuery` extends `RemoteResource` with `refresh` and `withOverride` methods, which should _not_ belong on the return value of a prerender function. (It looks like `set` should be on `RemoteQuery` too? I didn't add that though)
- removed the `override` method from queries. There's no real sense in exposing this; the only time you want to override a query value is in the context of an optimistic update
- …
=> remote functions: fix prerender types etc

.changeset/light-facts-hope.md, documentation/docs/20-core-concepts/20-load.md, documentation/docs/20-core-concepts/60-remote-functions.md, documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md, packages/kit/src/core/generate_manifest/index.js, packages/kit/src/runtime/server/page/render.js, packages/kit/src/types/internal.d.ts, packages/kit/types/index.d.ts
This PR corrects two grammatical issues:
- A few instances of a missing hyphen in "server-side rendering"
- A common mistake in which "as such" is used as a synonym for "therefore", "thus", "so", "this means that", "for this reason", etc.
To illustrate the second issue, this sentence uses "as such" correctly:
> `reroute` is considered a pure, idempotent function. **As such**, it must always return the same output for the same input and not have side effects.
The rule of thumb is that "such" should be able to be replaced with a noun phrase from the previous sentence:
> `reroute` is considered a pure, idempotent function. **As [_a pure, idempotent function_]**, it must always return the same output for the same input and not have side effects.
This sentence uses "as such" incorrectly:
> For …
=> docs: corrections

documentation/docs/20-core-concepts/60-remote-functions.md
Adds a missing `await` when calling the remote `getPost` query
---
=> docs: add missing `await` to remote query

.changeset/dark-heads-greet.md, packages/adapter-vercel/test/utils.spec.js, packages/kit/src/core/sync/create_manifest_data/index.spec.js, packages/kit/src/utils/routing.js, packages/kit/src/utils/routing.spec.js
Rest route params currently cannot match newline characters (or `%0A`, a URL-encoded newline character). This is because in regexes, `.` does not match a newline.
This PR adjusts the regexes created for rest route params to use `[^]` instead. It adjusts existing unit tests and adds a couple more. Note that we use actual newline characters in the unit tests (rather than `%0A`) because by the time the `exec()` function is called in real applications, the URL has already been decoded.
---
=> fix: match URL-encoded newlines in rest route params

documentation/docs/20-core-concepts/60-remote-functions.md, documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md
companion to https://github.com/sveltejs/svelte/pull/16559
=> docs: remove thus

documentation/docs/20-core-concepts/60-remote-functions.md
The current code sample is buggy — the post won't update when navigating between blog posts
=> docs: use `$derived` for query

documentation/docs/20-core-concepts/60-remote-functions.md
Seems like `.refresh()` returns a Promise and if you are not awaiting it the single-flight mutation does not work. Adding the await makes it work in my testing so might just be a typo in docs.
---
=> docs: correct .refresh() example

.changeset/cute-boats-hide.md, packages/kit/src/exports/vite/index.js, packages/kit/src/runtime/app/server/remote/form.js, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/remote-functions/form.svelte.js, packages/kit/src/runtime/server/event-state.js, packages/kit/src/runtime/server/page/render.js, packages/kit/src/types/global-private.d.ts
This is an alternative to #14121, which eliminates the (already remote) possibility of race conditions. It does so by making the entire boot payload (the `__sveltekit_abc123 = {...}` object that exists in the hydration `<script>`) accessible via a `__SVELTEKIT_PAYLOAD__` [define](https://vite.dev/config/shared-options.html#define).
No test because the failure conditions are quite hard to engineer. But this general approach feels more robust than what we have now, and could enable further simplifications (by reducing the need for virtual modules, etc)
Fixes #14120
---
=> fix: use `__SVELTEKIT_PAYLOAD__` to reference boot payload

packages/package/package.json, packages/package/test/errors/no-lib-folder/svelte.config.js, packages/package/test/fixtures/assets/svelte.config.js, packages/package/test/fixtures/javascript/svelte.config.js, packages/package/test/index.spec.js, packages/package/tsconfig.json, pnpm-lock.yaml
This is the only place we were still using `uvu`. After this PR we are using `vitest` everywhere
=> chore: convert from uvu to vitest

.npmrc, package.json, packages/adapter-cloudflare/test/apps/workers/package.json, packages/kit/test/apps/amp/package.json, packages/kit/test/apps/basics/package.json, packages/kit/test/apps/basics/playwright.config.js, packages/kit/test/apps/dev-only/package.json, packages/kit/test/apps/embed/package.json, packages/kit/test/apps/hash-based-routing/package.json, packages/kit/test/apps/no-ssr/package.json, packages/kit/test/apps/options-2/package.json, packages/kit/test/apps/options/package.json, packages/kit/test/apps/options/playwright.config.js, packages/kit/test/apps/prerendered-app-error-pages/package.json, packages/kit/test/apps/writes/package.json, packages/kit/test/build-errors/apps/private-static-env/package.json, packages/kit/test/types.d.ts, packages/kit/test/utils.js, pnpm-lock.yaml, pnpm-workspace.yaml
see https://github.com/sveltejs/kit/pull/14055#issuecomment-3136352643
=> chore: use pnpm shellEmulator instead of cross-env

.changeset/upset-dots-change.md, documentation/docs/20-core-concepts/60-remote-functions.md, packages/kit/src/runtime/client/remote-functions/command.svelte.js, packages/kit/src/runtime/client/remote-functions/form.svelte.js, packages/kit/src/runtime/client/remote-functions/shared.svelte.js, packages/kit/src/runtime/server/remote.js, packages/kit/src/types/internal.d.ts, packages/kit/test/apps/basics/test/client.test.js
Per https://github.com/sveltejs/kit/issues/14079#issuecomment-3170208066, this PR changes the behaviour of `command`. It no longer automatically refreshes queries that are used on the page — either use `c.updates(q1, q2, ...)` or use `q1.refresh()` on the server.
This doesn't affect the behaviour of forms — these will still invalidate all queries if they are not individually specified, since a progressively-enhanced form submission should behave like a regular one.
---
=> fix: don't refresh queries automatically when running commands

.changeset/petite-doors-taste.md, packages/kit/src/exports/index.js, packages/kit/src/runtime/app/server/index.js, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/fetcher.js, packages/kit/src/runtime/server/cookie.js, packages/kit/src/runtime/server/data/index.js, packages/kit/src/runtime/server/page/crypto.js, packages/kit/src/runtime/server/page/crypto.spec.js, packages/kit/src/runtime/server/page/csp.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/src/runtime/server/page/render.js, packages/kit/src/runtime/shared.js, packages/kit/src/runtime/utils.js, packages/kit/src/runtime/utils.spec.js, packages/kit/test/apps/basics/test/client.test.js
#14157, but with a simpler implementation of `base64_encode` and `base64_decode`. I got rid of the `omitPadding` and `alphabet` options, I think they're unnecessary
---
=> chore: refactor to consolidate base64 encoding functions (alternative)

packages/kit/src/exports/public.d.ts, packages/kit/types/index.d.ts
=> docs: update `navigation` descriptions

.changeset/brave-clowns-behave.md, .changeset/social-hounds-jam.md, packages/kit/src/core/config/fixtures/custom-src/svelte.config.js, packages/kit/src/core/config/index.js, packages/kit/src/core/config/index.spec.js, packages/kit/src/core/config/options.js, packages/kit/src/core/sync/create_manifest_data/index.spec.js, packages/kit/src/core/sync/write_types/index.spec.js, packages/kit/src/exports/public.d.ts, packages/kit/types/index.d.ts, packages/package/test/index.js
=> chore: deprecate `config.kit.files` options

.changeset/floppy-memes-warn.md, packages/adapter-node/src/handler.js
Fixes #14218, hopefully. This simply reverts the change from `??`s to `||`s. The values here being empty strings might indicate the environment variable not being set (in which case we definitely want to fall back to the default values) or it might indicate the env var being set and the header being set but to an empty value (in which case, it would be more helpful to also fall back to the default values). Using `??` over `||` is generally a worthwhile endeavor for more strict correctness, but not in this case.
---
=> fix: handling of PROTOCOL_HEADER and HOST_HEADER env vars

.changeset/shy-cooks-pay.md, packages/kit/src/exports/vite/index.js
I had the same issue mentioned in https://github.com/sveltejs/kit/issues/14217.
According to the warning message and the Rollup plugin development docs:
- https://rollupjs.org/plugin-development/#this-resolve
- https://rollupjs.org/plugin-development/#resolveid
The `resolveId` hook should forward the third `options` parameter to `this.resolve`.  (as stated in the warning):
```
[plugin commonjs--resolver] It appears a plugin has implemented a "resolveId" hook that uses "this.resolve" without forwarding the third "options" parameter of "resolveId". This is problematic as it can lead to wrong module resolutions especially for the node-resolve plugin and in certain cases cause early exit errors for the commonjs plugin.
In rare cases, this warning can appear if the same file is both imported …
```
=> fix: pass options to resolve in resolveId hook

packages/adapter-auto/tsconfig.json, packages/adapter-node/tsconfig.json, packages/adapter-static/tsconfig.json, packages/adapter-vercel/tsconfig.json
we added `skipLibCheck` in #13864; as of #14207 they should be unnecessary
=> chore: remove skipLibCheck

.changeset/kind-parents-melt.md, packages/kit/src/exports/vite/index.js, packages/kit/src/exports/vite/utils.js, packages/kit/src/exports/vite/utils.spec.js, packages/kit/src/runtime/app/server/remote/command.js, packages/kit/src/runtime/app/server/remote/form.js, packages/kit/src/runtime/app/server/remote/prerender.js, packages/kit/src/runtime/app/server/remote/query.js, packages/kit/src/runtime/app/server/remote/shared.js
=> fix: better error when `.remote.ts` files are used without the `experimental.remoteFunctions` flag

documentation/docs/20-core-concepts/60-remote-functions.md
This PR mentions the async config option ~and the pending and failed snippet~. These are essential to add/enable especially when the doc examples all use `await`.
---
=> docs: expand on async Svelte in Remote Functions

.changeset/dirty-rats-switch.md, packages/adapter-netlify/index.js
Fixes https://github.com/sveltejs/kit/issues/14216 by making the `exludedFiles` pattern more restrictive since remote functions are sent at `/_app/remote/*`. This updated pattern is inline with other adapters like Cloudflare, so I don't anticipate issues:
https://github.com/sveltejs/kit/blob/233ea22e4e4676c7041d7e225c836c7dc8096c31/packages/adapter-cloudflare/index.js#L215
I've extended the reproduction repo to use the changes from this PR in: 
https://github.com/nickbreaton/svelte-kit-netlify-adapter-repro/compare/main...fix
The permalink for this deploy is available here, which does allow for the remote function to work:
https://689df1462120180008ab45f6--svelte-kit-netlify-adapter-repro.netlify.app/
---
- [-] Ideally, include a test that fails without this PR but passes with it.
- I've …
=> fix: don't exclude remote functions when deploying to Netlify edge functions

.changeset/clever-boxes-feel.md, packages/kit/src/runtime/server/page/load_data.js, packages/kit/test/apps/basics/src/routes/load/serialization/+page.js
Fixes #12236. The implementation isn't totally ideal — it causes the server `load` return value to be serialized twice if `data` is used in a universal `load` function, and changing that would be finicky — but given our overall trajectory towards remote functions I think it's an acceptable trade-off given that using `data` is probably relatively rare (and it only affects SSR, not data for subsequent client-side navigations).
---
=> fix: serialize server `load` data before passing to universal `load`, to handle mutations

.changeset/brown-seals-rhyme.md, packages/kit/src/runtime/app/forms.js, packages/kit/src/runtime/client/bundle.js, packages/kit/src/runtime/server/page/render.js, packages/kit/test/apps/basics/src/routes/serialization-stream/+page.server.js, packages/kit/test/apps/basics/src/routes/serialization-stream/+page.server.ts, packages/kit/test/apps/basics/src/routes/serialization-stream/+page.svelte, packages/kit/test/apps/basics/test/test.js, packages/kit/test/apps/options-2/src/hooks.js, packages/kit/test/apps/options-2/src/lib/index.js, packages/kit/test/apps/options-2/src/routes/serialization-stream/+page.server.js, packages/kit/test/apps/options-2/src/routes/serialization-stream/+page.svelte, packages/kit/test/apps/options-2/test/test.js, packages/kit/test/apps/options-3/package.json, packages/kit/test/apps/options-3/playwright.config.js, packages/kit/test/apps/options-3/src/app.html, packages/kit/test/apps/options-3/src/hooks.js, packages/kit/test/apps/options-3/src/lib/index.js, packages/kit/test/apps/options-3/src/routes/+layout.svelte, packages/kit/test/apps/options-3/src/routes/serialization-stream/+page.server.js, packages/kit/test/apps/options-3/src/routes/serialization-stream/+page.svelte, packages/kit/test/apps/options-3/svelte.config.js, packages/kit/test/apps/options-3/test/test.js, packages/kit/test/apps/options-3/tsconfig.json, packages/kit/test/apps/options-3/vite.config.js, pnpm-lock.yaml
fixes https://github.com/sveltejs/kit/issues/13428
This PR ensures the `app` variable is available when the server pushes chunks to the client to decode custom data types as they stream in. This fixes streaming for split and single apps by wrapping the code that references `app` after an import statement, and providing the correct global variable for inline apps.
An additional test suite for inline apps has also been added since none existed before. However, feel free to remove it if it's too much just to test inline apps.
---
=> fix: deserialise streamed custom types

.changeset/famous-lands-bathe.md, .changeset/quick-seals-accept.md, packages/adapter-cloudflare/src/worker.js, packages/adapter-netlify/src/edge.js
follow up to https://github.com/sveltejs/kit/pull/14147/files#diff-da750858952944694371448b721a910039c987d1bd7d3e465a6aebb5cd760d9bR42
This PR changes the `read(...)` error message for Netlify's edge functions and Cloudflare to be similar to the one from the Vercel adapter.
---
=> chore: align error message when `read(...)` fails in an edge function

packages/kit/src/types/ambient.d.ts, packages/kit/types/index.d.ts
Previously, the link only pointed to the configuration docs. However, we now have individual links for each top level option, so we can now link to the service worker option directly.
---
=> chore: fix link pointing to service worker config option

.changeset/true-moles-tap.md, packages/kit/package.json, packages/kit/src/exports/vite/index.js, packages/kit/src/runtime/app/state/server.js, packages/kit/src/runtime/app/stores.js, packages/kit/src/runtime/server/cookie.js, packages/kit/src/runtime/server/cookie.spec.js, packages/kit/src/runtime/server/page/actions.js, packages/kit/src/runtime/server/page/csp.js, packages/kit/src/runtime/server/page/csp.spec.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/src/runtime/server/page/render.js, packages/kit/src/runtime/server/respond.js, packages/kit/src/runtime/server/utils.js, packages/kit/src/types/global-private.d.ts, packages/kit/test/prerendering/basics/test/tests.spec.js
This PR addresses one of the TODO comments by consolidating our dev environment checks to use `esm-env` instead of relying on the (probably legacy) `__SVELTEKIT_DEV__` global variable. It also adjusts some unit tests to run in production mode from the Vitest CLI where previously we just manipulated the global variable (but as far as I'm aware that's not possible to do inline in a test in Vitest to get `esm-env` to behave similarly)
Not sure if this is breaking or not but if it is let me know so we can adjust the changeset or delay the merging of this PR.
---
=> chore: remove `__SVELTEKIT_DEV__` global

.changeset/social-hats-hope.md, documentation/docs/20-core-concepts/60-remote-functions.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/app/server/remote/query.js, packages/kit/test/apps/basics/src/routes/remote/+page.svelte, packages/kit/test/apps/basics/test/client.test.js, packages/kit/types/index.d.ts
Exposes the `.set()` method on remote queries. Fixes #14302
---
=> fix: expose query.set

.changeset/modern-icons-film.md, packages/kit/src/exports/public.d.ts, packages/kit/src/runtime/server/respond.js, packages/kit/test/apps/basics/test/server.test.js, packages/kit/types/index.d.ts
https://github.com/sveltejs/kit/pull/14309#issuecomment-3221484582
closes #14309
---
=> fix: disable CSRF checks in dev

packages/kit/src/runtime/app/server/remote/query.js, packages/kit/src/runtime/app/server/remote/shared.js
see https://github.com/sveltejs/kit/pull/14304#discussion_r2307962421 — creating a `AbortController` every time we call a query function on the server is unnecessary overhead. We can just refer to the event cache
---
=> chore: get rid of AbortController when calling queries on server

.changeset/blue-deer-relax.md, packages/kit/src/runtime/server/data/index.js, packages/kit/src/runtime/server/page/data_serializer.js, packages/kit/src/runtime/server/page/index.js, packages/kit/src/runtime/server/page/load_data.js, packages/kit/src/runtime/server/page/render.js, packages/kit/src/runtime/server/page/respond_with_error.js, packages/kit/src/runtime/server/page/types.d.ts, packages/kit/src/runtime/server/respond.js, packages/kit/src/runtime/server/utils.js, packages/kit/src/utils/streaming.js, packages/kit/src/utils/streaming.spec.js, packages/kit/test/apps/basics/src/routes/streaming/server/+page.js
Alternative to #14268
Fixes #14291
CC @Rich-Harris
---
=> fix: serialize server `load` data before passing to universal load alternative

.changeset/every-kings-wink.md, packages/kit/src/utils/routing.js, packages/kit/src/utils/routing.spec.js
Issue #14047 
Previous PR was #14065, but it was actually just support a trailing slash for type Pathname, not solving the issue.
Apologize about that I misunderstood the issue.
Problem was `resolve() from @app/paths` drops trailing slash (technically `resolve_route()` in `resolve()` does).
For example `resolve('/hoge/huga/')` returns string of `/hoge/huga`
Change to keep the trailing slash if `id` has the trailing slash. 
---
=> fix: resolve_route prevent dropping a trailing slash of id

.changeset/large-parrots-grow.md, packages/kit/src/runtime/client/remote-functions/form.svelte.js, packages/kit/test/apps/basics/src/routes/remote/form/form.remote.js, packages/kit/test/apps/basics/test/test.js
=> fix: assign correct status code to form submission error on the client

package.json, pnpm-lock.yaml
I removed `tmp` from changesets to get rid of it since it's got a security vulnerability. This won't fix the dependabot warning yet until `netlify-cli` is also fixed (https://github.com/netlify/cli/pull/7598)
=> chore: upgrade changesets

.changeset/slow-chicken-serve.md, packages/adapter-node/package.json, pnpm-lock.yaml
sirv 3.0.2 fixed a theoretical security vulnerability where a sibling file that starts with the name of the root directory could be requested through a path that contains `..`  
sveltekit applications using adapter-node do not have this kind of file by default and users would have had to go out of their way to create one which is very unlikely.  
---
=> fix: bump sirv to 3.0.2

.changeset/lazy-boats-stay.md, packages/kit/src/runtime/server/page/data_serializer.js, packages/kit/src/runtime/server/page/index.js, packages/kit/test/apps/basics/src/routes/load/serialization-empty-node/+page.server.js, packages/kit/test/apps/basics/src/routes/load/serialization-empty-node/+page.svelte, packages/kit/test/apps/basics/test/test.js
Fixes #14390
Another bug in #14298 🫤
We must only `add_node()` if there is a `node` (`SSRNode`) and then remove empty array items from `strings` (like we do with the `branches` array).
---
=> fix: remove empty nodes from serialized server load data

.changeset/small-ghosts-fail.md, .changeset/witty-ties-brush.md, packages/package/src/utils.js, packages/package/test/fixtures/resolve-alias/expected/index.d.ts, packages/package/test/fixtures/resolve-alias/expected/index.js, packages/package/test/fixtures/resolve-alias/src/lib/index.ts
- handle `import/export * (as ...)` when resolving aliases (https://github.com/sveltejs/kit/pull/14413#issuecomment-3287235908)
- prevent false-positive alias replacement when another import starts with an alias but it's not the full one, e.g. don't replace `$libre` with `./re`
---
=> fix: more alias resolution fixes

.changeset/busy-pumas-tap.md, packages/kit/src/exports/vite/index.js, packages/kit/test/apps/basics/src/routes/remote/+page.js, packages/kit/test/apps/basics/src/routes/remote/+page.svelte, packages/kit/test/apps/basics/src/routes/remote/accessing-env.remote.js
This way you cannot run into initialization order issues where e.g. some remote function uses environment variables before they're set
Fixes #14439
---
=> fix: ensure environment setup is in its own chunk

.changeset/curvy-icons-fall.md, packages/kit/src/core/postbuild/analyse.js
It is currently possible for a chunk to import chunks that import itself. I'm not exactly sure where this occurs or why as I can't reproduce it in a simple repository, but a simple fix is to prevent importing already visited chunks.
This addresses #14444 
---
=> fix(build): RangeError - Maximum call stack size exceeded

.changeset/funny-onions-drive.md, packages/kit/src/exports/public.d.ts, packages/kit/test/types/remote.test.ts, packages/kit/types/index.d.ts
Optional properties make the resulting type `X | undefined` which when turned into an intersection results in the never type. We therefore mark all properties as required while transforming the objects into their desired shape.
There's another adjacent bug: If you have an object only consisting of optional properties, e.g. `{a?: string}`, then `RemoteFormInput` extends it and the type is degraded to e.g. `{ [key: string]: RemoteFormIssues[] }`. A fix to the "will recurse indefinetly" helper type solves this: we now check if the object keys match an index signature, and only bail in that case.
Also added a few tests
Fixes #14461
---
=> fix: robustify form helper types

.changeset/rude-crabs-rescue.md, packages/kit/src/runtime/server/page/render.js
fixes #14473
No tests because this fix will be very short-lived and will not regress
---
=> fix: ensure SSR rendering gets request store context

.changeset/shiny-schools-slide.md, packages/package/src/utils.js, packages/package/test/fixtures/resolve-alias/expected/baz.d.ts, packages/package/test/fixtures/resolve-alias/expected/baz.js, packages/package/test/fixtures/resolve-alias/expected/index.d.ts, packages/package/test/fixtures/resolve-alias/expected/index.js, packages/package/test/fixtures/resolve-alias/src/lib/baz.ts, packages/package/test/fixtures/resolve-alias/src/lib/index.ts
This PR continues #14433 by handling `import/export name, { ... }` when resolving aliases.
---
=> fix: one more alias resolution fix

packages/adapter-cloudflare/test/apps/pages/package.json, packages/adapter-cloudflare/test/apps/workers/package.json, packages/adapter-netlify/test/apps/basic/package.json, packages/adapter-netlify/test/apps/edge/package.json, packages/adapter-static/package.json, packages/adapter-static/test/apps/prerendered/package.json, packages/adapter-static/test/apps/spa/package.json, packages/enhanced-img/package.json, packages/package/package.json, playgrounds/basic/package.json, pnpm-lock.yaml
to reduce the size of the #14447 diff
It's probably worth doing this for all deps, as suggested by @hugos68 in https://github.com/sveltejs/kit/pull/14445#issuecomment-3310009361, but for now I'm just making minimal changes
=> chore: use catalog for more "svelte" dependencies

.changeset/late-dodos-move.md, packages/kit/src/runtime/client/client.js
In #14195, the access of `__SVELTEKIT_PAYLOAD__.data` had been fixed like this:
```js
export const remote_responses = __SVELTEKIT_PAYLOAD__?.data ?? {};
```
However, #14435 introduced a change (looks like a typo) where the `?` moved to the wrong spot:
```js
if (__SVELTEKIT_PAYLOAD__.data) {
remote_responses = __SVELTEKIT_PAYLOAD__?.data;
}
```
This brought back the earlier problem in some of my apps. This PR moves the `?` out into the condition.
---
=> fix: ensure `__SVELTEKIT_PAYLOAD__.data` access is safe

.changeset/five-rooms-draw.md, packages/kit/src/runtime/app/paths/server.js
In #14447 I broke a cardinal rule — code in `src/runtime` should only ever import code from `src/exports` via the public bare imports made available via `pkg.exports`. Otherwise, there's a danger that a given module will be loaded through both Vite _and_ Node, causing breakage.
I ignored that rule because I was trying to deal with some tricky resolution bug, and #14505 was my reward. Luckily I think the tricky resolution bug is solved by not having a nested `pkg.exports` map, and instead abusing `pkg.imports` to achieve the intended outcome.
This is one of those things that's extremely hard to test for from within the workspace, because of how Vite works. But I _think_ this solution is good. Closes #14505.
---
=> fix: consistently use bare import for internals

.changeset/large-chicken-obey.md, packages/kit/src/runtime/client/client.js, packages/kit/src/runtime/client/remote-functions/form.svelte.js, packages/kit/src/runtime/client/remote-functions/prerender.svelte.js, packages/kit/src/runtime/client/remote-functions/query.svelte.js
This PR allows both of these remote function calls...
```svelte
{#if await condition()}
<h1>{await message()}</h1>
{/if}
```
...to use the data that was serialized when those queries were encountered during SSR. At present, only `condition()` is used, because `started` becomes `true` synchronously after the `hydrate(...)` call, before the contents of the if block are rendered.
The heuristic here (use the serialized data until navigation occurs) is 98% good enough, though in the long term it would be preferable to knit this stuff into the actual hydration process. That's a ways off though.
---
=> fix: keep serialized remote data alive until navigation

.changeset/deep-insects-do.md, packages/kit/src/core/postbuild/queue.js, packages/kit/src/exports/internal/event.js, packages/kit/src/runtime/server/constants.js, packages/kit/src/runtime/server/index.js, packages/kit/src/utils/promise.js
Since [replacing ASL with zone.js](https://github.com/sveltejs/kit/pull/14482) doesn't seem to work, I thought it might make sense to not use ASL at all when we're running in a webcontainer (in dev mode).
It means we can only handle one request at a time, but since stackblitz/sveltelab is mostly used to reproduce issues IMO it is worth it.
*[Seems like it works](https://stackblitz.com/edit/sveltejs-kit-template-default-ajoj5bas?file=src%2Froutes%2F%2Bpage.server.js)*
---
=> fix: Webcontainer AsyncLocalStorage workaround

.changeset/stale-things-mix.md, packages/kit/src/runtime/client/client.js
This addresses a very finicky and hard-to-reproduce (and test for, unfortunately) bug: when navigating to a hash fragment on another page, the captured scroll position is wrong if the page has `scroll-behavior: smooth`, because it gets captured at the _start_ of the scroll rather than the end.
If my understanding is correct, the buggy sequence of events is:
- we navigate, and update the DOM
- we scroll to the desired place (either a previous scroll position, if navigating via `popstate`, or the position of a deep-linked element, or `0, 0`
- we reset focus:
- we capture the scroll position (incorrectly in the `smooth` case)
- reset everything
- scroll back to the desired scroll position
This PR changes the behaviour slightly: where appropriate, it passes the desired scroll state to …
=> fix: smooth scroll to deep link

.changeset/lucky-humans-make.md, packages/kit/src/runtime/app/server/remote/form.js, packages/kit/test/types/remote.test.ts, packages/kit/types/index.d.ts
fixes https://github.com/sveltejs/kit/issues/14570
One of the overloads for the `form` remote function was missing a `MaybePromise` for the function return type. This PR fixes that.
---
=> fix: correctly type `form` remote functions that do not accept data

.changeset/deep-eagles-punch.md, packages/adapter-auto/package.json, packages/adapter-cloudflare/package.json, packages/adapter-netlify/package.json, packages/adapter-node/package.json, packages/adapter-static/package.json, packages/adapter-vercel/package.json, packages/enhanced-img/package.json
This will enable the forthcoming `/packages` page on svelte.dev to link directly to the correct place
=> chore: fix "homepage" field in package.json

.changeset/late-ways-find.md, packages/kit/src/exports/vite/index.js
Fixes at least part of #14519 — I couldn't get the repro to start up, because Vite's `optimizeDeps` step prebundles any dependencies it finds from `+page.svelte` and `+page.js` entry points. Import tracing should stop at `.remote.js` files, because these don't run in the client. This PR makes it so.
---
=> fix: skip prebundling of .remote.js files

.changeset/cute-bushes-hope.md, packages/kit/src/exports/vite/index.js, packages/kit/src/runtime/client/remote-functions/query.svelte.js
At present, if you have something like this...
```svelte
<script>
import { foo } from './data.remote';
</script>
<p>{await foo()}</p>
```
...nothing immediately changes if you change the return value of `foo` — you have to reload the page to see the new data. This is unsatisfying.
With this PR, hot updates are accepted by the transformed remote module, and upon creating the replacement query we refresh anything that's currently referenced in an effect. The end result is HMR for queries.
Unfortunately this approach _doesn't_ extend to `prerender`, because prerender functions don't use state and thus cannot be reactively updated. We could change that, but we would only want to change it in dev, and it would be a whole thing. Maybe we'll want to do that at some point anyway though.
---
=> fix: HMR for `query`

.changeset/polite-rooms-invent.md, documentation/docs/20-core-concepts/60-remote-functions.md, packages/kit/src/runtime/app/server/remote/shared.js, packages/kit/src/runtime/client/remote-functions/command.svelte.js, packages/kit/src/runtime/client/remote-functions/form.svelte.js, packages/kit/src/runtime/client/remote-functions/shared.svelte.js, packages/kit/src/runtime/server/respond.js, packages/kit/test/apps/basics/src/routes/remote/+page.svelte, packages/kit/test/apps/basics/src/routes/remote/event/+page.svelte, packages/kit/test/apps/basics/src/routes/remote/event/data.remote.ts, packages/kit/test/apps/basics/svelte.config.js, packages/kit/test/apps/basics/test/test.js, pnpm-lock.yaml, pnpm-workspace.yaml
We originally chose to omit `event.route` and `event.url` from remote functions, because we worried that it could create confusion — if a query's return value is based on `event.url`, it could become incorrect later when the URL changes and the query result doesn't.
But it's too restrictive. It's often necessary to know which page a remote function was called from. For example if a query redirects to a `/login` page, it's nice to be able to include a `redirectTo` parameter, and for that you need to know the page the user was trying to access:
```js
if (!user) {
redirect(307, `/login?redirectTo=${encodeURIComponent(event.url.pathname)}`);
}
```
This PR makes that possible. Closes #14543.
---
=> feat: expose `event.route` and `event.url` to remote functions

.changeset/weak-rings-open.md, packages/kit/src/runtime/app/server/remote/shared.js, packages/kit/src/runtime/server/page/render.js, packages/kit/src/runtime/server/respond.js, packages/kit/src/types/internal.d.ts
Ordinarily if a server-side `fetch` occurs outside a `load` function, we emit a warning that steers people towards using `event.fetch` instead. This makes sense in the old world, where fetches in universal loads are serialized, but not really in the new world — we want people to use regular `fetch` inside remote functions, because the return value of the function itself is the thing that gets serialized.
I also suspect that the `is_in_remote_function` state will come in handy in various ways.
---
=> fix: allow `fetch` in remote function without emitting a warning

.changeset/thin-clubs-press.md, packages/kit/src/runtime/client/remote-functions/shared.svelte.js
We populate a hydration cache from the serialized remote function return values, and keep it around until the user navigates or a `refreshAll` happens. That covers most cases, but if a particular query is discarded _before_ navigation occurs, it should still be cleared. This makes it so.
---
=> fix: delete hydration cache on effect teardown

.changeset/nasty-walls-learn.md, packages/kit/src/exports/vite/index.js
For real this time - #14632 did put it on the wrong object
Fixes #14590
=> fix: prevent code execution order issues around SvelteKit's `env` modules

.changeset/fresh-peaches-live.md, packages/kit/src/runtime/app/server/remote/form.js
Without this, `fields.foo.set('one'); fields.bar.set('two')` won't work in SSR, because `data` already exists. No test because... I don't have time right now
---
=> fix: merge `field.set(...)` calls
